// "256-byte intro" README header for CASTAWAY.
//
//   node examples/castaway/src/110-256-byte-intro_opus_5.5.mjs
//   node examples/castaway/src/110-256-byte-intro_opus_5.5.mjs --at=13.5 --out=some/dir
//
// Regenerates, next to this folder:
//   ../assets/110-256-byte-intro_opus_5.5.svg   the banner
// Plain Node, no deps, deterministic (seeded PRNG, no clock). --at bakes a head
// start (seconds) into every animation delay so late frames can be checked
// without waiting; use it only together with --out, never in place.
// (The .md beside the assets is hand-written, not generated by this script.)
//
// The style: the PC 256-byte intro. With no room for data, every picture is
// arithmetic on the pixel's X and Y and a frame counter (XOR and AND patterns,
// a plane made by dividing by the row number, circles without square roots),
// coloured straight from the default VGA palette because setting your own
// costs bytes, and one effect speckles into the next by offsetting time with
// a per-pixel random number. Nothing here is copied from any production: the
// formulas are plain mathematics, and the letters, sprites and copy were made
// for this file. The colours are entries of the stock mode 13h palette, which
// this script rebuilds from its layout (16 EGA colours, a 16-step grey ramp,
// then 24 hues x 3 saturations x 3 intensities).
//
// The frame is 320x160 VGA pixels (one SVG unit = one pixel) and runs as five
// parts of two bars each (80 BPM: one bar = 3 s), 30 s in all, then loops:
//   1. SEA     a plane receding to a horizon, textured with (u xor v) and
//              scrolling toward you, under a dithered daytime sky. A small
//              island, one palm, a raft, and her, nodding on every beat.
//   2. SAND    the XOR quilt masked into a grid of little chessboards,
//              drifting, with the palette cycling through cream and coral.
//   3. PALM    the Sierpinski figure ((|x| and |y|) = 0) as a rotozoomer, in
//              the palette's green band. It zooms x2 every bar, forever.
//   4. SIGNAL  concentric rings, distance minus time, through the pastel hue
//              band: one bar of signal, broadcast from where the top of the
//              palm stood in part 1.
//   5. SKY     three see-through checkerboards sliding at three speeds.
// Between parts, a one-beat speckle dissolve: a 32x32 noise tile splits the
// screen into 16 groups and each group switches 1/16 beat after the last.
// CASTAWAY is knocked out of every part in plain block capitals, and a small
// caption in the corner gives the byte count: the real size of this file,
// found by iterating until the number it prints is the number it is.
//
// How the SVG does it
//   * Parts are stacked in order, each on top of the last. Parts 2-5 sit
//     under their own <mask>: 16 rects, one per noise group (a <pattern> of
//     that group's cells, drawn as stroked runs), plus one solid rect for the
//     steady state. They share a few 30 s step-end opacity tracks and differ
//     only in animation-delay. The part beneath stays whole while the next
//     one speckles in, so the sea at the bottom needs no mask; the last part
//     speckles OUT on top of it instead. A visibility track hides each part
//     while it is off screen, so only one or two parts are ever painted.
//   * SEA: 36 horizontal strips, each a nested <svg> viewport (it clips) with
//     the 16x16 XOR tile scaled by the row's perspective. One shared keyframe
//     scrolls every strip by one tile in texture space per bar, so near rows
//     move fast and far rows crawl. A stepped haze covers the horizon, and
//     glints take turns on the four beats of the bar.
//   * SAND: one 64 px tile of 16 paths whose strokes step through a 16-entry
//     ping-pong ramp (CSS inside a <pattern> animates in Chrome and Firefox).
//   * PALM: the AND figure is the union of "blank" squares, one periodic
//     pattern per bit level. Zooming x2 maps level k onto level k+1, so the
//     zoom loops if every level's colour also slides to the next level's and
//     the finest level fades in from sub-pixel size. One quadrant is drawn
//     and mirrored into the other three, so no quadrant goes flat.
//   * SIGNAL: 72 stroked circles whose radii grow linearly (SMIL), each with a
//     fixed hue, so the hue sequence flows outward with no seam.
//   * prefers-reduced-motion pauses every CSS track on its first frame, which
//     is the complete SEA picture with the name. (The SMIL rings keep going,
//     but their part is hidden.)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const arg = (name) => {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const T0 = Number(arg('at') || 0);
const OUTDIR = arg('out') ? path.resolve(arg('out')) : path.resolve(here, '../assets');
const SLUG = '110-256-byte-intro_opus_5.5';

const W = 320;
const H = 160;
const BEAT = 0.75;            // 80 BPM
const BAR = 4 * BEAT;         // 3 s
const PART = 2 * BAR;         // 6 s per effect
const NPART = 5;
const LOOP = PART * NPART;    // 30 s
const DIS = BEAT;             // the dissolve takes one beat
const G = 16;                 // dissolve groups

const n = (v, d = 2) => String(+(+v).toFixed(d));
// animation-delay that puts a track of period P at phase 0 at time `start`
const ph = (start, P = LOOP) => `${n((((start % P) + P) % P) - P - T0, 3)}s`;

// ------------------------------------------------------------ VGA palette
// The default mode 13h palette, rebuilt from its layout (6-bit DAC values).
const VGA = (() => {
  const pal = [];
  const ega = ['000000', '0000aa', '00aa00', '00aaaa', 'aa0000', 'aa00aa', 'aa5500', 'aaaaaa',
    '555555', '5555ff', '55ff55', '55ffff', 'ff5555', 'ff55ff', 'ffff55', 'ffffff'];
  ega.forEach((h) => pal.push(`#${h}`));
  const six = (v) => Math.round((v * 255) / 63).toString(16).padStart(2, '0');
  const rgb6 = (r, g, b) => `#${six(r)}${six(g)}${six(b)}`;
  [0, 5, 8, 11, 14, 17, 20, 24, 28, 32, 36, 40, 45, 50, 56, 63].forEach((v) => pal.push(rgb6(v, v, v)));
  const LEVELS = [
    [0, 16, 31, 47, 63], [31, 39, 47, 55, 63], [45, 49, 54, 58, 63],
    [0, 7, 14, 21, 28], [14, 17, 21, 24, 28], [20, 22, 24, 26, 28],
    [0, 4, 8, 12, 16], [8, 10, 12, 14, 16], [11, 12, 13, 15, 16],
  ];
  // 24 hues: blue -> magenta -> red -> yellow -> green -> cyan -> blue
  const HUE = [];
  for (let i = 0; i < 4; i++) HUE.push([i, 0, 4]);
  for (let i = 4; i > 0; i--) HUE.push([4, 0, i]);
  for (let i = 0; i < 4; i++) HUE.push([4, i, 0]);
  for (let i = 4; i > 0; i--) HUE.push([i, 4, 0]);
  for (let i = 0; i < 4; i++) HUE.push([0, 4, i]);
  for (let i = 4; i > 0; i--) HUE.push([0, i, 4]);
  for (const L of LEVELS) for (const [r, g, b] of HUE) pal.push(rgb6(L[r], L[g], L[b]));
  while (pal.length < 256) pal.push('#000000');
  return pal;
})();
// block 0..8 (hi/mid/low intensity x high/mid/low saturation), hue 0..23
const VH = (block, hue) => VGA[32 + 24 * block + (((hue % 24) + 24) % 24)];
const EGA = (i) => VGA[i];

// ------------------------------------------------------------ PRNG
function mulberry32(a) {
  return () => {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ------------------------------------------------------------ pixels
// Scattered cells (noise, chessboards) cost less as stroked runs: each run is
// "m dx dy h len" drawn with stroke-width S and butt caps, which paints exactly
// the same squares as a filled rect. Use as <path stroke=".." stroke-width=S>.
function runsD(cells, S = 1) {
  const rows = new Map();
  for (const [x, y] of cells) {
    if (!rows.has(y)) rows.set(y, []);
    rows.get(y).push(x);
  }
  let d = '';
  let px = 0;
  let py = 0;
  for (const y of [...rows.keys()].sort((a, b) => a - b)) {
    const xs = [...new Set(rows.get(y))].sort((a, b) => a - b);
    for (let i = 0; i < xs.length;) {
      let j = i;
      while (j + 1 < xs.length && xs[j + 1] === xs[j] + 1) j++;
      const x0 = xs[i] * S;
      const yc = y * S + S / 2;
      const len = (j - i + 1) * S;
      d += `${d ? 'm' : 'M'}${n(x0 - px)} ${n(yc - py)}h${len}`;
      px = x0 + len;
      py = yc;
      i = j + 1;
    }
  }
  return d.replace(/ -/g, '-');
}
// Cells are [x, y]. Merge into horizontal runs, stack equal runs into rects,
// emit one path (scale S, offset ox/oy).
function cellsPath(cells, S = 1, ox = 0, oy = 0) {
  const rows = new Map();
  for (const [x, y] of cells) {
    if (!rows.has(y)) rows.set(y, new Set());
    rows.get(y).add(x);
  }
  const runs = [];
  for (const [y, set] of rows) {
    const xs = [...set].sort((a, b) => a - b);
    let s = xs[0];
    let p = xs[0];
    for (let i = 1; i <= xs.length; i++) {
      if (i < xs.length && xs[i] === p + 1) { p = xs[i]; continue; }
      runs.push([s, p + 1, y]);
      if (i < xs.length) { s = xs[i]; p = xs[i]; }
    }
  }
  runs.sort((a, b) => a[2] - b[2] || a[0] - b[0]);
  const live = new Set(runs.map((r) => r.join(',')));
  let d = '';
  for (const r of runs) {
    const k0 = r.join(',');
    if (!live.has(k0)) continue;
    live.delete(k0);
    let h = 1;
    while (live.has(`${r[0]},${r[1]},${r[2] + h}`)) { live.delete(`${r[0]},${r[1]},${r[2] + h}`); h++; }
    const w = (r[1] - r[0]) * S;
    d += `M${n(ox + r[0] * S)} ${n(oy + r[2] * S)}h${n(w)}v${n(h * S)}h${n(-w)}z`;
  }
  return d;
}
// A paint box: set(x, y, colour), then paths() groups by colour.
class Canvas {
  constructor() { this.m = new Map(); }
  set(x, y, c) { if (c) this.m.set(`${x},${y}`, [x, y, c]); else this.m.delete(`${x},${y}`); }
  get(x, y) { const v = this.m.get(`${x},${y}`); return v ? v[2] : null; }
  paths(S = 1, ox = 0, oy = 0, extra = '') {
    const by = new Map();
    for (const [x, y, c] of this.m.values()) {
      if (!by.has(c)) by.set(c, []);
      by.get(c).push([x, y]);
    }
    let out = '';
    for (const [c, cells] of by) out += `<path${extra} fill="${c}" d="${cellsPath(cells, S, ox, oy)}"/>`;
    return out;
  }
}
const sprite = (rows, pal, cv, ox, oy) => rows.forEach((row, y) => [...row].forEach((ch, x) => {
  if (pal[ch]) cv.set(ox + x, oy + y, pal[ch]);
}));

// ------------------------------------------------------------ fonts
// Plain block capitals, 5x5, for the knocked-out name.
const BIG = {
  C: '#####|#....|#....|#....|#####',
  A: '#####|#...#|#####|#...#|#...#',
  S: '#####|#....|#####|....#|#####',
  T: '#####|..#..|..#..|..#..|..#..',
  W: '#...#|#...#|#.#.#|#.#.#|#####',
  Y: '#...#|#...#|#####|..#..|..#..',
};
// 3x5 for the corner caption.
const TINY = {
  A: '.#.|#.#|###|#.#|#.#', B: '##.|#.#|##.|#.#|##.', E: '###|#..|##.|#..|###',
  G: '.##|#..|#.#|#.#|.##', I: '###|.#.|.#.|.#.|###', K: '#.#|#.#|##.|#.#|#.#',
  O: '.#.|#.#|#.#|#.#|.#.', R: '##.|#.#|##.|#.#|#.#', S: '.##|#..|.#.|..#|##.',
  T: '###|.#.|.#.|.#.|.#.', V: '#.#|#.#|#.#|#.#|.#.', Y: '#.#|#.#|.#.|.#.|.#.',
  0: '###|#.#|#.#|#.#|###', 1: '.#.|##.|.#.|.#.|###', 2: '##.|..#|.#.|#..|###',
  3: '##.|..#|.#.|..#|##.', 4: '#.#|#.#|###|..#|..#', 5: '###|#..|##.|..#|##.',
  6: '.##|#..|###|#.#|###', 7: '###|..#|.#.|.#.|.#.', 8: '###|#.#|###|#.#|###',
  // the comma drops one row below the baseline, so 69,940 never reads as 69.940
  9: '###|#.#|###|..#|##.', ',': '...|...|...|...|.#.|#..', ' ': '...|...|...|...|...',
};
function textCells(str, font, unit, adv, ox, oy) {
  const cells = [];
  [...str].forEach((ch, i) => {
    const g = font[ch];
    if (!g) throw new Error(`no glyph for ${JSON.stringify(ch)}`);
    g.split('|').forEach((row, y) => [...row].forEach((c, x) => {
      if (c !== '#') return;
      for (let a = 0; a < unit; a++) for (let b = 0; b < unit; b++) {
        cells.push([ox + (i * adv + x) * unit + a, oy + y * unit + b]);
      }
    }));
  });
  return cells;
}
const tinyW = (str) => str.length * 4 - 1;

// ------------------------------------------------------------ document
const defs = [];
const css = [];

// ===================================================== DISSOLVE + WINDOWS
// noise: a 32x32 tile, 1024 cells shuffled into 16 groups of 64
function noisePatterns() {
  const rnd = mulberry32(1992);
  const idx = [...Array(1024).keys()];
  for (let i = idx.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    [idx[i], idx[j]] = [idx[j], idx[i]];
  }
  const groups = Array.from({ length: G }, () => []);
  idx.forEach((cell, order) => groups[order >> 6].push([cell & 31, cell >> 5]));
  groups.forEach((cells, g) => {
    defs.push(`<pattern id="ng${g}" patternUnits="userSpaceOnUse" width="32" height="32">`
      + `<path stroke="#fff" d="${runsD(cells)}"/></pattern>`);
  });
}
// part k is fully on from 6k; its dissolve runs over the beat before.
const switchAt = (k, g) => PART * k - DIS + (g * DIS) / G;
// Parts are stacked in order, each new one on top of the last, so a part only
// needs its mask while it speckles in: the part beneath stays whole until the
// dissolve is done, and any hairline between two noise groups just shows the
// old picture. The sea sits at the bottom and needs no mask at all; the last
// part speckles OUT on top of it instead.
const VIS = PART + DIS + 0.2;                       // painted window per part
function windowsCSS() {
  const kf = (name, prop, len, onV, offV) => {
    css.push(`@keyframes ${name}{0%{${prop}:${onV}}${n((len / LOOP) * 100, 4)}%{${prop}:${offV}}}`
      + `.${name}{${prop}:${offV};animation:${name} ${LOOP}s step-end infinite}`);
  };
  kf('gi', 'opacity', PART + DIS, 1, 0);            // groups, parts 2-4: on until covered
  kf('si', 'opacity', PART, 1, 0);                  // solid, parts 2-4
  kf('go', 'opacity', PART, 1, 0);                  // groups, last part: speckles out
  kf('so', 'opacity', PART - DIS + DIS / G, 1, 0);  // solid, last part
  kf('v', 'visibility', VIS, 'visible', 'hidden');
  css.push('.sea.v{visibility:visible}');
}
function part(k, body) {
  const vis = `style="animation-delay:${ph(PART * k - DIS - 0.1)}"`;
  if (k === 0) return `<g class="sea v" ${vis}>${body}</g>`;
  const last = k === NPART - 1;
  let m = `<mask id="m${k}" maskUnits="userSpaceOnUse" x="0" y="0" width="${W}" height="${H}">`;
  for (let g = 0; g < G; g++) {
    m += `<rect class="${last ? 'go' : 'gi'}" style="animation-delay:${ph(switchAt(k, g))}" width="${W}" height="${H}" fill="url(#ng${g})"/>`;
  }
  m += `<rect class="${last ? 'so' : 'si'}" style="animation-delay:${ph(switchAt(k, G - 1))}" width="${W}" height="${H}" fill="#fff"/></mask>`;
  defs.push(m);
  return `<g class="v" ${vis} mask="url(#m${k})">${body}</g>`;
}

// ================================================================ 1. SEA
const HOR = 66;
// the palm, shared with SIGNAL: its rings start where the crown was
const PALM_BASE_X = 188;
const PALM_BASE_Y = 116;
const TOPY = 58;
const trunkX = (t) => PALM_BASE_X - 9 * Math.pow(t, 1.7) + 2 * Math.sin(t * 3);
const PALM_TOP = [Math.round(trunkX(1)), TOPY];
function seaPart() {
  let s = '';
  // --- sky: four VGA blues with 2x2 ordered-dither steps between them
  const SKY = [VH(0, 22), VH(0, 21), VH(1, 21), VH(2, 21)];
  const bayer = [[0, 2], [3, 1]];
  [1, 2, 3].forEach((lvl) => SKY.slice(1).forEach((c, i) => {
    let d = '';
    for (let y = 0; y < 2; y++) for (let x = 0; x < 2; x++) if (bayer[y][x] < lvl) d += `M${x} ${y}h1v1h-1z`;
    defs.push(`<pattern id="d${i}${lvl}" patternUnits="userSpaceOnUse" width="2" height="2"><path fill="${c}" d="${d}"/></pattern>`);
  }));
  const bands = [[0, 10], [16, 30], [36, 46], [52, HOR + 1]];
  bands.forEach(([y0, y1], i) => {
    s += `<rect y="${y0}" width="${W}" height="${y1 - y0}" fill="${SKY[i]}"/>`;
    if (i < 3) {
      for (let lvl = 1; lvl <= 3; lvl++) {
        const y = y1 + (lvl - 1) * 2;
        s += `<rect y="${y}" width="${W}" height="2" fill="${SKY[i]}"/><rect y="${y}" width="${W}" height="2" fill="url(#d${i}${lvl})"/>`;
      }
    }
  });

  // --- the sun and two clouds: circles without square roots
  const sky = new Canvas();
  const disc = (cx, cy, r, c, keep = null) => {
    for (let y = Math.floor(cy - r); y <= cy + r; y++) for (let x = Math.floor(cx - r); x <= cx + r; x++) {
      const dx = x + 0.5 - cx;
      const dy = y + 0.5 - cy;
      if (dx * dx + dy * dy <= r * r && x >= 0 && x < W && y >= 0 && (!keep || keep(x, y))) sky.set(x, y, c);
    }
  };
  disc(304, 2, 19, VH(1, 12));
  disc(304, 2, 15, VH(2, 12));
  disc(304, 2, 11, EGA(15));
  const cloud = (cx, cy, puffs) => {
    const base = (x, y) => y <= cy + 3;
    puffs.forEach(([dx, dy, r]) => disc(cx + dx, cy + dy, r, VH(2, 21), base));
    puffs.forEach(([dx, dy, r]) => disc(cx + dx, cy + dy - 1, r - 0.6, EGA(15), base));
  };
  cloud(46, 54, [[-12, 1, 4.5], [-5, -2, 6], [4, -3, 7], [12, 0, 5], [18, 2, 3.5]]);
  cloud(268, 50, [[-8, 1, 3.5], [-2, -2, 5], [6, -1, 5.5], [12, 1, 3.5]]);
  s += sky.paths();

  // --- the sea: (u xor v) on a plane, strip by strip
  // 16x16 texel tile; colour by the top two bits of (u xor v)
  const SEA = [VH(0, 23), VH(0, 22), VH(0, 21), VH(1, 21)];
  const tile = new Canvas();
  for (let v = 0; v < 16; v++) for (let u = 0; u < 16; u++) tile.set(u, v, SEA[((u ^ v) >> 2) & 3]);
  defs.push(`<pattern id="sea" patternUnits="userSpaceOnUse" width="16" height="16">${tile.paths()}</pattern>`);
  css.push(`.sc{animation:sc ${BAR}s linear infinite;animation-delay:${ph(0, BAR)}}@keyframes sc{from{transform:translateY(0)}to{transform:translateY(-16px)}}`);
  const HC = 10;              // camera height, in texels
  const DV = 2900;            // v = DV / (row - horizon)
  const vAt = (y) => DV / (y - HOR);
  let y = HOR + 1;
  let fog = '';
  const HAZE = VH(2, 21);
  while (y < H) {
    const dy = y - HOR;
    const h = Math.min(H - y, Math.max(1, Math.round(dy / 11)));
    const v0 = vAt(y);
    const v1 = vAt(y + h);
    const sx = (dy + h / 2) / HC;
    const sy = h / (v0 - v1);
    const uw = W / 2 / sx + 2;
    s += `<svg y="${y}" width="${W}" height="${h}"><g transform="translate(160 0) scale(${n(sx, 4)} ${n(-sy, 5)}) translate(0 ${n(-v0, 3)})">`
      + `<rect class="sc" x="${n(-uw)}" y="${n(v1 - 1, 3)}" width="${n(2 * uw)}" height="${n(v0 - v1 + 18, 3)}" fill="url(#sea)"/></g></svg>`;
    const f = Math.max(0, 1 - (dy + h / 2) / 34);
    const q = Math.round(Math.pow(f, 1.25) * 8) / 8;
    if (q > 0) fog += `<rect y="${y}" width="${W}" height="${h}" opacity="${q}"/>`;
    y += h;
  }
  s += `<g fill="${HAZE}">${fog}<rect y="${HOR}" width="${W}" height="1"/></g>`;

  // glints: four groups, each lit for one beat of the bar; bigger when near
  const rnd = mulberry32(80);
  const glints = [new Canvas(), new Canvas(), new Canvas(), new Canvas()];
  for (let i = 0; i < 64; i++) {
    const gx = Math.floor(rnd() * (W - 8)) + 4;
    const gy = Math.floor(HOR + 6 + Math.pow(rnd(), 0.8) * (H - HOR - 10));
    const nearIsland = ((gx - 178) / 50) ** 2 + ((gy - 121) / 17) ** 2 < 1;
    const underCaption = gx > 214 && gy > 132;
    if (nearIsland || underCaption) continue;
    const cv = glints[i % 4];
    const len = gy < HOR + 22 ? 1 : gy < HOR + 50 ? 2 : 3;
    for (let k = 0; k < len; k++) cv.set(gx + k, gy, EGA(15));
    if (len === 3) { cv.set(gx + 1, gy - 1, VH(2, 21)); cv.set(gx + 1, gy + 1, VH(2, 21)); }
  }
  css.push(`@keyframes gl{0%{opacity:1}25%{opacity:0}}.gl{opacity:0;animation:gl ${BAR}s step-end infinite}`);
  glints.forEach((cv, i) => { s += `<g class="gl" style="animation-delay:${ph(i * BEAT, BAR)}">${cv.paths()}</g>`; });

  // --- the island, the palm, the raft, her
  const isl = new Canvas();
  const ICX = 178;
  const ICY = 121;
  const IA = 37;
  const IB = 8.5;
  const inEll = (x, y, a, b) => {
    const dx = (x + 0.5 - ICX) / a;
    const dy = (y + 0.5 - ICY) / b;
    return dx * dx + dy * dy;
  };
  for (let yy = ICY - 12; yy <= ICY + 12; yy++) for (let xx = ICX - IA - 6; xx <= ICX + IA + 6; xx++) {
    const e = inEll(xx, yy, IA, IB);
    if (e <= 1) {
      let c = VH(2, 12);                       // dry sand
      if (yy + 0.5 > ICY + IB * 0.25) c = VH(2, 11);
      if (e > 0.62 && yy + 0.5 > ICY) c = VH(1, 10);   // wet rim
      isl.set(xx, yy, c);
    }
  }
  // shallow water ring: a lighter turquoise halo around the sand
  const shallow = new Canvas();
  for (let yy = ICY - 14; yy <= ICY + 14; yy++) for (let xx = ICX - IA - 10; xx <= ICX + IA + 10; xx++) {
    const e = inEll(xx, yy, IA + 7, IB + 4);
    if (e <= 1 && inEll(xx, yy, IA, IB) > 1) shallow.set(xx, yy, VH(0, 20));
  }
  // foam: two frames, swapped on every beat
  const foamA = new Canvas();
  const foamB = new Canvas();
  for (let yy = ICY - 14; yy <= ICY + 14; yy++) for (let xx = ICX - IA - 6; xx <= ICX + IA + 6; xx++) {
    const e = inEll(xx, yy, IA + 2, IB + 1.6);
    if (e <= 1 && inEll(xx, yy, IA, IB) > 1) {
      const k = (xx * 3 + yy * 5) % 4;
      if (k === 0 || k === 1) foamA.set(xx, yy, EGA(15));
      if (k === 2 || k === 3) foamB.set(xx, yy, EGA(15));
    }
  }
  // grass and two rocks
  [[-24, -3], [-22, -4], [-21, -3], [-19, -4], [-18, -3], [-26, -2], [-17, -2], [6, -5], [8, -6], [9, -5], [11, -5], [7, -4], [10, -4]]
    .forEach(([dx, dy], i) => isl.set(ICX + dx, ICY + dy, i % 3 ? EGA(2) : EGA(10)));
  [[-30, 4, 8], [-29, 4, 7], [-29, 3, 7], [26, 5, 8], [27, 5, 8], [27, 4, 7]]
    .forEach(([dx, dy, c]) => isl.set(ICX + dx, ICY + dy, EGA(c)));

  // palm: a trunk that leans and curls, segmented bark, fronds that droop
  const palm = new Canvas();
  const BY = PALM_BASE_Y;
  for (let yy = BY; yy >= TOPY; yy--) {
    const t = (BY - yy) / (BY - TOPY);
    const x = Math.round(trunkX(t));
    const seg = Math.floor((BY - yy) / 3) % 2;
    palm.set(x, yy, seg ? EGA(6) : VH(3, 10));
    palm.set(x + 1, yy, seg ? VH(3, 10) : VH(6, 10));
    if (t < 0.12) palm.set(x - 1, yy, EGA(6));
  }
  const [CX, CY] = PALM_TOP;
  const fronds = [[-172, 21, 0.05], [-150, 20, 0.04], [-122, 14, 0.06], [-60, 14, 0.06], [-30, 20, 0.04], [-6, 22, 0.05], [150, 15, 0.03], [35, 15, 0.03], [-92, 10, 0.1]];
  fronds.forEach(([deg, len, droop]) => {
    const a = (deg * Math.PI) / 180;
    for (let i = 1; i <= len; i++) {
      const x = CX + Math.cos(a) * i;
      const yv = CY + Math.sin(a) * i + droop * i * i;
      const px = Math.round(x);
      const py = Math.round(yv);
      palm.set(px, py, EGA(10));
      const w = Math.round(2.4 * Math.sin((i / len) * Math.PI));
      for (let j = 1; j <= w; j++) palm.set(px, py + j, j === w ? VH(3, 16) : EGA(2));
    }
  });
  [[0, 1], [1, 1], [-1, 2], [1, 2], [0, 2]].forEach(([dx, dy], i) => palm.set(CX + dx, CY + dy, i % 2 ? EGA(6) : VH(3, 10)));

  // raft: four lashed logs
  const raft = new Canvas();
  for (let i = 0; i < 4; i++) {
    for (let x = 0; x < 19; x++) raft.set(222 + x - i, 120 + i, x === 0 || x === 18 ? VH(3, 10) : i % 2 ? EGA(6) : VH(1, 10));
  }
  [[226, 120], [225, 121], [224, 122], [223, 123], [234, 120], [233, 121], [232, 122], [231, 123]].forEach(([x, yy]) => raft.set(x, yy, VH(2, 11)));

  // her: brown hair in a low bun, cream headphones, coral tank top, cream
  // shorts, bare feet. A dark outline keeps her off the sand.
  const HER = {
    h: VH(3, 10), c: VH(2, 11), s: VH(1, 10), e: VH(6, 10), t: EGA(12), T: VH(1, 8), w: VH(2, 11),
  };
  const head = ['..hhh..', '.hhhhh.', 'chssshc', 'chesehc', '..sssh.'];
  const body = ['.sTTTs.', '.ttttt.', 'sttttts', 's.ttt.s', '..www..', '..w.w..', '..s.s..', '..s.s..', '.ss.ss.'];
  const HX = 160;
  const HY = 102;
  const outlined = (rows, oy) => {
    const cv = new Canvas();
    const filled = new Set();
    rows.forEach((row, y) => [...row].forEach((ch, x) => { if (HER[ch]) filled.add(`${x},${y}`); }));
    rows.forEach((row, y) => [...row].forEach((ch, x) => {
      if (!HER[ch]) return;
      for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
        if (!filled.has(`${x + dx},${y + dy}`)) cv.set(HX + x + dx, oy + y + dy, VH(6, 10));
      }
    }));
    sprite(rows, HER, cv, HX, oy);
    return cv;
  };
  const herBody = outlined(body, HY + head.length);
  const herHead = outlined(head, HY);
  css.push(`.nod{animation:nod ${BEAT}s step-end infinite;animation-delay:${ph(0, BEAT)}}@keyframes nod{0%{transform:translateY(1px)}35%{transform:translateY(0)}}`);
  css.push(`.foa{animation:foa ${2 * BEAT}s step-end infinite;animation-delay:${ph(0, 2 * BEAT)}}@keyframes foa{0%{opacity:1}50%{opacity:0}}`);
  css.push(`.fob{animation:fob ${2 * BEAT}s step-end infinite;animation-delay:${ph(0, 2 * BEAT)}}@keyframes fob{0%{opacity:0}50%{opacity:1}}`);
  css.push(`.bob{animation:bob ${BAR}s step-end infinite;animation-delay:${ph(0, BAR)}}@keyframes bob{0%{transform:translateY(0)}50%{transform:translateY(1px)}}`);

  defs.push(`<pattern id="shc" patternUnits="userSpaceOnUse" width="2" height="2"><path fill="${VH(1, 20)}" d="M0 0h1v1h-1zM1 1h1v1h-1z"/></pattern>`);
  s += shallow.paths() + shallow.paths(1, 0, 0).replace(/fill="[^"]+"/, 'fill="url(#shc)"') + isl.paths()
    + `<g class="foa">${foamA.paths()}</g><g class="fob">${foamB.paths()}</g>`
    + `<g class="bob">${raft.paths()}</g>`
    + palm.paths()
    + herBody.paths() + `<g class="nod">${herHead.paths()}</g>`;
  return s;
}

// ================================================================ 2. SAND
function sandPart() {
  // 9 VGA entries from cream to dark brown, ping-ponged to 16
  const R9 = [VH(2, 12), VH(2, 11), VH(2, 10), VH(1, 10), VH(1, 9), VH(1, 8), EGA(12), EGA(6), VH(3, 10)];
  const R = [...R9, ...R9.slice(1, 8).reverse()];
  const P = 2 * BAR;
  let kf = '';
  R.forEach((c, i) => { kf += `${n((i / 16) * 100, 3)}%{stroke:${c}}`; });
  css.push(`@keyframes cy{${kf}}.cy{animation:cy ${P}s step-end infinite}`);
  // tile: 64 px; 2 px texels; 8 px blocks, each a 4x4 chessboard;
  // block colour from (bx xor by), chess squares 3 ramp steps apart
  let tile = '';
  for (let q = 0; q < 8; q++) for (let chess = 0; chess < 2; chess++) {
    const cells = [];
    for (let by = 0; by < 8; by++) {
      const bx = by ^ q;
      for (let ty = 0; ty < 4; ty++) for (let tx = 0; tx < 4; tx++) {
        if (((tx ^ ty) & 1) !== chess) continue;
        cells.push([bx * 4 + tx, by * 4 + ty]);
      }
    }
    const idx = q + 3 * chess;
    tile += `<path class="cy" style="animation-delay:${ph((-idx * P) / 16, P)}" stroke="${R[idx % 16]}" stroke-width="2" d="${runsD(cells, 2)}"/>`;
  }
  defs.push(`<pattern id="sand" patternUnits="userSpaceOnUse" width="64" height="64">${tile}</pattern>`);
  css.push(`.sd{animation:sd ${PART}s linear infinite;animation-delay:${ph(0, PART)}}@keyframes sd{from{transform:translate(0,0)}to{transform:translate(-64px,-64px)}}`);
  return `<rect width="${W}" height="${H}" fill="${R[0]}"/><rect class="sd" width="${W + 64}" height="${H + 64}" fill="url(#sand)"/>`;
}

// ================================================================ 3. PALM
// (x and y) = 0 is the union of "blank" squares, one periodic pattern per bit
// level k: tile 2^(k+1), blank square at (2^k, 2^k). Drawn finest first, so a
// pixel takes the colour of the coarsest level that blanks it. Zooming x2
// about the origin turns level k into level k+1, so the zoom loops when each
// level's colour slides to the next level's and level 0 fades in while it is
// still sub-pixel. The figure is taken of (|x|, |y|), so four copies meet at
// the corner like a compass rose. (With plain signed x and y every high bit is
// set in the (-,-) quadrant, which then fills with one flat colour: a quarter
// of the screen doing nothing, and not in the good way.) The view never
// reaches 512 texels from the corner, so level 9 is the last one that matters.
function palmPart() {
  const SET = VH(2, 15);                           // the figure itself: pale lime lace
  const LV = [VH(1, 15), VH(1, 16), EGA(10), VH(0, 15), VH(0, 16), EGA(2)];  // holes, finest to coarsest
  const K = 10;
  const col = (k) => LV[Math.min(k, LV.length - 1)];
  const Z = BAR;
  let s = `<rect width="800" height="800" fill="${SET}"/>`;
  // pattern contents inherit from the pattern, not from the rect that uses
  // it, so each level's colour track runs on the squares inside its pattern
  css.push(`@keyframes l0o{from{opacity:0}to{opacity:1}}.l0o{animation:l0o ${Z}s linear infinite;animation-delay:${ph(0, Z)}}`);
  for (let k = 0; k < K; k++) {
    const p = 2 ** (k + 1);
    const q = 2 ** k;
    const a = col(k);
    const b = col(k + 1);
    let cls = '';
    if (a !== b) {
      css.push(`@keyframes l${k}{from{fill:${a}}to{fill:${b}}}.l${k}{animation:l${k} ${Z}s linear infinite;animation-delay:${ph(0, Z)}}`);
      cls = ` class="l${k}"`;
    }
    // big squares grow a hair (wrapped round the tile) so neighbours of the
    // same colour do not show a seam of lace colour between them
    const e = k >= 4 ? 0.3 : 0;
    let sq = '';
    for (const [ox, oy] of e ? [[0, 0], [-p, 0], [0, -p], [-p, -p]] : [[0, 0]]) {
      sq += `M${n(q + ox - e)} ${n(q + oy - e)}h${n(q + 2 * e)}v${n(q + 2 * e)}h${n(-q - 2 * e)}z`;
    }
    defs.push(`<pattern id="sp${k}" patternUnits="userSpaceOnUse" width="${p}" height="${p}"><path${cls} fill="${a}" d="${sq}"/></pattern>`);
    s += `<rect${k === 0 ? ' class="l0o" opacity="0"' : ''} width="800" height="800" fill="url(#sp${k})"/>`;
  }
  // one quadrant, mirrored into the other three
  s = [[1, 1], [-1, 1], [1, -1], [-1, -1]].map(([a, b]) => (a === 1 && b === 1 ? `<g>${s}</g>` : `<g transform="scale(${a} ${b})">${s}</g>`)).join('');
  // exponential zoom x2 per bar about the figure's corner, sampled; the
  // corner sits off centre and the whole view turns once per loop
  let zk = '';
  const ZS = 24;
  for (let i = 0; i <= ZS; i++) zk += `${n((i / ZS) * 100, 3)}%{transform:scale(${n(0.5 * 2 ** (i / ZS), 5)})}`;
  css.push(`@keyframes zz{${zk}}.zz{animation:zz ${Z}s linear infinite;animation-delay:${ph(0, Z)}}`);
  css.push(`@keyframes rr{from{transform:rotate(0deg)}to{transform:rotate(-360deg)}}.rr{animation:rr ${LOOP}s linear infinite;animation-delay:${ph(0)}}`);
  return `<g transform="translate(${W / 2} ${H / 2 + 6})"><g class="rr"><g transform="translate(-46 -30)"><g class="zz">${s}</g></g></g></g>`;
}

// ============================================================== 4. SIGNAL
function signalPart() {
  const NR = 72;
  const RW = 3;
  const RMAX = NR * RW;
  const P = 7.5;                                   // one ring width every P/72 s
  const [CX, CY] = PALM_TOP;                       // one bar of signal, at the top of the palm
  let s = '';
  for (let i = 0; i < NR; i++) {
    const start = (i / NR) * P;                    // ring i is at radius RMAX * (t + start) / P
    s += `<circle r="0" stroke="${VH(1, i % 24)}"><animate attributeName="r" values="0;${RMAX}" dur="${P}s"`
      + ` begin="${n(-start - (T0 % P), 3)}s" repeatCount="indefinite"/></circle>`;
  }
  return `<rect width="${W}" height="${H}" fill="${VH(1, 0)}"/>`
    + `<g transform="translate(${CX} ${CY})" fill="none" stroke-width="${RW + 0.4}">${s}</g>`;
}

// ================================================================= 5. SKY
function skyPart() {
  // cell sizes that never line up, three directions, three speeds; each
  // layer moves a whole number of checker periods per loop of its own
  const layers = [
    { cell: 6, c: VH(0, 22), dx: 12, dy: 0, dur: BAR, op: 1 },
    { cell: 14, c: VH(1, 21), dx: -28, dy: 28, dur: BAR, op: 1 },
    { cell: 30, c: VH(2, 21), dx: -60, dy: -60, dur: 2 * BAR, op: 0.82 },
  ];
  let s = `<rect width="${W}" height="${H}" fill="${VH(0, 23)}"/>`;
  layers.forEach(({ cell, c, dx, dy, dur, op }, i) => {
    const p = 2 * cell;
    defs.push(`<pattern id="ck${i}" patternUnits="userSpaceOnUse" width="${p}" height="${p}"><path fill="${c}" d="M0 0h${cell}v${cell}h-${cell}zM${cell} ${cell}h${cell}v${cell}h-${cell}z"/></pattern>`);
    css.push(`@keyframes k${i}{from{transform:translate(0,0)}to{transform:translate(${dx}px,${dy}px)}}.k${i}{animation:k${i} ${dur}s linear infinite;animation-delay:${ph(0, dur)}}`);
    s += `<rect class="k${i}" x="-${2 * p}" y="-${2 * p}" width="${W + 4 * p}" height="${H + 4 * p}" fill="url(#ck${i})"${op < 1 ? ` opacity="${op}"` : ''}/>`;
  });
  return s;
}

// ================================================================= NAME
function nameLayer() {
  const U = 6;
  const str = 'CASTAWAY';
  const w = (str.length * 6 - 1) * U;
  const x0 = Math.round((W - w) / 2);
  return `<path fill="#000" d="${cellsPath(textCells(str, BIG, 1, 6, 0, 0), U, x0, 12)}"/>`;
}
// Each caption glyph is a <use> of a two-letter id at a fixed x, and every
// digit is always defined, so the file's length does not depend on which
// digits the caption shows: the size it prints can be the size it is.
const qid = (ch) => `q${ch === ',' ? 'c' : ch === ' ' ? 's' : ch}`;
function captionDefs() {
  const chars = [...new Set([...'0123456789,', ...'BYTESGIVEORAK'])];
  for (const ch of chars) {
    defs.push(`<path id="${qid(ch)}" d="${cellsPath(textCells(ch, TINY, 1, 4, 0, 0))}"/>`);
  }
}
function captionLine(str, x, y, fill) {
  let uses = '';
  [...str].forEach((ch, i) => {
    if (ch === ' ') return;
    if (!TINY[ch]) throw new Error(`no tiny glyph for ${ch}`);
    uses += `<use href="#${qid(ch)}" x="${i * 4}"/>`;
  });
  return `<g fill="${fill}" transform="translate(${x} ${y})">${uses}</g>`;
}
function caption(bytes) {
  const over = (bytes - 256).toLocaleString('en-US');
  const l1 = '256 BYTES';
  const l2 = `GIVE OR TAKE ${over}`;
  const cw = Math.max(tinyW(l1), tinyW(l2)) + 6;
  const ch = 5 + 2 + 5 + 6;
  const x = W - cw - 4;
  const y = H - ch - 4;
  return `<rect x="${x}" y="${y}" width="${cw}" height="${ch}" fill="#000"/>`
    + captionLine(l1, x + 3, y + 3, EGA(15)) + captionLine(l2, x + 3, y + 10, EGA(7));
}

// ================================================================= BUILD
function build(bytes) {
  defs.length = 0;
  css.length = 0;
  noisePatterns();
  captionDefs();
  windowsCSS();
  const parts = [seaPart(), sandPart(), palmPart(), signalPart(), skyPart()];
  let body = '';
  parts.forEach((p, k) => { body += part(k, p); });
  css.push('@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}');
  defs.push(`<clipPath id="frame"><rect width="${W}" height="${H}" rx="5"/></clipPath>`);
  const title = 'CASTAWAY, a 256-byte-style intro: sea, sand, palm, signal, sky';
  const desc = 'The name CASTAWAY in black block capitals over five looping tiny-intro effects in the stock VGA palette,'
    + ' two bars each at 80 BPM, each speckling into the next: an XOR-textured sea with her island, palm and raft;'
    + ' a grid of colour-cycling chessboards; a mirrored Sierpinski rotozoomer; pastel rings from the top of the palm;'
    + ' three sliding checkerboards. A corner caption says 256 BYTES, GIVE OR TAKE, and how many bytes over that the file really is.';
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="960" height="480" role="img" shape-rendering="crispEdges">`
    + `<title>${title}</title><desc>${desc}</desc><style>${css.join('')}</style><defs>${defs.join('')}</defs>`
    + `<g clip-path="url(#frame)"><rect width="${W}" height="${H}" fill="#000"/>${body}${nameLayer()}${caption(bytes)}</g></svg>\n`;
}

// The caption states this file's own size, so iterate to a fixed point.
let bytes = 60000;
let svg = build(bytes);
for (let i = 0; i < 12 && Buffer.byteLength(svg) !== bytes; i++) {
  bytes = Buffer.byteLength(svg);
  svg = build(bytes);
}
if (Buffer.byteLength(svg) !== bytes) throw new Error('caption size did not settle');

fs.mkdirSync(OUTDIR, { recursive: true });
const out = path.join(OUTDIR, `${SLUG}.svg`);
fs.writeFileSync(out, svg);
console.log(`${path.relative(process.cwd(), out)}  ${(svg.length / 1024).toFixed(1)} KB (${bytes} bytes)`);
