// "Atari 8-bit demo screen" README banner for CASTAWAY.
//
//   node examples/castaway/src/113-atari-8-bit-demo_opus_5.5.mjs
//   node examples/castaway/src/113-atari-8-bit-demo_opus_5.5.mjs --at=7.5 --out=some/where.svg
//   node examples/castaway/src/113-atari-8-bit-demo_opus_5.5.mjs --sheet=some/where.svg
//
// Regenerates ../assets/113-atari-8-bit-demo_opus_5.5.svg. Plain Node, no
// deps, deterministic (no clock, no Math.random). --at bakes a head start (in
// seconds) into every animation so later frames can be checked without
// waiting; use it only together with --out, never in place. --sheet writes a
// big contact sheet of the sprites and the 8x8 font, for pixel work.
//
// The style: an Atari 8-bit (800XL / 130XE) demo screen, catalogue entry
// demo-09. The machine builds its picture from a display list, one mode per
// row, and can fire an interrupt on any row to change the colour registers.
// The GTIA chip adds a mode only 80 pixels across (each pixel four hi-res
// pixels wide and one scanline tall) that shows sixteen brightness steps of
// ONE hue; the hue is whatever the register says on that scanline. So demo
// screens are soft, shaded, brick-like pictures whose tint changes band by
// band down the screen, with text rows and four-colour rows stacked in
// between, and small single-colour sprites (players and missiles) on top.
// Credited references, nothing copied: the hardware documentation on
// Wikipedia, and the Polish-centred scene's screens as described on Pouet and
// Demozoo. No group's logo, font, picture or words are reproduced; the letters,
// the 8x8 font, the island and the sprites are all drawn here.
//
// How the SVG does it (the real mechanism, not a picture of it)
//   * Units: x in hi-res pixels (352 across, the wide playfield), y in
//     scanlines (192 of them, the standard Atari screen). The viewBox adds an
//     8-unit border, so the frame is 368 x 208, close to 16:9.
//   * Palette: 16 hues x 16 luminances, built here in OKLCH (hue 0 is grey,
//     hues 1-15 go round the wheel 24 degrees apart). Every filled colour in
//     the picture is one of those 256.
//   * LOGO band (16-shade mode): the letters are a 0-15 luminance map on the
//     80-pixel grid, shaded by a little emboss (distance field -> normal ->
//     light from the top left). Each scanline is one <g>; inside it, one path
//     per luminance. The hue is not in the picture at all: one CSS keyframe
//     track per luminance walks round the hue wheel, and each scanline's
//     track is delayed by one step per line, so the hue bands roll up through
//     the letters like a per-scanline colour kernel, while the picture itself
//     never moves. That is the whole effect, and the whole joke.
//   * ISLAND band (16-shade mode + split colours + sprites): sky and sea are
//     pure per-scanline gradients whose hue steps every few lines, a sun of
//     luminance rings, clouds that drift by hardware-style fine scroll (two
//     hi-res pixels a step), an island, palm and raft in the same wide
//     pixels, sea glints that twinkle one beat in four and foam that swaps on
//     the half bar. She, the cat, the coconut crab and the bottle are drawn
//     like players: two-unit pixels laid over the picture, moved on the beat.
//   * TEXT rows (40-column mode, here 44 on the wide playfield): an 8x8 font
//     drawn for this file. In that mode the letters take the row's hue and
//     only choose a brightness, so each row is one hue; a stack of one-line
//     rects behind a clip of the glyphs scrolls up a line at a time, which is
//     the raster rolling through the text. The rows under the island use the
//     ten-line text mode (mode 3), so descenders clear the next row.
//   * TIMELINE row (four-colour mode, two-unit pixels): the real seed-1992
//     ten-hour run of activities.toml as of 2026-10-01, one pixel per 24
//     seconds, regular / occasional / rare in the three playfield colours and
//     the one super-rare event as a missile. Her activities are blocks as
//     long as they last; other lanes (cat, sea and sky, shore) are ticks. It
//     scrolls past under a NOW player, ten hours in four minutes, and wraps
//     without a seam.
//   * prefers-reduced-motion pauses every track where it starts, which is a
//     complete frame. Nothing flashes: each hue step keeps its brightness,
//     each logo line changes hue once per 0.8 s, and the sprites move on
//     the beat.
// (The .md beside the assets is hand-written, not generated by this script.)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const SLUG = '113-atari-8-bit-demo_opus_5.5';
const arg = (name) => {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const T0 = Number(arg('at') || 0);
const OUT = arg('out') ? path.resolve(arg('out')) : path.resolve(here, `../assets/${SLUG}.svg`);
const SHEET = arg('sheet') ? path.resolve(arg('sheet')) : null;
// --view=x,y,w,h and --scale=k: crop and enlarge, for close inspection only (with --out).
const VIEW = arg('view') ? arg('view').split(',').map(Number) : null;
const SCALE = Number(arg('scale') || 2);

// ------------------------------------------------------------------ screen
const SW = 352; // wide playfield, hi-res pixels
const SH = 192; // scanlines
const BX = 8;
const BY = 8;
const VW = SW + 2 * BX;
const VH = SH + 2 * BY;
const BEAT = 0.75; // 80 BPM
const BAR = 4 * BEAT; // 3 s, one bar of the theme

const n = (v, d = 3) => String(+(+v).toFixed(d));
const dly = (s) => `${n(s - T0, 4)}s`;
const mod = (a, m) => ((a % m) + m) % m;
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));

// A seeded integer hash, for textures (sea crests, sand speckle, bushes).
const hash2 = (x, y, s = 0) => {
  let h = (x * 374761393 + y * 668265263 + s * 2147483647) >>> 0;
  h = Math.imul(h ^ (h >>> 13), 1274126177) >>> 0;
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
};

// ------------------------------------------------------------------ palette
// 16 hues x 16 luminances. Hue 0 is the grey ramp; hues 1-15 step 24 degrees
// round the OKLCH wheel from amber, through red, violet, blue, cyan and green,
// back to yellow, which is the order the real chip's hues run in.
function oklchHex(L, C, hDeg) {
  const toRgb = (c) => {
    const h = (hDeg * Math.PI) / 180;
    const a = c * Math.cos(h);
    const b = c * Math.sin(h);
    const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
    const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
    const s_ = L - 0.0894841775 * a - 1.291485548 * b;
    const l = l_ ** 3;
    const m = m_ ** 3;
    const s = s_ ** 3;
    return [
      4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
      -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
      -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
    ];
  };
  let lo = 0;
  let hi = C;
  let rgb = toRgb(C);
  const ok = (v) => v.every((x) => x >= -0.0005 && x <= 1.0005);
  if (!ok(rgb)) {
    for (let i = 0; i < 24; i++) {
      const mid = (lo + hi) / 2;
      if (ok(toRgb(mid))) lo = mid;
      else hi = mid;
    }
    rgb = toRgb(lo);
  }
  const enc = (x) => {
    const v = clamp(x, 0, 1);
    const g = v <= 0.0031308 ? 12.92 * v : 1.055 * v ** (1 / 2.4) - 0.055;
    return Math.round(g * 255).toString(16).padStart(2, '0');
  };
  return `#${rgb.map(enc).join('')}`;
}
const HUE_DEG = [0, 75, 51, 27, 3, 339, 315, 291, 267, 243, 219, 195, 171, 147, 123, 99];
const PAL = [];
for (let h = 0; h < 16; h++) {
  PAL.push([]);
  for (let l = 0; l < 16; l++) {
    if (h === 0) {
      PAL[h].push(oklchHex(0.07 + 0.91 * (l / 15) ** 1.05, 0, 0));
    } else {
      const L = 0.2 + 0.77 * (l / 15) ** 0.95;
      const C = 0.17 * Math.sin((Math.PI * (l + 1.2)) / 17.6) ** 0.85;
      PAL[h].push(oklchHex(L, C, HUE_DEG[h]));
    }
  }
}
const col = (h, l) => PAL[h][clamp(Math.round(l), 0, 15)];

// Named hues for the island.
const H = {
  GREY: 0, AMBER: 1, ORANGE: 2, RED: 3, PINK: 4, MAGENTA: 5, VIOLET: 7, BLUE: 8,
  SKY: 9, AZURE: 10, CYAN: 11, TEAL: 12, GREEN: 13, LIME: 14, SAND: 15,
};

const defs = [];
const css = [];
const body = [];

// ------------------------------------------------------------------ runs -> paths
// grid: rows of colour strings (or null); pw: width of one pixel in units.
// Merges each colour into horizontal runs, stacks identical runs vertically.
function gridPaths(grid, pw, ox, oy) {
  const runs = new Map();
  grid.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const c = row[x];
      if (c == null) { x++; continue; }
      let e = x + 1;
      while (e < row.length && row[e] === c) e++;
      if (!runs.has(c)) runs.set(c, []);
      runs.get(c).push([x, e, y]);
      x = e;
    }
  });
  const out = new Map();
  for (const [c, list] of runs) {
    const live = new Set(list.map((r) => r.join(',')));
    const parts = [];
    for (const r of list) {
      const k = r.join(',');
      if (!live.has(k)) continue;
      live.delete(k);
      let hgt = 1;
      while (live.has(`${r[0]},${r[1]},${r[2] + hgt}`)) { live.delete(`${r[0]},${r[1]},${r[2] + hgt}`); hgt++; }
      const w = (r[1] - r[0]) * pw;
      parts.push(`M${n(ox + r[0] * pw)} ${n(oy + r[2])}h${n(w)}v${hgt}h${n(-w)}z`);
    }
    out.set(c, parts.join(''));
  }
  return out;
}
const pathsSvg = (map, attrs = '') => [...map].map(([c, d]) => `<path fill="${c}"${attrs} d="${d}"/>`).join('');

// ------------------------------------------------------------------ display list
// One mode per row band. y is in scanlines from the top of the screen. The
// text rows under the island are mode 3: ten lines a row, the glyph on the top
// eight and two lines of the row's own colour under it, so descenders clear
// the next row (and the last row clears the frame).
const DL = {
  credit: 0, // 8 lines, 40-column text
  logo: 8, // 44 lines, 16-shade mode
  tag: 52, // 8 lines, text
  island: 60, // 84 lines, 16-shade mode + players
  caption: 144, // 10 lines, text (mode 3)
  timeline: 154, // 8 lines, four-colour mode
  legend: 162, // 10 lines, text (mode 3) + missiles
  sound: 172, // 10 lines, text (mode 3)
  run: 182, // 10 lines, text (mode 3): 192 in all
};
const LOGO_H = 44;
const ISLAND_H = 84;

// ================================================================== 8x8 FONT
// Drawn for this file: mixed case, two-pixel verticals and one-pixel
// horizontals (one-pixel verticals smear on a TV), seven pixels wide, capitals
// seven rows high, lower case on a five-row x-height with one-row descenders.
const FONT = {
  A: ['..###..', '.##.##.', '##...##', '##...##', '#######', '##...##', '##...##'],
  B: ['######.', '##...##', '##...##', '######.', '##...##', '##...##', '######.'],
  C: ['.#####.', '##...##', '##.....', '##.....', '##.....', '##...##', '.#####.'],
  D: ['#####..', '##..##.', '##...##', '##...##', '##...##', '##..##.', '#####..'],
  E: ['#######', '##.....', '##.....', '######.', '##.....', '##.....', '#######'],
  F: ['#######', '##.....', '##.....', '######.', '##.....', '##.....', '##.....'],
  G: ['.#####.', '##...##', '##.....', '##.####', '##...##', '##...##', '.######'],
  H: ['##...##', '##...##', '##...##', '#######', '##...##', '##...##', '##...##'],
  I: ['######.', '..##...', '..##...', '..##...', '..##...', '..##...', '######.'],
  J: ['....###', '.....##', '.....##', '.....##', '##...##', '##...##', '.#####.'],
  K: ['##...##', '##..##.', '##.##..', '####...', '##.##..', '##..##.', '##...##'],
  L: ['##.....', '##.....', '##.....', '##.....', '##.....', '##.....', '#######'],
  M: ['##...##', '###.###', '#######', '##.#.##', '##...##', '##...##', '##...##'],
  N: ['##...##', '###..##', '####.##', '##.####', '##..###', '##...##', '##...##'],
  O: ['.#####.', '##...##', '##...##', '##...##', '##...##', '##...##', '.#####.'],
  P: ['######.', '##...##', '##...##', '######.', '##.....', '##.....', '##.....'],
  Q: ['.#####.', '##...##', '##...##', '##...##', '##.#.##', '##..##.', '.###.##'],
  R: ['######.', '##...##', '##...##', '######.', '##.##..', '##..##.', '##...##'],
  S: ['.#####.', '##...##', '##.....', '.#####.', '.....##', '##...##', '.#####.'],
  T: ['######.', '..##...', '..##...', '..##...', '..##...', '..##...', '..##...'],
  U: ['##...##', '##...##', '##...##', '##...##', '##...##', '##...##', '.#####.'],
  V: ['##...##', '##...##', '##...##', '##...##', '.##.##.', '.##.##.', '..###..'],
  W: ['##...##', '##...##', '##...##', '##.#.##', '#######', '###.###', '##...##'],
  X: ['##...##', '##...##', '.##.##.', '..###..', '.##.##.', '##...##', '##...##'],
  Y: ['##..##.', '##..##.', '##..##.', '.####..', '..##...', '..##...', '..##...'],
  Z: ['#######', '.....##', '....##.', '..###..', '.##....', '##.....', '#######'],
  a: ['.......', '.......', '.#####.', '.....##', '.######', '##...##', '.######'],
  b: ['##.....', '##.....', '######.', '##...##', '##...##', '##...##', '######.'],
  c: ['.......', '.......', '.######', '##.....', '##.....', '##.....', '.######'],
  d: ['.....##', '.....##', '.######', '##...##', '##...##', '##...##', '.######'],
  e: ['.......', '.......', '.#####.', '##...##', '#######', '##.....', '.######'],
  f: ['...####', '..##...', '######.', '..##...', '..##...', '..##...', '..##...'],
  g: ['.......', '.......', '.######', '##...##', '##...##', '.######', '.....##', '.#####.'],
  h: ['##.....', '##.....', '######.', '##...##', '##...##', '##...##', '##...##'],
  i: ['..##...', '.......', '.###...', '..##...', '..##...', '..##...', '.####..'],
  j: ['....##.', '.......', '...###.', '....##.', '....##.', '....##.', '##..##.', '.####..'],
  k: ['##.....', '##.....', '##..##.', '##.##..', '####...', '##.##..', '##..##.'],
  l: ['.###...', '..##...', '..##...', '..##...', '..##...', '..##...', '.####..'],
  m: ['.......', '.......', '###.##.', '#######', '##.#.##', '##.#.##', '##...##'],
  n: ['.......', '.......', '######.', '##...##', '##...##', '##...##', '##...##'],
  o: ['.......', '.......', '.#####.', '##...##', '##...##', '##...##', '.#####.'],
  p: ['.......', '.......', '######.', '##...##', '##...##', '######.', '##.....', '##.....'],
  q: ['.......', '.......', '.######', '##...##', '##...##', '.######', '.....##', '.....##'],
  r: ['.......', '.......', '##.###.', '###..##', '##.....', '##.....', '##.....'],
  s: ['.......', '.......', '.######', '##.....', '.#####.', '.....##', '######.'],
  t: ['..##...', '..##...', '######.', '..##...', '..##...', '..##...', '...###.'],
  u: ['.......', '.......', '##...##', '##...##', '##...##', '##...##', '.######'],
  v: ['.......', '.......', '##...##', '##...##', '##...##', '.##.##.', '..###..'],
  w: ['.......', '.......', '##...##', '##.#.##', '##.#.##', '#######', '.##.##.'],
  x: ['.......', '.......', '##...##', '.##.##.', '..###..', '.##.##.', '##...##'],
  y: ['.......', '.......', '##...##', '##...##', '##...##', '.######', '.....##', '.#####.'],
  z: ['.......', '.......', '#######', '....##.', '..###..', '.##....', '#######'],
  0: ['.#####.', '##...##', '##..###', '##.#.##', '###..##', '##...##', '.#####.'],
  1: ['..##...', '.###...', '..##...', '..##...', '..##...', '..##...', '.####..'],
  2: ['.#####.', '##...##', '.....##', '...###.', '.##....', '##.....', '#######'],
  3: ['######.', '....##.', '...##..', '....##.', '.....##', '##...##', '.#####.'],
  4: ['...###.', '..####.', '.##.##.', '##..##.', '#######', '....##.', '....##.'],
  5: ['#######', '##.....', '######.', '.....##', '.....##', '##...##', '.#####.'],
  6: ['..####.', '.##....', '##.....', '######.', '##...##', '##...##', '.#####.'],
  7: ['#######', '.....##', '....##.', '...##..', '..##...', '..##...', '..##...'],
  8: ['.#####.', '##...##', '##...##', '.#####.', '##...##', '##...##', '.#####.'],
  9: ['.#####.', '##...##', '##...##', '.######', '.....##', '....##.', '.####..'],
  '.': ['.......', '.......', '.......', '.......', '.......', '..##...', '..##...'],
  ',': ['.......', '.......', '.......', '.......', '.......', '..##...', '..##...', '.##....'],
  ':': ['.......', '..##...', '..##...', '.......', '.......', '..##...', '..##...'],
  ';': ['.......', '..##...', '..##...', '.......', '.......', '..##...', '..##...', '.##....'],
  '!': ['..##...', '..##...', '..##...', '..##...', '..##...', '.......', '..##...'],
  '?': ['.#####.', '##...##', '....##.', '...##..', '...##..', '.......', '...##..'],
  '-': ['.......', '.......', '.......', '.#####.', '.......', '.......', '.......'],
  '+': ['.......', '..##...', '..##...', '######.', '..##...', '..##...', '.......'],
  '/': ['.....##', '....##.', '....##.', '...##..', '..##...', '.##....', '##.....'],
  '(': ['...##..', '..##...', '.##....', '.##....', '.##....', '..##...', '...##..'],
  ')': ['.##....', '..##...', '...##..', '...##..', '...##..', '..##...', '.##....'],
  "'": ['..##...', '..##...', '.##....', '.......', '.......', '.......', '.......'],
  '>': ['.##....', '..##...', '...##..', '....##.', '...##..', '..##...', '.##....'],
  '=': ['.......', '.......', '######.', '.......', '######.', '.......', '.......'],
  '*': ['.......', '.##.##.', '..###..', '#######', '..###..', '.##.##.', '.......'],
  '_': ['.......', '.......', '.......', '.......', '.......', '.......', '.......', '#######'],
  '·': ['.......', '.......', '.......', '..##...', '.......', '.......', '.......'],
  '~': ['...##..', '...###.', '...#.##', '...#...', '.###...', '####...', '.##....'], // a quaver
  ' ': [],
};
const GLYPH = new Map();
function glyph(ch) {
  if (GLYPH.has(ch)) return GLYPH.get(ch);
  const rows = FONT[ch];
  if (!rows) throw new Error(`no glyph for "${ch}"`);
  const grid = rows.map((r) => [...r].map((c) => (c === '#' ? 'x' : null)));
  const d = gridPaths(grid, 1, 0, 0).get('x');
  const id = `g${GLYPH.size.toString(36)}`;
  GLYPH.set(ch, d ? id : null);
  if (d) defs.push(`<path id="${id}" d="${d}"/>`);
  return d ? id : null;
}

// One 40-column text row: plain dark hue behind, letters of the same hue whose
// brightness is set per scanline by a rolling table (the raster in the text).
let textRowCount = 0;
// lines: 8 for mode 2, 10 for mode 3 (two more lines of background under it).
function textRow(y, str, { hue, bg, lums, dur = BAR, col0 = null, align = 'center', lines = 8 }) {
  if ([...str].length > 44) throw new Error(`text row too long (${[...str].length}): ${str}`);
  const id = `t${textRowCount++}`;
  const len = [...str].length;
  const c0 = col0 ?? (align === 'center' ? Math.floor((44 - len) / 2) : 1);
  const uses = [];
  [...str].forEach((ch, i) => {
    const g = glyph(ch);
    if (g) uses.push(`<use href="#${g}" x="${BX + (c0 + i) * 8}" y="${BY + y}"/>`);
  });
  defs.push(`<clipPath id="${id}">${uses.join('')}</clipPath>`);
  const P = lums.length;
  const rects = [];
  for (let i = 0; i < 8 + P; i++) {
    rects.push(`<rect x="${BX}" y="${BY + y + i}" width="${SW}" height="1" fill="${col(hue, lums[i % P])}"/>`);
  }
  css.push(`@keyframes r${id}{from{transform:translateY(0)}to{transform:translateY(-${P}px)}}`);
  const bgRect = bg == null ? '' : `<rect x="${BX}" y="${BY + y}" width="${SW}" height="${lines}" fill="${col(hue, bg)}"/>`;
  body.push(`${bgRect}<g clip-path="url(#${id})"><g style="animation:r${id} ${dur}s steps(${P}) infinite;animation-delay:${dly(0)}">${rects.join('')}</g></g>`);
  return { c0, len };
}

// ================================================================== LOGO
// CASTAWAY in a blocky face built for the 80-pixel grid: three-pixel stems,
// rounded outer corners, two-pixel counters. Each letter is an inside(x, y)
// test in display units (x in hi-res pixels, y in scanlines).
const LH = 32; // letter height, scanlines
function rr(x, y, x0, y0, x1, y1, r = {}) {
  if (x < x0 || x >= x1 || y < y0 || y >= y1) return false;
  const corner = (cx, cy, rad) => (rad ? (x - cx) ** 2 + (y - cy) ** 2 <= rad * rad : true);
  if (r.tl && x < x0 + r.tl && y < y0 + r.tl) return corner(x0 + r.tl, y0 + r.tl, r.tl);
  if (r.tr && x > x1 - r.tr && y < y0 + r.tr) return corner(x1 - r.tr, y0 + r.tr, r.tr);
  if (r.bl && x < x0 + r.bl && y > y1 - r.bl) return corner(x0 + r.bl, y1 - r.bl, r.bl);
  if (r.br && x > x1 - r.br && y > y1 - r.br) return corner(x1 - r.br, y1 - r.br, r.br);
  return true;
}
const box = (x, y, x0, y0, x1, y1) => x >= x0 && x < x1 && y >= y0 && y < y1;
const LETTERS = {
  C: { w: 32, f: (x, y) => rr(x, y, 0, 0, 32, LH, { tl: 11, bl: 11, tr: 4, br: 4 }) && !rr(x, y, 12, 7, 40, LH - 7, { tl: 3, bl: 3 }) },
  A: { w: 32, f: (x, y) => rr(x, y, 0, 0, 32, LH, { tl: 12, tr: 12 }) && !rr(x, y, 12, 7, 20, 14, { tl: 3, tr: 3 }) && !box(x, y, 12, 21, 20, LH) },
  S: { w: 32, f: (x, y) => rr(x, y, 0, 0, 32, LH, { tl: 11, tr: 4, bl: 4, br: 11 }) && !box(x, y, 12, 7, 32, 13) && !box(x, y, 0, 19, 20, 25) },
  T: { w: 32, f: (x, y) => rr(x, y, 0, 0, 32, 7, { tl: 3, tr: 3 }) || rr(x, y, 8, 0, 24, LH, { bl: 3, br: 3 }) },
  W: { w: 52, f: (x, y) => rr(x, y, 0, 0, 52, LH, { bl: 11, br: 11 }) && !box(x, y, 12, 0, 20, LH - 7) && !box(x, y, 32, 0, 40, LH - 7) && !box(x, y, 20, 0, 32, 6) },
  Y: { w: 32, f: (x, y) => (rr(x, y, 0, 0, 32, 20, { bl: 10, br: 10 }) && !box(x, y, 12, 0, 20, 13)) || rr(x, y, 8, 14, 24, LH, { bl: 2, br: 2 }) },
};
function buildLogo() {
  const word = 'CASTAWAY';
  const GAP = 8;
  const total = [...word].reduce((s, ch) => s + LETTERS[ch].w, 0) + GAP * (word.length - 1);
  const X0 = 8; // left margin; the shadow takes 4 more on the right
  const Y0 = 5; // first letter scanline inside the band
  // Fine mask in display units.
  const MW = SW;
  const MH = LOGO_H;
  const mask = Array.from({ length: MH }, () => new Uint8Array(MW));
  let xc = X0;
  for (const ch of word) {
    const L = LETTERS[ch];
    for (let y = 0; y < LH; y++) for (let x = 0; x < L.w; x++) if (L.f(x + 0.5, y + 0.5)) mask[Y0 + y][xc + x] = 1;
    xc += L.w + GAP;
  }
  if (xc - GAP !== X0 + total) throw new Error('logo width');
  // Distance to the outside, brute force inside a small window.
  const R = 9;
  const dist = Array.from({ length: MH }, () => new Float32Array(MW));
  for (let y = 0; y < MH; y++) {
    for (let x = 0; x < MW; x++) {
      if (!mask[y][x]) continue;
      let best = R;
      for (let dy = -R; dy <= R; dy++) {
        for (let dx = -R; dx <= R; dx++) {
          const yy = y + dy;
          const xx = x + dx;
          const out = yy < 0 || yy >= MH || xx < 0 || xx >= MW || !mask[yy][xx];
          if (out) best = Math.min(best, Math.hypot(dx, dy));
        }
      }
      dist[y][x] = best;
    }
  }
  const B = 6.5;
  const hgt = (x, y) => (y < 0 || y >= MH || x < 0 || x >= MW ? 0 : Math.sin((Math.min(dist[y][x], B) / B) * (Math.PI / 2)));
  const Lx = -0.55;
  const Ly = -0.75;
  const Lz = 0.75;
  const ln = Math.hypot(Lx, Ly, Lz);
  // The 80-pixel grid: luminance per wide pixel.
  const PX = SW / 4;
  const lum = Array.from({ length: MH }, () => new Array(PX).fill(null));
  const inside = (px, y) => {
    let c = 0;
    for (let k = 0; k < 4; k++) c += mask[y]?.[px * 4 + k] ? 1 : 0;
    return c >= 2;
  };
  for (let y = 0; y < MH; y++) {
    for (let px = 0; px < PX; px++) {
      if (!inside(px, y)) continue;
      let acc = 0;
      for (let k = 0; k < 4; k++) {
        const x = px * 4 + k;
        const gx = (hgt(x + 1, y) - hgt(x - 1, y)) / 2;
        const gy = (hgt(x, y + 1) - hgt(x, y - 1)) / 2;
        const S = 4.2;
        const nx = -gx * S;
        const ny = -gy * S;
        const nz = 1;
        const nl = Math.hypot(nx, ny, nz);
        const shade = (nx * Lx + ny * Ly + nz * Lz) / (nl * ln);
        acc += shade;
      }
      const shade = acc / 4;
      const flat = Lz / ln;
      const yr = (y - Y0) / LH;
      // A soft chrome: bright top, a darker waist, lifting again at the foot.
      const base = yr < 0.5 ? 13 - 5 * yr : 8.5 + 4 * (yr - 0.5);
      lum[y][px] = clamp(Math.round(base + 11 * (shade - flat)), 2, 15);
    }
  }
  // Outline (one wide pixel / one line round each letter) and a drop shadow.
  const isL = (px, y) => y >= 0 && y < MH && px >= 0 && px < PX && lum[y][px] != null;
  const out = Array.from({ length: MH }, () => new Array(PX).fill(null));
  for (let y = 0; y < MH; y++) {
    for (let px = 0; px < PX; px++) {
      if (isL(px, y)) { out[y][px] = lum[y][px]; continue; }
      const edge = isL(px - 1, y) || isL(px + 1, y) || isL(px, y - 1) || isL(px, y + 1);
      const shadow = isL(px - 1, y - 3) || isL(px - 1, y - 2);
      if (edge) out[y][px] = 0;
      else if (shadow) out[y][px] = 1;
    }
  }
  // Background: one palette step per scanline near the edges of the band.
  const bgLum = (y) => {
    const e = Math.min(y, MH - 1 - y);
    return e < 6 ? [7, 6, 5, 4, 3, 2][e] : 2 + (Math.sin((y / MH) * Math.PI) > 0.9 ? 1 : 0);
  };
  return { out, bgLum };
}

// Hue wash: the sequence each scanline walks through, one step every
// BAND * DT seconds, offset one DT per line, so the bands rise steadily.
const WASH = [9, 10, 11, 12, 13, 14, 15, 1, 2, 3, 4, 5, 6, 7, 8];
const BAND = 4; // scanlines per hue band
const DT = 0.2; // seconds per scanline of rise: five lines a second
const WASH_P = WASH.length * BAND * DT; // 12 s, four bars
function logoSvg() {
  const { out, bgLum } = buildLogo();
  const N = WASH.length;
  // Keyframes per luminance.
  for (let l = 0; l < 16; l++) {
    const fr = [];
    for (let i = 0; i < N; i++) fr.push(`${n((i / N) * 100, 3)}%{fill:${col(WASH[i], l)}}`);
    fr.push(`100%{fill:${col(WASH[0], l)}}`);
    css.push(`@keyframes L${l}{${fr.join('')}}`);
    css.push(`.L${l}{animation-name:L${l}}`);
  }
  css.push(`#logo path{animation-duration:${n(WASH_P)}s;animation-timing-function:step-end;animation-iteration-count:infinite}`);
  const rows = [];
  for (let y = 0; y < LOGO_H; y++) {
    // Row y shows WASH[floor((t/DT + y + C) / BAND)]: bands rise as t grows.
    const off = y + 4;
    const delay = -off * DT; // negative: already running
    const hueAt0 = WASH[Math.floor(mod(T0 / DT + off, N * BAND) / BAND)];
    css.push(`.y${y}>*{animation-delay:${dly(delay)}}`);
    const row = out[y].map((v) => (v == null ? bgLum(y) : v));
    const g = gridPaths([row.map((v) => `${v}`)], 4, BX, BY + DL.logo + y);
    const parts = [];
    for (const [l, d] of g) parts.push(`<path class="L${l}" fill="${col(hueAt0, +l)}" d="${d}"/>`);
    rows.push(`<g class="y${y}">${parts.join('')}</g>`);
  }
  body.push(`<g id="logo">${rows.join('')}</g>`);
}

// ================================================================== ISLAND
// 88 wide pixels x 84 lines. Each cell is [hue, lum] or null.
const IW = SW / 4;
const IH = ISLAND_H;
const HORIZON = 32;
const skyHue = (y) => (y < 12 ? H.SKY : H.AZURE);
const skyLum = (y) => Math.round(5.5 + (y / (HORIZON - 1)) * 7.4);
const seaHue = (y) => (y < HORIZON + 8 ? H.SKY : y < HORIZON + 22 ? H.AZURE : y < HORIZON + 38 ? H.CYAN : H.TEAL);
const seaLum = (y) => {
  const d = y - HORIZON;
  if (d === 0) return 11;
  if (d === 1) return 9;
  return Math.round(6 + Math.min(3, d / 16));
};
// Wide-pixel centre in display units.
const cx = (px) => px * 4 + 2;

// Island geometry (display units: x hi-res, y lines inside the band).
const ISL = { x: 186, y: 66, rx: 104, ry: 10 };
const islandEdge = (x) => {
  // top and bottom of the sand at column x, or null; a little wobble.
  const u = (x - ISL.x) / ISL.rx;
  if (Math.abs(u) >= 1) return null;
  const w = Math.sqrt(1 - u * u);
  const wob = Math.sin(x * 0.11) * 0.6 + Math.sin(x * 0.037 + 1) * 0.8;
  return [ISL.y - ISL.ry * w * 0.85 - Math.max(0, wob), ISL.y + ISL.ry * w * 0.55 + wob * 0.4];
};

function buildIsland() {
  const bg = Array.from({ length: IH }, () => new Array(IW).fill(null));
  const fg = Array.from({ length: IH }, () => new Array(IW).fill(null));
  const set = (g, px, y, h, l) => { if (px >= 0 && px < IW && y >= 0 && y < IH) g[y][px] = [h, clamp(Math.round(l), 0, 15)]; };
  // Sky, one luminance step every few lines; sea below the horizon.
  for (let y = 0; y < IH; y++) {
    for (let px = 0; px < IW; px++) {
      if (y < HORIZON) set(bg, px, y, skyHue(y), skyLum(y));
      else set(bg, px, y, seaHue(y), seaLum(y));
    }
  }
  // The sun: rings of luminance in the sky's own hue.
  // Kept clear of the band's top line so the whole disc shows (the tagline
  // row above would otherwise slice it into a pale square).
  const SUN = { x: 86, y: 14, r: 6 }; // centred on a wide pixel, between two clouds
  for (let y = 0; y < HORIZON; y++) {
    for (let px = 0; px < IW; px++) {
      const d = Math.hypot(cx(px) - SUN.x, (y + 0.5 - SUN.y) * 1.0);
      let l = null;
      if (d < SUN.r) l = 15;
      else if (d < SUN.r + 2.5) l = 14;
      else if (d < SUN.r + 5) l = 13;
      else if (d < SUN.r + 7.5) l = 12;
      if (l != null && l > bg[y][px][1]) set(bg, px, y, skyHue(y), l);
    }
  }
  // Sea texture, part 1 (static): darker troughs under some crests.
  const crest = [];
  for (let y = HORIZON + 2; y < IH; y++) {
    const d = y - HORIZON;
    const p = 0.1 + Math.min(0.2, d / 260);
    for (let px = 0; px < IW; px++) {
      const r = hash2(px, y, 7);
      if (r < p) {
        const len = 1 + Math.floor(hash2(px, y, 8) * (1 + d / 22));
        crest.push({ px, y, len, ph: Math.floor(hash2(px, y, 9) * 4) });
        if (y + 1 < IH && hash2(px, y, 10) < 0.6) for (let k = 0; k < len; k++) set(bg, px + k, y + 1, seaHue(y + 1), seaLum(y + 1) - 1);
        px += len;
      }
    }
  }
  // The island: shallow ring, foam, sand.
  const foam = [[], []];
  for (let y = HORIZON + 6; y < IH; y++) {
    for (let px = 0; px < IW; px++) {
      const x = cx(px);
      const yy = y + 0.5;
      const e = Math.hypot((x - ISL.x) / (ISL.rx + 16), (yy - ISL.y - 0.5) / (ISL.ry * 0.85 + 4.5));
      if (e < 1) set(bg, px, y, H.TEAL, seaLum(y) + 3 - (e > 0.8 ? 1 : 0));
    }
  }
  for (let px = 0; px < IW; px++) {
    const x = cx(px);
    const ed = islandEdge(x);
    if (!ed) continue;
    const [top, bot] = ed;
    for (let y = Math.floor(top); y <= Math.ceil(bot); y++) {
      const yy = y + 0.5;
      if (yy < top || yy > bot) continue;
      const v = (yy - top) / (bot - top); // 0 back, 1 front
      const u = (x - ISL.x) / ISL.rx;
      let l = 13.4 - v * 2.2 - Math.abs(u) * 1.2 + (hash2(px, y, 3) < 0.18 ? -1 : 0);
      if (v > 0.82) l = 10 - (hash2(px, y, 4) < 0.3 ? 1 : 0); // wet sand
      set(fg, px, y, H.SAND, l);
    }
    // Foam: two rings round the front and the ends, swapped on the half bar.
    const fy = Math.ceil(bot) + 1;
    foam[px % 3 === 0 ? 1 : 0].push([px, fy]);
    if (hash2(px, 1, 5) < 0.5) foam[1].push([px, fy + 1]);
    else foam[0].push([px, fy - 0]);
  }
  // A few rocks at the waterline.
  for (const [px, y] of [[24, 72], [25, 72], [60, 73], [32, 74]]) { set(fg, px, y, H.GREY, 7); set(fg, px, y - 1, H.GREY, 10); }
  // Bushes along the back of the sand.
  const bush = [[30, 57, 9], [41, 58, 7], [50, 57, 8], [58, 59, 6], [36, 60, 5]];
  for (const [bx, by, br] of bush) {
    for (let y = by - 6; y <= by + 2; y++) {
      for (let px = Math.floor((bx * 4 - br * 4) / 4); px <= Math.ceil((bx * 4 + br * 4) / 4); px++) {
        const x = cx(px);
        const d = Math.hypot((x - bx * 4) / (br * 1.6), (y + 0.5 - by) / 4.2);
        if (d < 1 && hash2(px, y, 11) > d * 0.5) {
          const l = 10.5 - (y + 0.5 - (by - 6)) * 0.85 + (hash2(px, y, 12) < 0.35 ? 1.2 : 0) - d * 1.5;
          set(fg, px, y, l > 9.5 ? H.LIME : H.GREEN, l);
        }
      }
    }
  }
  // The palm: a tall, slender trunk leaning left, segmented bark.
  const base = { x: 214, y: 62 };
  const crown = { x: 190, y: 12 };
  const ctrl = { x: 219, y: 42 };
  const trunkAt = (y) => {
    // Solve the quadratic bezier for t at height y (monotonic in y).
    let lo = 0;
    let hi = 1;
    for (let i = 0; i < 30; i++) {
      const t = (lo + hi) / 2;
      const yt = (1 - t) ** 2 * crown.y + 2 * (1 - t) * t * ctrl.y + t * t * base.y;
      if (yt < y) lo = t; else hi = t;
    }
    const t = lo;
    return { x: (1 - t) ** 2 * crown.x + 2 * (1 - t) * t * ctrl.x + t * t * base.x, t };
  };
  for (let y = crown.y; y <= base.y; y++) {
    const { x: tx, t } = trunkAt(y + 0.5);
    const w = 4 + t * 5;
    for (let px = Math.floor((tx - w) / 4); px <= Math.ceil((tx + w) / 4); px++) {
      const x = cx(px);
      if (Math.abs(x - tx) > w / 2 + 1.4) continue;
      const seg = mod(y + Math.round(t * 3), 4) === 0;
      const side = x < tx ? 1 : -1;
      set(fg, px, y, H.ORANGE, (seg ? 2.5 : 4.5) + side);
    }
  }
  // Fronds: a rachis that arcs out and droops, leaflets hanging below it,
  // serrated at the tips because every other wide pixel stops a line short.
  const fronds = [
    // angle (0 = right, negative = up), length in units, droop
    [-170, 56, 0.8], [-140, 40, 0.7], [-112, 22, 0.35], [-72, 24, 0.35], [-36, 42, 0.7], [-8, 58, 0.85],
    [160, 32, 1.3], [40, 24, 0.9],
  ];
  const leafPx = new Map();
  for (const [ang, len, droop] of fronds) {
    const a = (ang * Math.PI) / 180;
    for (let i = 0; i <= 120; i++) {
      const t = i / 120;
      const x = crown.x + Math.cos(a) * len * t;
      const y = crown.y + Math.sin(a) * len * t * 0.5 + droop * 14 * t * t;
      const px = Math.floor(x / 4);
      const hang = 1.5 + (len / 50) * 8.5 * Math.sin(Math.PI * Math.min(1, t * 1.08)) * (1 - 0.3 * t);
      for (let yy = Math.floor(y - 1); yy <= Math.ceil(y + hang); yy++) {
        const v = (yy + 0.5 - y) / hang; // <0 above the rachis, 0..1 down the leaflet
        if (v < -1 / hang || v > 1) continue;
        if (v > 0.5 && mod(px + Math.floor(t * 9), 2)) continue; // serration
        if (v > 0.8 && mod(px, 3) === 0) continue;
        let l = v < 0 ? 11.5 : 10.4 - v * 5;
        l -= t * 1.2;
        const k = `${px},${yy}`;
        const prev = leafPx.get(k);
        if (prev == null || l > prev) leafPx.set(k, l);
      }
    }
  }
  for (const [k, l] of leafPx) {
    const [px, y] = k.split(',').map(Number);
    set(fg, px, y, l >= 10 ? H.LIME : H.GREEN, l);
  }
  // The heart of the crown, in shadow.
  for (const [px, y, l] of [[46, 11, 5], [47, 11, 4], [48, 11, 5], [46, 12, 4], [47, 12, 3], [48, 12, 4]]) set(fg, px, y, H.GREEN, l);
  // Coconuts.
  for (const [px, y, l] of [[46, 13, 4], [47, 14, 3], [48, 13, 5], [47, 13, 6]]) set(fg, px, y, H.ORANGE, l);
  // The raft, off the right-hand shore: four logs, two lashings.
  const RAFT = { x0: 76, x1: 86, y0: 67 };
  for (let k = 0; k < 4; k++) {
    for (let px = RAFT.x0 - (k % 2); px < RAFT.x1 + ((k + 1) % 2); px++) {
      const y = RAFT.y0 + k * 2;
      const lash = px === RAFT.x0 + 2 || px === RAFT.x1 - 3;
      set(fg, px, y, lash ? H.AMBER : H.ORANGE, lash ? 11 : 8);
      set(fg, px, y + 1, lash ? H.AMBER : H.ORANGE, lash ? 8 : 5);
    }
  }
  for (let px = RAFT.x0 - 1; px <= RAFT.x1; px++) set(bg, px, RAFT.y0 + 8, seaHue(RAFT.y0 + 8), seaLum(RAFT.y0 + 8) - 2);

  // Clouds: their own layer, drifted by fine scroll; tiled across the width.
  const clouds = Array.from({ length: IH }, () => new Array(IW).fill(null));
  const puffs = [
    // cx (units), base y, puffs as [dx, dy, rx, ry]
    [40, 31, [[0, -4, 22, 5], [-14, -2, 14, 4], [16, -2, 16, 4], [-2, -8, 12, 5], [8, -10, 9, 4]]],
    [128, 30, [[0, -3, 16, 4], [12, -5, 12, 4], [-10, -2, 10, 3]]],
    [262, 31, [[0, -4, 26, 5], [-18, -2, 16, 3.5], [20, -3, 18, 4], [4, -9, 14, 5], [-8, -12, 8, 4], [14, -12, 7, 3]]],
    [330, 18, [[0, -1, 12, 2.4], [8, -2, 8, 2]]],
    [196, 22, [[0, -1, 10, 2], [-6, -2, 6, 1.8]]],
  ];
  for (let y = 0; y < HORIZON; y++) {
    for (let px = 0; px < IW; px++) {
      const x = cx(px);
      let hit = null;
      for (const [ccx, cby, ps] of puffs) {
        for (const [dx, dy, rx, ry] of ps) {
          const ddx = mod(x - (ccx + dx) + SW / 2, SW) - SW / 2;
          const e = (ddx / rx) ** 2 + ((y + 0.5 - (cby + dy)) / ry) ** 2;
          if (e < 1 && y + 0.5 <= cby) {
            const lift = (cby - (y + 0.5)) / 10;
            const v = Math.max(hit ?? -9, lift - e * 0.25);
            hit = v;
          }
        }
      }
      if (hit == null) continue;
      const l = hit > 0.75 ? 15 : hit > 0.45 ? 14 : hit > 0.2 ? 13 : 12;
      if (l > bg[y][px][1]) clouds[y][px] = [skyHue(y), l];
    }
  }
  return { bg, fg, clouds, crest, foam };
}

const keyOf = (c) => (c ? col(c[0], c[1]) : null);
function islandSvg() {
  const { bg, fg, clouds, crest, foam } = buildIsland();
  const Y = BY + DL.island;
  const clipId = 'isl';
  defs.push(`<clipPath id="${clipId}"><rect x="${BX}" y="${Y}" width="${SW}" height="${IH}"/></clipPath>`);
  const out = [];
  out.push(pathsSvg(gridPaths(bg.map((r) => r.map(keyOf)), 4, BX, Y)));
  // Clouds: one copy, used twice, scrolled left two units a step.
  const cl = pathsSvg(gridPaths(clouds.map((r) => r.map(keyOf)), 4, 0, 0));
  defs.push(`<g id="cl">${cl}</g>`);
  const CLOUD_T = 96; // seconds per full width
  css.push(`@keyframes drift{from{transform:translateX(0)}to{transform:translateX(-${SW}px)}}`);
  out.push(`<g clip-path="url(#${clipId})"><g transform="translate(${BX} ${Y})"><g style="animation:drift ${CLOUD_T}s steps(${SW / 2}) infinite;animation-delay:${dly(0)}"><use href="#cl"/><use href="#cl" x="${SW}"/></g></g></g>`);
  // Sea crests: four phases that twinkle one beat in four.
  css.push('@keyframes tw{0%{opacity:1}25%{opacity:0}100%{opacity:0}}');
  for (let ph = 0; ph < 4; ph++) {
    const g = Array.from({ length: IH }, () => new Array(IW).fill(null));
    for (const c of crest) {
      if (c.ph !== ph) continue;
      for (let k = 0; k < c.len && c.px + k < IW; k++) {
        if (fg[c.y][c.px + k]) continue;
        const bh = bg[c.y][c.px + k][0];
        g[c.y][c.px + k] = col(bh, bg[c.y][c.px + k][1] + 3);
      }
    }
    out.push(`<g style="animation:tw ${BAR}s step-end infinite;animation-delay:${dly(-ph * BEAT)}">${pathsSvg(gridPaths(g, 4, BX, Y))}</g>`);
  }
  // Foam rings: swap on every half bar.
  css.push('@keyframes fa{0%{opacity:1}50%{opacity:0}}');
  foam.forEach((ring, i) => {
    const g = Array.from({ length: IH }, () => new Array(IW).fill(null));
    for (const [px, y] of ring) if (y < IH && !fg[y][px]) g[y][px] = col(H.TEAL, 15 - i);
    out.push(`<g style="animation:fa ${BAR / 2}s step-end infinite;animation-delay:${dly(-i * BAR / 4)}">${pathsSvg(gridPaths(g, 4, BX, Y))}</g>`);
  });
  out.push(pathsSvg(gridPaths(fg.map((r) => r.map(keyOf)), 4, BX, Y)));
  body.push(`<g id="island">${out.join('')}</g>`);
}

// ================================================================== PLAYERS
// Two-unit pixels, one line tall. Letters map to colours; '.' is clear.
const PCOL = {
  p: col(H.SAND, 15), // headphones, cream
  h: col(H.ORANGE, 3), // hair, brown
  k: col(H.ORANGE, 13), // skin
  K: col(H.ORANGE, 12), // skin, shade
  c: col(H.RED, 9), // coral tank top
  C: col(H.RED, 7), // coral, shade
  s: col(H.AMBER, 15), // cream shorts
  S: col(H.AMBER, 14), // shorts, shade
  e: col(H.ORANGE, 2), // eyes
  g: col(H.GREY, 10), // tabby grey
  G: col(H.GREY, 6), // tabby stripe
  d: col(H.GREY, 3), // closed eyes
  w: col(H.GREY, 15), // white chest
  n: col(H.PINK, 11), // nose
  b: col(H.GREEN, 7), // bottle glass
  B: col(H.GREEN, 11), // glint
  o: col(H.AMBER, 9), // cork
  m: col(H.GREY, 15), // missile white
  u: col(H.ORANGE, 3), // coconut shell
  U: col(H.ORANGE, 6), // shell, lit
  r: col(H.RED, 8), // crab legs
};
// She faces us, standing, arms down, nodding. Head is rows 0-6, and drops
// one line on every beat; the bun peeks out low on the left.
const HER_HEAD = [
  '...ppp...',
  '..phhhp..',
  '..hhhhh..',
  '.phkkkhp.',
  '.phekehp.',
  'hphkkkhp.',
  'hh.kkk...',
];
const HER_BODY = [
  '....k....',
  '..kcccK..',
  '..kccCK..',
  '..kccCK..',
  '..kccCK..',
  '..kccCK..',
  '..kccCK..',
  '..kssSK..',
  '..kssSK..',
  '..kssSK..',
  '...sSS...',
  '...s.S...',
  '...k.K...',
  '...k.K...',
  '...k.K...',
  '...k.K...',
  '...k.K...',
  '...k.K...',
  '...k.K...',
  '...k.K...',
  '..kk.KK..',
];
// The stray cat: a grey tabby with a white chest, asleep in a loaf on a
// frond, head to the right (ears up, eyes shut, pink nose), striped flank,
// tail hanging over the edge. The tail tip has two frames: it flicks once a bar.
const CAT = [
  '......g...g',
  '......gg.gg',
  '..gGgGggggg',
  '.ggGgGgdgdg',
  'gGgGgGgwnwg',
  'gGgGgGgwwwg',
  'gggggggwwww',
  '.gggggggww.',
  'G..........',
  'g..........',
];
const CAT_TIP = [['.G'], ['G.', 'G.']];
// The bottle, lying in the water: cork, neck, green glass, a glint.
const BOTTLE = [
  '...bbbb',
  'obbbBbb',
  '...bbbb',
];
// The hermit crab, now wearing the coconut that fell on it. Two leg frames.
const CRAB = [
  '.uUu.',
  'uUuuu',
];
const CRAB_LEGS = ['r.r.r', '.r.r.'];
function spriteGrid(rows) {
  return rows.map((r) => [...r].map((ch) => (ch === '.' ? null : PCOL[ch])));
}
function playersSvg() {
  const Y = BY + DL.island;
  // Her, on the sand left of the palm; feet on line 70 of the band.
  const herX = BX + 132;
  const herFeet = Y + 71;
  const herTop = herFeet - HER_BODY.length - HER_HEAD.length;
  css.push('@keyframes nod{0%{transform:translateY(0)}50%{transform:translateY(1px)}}');
  const head = pathsSvg(gridPaths(spriteGrid(HER_HEAD), 2, herX, herTop));
  const bodyP = pathsSvg(gridPaths(spriteGrid(HER_BODY), 2, herX, herTop + HER_HEAD.length));
  body.push(`<g id="her">${bodyP}<g style="animation:nod ${BEAT}s step-end infinite;animation-delay:${dly(0)}">${head}</g></g>`);
  // The cat, asleep on the fronds; the tail tip flicks for one beat a bar.
  const catX = BX + 156;
  const catY = Y + 2;
  // Frame 0 (tip curled) for three beats, frame 1 (tip down) on the fourth.
  css.push('@keyframes tip0{0%{opacity:1}75%{opacity:0}}@keyframes tip1{0%{opacity:0}75%{opacity:1}}');
  const tip = CAT_TIP.map((rows, i) => `<g style="animation:tip${i} ${BAR}s step-end infinite;animation-delay:${dly(0)}"${i ? ' opacity="0"' : ''}>${pathsSvg(gridPaths(spriteGrid(rows), 2, catX, catY + CAT.length))}</g>`);
  body.push(`<g id="cat">${pathsSvg(gridPaths(spriteGrid(CAT), 2, catX, catY))}${tip.join('')}</g>`);
  // The coconut walks along the front of the sand, sideways (it is a crab),
  // one step every beat, legs swapping on the beat. 48 s there and back.
  {
    const CR_T = 16 * BAR;
    const cx0 = BX + 170;
    const cy = Y + 67;
    const span = 64;
    const st = span / 2;
    const kf = [];
    for (let i = 0; i <= st; i++) kf.push(`${n((i / st) * 50, 3)}%{transform:translateX(${i * 2}px)}`);
    for (let i = 1; i <= st; i++) kf.push(`${n(50 + (i / st) * 50, 3)}%{transform:translateX(${span - i * 2}px)}`);
    css.push(`@keyframes crab{${kf.join('')}}`);
    css.push('@keyframes leg{0%{opacity:1}50%{opacity:0}}');
    const shell = pathsSvg(gridPaths(spriteGrid(CRAB), 2, cx0, cy));
    const legs = CRAB_LEGS.map((r, i) => `<g style="animation:leg ${2 * BEAT}s step-end infinite;animation-delay:${dly(-i * BEAT)}">${pathsSvg(gridPaths(spriteGrid([r]), 2, cx0, cy + 2))}</g>`).join('');
    body.push(`<g id="crab" style="animation:crab ${CR_T}s step-end infinite;animation-delay:${dly(0)}">${shell}${legs}</g>`);
  }
  // The bottle: drifts in to the shallows, then straight back out. 24 s.
  const BOT_T = 8 * BAR;
  const bx0 = BX + 36;
  const travel = 32; // two units a beat, sixteen beats in, sixteen out
  const steps = travel / 2;
  const kf = [];
  for (let i = 0; i <= steps; i++) kf.push(`${n((i / steps) * 50, 3)}%{transform:translateX(${i * 2}px)}`);
  for (let i = 1; i <= steps; i++) kf.push(`${n(50 + (i / steps) * 50, 3)}%{transform:translateX(${travel - i * 2}px)}`);
  css.push(`@keyframes bot{${kf.join('')}}`);
  css.push('@keyframes bob{0%{transform:translateY(0)}50%{transform:translateY(1px)}}');
  body.push(`<g style="animation:bot ${BOT_T}s step-end infinite;animation-delay:${dly(0)}"><g style="animation:bob ${2 * BEAT}s step-end infinite;animation-delay:${dly(0)}">${pathsSvg(gridPaths(spriteGrid(BOTTLE), 2, bx0, Y + 75))}</g></g>`);
}

// ================================================================== TIMELINE
// The seed-1992 ten-hour run from activities.toml (tools/schedule.py --json,
// 2026-10-01): [start bar, length in bars] per event, bars of 3 s.
const RUN = {
  regular: '2b:v,48:e,5s:a,7q:b,8v:e,ax:b,df:h,fn:7,hn:b,jk:b,mc:b,ol:9,px:g,sl:y,tz:d,wc:b,xq:s,zu:16,11e:8,13c:e,14p:e,17e:d,1bh:c,1cr:17,1fe:7,1gj:g,1jb:d,1lu:a,1nj:9,1os:t,1qd:a,1sx:c,1ue:a,1wx:12,1z5:b,219:9,23f:b,258:c,26e:a,27r:k,29y:c,2bg:d,2d4:9,2fk:b,2h2:d,2il:b,2na:b,2pq:8,2s2:15,2vm:c,2y2:d,30r:f,32n:d,352:14,36t:d,38d:b,39y:b,3bk:9,3dz:c,3gh:m,3ig:d,3k3:7,3ld:b,3nv:a,3p2:c,3rt:f,3ts:c,3w5:a,3xg:w,3z6:c,41k:e,43b:9,44j:a,45r:p,489:b,49m:r,4aw:d,4c5:c,4g1:8,4i5:c,4le:m,4mr:r,4oc:a,4pq:7,4rl:c,4th:e,4vv:b,4xt:a,4zo:d,51s:d,552:f,57m:a,58u:t,5b8:9,5dv:b,5f0:f,5g9:d,5i0:e,5ke:19,5q2:a,5s1:a,5up:n,5x8:8,5zb:q,61y:8,649:b,65x:b,67s:b,6ac:11,6c3:c,6e1:a,6fh:b,6i4:9,6km:b,6ql:17,6ss:9,6un:b,6xd:d,6zw:9,723:j,73a:e,74t:c,775:e,79r:c,7cs:b,7fh:c,7hh:d,7is:b,7k7:d,7lv:y,7o8:e,7pm:a,7rp:a,7ty:s,7xl:d,7zf:a,81j:c,83e:e,85c:a,87a:8,89s:c,8bt:9,8ei:x,8g7:c,8hg:b,8j0:a,8k7:b,8lo:d,8nc:c,8om:a,8r3:t,8tt:w,8vg:9,8wm:9,8zd:9,90s:g,937:k,95u:a,988:g',
  occasional: '4:g,!di:1d,p4:i,!wf:1a,189:e,!1m2:z,1uw:7,!27u:13,2je:30,2ud:10,!357:11,3c1:16,!3pz:1a,3yq:4,47l:c,4kj:e,!4w2:15,52t:1n,5ai:7,5lx:n,5y7:g,69j:a,6mf:3m,6tv:h,719:e,7bv:h,!7of:z,7we:h,84l:c,!8f1:14,8mm:e,909:5',
  rare: '!oi:ei,197:1l,204:b,!2q5:cl,3mz:e,4d7:27,!53m:cg,5o4:1g,66o:o,!6ue:bo,7n9:c,8cl:q,!90j:9r',
  chained: '!11r:2,!24d:2,2mw:4,!3t6:2,!42c:2,!4kb:2,!4ra:3,5mu:i,5nr:4,!65i:2,!6p6:2,!88r:2,!8l4:3,!95m:2',
  super_rare: '4ui:12',
};
// '!' marks an event outside her lane. Returns [bar, bars, other].
function parseRun(s) {
  return s.split(',').map((e) => {
    const other = e.startsWith('!');
    const [a, b] = e.replace('!', '').split(':').map((v) => parseInt(v, 36));
    return [a, b, other];
  });
}
function timelineSvg() {
  const Y = BY + DL.timeline;
  const SEC_PER_PX = 24; // one four-colour pixel (2 units) per 24 seconds
  const RUN_S = 36000;
  const WPX = RUN_S / SEC_PER_PX; // 1500 pixels = 3000 units
  const W = WPX * 2;
  const tierCol = {
    regular: col(H.CYAN, 10),
    chained: col(H.CYAN, 10),
    occasional: col(H.AMBER, 12),
    rare: col(H.PINK, 10),
  };
  const BAK = col(H.BLUE, 1);
  const parts = [];
  // Idle track and hour marks. Four-colour mode allows background plus three
  // playfield colours per line, so: line 5 is the idle track (the background
  // register changed for that one line), lines 0-6 carry the three tier
  // colours, and line 7 has only the hour notches, the 0:00:00 one (where
  // the run wraps) brighter and wider.
  parts.push(`<rect x="0" y="5" width="${W}" height="1" fill="${col(H.BLUE, 4)}"/>`);
  for (let hr = 0; hr < 10; hr++) {
    const x = (hr * 3600) / SEC_PER_PX * 2;
    if (hr === 0) parts.push(`<rect x="${x - 2}" y="7" width="6" height="1" fill="${col(H.BLUE, 11)}"/>`);
    else parts.push(`<rect x="${x}" y="7" width="2" height="1" fill="${col(H.BLUE, 7)}"/>`);
  }
  // Her lane: a block as long as the activity, on lines 3-6. Everything
  // else (the cat, the sea and sky, the shore): a one-pixel tick on lines 0-1.
  const byColour = new Map();
  for (const tier of ['regular', 'chained', 'occasional', 'rare']) {
    for (const [bar, len, other] of parseRun(RUN[tier])) {
      const x0 = Math.floor((bar * 3) / SEC_PER_PX);
      const w = other ? 1 : Math.max(1, Math.round((len * 3) / SEC_PER_PX));
      const c = tierCol[tier];
      if (!byColour.has(c)) byColour.set(c, []);
      const rows = other ? [0, 2] : [3, 7];
      byColour.get(c).push(`M${x0 * 2} ${rows[0]}h${w * 2}v${rows[1] - rows[0]}h${-w * 2}z`);
    }
  }
  for (const [c, d] of byColour) parts.push(`<path fill="${c}" d="${d.join('')}"/>`);
  // Missile: the super-rare event, full height, one pixel wide.
  for (const [bar] of parseRun(RUN.super_rare)) {
    const x0 = Math.floor((bar * 3) / SEC_PER_PX) * 2;
    parts.push(`<rect x="${x0}" y="0" width="2" height="8" fill="${PCOL.m}"/>`);
  }
  defs.push(`<g id="tl">${parts.join('')}</g>`);
  defs.push(`<clipPath id="tlc"><rect x="${BX}" y="${Y}" width="${SW}" height="8"/></clipPath>`);
  const TL_T = 80 * BAR; // four minutes for the ten hours
  css.push(`@keyframes tl{from{transform:translateX(0)}to{transform:translateX(-${W}px)}}`);
  body.push(`<rect x="${BX}" y="${Y}" width="${SW}" height="8" fill="${BAK}"/>`);
  const NOW = 64; // the NOW player's column, units from the left
  body.push(`<g clip-path="url(#tlc)"><g transform="translate(${BX + NOW} ${Y})"><g style="animation:tl ${TL_T}s steps(${WPX}) infinite;animation-delay:${dly(0)}"><use href="#tl"/><use href="#tl" x="${W}"/><use href="#tl" x="${-W}"/></g></g></g>`);
  // NOW: a player drawn as an I-beam, eight lines tall, inside the row.
  body.push(`<path fill="${col(H.SAND, 15)}" d="M${BX + NOW - 2} ${Y}h6v1h-2v6h2v1h-6v-1h2v-6h-2z"/>`);
}

// ================================================================== TEXT ROWS
function textRows() {
  const roll = (a) => a;
  textRow(DL.credit, 'Very Blank Island presents', { hue: H.GREY, bg: 0, lums: roll([6, 7, 8, 9, 10, 11, 12, 11, 10, 9, 8, 7]), dur: BAR });
  textRow(DL.tag, 'sixteen shades of the same afternoon', { hue: H.AZURE, bg: 1, lums: roll([15, 15, 14, 13, 12, 11, 10, 11, 12, 13, 14, 15]), dur: BAR });
  textRow(DL.caption, 'the whole 10-hour run, seed 1992:', { hue: H.BLUE, bg: 1, lums: roll([12, 12, 11, 10, 9, 10, 11, 12]), dur: BAR, align: 'left', lines: 10 });
  // Legend: words in one hue; the colour swatches are the missiles.
  const leg = '  regular   occasional   rare   super rare';
  const { c0 } = textRow(DL.legend, leg, { hue: H.GREY, bg: 1, lums: [12, 12, 12, 11, 11, 10, 10, 11], dur: BAR, align: 'left', lines: 10 });
  const sw = [
    [leg.indexOf('regular') - 2, col(H.CYAN, 10)],
    [leg.indexOf('occasional') - 2, col(H.AMBER, 12)],
    [leg.indexOf('rare  ') - 2, col(H.PINK, 10)],
    [leg.indexOf('super') - 2, PCOL.m],
  ];
  // Missile widths: both bits at normal width are four hi-res pixels; the
  // super-rare one uses a single bit, two pixels, as it does in the timeline.
  for (const [c, fill] of sw) {
    const one = c === sw[3][0];
    body.push(`<rect x="${BX + (c0 + c) * 8 + (one ? 3 : 2)}" y="${BY + DL.legend}" width="${one ? 2 : 4}" height="7" fill="${fill}"/>`);
  }
  textRow(DL.sound, '~ every sound synthesized from code ~', { hue: H.AMBER, bg: 1, lums: roll([14, 13, 12, 11, 10, 11, 12, 13]), dur: BAR, lines: 10 });
  textRow(DL.run, 'python tools/serve.py -> 127.0.0.1:8765', { hue: H.TEAL, bg: 1, lums: roll([13, 12, 11, 10, 11, 12, 13, 14]), dur: BAR, lines: 10 });
}

// ================================================================== ASSEMBLE
function build() {
  // Border, and the screen's own background behind every band.
  body.push(`<rect x="${BX}" y="${BY}" width="${SW}" height="${SH}" fill="${col(H.GREY, 0)}"/>`);
  logoSvg();
  islandSvg();
  playersSvg();
  timelineSvg();
  textRows();
  css.push('@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${VIEW ? VIEW.join(' ') : `0 0 ${VW} ${VH}`}" width="${(VIEW ? VIEW[2] : VW) * SCALE}" height="${(VIEW ? VIEW[3] : VH) * SCALE}" shape-rendering="crispEdges">
<title>CASTAWAY: an Atari 8-bit style demo screen</title>
<desc>CASTAWAY in fat, chrome-shaded wide pixels with hue bands rolling up through the letters, over a wide-pixel island where she nods to the beat, a grey tabby naps on the palm, a coconut crab walks sideways and a bottle drifts in and out. Below: the seed-1992 ten-hour run as a scrolling row of blips, every sound synthesized from code, and python tools/serve.py -> 127.0.0.1:8765.</desc>
<style>${css.join('')}</style>
<defs>${defs.join('')}</defs>
<rect width="${VW}" height="${VH}" rx="10" fill="${col(H.GREY, 0)}"/>
${body.join('\n')}
</svg>
`;
  return svg;
}

const svg = build();
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
console.log(`wrote ${OUT} (${(svg.length / 1024).toFixed(1)} KB)`);

if (SHEET) {
  // Contact sheet: the 256-colour palette, the sprites at 8x and the font.
  const Z = 8;
  const cells = [];
  for (let h = 0; h < 16; h++) for (let l = 0; l < 16; l++) cells.push(`<rect x="${l * 24}" y="${h * 14}" width="24" height="14" fill="${PAL[h][l]}"/>`);
  const sprites = [
    [HER_HEAD.concat(HER_BODY), 420, 0],
    [CAT, 600, 0],
    [BOTTLE, 600, 120],
    [CRAB.concat([CRAB_LEGS[0]]), 600, 160],
  ].map(([rows, ox, oy]) => {
    const g = spriteGrid(rows);
    return g.map((r, y) => r.map((c, x) => (c ? `<rect x="${ox + x * 2 * Z}" y="${oy + y * Z}" width="${2 * Z}" height="${Z}" fill="${c}"/>` : '')).join('')).join('');
  });
  const chars = Object.keys(FONT).filter((c) => c !== ' ');
  const font = chars.map((ch, i) => {
    const rows = FONT[ch];
    const ox = (i % 24) * 9 * 4;
    const oy = 360 + Math.floor(i / 24) * 10 * 4;
    return rows.map((r, y) => [...r].map((c, x) => (c === '#' ? `<rect x="${ox + x * 4}" y="${oy + y * 4}" width="4" height="4" fill="#fff"/>` : '')).join('')).join('');
  });
  const sheet = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 540" width="900" height="540" shape-rendering="crispEdges"><rect width="900" height="540" fill="#123"/>${cells.join('')}${sprites.join('')}${font.join('')}</svg>`;
  fs.writeFileSync(SHEET, sheet);
  console.log(`wrote ${SHEET}`);
}
