// "Vertical copper bars" README banner for CASTAWAY.
//
//   node examples/castaway/src/15-kefrens-bars_opus_5.5.mjs
//   node examples/castaway/src/15-kefrens-bars_opus_5.5.mjs --at=7.5 --out=some/where.svg
//
// Regenerates ../assets/15-kefrens-bars_opus_5.5.svg. Plain Node, no deps,
// deterministic (no clock, no Math.random). --at bakes a head start (seconds)
// into every animation delay so late frames can be checked without waiting;
// use it only together with --out, never in place.
//
// The style: the Amiga "Kefrens bars" / "Alcatraz bars" effect (c. 1989-91).
// The hardware trick was to show ONE line of video memory on every scanline
// and to draw one more shaded vertical bar into that line each time the beam
// moved down. A bar drawn at scanline k therefore shows on every line from k
// to the bottom, later bars cover earlier ones, the top of the screen is
// sparse and the bottom is a woven wall, and because each new bar sits on a
// sine of k the pile braids into ribbons. Nothing here is copied from any
// production: the letters, palette, sprites and copy are drawn for this file.
//
// How the SVG does it (the real mechanism, not a picture of it)
//   * For every virtual scanline k and every ribbon r there is one bar that
//     starts at row k and runs off the bottom. Paint order is k ascending, so
//     later bars cover earlier ones exactly as the beam did.
//   * Its X is the sum of two sines. Each sine is ONE shared @keyframes track,
//     pre-quantised to whole virtual pixels and played with step-end timing,
//     so a bar only ever moves by a whole (3 px) Amiga pixel. Rows differ only
//     in animation-delay (a class per phase), which is the "phase per
//     scanline" of the original. Outer <g> = slow swing, inner <use> = twist,
//     and the twist runs up the screen while the swing runs down.
//   * The bar shading is one 12-bit ramp per ribbon (hard-stop gradient,
//     objectBoundingBox), so all 304 bars share three gradients. The sea
//     ribbon starts on the top line, the sun a quarter of the way down and
//     the coral half way, so the top is sparse round the title.
//   * Swing period 12 s, twist period 6 s: four and two bars of the theme
//     (80 BPM, 3 s a bar), so the whole braid loops every 12 s.
//   * The title is rasterised here, pixel by pixel, into sandcastle bricks;
//     the scroller is 7x8 glyph symbols placed with <use>, moving one whole
//     pixel per step. She sits in the crook of the Y and nods on every beat.
//   * prefers-reduced-motion pauses every track where it starts (a full
//     braid, not a collapsed column), so the scroller, beat lights and her
//     head simply hold still on a complete frame.
// (The .md beside the assets is hand-written, not generated by this script.)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const arg = (name) => {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const T0 = Number(arg('at') || 0);
const OUT = arg('out') ? path.resolve(arg('out')) : path.resolve(here, '../assets/15-kefrens-bars_opus_5.5.svg');

// ------------------------------------------------------------------ screen
const S = 3;            // real px per virtual (Amiga lo-res) pixel
const VW = 320;         // virtual screen
const VH = 136;
const W = VW * S;
const H = VH * S;
const BEAT = 0.75;      // 80 BPM
const BAR = 4 * BEAT;   // one bar of the theme: 3 s

const n = (v, d = 3) => String(+(+v).toFixed(d));
const dly = (s) => `${n(s - T0, 3)}s`;
const hex = (c) => (c.length === 4 ? `#${c[1]}${c[1]}${c[2]}${c[2]}${c[3]}${c[3]}` : c);

const defs = [];
const css = [];

// ------------------------------------------------------------------ pixels
// A pixel set is a Set of "x,y" strings in virtual px.
const key = (x, y) => `${x},${y}`;
const unkey = (k) => k.split(',').map(Number);
// Merge pixels into horizontal runs, stack identical runs into rects, and
// emit one path (real px). ox/oy offset in virtual px.
function pathOf(set, ox = 0, oy = 0) {
  const rows = new Map();
  for (const k of set) {
    const [x, y] = unkey(k);
    if (!rows.has(y)) rows.set(y, []);
    rows.get(y).push(x);
  }
  const runs = [];
  for (const [y, xs] of rows) {
    xs.sort((a, b) => a - b);
    let s = xs[0];
    let p = xs[0];
    for (let i = 1; i <= xs.length; i++) {
      if (i < xs.length && xs[i] === p + 1) { p = xs[i]; continue; }
      runs.push([s, p + 1, y]);
      if (i < xs.length) { s = xs[i]; p = xs[i]; }
    }
  }
  runs.sort((a, b) => a[2] - b[2] || a[0] - b[0]);
  const live = new Set(runs.map((r) => `${r[0]},${r[1]},${r[2]}`));
  const out = [];
  for (const r of runs) {
    const k0 = `${r[0]},${r[1]},${r[2]}`;
    if (!live.has(k0)) continue;
    live.delete(k0);
    let h = 1;
    while (live.has(`${r[0]},${r[1]},${r[2] + h}`)) { live.delete(`${r[0]},${r[1]},${r[2] + h}`); h++; }
    out.push(`M${(ox + r[0]) * S} ${(oy + r[2]) * S}h${(r[1] - r[0]) * S}v${h * S}h${-(r[1] - r[0]) * S}z`);
  }
  return out.join('');
}
// Pixels around `set` (8-neighbour ring), plus optional extra offsets.
function ring(set, extra = []) {
  const out = new Set();
  const offs = [];
  for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) offs.push([dx, dy]);
  offs.push(...extra);
  for (const k of set) {
    const [x, y] = unkey(k);
    for (const [dx, dy] of offs) {
      const k2 = key(x + dx, y + dy);
      if (!set.has(k2)) out.add(k2);
    }
  }
  return out;
}
// Parse a bitmap ('#' or colour letters) at `cell` virtual px per cell.
function bitmap(rows, cell = 1, lit = (c) => c !== '.') {
  const set = new Set();
  rows.forEach((row, y) => [...row].forEach((c, x) => {
    if (!lit(c)) return;
    for (let dy = 0; dy < cell; dy++) for (let dx = 0; dx < cell; dx++) set.add(key(x * cell + dx, y * cell + dy));
  }));
  return set;
}

// ------------------------------------------------------------------ palette
// Amiga OCS: 12-bit colour, ramps of 7 steps from a near-black edge to a
// bright centre. Three sunny hues from the island: the shallow sea, the
// midday sun and her coral tank top. (Always daytime: the black is the
// screen, not the sky.)
const RAMPS = {
  sea: ['#012', '#024', '#047', '#079', '#0ab', '#4cd', '#9ee', '#eff'],
  sun: ['#110', '#420', '#740', '#a70', '#da1', '#fc3', '#fe7', '#ffd'],
  coral: ['#200', '#511', '#833', '#b44', '#e66', '#f98', '#fcb', '#fed'],
};
const BW = 14; // bar width, virtual px
function barGradient(id, ramp) {
  // columns 0 1 2 3 4 5 7 7 5 4 3 2 1 0: dark edges, hot centre, each a flat
  // 12-bit colour (hard-stop pairs)
  const st = [];
  for (let i = 0; i < BW; i++) {
    const d = Math.min(i, BW - 1 - i);
    const c = hex(ramp[d >= 6 ? 7 : d]);
    st.push(`<stop offset="${n(i / BW, 4)}" stop-color="${c}"/><stop offset="${n((i + 1) / BW, 4)}" stop-color="${c}"/>`);
  }
  defs.push(`<linearGradient id="${id}">${st.join('')}</linearGradient>`);
}

// ------------------------------------------------------------------ bars
const T1 = 4 * BAR;   // swing period: 12 s
const T2 = 2 * BAR;   // twist period: 6 s
const A1 = 116;       // swing amplitude (virtual px)
const A2 = 28;        // twist amplitude
const P1 = 96;        // scanlines per swing cycle
const P2 = 60;        // scanlines per twist cycle
// Ribbons join the pile at different scanlines: the sea from the top line,
// the sun a quarter of the way down, her coral half way. So the top of the
// screen is one lone ribbon round the title and the bottom is all three.
const RIBBONS = [['sea', 0], ['sun', 34], ['coral', 70]];
const NR = RIBBONS.length;
const CX = Math.round(VW / 2 - BW / 2);
RIBBONS.forEach(([hue], r) => {
  barGradient(`g${hue}`, RAMPS[hue]);
  defs.push(`<rect id="r${r}" x="${CX * S}" width="${BW * S}" height="${H}" fill="url(#g${hue})"/>`);
});

// One quantised sine track: a keyframe only where the rounded value changes.
function track(name, A, T) {
  const N = 6000;
  const frames = [];
  let last = null;
  for (let i = 0; i < N; i++) {
    const v = Math.round(A * Math.sin((2 * Math.PI * i) / N));
    if (v !== last) {
      frames.push(`${n((i / N) * 100, 3)}%{transform:translateX(${v * S}px)}`);
      last = v;
    }
  }
  frames.push('100%{transform:translateX(0)}');
  css.push(`@keyframes ${name}{${frames.join('')}}.${name}{animation:${name} ${T}s step-end infinite}`);
}
track('A', A1, T1);
track('B', A2, T2);
for (let i = 0; i < P1; i++) css.push(`.a${i}{animation-delay:${dly((-T1 * i) / P1)}}`);
for (let i = 0; i < P2; i++) css.push(`.b${i}{animation-delay:${dly((-T2 * i) / P2)}}`);

const bars = [];
for (let k = 0; k < VH; k++) {
  for (let r = 0; r < NR; r++) {
    if (k < RIBBONS[r][1]) continue;
    const i1 = (((k + Math.round((r * P1) / NR)) % P1) + P1) % P1;
    const i2 = (((-k + Math.round((r * P2) / NR)) % P2) + P2) % P2;
    bars.push(`<g class="A a${i1}"><use class="B b${i2}" href="#r${r}" y="${k * S}"/></g>`);
  }
}

// The same trick in text, for the README's details block: one line buffer,
// one more bar per ribbon written into it per printed row, and every row
// printed is the whole buffer so far. `--ascii` prints it and exits.
function asciiBars() {
  const COLS = 76;
  const ROWS = 18;
  const BAR_TXT = '░▒▓█▓▒░';
  const line = [...' '.repeat(COLS)];
  const out = [];
  for (let k = 0; k < ROWS; k++) {
    for (const ph of [0, Math.PI]) {
      const x = Math.round(COLS / 2 - 3.5 + 28 * Math.sin((2 * Math.PI * k) / 34 + ph + 0.3) + 4 * Math.sin((-2 * Math.PI * k) / 11 + 1));
      [...BAR_TXT].forEach((c, i) => { if (x + i >= 0 && x + i < COLS) line[x + i] = c; });
    }
    out.push(line.join('').replace(/\s+$/, ''));
  }
  return out.join('\n');
}
if (process.argv.includes('--ascii')) {
  console.log(asciiBars());
  process.exit(0);
}

// ------------------------------------------------------------------ 5x7 font
const FONT5 = {
  A: '.###.|#...#|#...#|#...#|#####|#...#|#...#', B: '####.|#...#|#...#|####.|#...#|#...#|####.',
  C: '.###.|#...#|#....|#....|#....|#...#|.###.', D: '###..|#..#.|#...#|#...#|#...#|#..#.|###..',
  E: '#####|#....|#....|####.|#....|#....|#####', F: '#####|#....|#....|####.|#....|#....|#....',
  G: '.###.|#...#|#....|#.###|#...#|#...#|.####', H: '#...#|#...#|#...#|#####|#...#|#...#|#...#',
  I: '.###.|..#..|..#..|..#..|..#..|..#..|.###.', J: '..###|...#.|...#.|...#.|...#.|#..#.|.##..',
  K: '#...#|#..#.|#.#..|##...|#.#..|#..#.|#...#', L: '#....|#....|#....|#....|#....|#....|#####',
  M: '#...#|##.##|#.#.#|#.#.#|#...#|#...#|#...#', N: '#...#|#...#|##..#|#.#.#|#..##|#...#|#...#',
  O: '.###.|#...#|#...#|#...#|#...#|#...#|.###.', P: '####.|#...#|#...#|####.|#....|#....|#....',
  Q: '.###.|#...#|#...#|#...#|#.#.#|#..#.|.##.#', R: '####.|#...#|#...#|####.|#.#..|#..#.|#...#',
  S: '.####|#....|#....|.###.|....#|....#|####.', T: '#####|..#..|..#..|..#..|..#..|..#..|..#..',
  U: '#...#|#...#|#...#|#...#|#...#|#...#|.###.', V: '#...#|#...#|#...#|#...#|#...#|.#.#.|..#..',
  W: '#...#|#...#|#...#|#.#.#|#.#.#|#.#.#|.#.#.', X: '#...#|#...#|.#.#.|..#..|.#.#.|#...#|#...#',
  Y: '#...#|#...#|#...#|.#.#.|..#..|..#..|..#..', Z: '#####|....#|...#.|..#..|.#...|#....|#####',
  0: '.###.|#...#|#..##|#.#.#|##..#|#...#|.###.', 1: '..#..|.##..|..#..|..#..|..#..|..#..|.###.',
  2: '.###.|#...#|....#|...#.|..#..|.#...|#####', 3: '#####|...#.|..#..|...#.|....#|#...#|.###.',
  4: '...#.|..##.|.#.#.|#..#.|#####|...#.|...#.', 5: '#####|#....|####.|....#|....#|#...#|.###.',
  6: '..##.|.#...|#....|####.|#...#|#...#|.###.', 7: '#####|....#|...#.|..#..|.#...|.#...|.#...',
  8: '.###.|#...#|#...#|.###.|#...#|#...#|.###.', 9: '.###.|#...#|#...#|.####|....#|...#.|.##..',
  '.': '.....|.....|.....|.....|.....|.##..|.##..', ',': '.....|.....|.....|.....|.##..|..#..|.#...',
  ':': '.....|.##..|.##..|.....|.##..|.##..|.....', '-': '.....|.....|.....|#####|.....|.....|.....',
  "'": '..#..|..#..|.#...|.....|.....|.....|.....', '!': '..#..|..#..|..#..|..#..|..#..|.....|..#..',
  '/': '....#|....#|...#.|..#..|.#...|#....|#....', '?': '.###.|#...#|....#|...#.|..#..|.....|..#..',
  '♪': '..###|..#.#|..#..|..#..|###..|###..|.....',
};
const used5 = new Set();
// x, y in virtual px; 6 px advance. Fill comes from the group class.
function text5(str, x, y, cls) {
  const out = [];
  let cx = x;
  for (const ch of str.toUpperCase()) {
    if (ch !== ' ' && FONT5[ch]) {
      used5.add(ch);
      out.push(`<use href="#f${ch.codePointAt(0)}" x="${cx * S}" y="${y * S}"/>`);
    }
    cx += 6;
  }
  return `<g class="${cls}">${out.join('')}</g>`;
}
const width5 = (str) => str.length * 6 - 1;
function defineFont5() {
  for (const ch of used5) {
    const g = bitmap(FONT5[ch].split('|'), 1, (c) => c === '#');
    const kl = ring(g, [[2, 1], [1, 2], [2, 2]]);
    defs.push(`<symbol id="f${ch.codePointAt(0)}" overflow="visible"><path fill="#000" d="${pathOf(kl)}"/><path d="${pathOf(g)}"/></symbol>`);
  }
}

// ------------------------------------------------------------------ title
// Sandcastle capitals on a 2-px grid: 15 rows of body plus 2 of battlements
// (teeth along each top bar, a little turret on each W and Y stem). Drawn
// for this banner: built from sand bricks, the way the oldest of these
// screens built their giant letters out of stone.
const BODY = {
  C: [
    '.##############.', '################', '################', '#####......#####', '####........####',
    '####............', '####............', '####............', '####............', '####............',
    '####........####', '#####......#####', '################', '################', '.##############.',
  ],
  A: [
    '.##############.', '################', '################', '####........####', '####........####',
    '####........####', '####........####', '################', '################', '####........####',
    '####........####', '####........####', '####........####', '####........####', '####........####',
  ],
  S: [
    '.##############.', '################', '################', '####........####', '####............',
    '####............', '################', '.###############', '............####', '............####',
    '####........####', '####........####', '################', '################', '.##############.',
  ],
  T: [
    '.##############.', '################', '################', '......####......', '......####......',
    '......####......', '......####......', '......####......', '......####......', '......####......',
    '......####......', '......####......', '......####......', '......####......', '......####......',
  ],
  // The middle stem rises most of the way and the floor is one solid course:
  // a notch under the middle stem, or a short stem, splits it into "UJ".
  W: [
    '####..........####', '####..........####', '####..........####', '####...####...####', '####...####...####',
    '####...####...####', '####...####...####', '####...####...####', '####...####...####', '####...####...####',
    '####...####...####', '####...####...####', '##################', '##################', '.################.',
  ],
  Y: [
    '####........####', '####........####', '####........####', '####........####', '#####......#####',
    '.######..######.', '..############..', '....########....', '......####......', '......####......',
    '......####......', '......####......', '......####......', '......####......', '......####......',
  ],
};
function teeth(letter) {
  const top = BODY[letter][0];
  const w = top.length;
  const row = [...'.'.repeat(w)];
  for (let x = 0; x < w; x++) {
    if (top[x] !== '#') continue;
    if (letter === 'W' || letter === 'Y') {
      const s = x === 0 || top[x - 1] !== '#';
      const e = x === w - 1 || top[x + 1] !== '#';
      if (s || e) row[x] = '#';
    } else if (x % 4 === 1 || x % 4 === 2) row[x] = '#';
  }
  const r = row.join('');
  return [r, r];
}

const TITLE = 'CASTAWAY';
const CELL = 2;
const GAP = 2;
const TROWS = 17;
const TY = 18;
const letterAt = [];
let tw = 0;
const tcells = [];
for (const ch of TITLE) {
  const rows = [...teeth(ch), ...BODY[ch]];
  letterAt.push(tw);
  rows.forEach((row, y) => [...row].forEach((c, x) => { if (c === '#') tcells.push([tw + x, y]); }));
  tw += rows[0].length + GAP;
}
tw -= GAP;
const TX = Math.round((VW - tw * CELL) / 2);
const tset = new Set();
for (const [x, y] of tcells) {
  for (let dy = 0; dy < CELL; dy++) for (let dx = 0; dx < CELL; dx++) tset.add(key(TX + x * CELL + dx, TY + y * CELL + dy));
}
const has = (x, y) => tset.has(key(x, y));
// sunlit sand, top to bottom, and the mortar under it
const SAND = ['#ffe', '#ffd', '#fec', '#feb', '#eda', '#ec9', '#db8', '#ca7', '#b96'];
const MORTAR = ['#db8', '#ca7', '#b96', '#a85', '#974', '#863', '#752', '#641', '#531'];
const tgroups = new Map();
const put = (c, k) => {
  if (!tgroups.has(c)) tgroups.set(c, new Set());
  tgroups.get(c).add(k);
};
const ty1 = TY + TROWS * CELL;
for (const k of tset) {
  const [x, y] = unkey(k);
  const yy = y - TY;
  const band = Math.min(SAND.length - 1, Math.floor((yy / (ty1 - TY)) * SAND.length));
  const course = Math.floor(yy / 4);
  const mortarH = yy % 4 === 3;
  const mortarV = (x + (course % 2 ? 4 : 0)) % 8 === 0;
  let c;
  if (!has(x, y - 1) || !has(x - 1, y)) c = '#fff';                      // lit top and left edges
  else if (!has(x, y + 1) || !has(x + 1, y)) c = MORTAR[band];          // shaded bottom and right
  else if (mortarH || mortarV) c = MORTAR[band];
  else if (yy % 4 === 0) c = SAND[Math.max(0, band - 2)];               // brick tops catch the sun
  else c = SAND[band];
  put(c, k);
}
// extrusion down-right (3 px deep), then a black keyline round everything
const ext = new Set();
for (const k of tset) {
  const [x, y] = unkey(k);
  for (let d = 1; d <= 3; d++) if (!has(x + d, y + d)) ext.add(key(x + d, y + d));
}
const extLit = new Set();
const extDark = new Set();
for (const k of ext) {
  const [x, y] = unkey(k);
  // the face under a bottom edge catches a little light; the face beside a
  // right-hand edge stays dark
  if (has(x, y - 1) || (has(x - 1, y - 1) && !has(x - 1, y) && !ext.has(key(x, y - 1)))) extLit.add(k);
  else extDark.add(k);
}
const solid = new Set([...tset, ...ext]);
const tkey = ring(solid);
const titleSvg = [
  `<path fill="#000" d="${pathOf(tkey)}"/>`,
  `<path fill="#742" d="${pathOf(extLit)}"/>`,
  `<path fill="#421" d="${pathOf(extDark)}"/>`,
  ...[...tgroups].map(([c, set]) => `<path fill="${hex(c)}" d="${pathOf(set)}"/>`),
];

// ------------------------------------------------------------------ her
// Small and simple, sitting in the crook of the Y with her legs over the
// front: cream headphones, brown hair, coral tank top, cream shorts, bare
// feet. Eyes closed. Head nods on every beat.
const HER_HEAD = [
  '...PPPPP...',
  '..PHHHHHP..',
  '.PHHHHHHHP.',
  'CCHHSSSHHCC',
  'CcHSSSSSHcC',
  'CCSESSSESCC',
  '..HSSSSSHH.',
];
const HER_BODY = [
  '....sSs....',
  '..SSTTTSS..',
  '..STTTTTS..',
  '..STTTTTS..',
  '..StTTTtS..',
  '..SWWWWWS..',
  '..WWWwWWW..',
  '..SS...SS..',
  '..SS...SS..',
  '..SS...SS..',
  '..Ss...Ss..',
  '..FF...FF..',
];
const HER_COL = {
  P: '#dcb', C: '#fed', c: '#a98', H: '#743', S: '#fc9', s: '#d97', E: '#421', T: '#e76', t: '#c55', W: '#fec', w: '#dca', F: '#e98',
};
const yAt = TX + letterAt[TITLE.length - 1] * CELL;           // Y letter left, virtual px
const HX = yAt + 16 - 5;                                        // centred on the Y
const HY = TY + 1;            // seat (shorts) lands on the floor of the V
function sprite(rows, ox, oy) {
  const groups = new Map();
  const all = new Set();
  rows.forEach((row, y) => [...row].forEach((c, x) => {
    if (c === '.') return;
    const k = key(ox + x, oy + y);
    all.add(k);
    if (!groups.has(c)) groups.set(c, new Set());
    groups.get(c).add(k);
  }));
  return { all, paths: [...groups].map(([c, set]) => `<path fill="${HER_COL[c]}" d="${pathOf(set)}"/>`).join('') };
}
const head = sprite(HER_HEAD, HX, HY);
const torso = sprite(HER_BODY, HX, HY + HER_HEAD.length);
const herSvg = [
  `<g class="nod"><path fill="#000" d="${pathOf(ring(head.all))}"/></g>`,
  `<path fill="#000" d="${pathOf(ring(torso.all))}"/>`,
  torso.paths,
  `<g class="nod">${head.paths}</g>`,
].join('');
css.push(`.nod{animation:nod ${BEAT}s step-end infinite;animation-delay:${dly(0)}}@keyframes nod{0%{transform:translateY(${S}px)}40%{transform:translateY(0)}100%{transform:translateY(0)}}`);

// ------------------------------------------------------------------ scroller
// Bold 7x8 capitals on a 2-px grid, sky over sand like a beach-coloured
// chrome, black keyline. '*' is a little palm, the note is a note.
const BOLD = {
  A: ['..XXX..', '.XX.XX.', 'XX...XX', 'XX...XX', 'XXXXXXX', 'XX...XX', 'XX...XX', 'XX...XX'],
  B: ['XXXXXX.', 'XX...XX', 'XX...XX', 'XXXXXX.', 'XX...XX', 'XX...XX', 'XX...XX', 'XXXXXX.'],
  C: ['.XXXXX.', 'XX...XX', 'XX.....', 'XX.....', 'XX.....', 'XX.....', 'XX...XX', '.XXXXX.'],
  D: ['XXXXX..', 'XX..XX.', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', 'XX..XX.', 'XXXXX..'],
  E: ['XXXXXXX', 'XX.....', 'XX.....', 'XXXXXX.', 'XX.....', 'XX.....', 'XX.....', 'XXXXXXX'],
  F: ['XXXXXXX', 'XX.....', 'XX.....', 'XXXXXX.', 'XX.....', 'XX.....', 'XX.....', 'XX.....'],
  G: ['.XXXXX.', 'XX...XX', 'XX.....', 'XX.....', 'XX..XXX', 'XX...XX', 'XX...XX', '.XXXXXX'],
  H: ['XX...XX', 'XX...XX', 'XX...XX', 'XXXXXXX', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX'],
  I: ['XXXXXX', '..XX..', '..XX..', '..XX..', '..XX..', '..XX..', '..XX..', 'XXXXXX'],
  J: ['...XXXX', '.....XX', '.....XX', '.....XX', '.....XX', 'XX...XX', 'XX...XX', '.XXXXX.'],
  K: ['XX...XX', 'XX..XX.', 'XX.XX..', 'XXXX...', 'XXXXX..', 'XX..XX.', 'XX...XX', 'XX...XX'],
  L: ['XX.....', 'XX.....', 'XX.....', 'XX.....', 'XX.....', 'XX.....', 'XX.....', 'XXXXXXX'],
  M: ['XX...XX', 'XXX.XXX', 'XXXXXXX', 'XX.X.XX', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX'],
  N: ['XX...XX', 'XXX..XX', 'XXXX.XX', 'XX.XXXX', 'XX..XXX', 'XX...XX', 'XX...XX', 'XX...XX'],
  O: ['.XXXXX.', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', '.XXXXX.'],
  P: ['XXXXXX.', 'XX...XX', 'XX...XX', 'XX...XX', 'XXXXXX.', 'XX.....', 'XX.....', 'XX.....'],
  Q: ['.XXXXX.', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', 'XX.XXXX', 'XX..XX.', '.XXX.XX'],
  R: ['XXXXXX.', 'XX...XX', 'XX...XX', 'XX...XX', 'XXXXXX.', 'XX.XX..', 'XX..XX.', 'XX...XX'],
  S: ['.XXXXX.', 'XX...XX', 'XX.....', '.XXXXX.', '.....XX', '.....XX', 'XX...XX', '.XXXXX.'],
  T: ['XXXXXX', '..XX..', '..XX..', '..XX..', '..XX..', '..XX..', '..XX..', '..XX..'],
  U: ['XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', '.XXXXX.'],
  V: ['XX...XX', 'XX...XX', 'XX...XX', 'XX...XX', '.XX.XX.', '.XX.XX.', '..XXX..', '...X...'],
  W: ['XX...XX', 'XX...XX', 'XX...XX', 'XX.X.XX', 'XXXXXXX', 'XXX.XXX', 'XX...XX', 'X.....X'],
  X: ['XX...XX', 'XX...XX', '.XX.XX.', '..XXX..', '..XXX..', '.XX.XX.', 'XX...XX', 'XX...XX'],
  Y: ['XX....XX', 'XX....XX', '.XX..XX.', '..XXXX..', '...XX...', '...XX...', '...XX...', '...XX...'],
  Z: ['XXXXXXX', '.....XX', '....XX.', '...XX..', '..XX...', '.XX....', 'XX.....', 'XXXXXXX'],
  0: ['.XXXXX.', 'XX...XX', 'XX..XXX', 'XX.X.XX', 'XXX..XX', 'XX...XX', 'XX...XX', '.XXXXX.'],
  1: ['..XX..', '.XXX..', 'XXXX..', '..XX..', '..XX..', '..XX..', '..XX..', 'XXXXXX'],
  2: ['.XXXXX.', 'XX...XX', '.....XX', '....XX.', '..XXX..', '.XX....', 'XX.....', 'XXXXXXX'],
  3: ['.XXXXX.', 'XX...XX', '.....XX', '..XXXX.', '.....XX', '.....XX', 'XX...XX', '.XXXXX.'],
  4: ['....XX.', '...XXX.', '..XXXX.', '.XX.XX.', 'XX..XX.', 'XXXXXXX', '....XX.', '....XX.'],
  5: ['XXXXXXX', 'XX.....', 'XXXXXX.', '.....XX', '.....XX', '.....XX', 'XX...XX', '.XXXXX.'],
  6: ['..XXXX.', '.XX....', 'XX.....', 'XXXXXX.', 'XX...XX', 'XX...XX', 'XX...XX', '.XXXXX.'],
  7: ['XXXXXXX', '.....XX', '....XX.', '...XX..', '..XX...', '..XX...', '..XX...', '..XX...'],
  8: ['.XXXXX.', 'XX...XX', 'XX...XX', '.XXXXX.', 'XX...XX', 'XX...XX', 'XX...XX', '.XXXXX.'],
  9: ['.XXXXX.', 'XX...XX', 'XX...XX', 'XX...XX', '.XXXXXX', '.....XX', '....XX.', '.XXXX..'],
  '.': ['..', '..', '..', '..', '..', '..', 'XX', 'XX'],
  ',': ['..', '..', '..', '..', '..', 'XX', 'XX', 'X.'],
  '!': ['XX', 'XX', 'XX', 'XX', 'XX', '..', 'XX', 'XX'],
  ':': ['..', 'XX', 'XX', '..', '..', 'XX', 'XX', '..'],
  "'": ['XX', 'XX', 'X.', '..', '..', '..', '..', '..'],
  '-': ['.....', '.....', '.....', 'XXXXX', 'XXXXX', '.....', '.....', '.....'],
  '?': ['.XXXXX.', 'XX...XX', '.....XX', '...XXX.', '..XX...', '.......', '..XX...', '..XX...'],
  '/': ['.....XX', '....XX.', '....XX.', '...XX..', '..XX...', '.XX....', '.XX....', 'XX.....'],
  '♪': ['...XXXX', '...X..X', '...X..X', '...X...', '.XXX...', 'XXXX...', 'XXXX...', '.XX....'],
};
const PALM = [
  '..GGG...GGG..',
  '.GGgGG.GGgGG.',
  'GG..gGCGg..GG',
  'G....gTg....G',
  '......Tt.....',
  '......tT.....',
  '.....Tt......',
  '...YYYYYYY...',
];
const PALM_COL = { G: '#6c4', g: '#283', C: '#753', T: '#d97', t: '#954', Y: '#fd8' };
// sky over sand: one flat colour per 2-px row of the glyph
const SKYSAND = ['#fff', '#eff', '#cef', '#9cf', '#fe9', '#fd7', '#ec5', '#c93'];
defs.push(`<linearGradient id="sg" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="${16 * S}">${SKYSAND.map((c, i) => `<stop offset="${n(i / 8, 4)}" stop-color="${hex(c)}"/><stop offset="${n((i + 1) / 8, 4)}" stop-color="${hex(c)}"/>`).join('')}</linearGradient>`);

const SCROLL = [
  'ONE ISLAND. TEN HOURS.',
  'ALMOST NOTHING HAPPENS, ON PURPOSE.',
  'SHE NODS TO THE MUSIC ON HER HEADPHONES. EVERY SO OFTEN, SOMETHING HAPPENS. THEN SHE NODS SOME MORE.',
  'A SHIP SAILS PAST, EXACTLY WHILE SHE IS BUSY WITH A COCONUT.',
  'A MESSAGE IN A BOTTLE WASHES STRAIGHT BACK.',
  'A SHARK IN HEADPHONES NODS TO THE BEAT.',
  'ONE BAR OF SIGNAL, AT THE TOP OF THE PALM.',
  'A COCONUT FALLS ON A HERMIT CRAB. THE COCONUT WALKS OFF.',
  'A CAT ARRIVES ON A CRATE, NAPS UP THE PALM AND ONE DAY FLOATS AWAY AGAIN.',
  'SHE COULD LEAVE ANY TIME. SHE WALKS OUT OVER THE WATER AND COMES BACK WITH AN ICED COFFEE.',
  'EVERY GAG STARTS ON THE NEXT BAR OF THE MUSIC. EVERY COPPER BAR ON THIS SCREEN STARTS ON THE NEXT SCANLINE.',
  'EVERY SOUND IS SYNTHESIZED FROM CODE. ALWAYS DAYTIME.',
  'LET IT RUN. NOTHING WILL HAPPEN. THEN SOMETHING WILL.',
].join('  *  ') + '  *  ';
const usedBold = new Set();
const SY = 105;              // scroller glyph top, virtual px
const scrollUses = [];
let sx = 0;
for (const ch of SCROLL) {
  if (ch === ' ') { sx += 6; continue; }
  if (ch === '*') {
    usedBold.add('*');
    scrollUses.push(`<use href="#palm" x="${sx * S}"/>`);
    sx += PALM[0].length * 2 + 4;
    continue;
  }
  const g = BOLD[ch];
  if (!g) throw new Error(`no scroller glyph for ${JSON.stringify(ch)}`);
  usedBold.add(ch);
  scrollUses.push(`<use href="#s${ch.codePointAt(0)}" x="${sx * S}"/>`);
  sx += g[0].length * 2 + 2;
}
const SL = sx;                         // loop length, virtual px
const SPEED = 60;                      // virtual px per second
for (const ch of usedBold) {
  if (ch === '*') continue;
  const g = bitmap(BOLD[ch], 2, (c) => c === 'X');
  const kl = ring(g, [[2, 1], [1, 2], [2, 2], [3, 2], [2, 3], [3, 3]]);
  defs.push(`<symbol id="s${ch.codePointAt(0)}" overflow="visible"><path fill="#000" d="${pathOf(kl)}"/><path fill="url(#sg)" d="${pathOf(g)}"/></symbol>`);
}
{
  const all = bitmap(PALM, 2);
  const kl = ring(all, [[2, 1], [1, 2], [2, 2], [3, 2], [2, 3], [3, 3]]);
  const parts = Object.entries(PALM_COL).map(([c, col]) => `<path fill="${col}" d="${pathOf(bitmap(PALM, 2, (x) => x === c))}"/>`).join('');
  defs.push(`<symbol id="palm" overflow="visible"><path fill="#000" d="${pathOf(kl)}"/>${parts}</symbol>`);
}
css.push(`.sc{animation:sc ${n(SL / SPEED)}s steps(${SL}) infinite;animation-delay:${dly(0)}}@keyframes sc{from{transform:translateX(0)}to{transform:translateX(-${SL * S}px)}}`);
// The scroller starts 12 px in, so the first frame (and the frozen
// reduced-motion frame) shows "ONE ISLAND. TEN HOURS." whole and centred,
// with the first palm just off the right edge. The left margin only ever
// shows the trailing spaces of the loop, so the wrap stays seamless.
const scrollSvg = `<g transform="translate(${12 * S} ${SY * S})"><g class="sc"><g id="st">${scrollUses.join('')}</g><use href="#st" x="${SL * S}"/></g></g>`;

// ------------------------------------------------------------------ corners
// top left: the music's bars (80 BPM, a light per beat); top right: the
// signal's bars (one). The copper bars are everything else.
const bpm = '80 BPM';
const beatLights = [];
for (let i = 0; i < 4; i++) {
  beatLights.push(`<rect class="bl" style="animation-delay:${dly(i * BEAT - BAR)}" x="${(8 + width5(bpm) + 4 + i * 5) * S}" y="${8 * S}" width="${3 * S}" height="${3 * S}"/>`);
}
css.push(`.bl{fill:#422;animation:bl ${BAR}s step-end infinite}@keyframes bl{0%{fill:#fcb}25%{fill:#422}100%{fill:#422}}`);
// The meter sits 6 px clear of its label, and its lowest (lit) bar is 3 px
// tall, so the one bar of signal can't be mistaken for a full stop.
const sig = 'SIGNAL';
const sigX = VW - 8 - 15 - 6 - width5(sig);
const sigBars = [];
for (let i = 0; i < 4; i++) {
  const h = 3 + i * 2;
  sigBars.push(`<rect fill="${i === 0 ? '#fcb' : '#333'}" x="${(VW - 8 - 15 + i * 4) * S}" y="${(13 - h) * S}" width="${3 * S}" height="${h * S}"/>`);
}

// ------------------------------------------------------------------ assemble
const credit = 'BAREFOOT COPPERWORKS PRESENTS';
const sub = 'SHE IDLES. EVERY SO OFTEN, SOMETHING HAPPENS.';
const textBits = [
  text5(credit, Math.round((VW - width5(credit)) / 2), 6, 'tc'),
  text5(sub, Math.round((VW - width5(sub)) / 2), 63, 'ts'),
  text5(bpm, 8, 6, 'tq'),
  text5(sig, sigX, 6, 'tq'),
];
defineFont5();
css.push('.tc{fill:#fb9}.ts{fill:#ffe}.tq{fill:#9ab}');
css.push('@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}');

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" shape-rendering="crispEdges">
<title>CASTAWAY: one island, ten hours, vertical copper bars</title>
<desc>CASTAWAY in sandcastle capitals over ${bars.length} vertical copper bars in sea, sun and coral that braid into ribbons as they sway. A small young woman in cream headphones, a coral tank top and cream shorts sits in the crook of the Y and nods on every beat. A giant scroller runs along the bottom.</desc>
<defs>${defs.join('')}<clipPath id="scr"><rect width="${W}" height="${H}" rx="15"/></clipPath></defs>
<style>${css.join('')}</style>
<g clip-path="url(#scr)">
<rect width="${W}" height="${H}" fill="#000"/>
<g>${bars.join('')}</g>
<g>${titleSvg.join('')}</g>
<g>${herSvg}</g>
${textBits.join('')}
<g>${beatLights.join('')}${sigBars.join('')}</g>
${scrollSvg}
</g>
<rect x="1.5" y="1.5" width="${W - 3}" height="${H - 3}" rx="14" fill="none" stroke="#3a3530" stroke-width="3"/>
</svg>
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
console.log(`wrote ${path.relative(process.cwd(), OUT)} (${(svg.length / 1024).toFixed(1)} KB): ${bars.length} copper bars, scroller loop ${n(SL / SPEED, 1)} s`);
