// "Vector objects" README banner for CASTAWAY.
//
//   node examples/castaway/src/26-vector-objects_opus_5.5.mjs
//   node examples/castaway/src/26-vector-objects_opus_5.5.mjs --at=9.4 --out=some/where.svg
//
// Regenerates ../assets/26-vector-objects_opus_5.5.svg (the banner) and
// ../assets/26-vector-objects_opus_5.5-props.svg (a strip of wireframe props
// for the .md's details block). Plain Node, no deps, deterministic (no clock,
// no Math.random). --at bakes a head start (seconds) into every animation so
// a late frame can be checked without waiting; use it only with --out.
// (The .md beside the assets is hand-written, not generated by this script.)
//
// The style: the demo/cracktro "vector object" family (glenz, dot scroller,
// vector balls, wireframe). One translucent object turns slowly in the middle
// of a plain field while the text does the talking. Nothing here is copied
// from any production: the object, fonts, palette, copy and crew are made up
// in this file.
//
// How the SVG does it
//   * GLENZ. A tetrakis hexahedron (a cube with a low pyramid on every face,
//     24 triangles, two-coloured like a chessboard) is rotated here on three
//     axes and projected with perspective, F frames per turn. Every face is
//     one <polygon> whose points and fill are SMIL value lists; the browser
//     interpolates between frames. Faces are 46 (white) and 74 (coral pink)
//     percent opaque, so the back of the object shows through the front and
//     overlaps get brighter. No depth sort needed: the point of glenz.
//   * DOT SCROLLER. A ring of N character slots round the object's equator,
//     tilted towards the viewer. Every slot shares ONE @keyframes (a full
//     turn: translate on the ellipse, scaleX = cos, skewY for the slope, and
//     the brightness) and differs only in animation-delay. The ring is drawn
//     twice: the far half behind the glenz (dim, mirrored, seen through the
//     glass) and the near half in front. A slot holds R glyphs, one per turn,
//     and swaps glyph while it is directly behind the object, so N*R
//     characters of text go round on N slots.
//   * VECTOR BALLS. The title is a 5x7 matrix of shaded balls (one radial
//     gradient, one <use> each). The columns float on a slow wave, and once
//     a minute, on the bar, the letters flip one after another: a per-ball
//     CSS variable (its distance from the letter's axis) feeds one shared
//     @keyframes, so the balls swing round in 3D with depth scaling.
//   * TEXT WRITER. Five pages, hard cuts between them (the project's own
//     motion default). Page 1 is already typed at t = 0. Typing is a cover
//     cut from the field's own gradient stepping off one character at a time,
//     with the cursor riding its edge.
//   * Every period divides 60 s, the length of the project's theme (20 bars
//     of 3 s at 80 BPM): the glenz cycles every 30 s, the ring every 15 s, the
//     object dips on every beat, a ripple leaves it on every bar, and the
//     title flip starts on bar 4.
//   * prefers-reduced-motion pauses every CSS track where it starts and swaps
//     the SMIL glenz for a still copy of its first frame.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const arg = (name) => {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const T0 = Number(arg('at') || 0);
const OUT = arg('out') ? path.resolve(arg('out')) : path.resolve(here, '../assets/26-vector-objects_opus_5.5.svg');

// ------------------------------------------------------------------ basics
const W = 1000;
const H = 400;
const LOOP = 60;             // s, the theme's loop
const BAR = 3;               // s, one bar at 80 BPM
const BEAT = BAR / 4;
const TAU = Math.PI * 2;
const CREW = 'TIDEPOOL POLYGON SOCIETY';

const n = (v, d = 2) => String(+(+v).toFixed(d));
const n1 = (v) => n(v, 1);
const mod = (a, m) => ((a % m) + m) % m;
// animation-delay for a track whose state at time t is progress ((t + off) mod P) / P
const del = (off, P) => {
  const d = mod(off + T0, P);
  return d < 0.0005 || P - d < 0.0005 ? '0s' : `-${n(d, 3)}s`;
};
const hexRgb = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const rgbHex = (c) => `#${c.map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('')}`;
const lerpHex = (a, b, t) => { const pa = hexRgb(a), pb = hexRgb(b); return rgbHex(pa.map((v, i) => v + (pb[i] - v) * t)); };
const stops = (list) => list.map(([o, c, a]) => `<stop offset="${o}" stop-color="${c}"${a === undefined ? '' : ` stop-opacity="${a}"`}/>`).join('');

// ------------------------------------------------------------------ palette
const FIELD = [[0, '#3c9fe6'], [0.55, '#28afdc'], [1, '#17bfc6']];   // sky into lagoon
const INK = '#0b335a';        // deep-water navy: shadows, outlines
const CREAM = '#fff8e6';
const CORAL = '#ff7a6b';
const SAND = '#ffd98a';

// ------------------------------------------------------------------ 5x7 font
// Capitals, digits, a few symbols, and lowercase (rows 7-8 are descenders)
// so `python tools/serve.py` is spelt the way it is typed.
const FONT = {
  A: '.###.|#...#|#...#|#####|#...#|#...#|#...#', B: '####.|#...#|#...#|####.|#...#|#...#|####.',
  C: '.###.|#...#|#....|#....|#....|#...#|.###.', D: '####.|#...#|#...#|#...#|#...#|#...#|####.',
  E: '#####|#....|#....|####.|#....|#....|#####', F: '#####|#....|#....|####.|#....|#....|#....',
  G: '.###.|#...#|#....|#.###|#...#|#...#|.####', H: '#...#|#...#|#...#|#####|#...#|#...#|#...#',
  I: '.###.|..#..|..#..|..#..|..#..|..#..|.###.', J: '..###|...#.|...#.|...#.|...#.|#..#.|.##..',
  K: '#...#|#..#.|#.#..|##...|#.#..|#..#.|#...#', L: '#....|#....|#....|#....|#....|#....|#####',
  M: '#...#|##.##|#.#.#|#.#.#|#...#|#...#|#...#', N: '#...#|#...#|##..#|#.#.#|#..##|#...#|#...#',
  O: '.###.|#...#|#...#|#...#|#...#|#...#|.###.', P: '####.|#...#|#...#|####.|#....|#....|#....',
  Q: '.###.|#...#|#...#|#...#|#.#.#|#..#.|.##.#', R: '####.|#...#|#...#|####.|#.#..|#..#.|#...#',
  S: '.####|#....|#....|.###.|....#|....#|####.', T: '#####|..#..|..#..|..#..|..#..|..#..|..#..',
  U: '#...#|#...#|#...#|#...#|#...#|#...#|.###.', V: '#...#|#...#|#...#|#...#|#...#|.#.#.|..#..',
  W: '#...#|#...#|#...#|#.#.#|#.#.#|#.#.#|.#.#.', X: '#...#|#...#|.#.#.|..#..|.#.#.|#...#|#...#',
  Y: '#...#|#...#|.#.#.|..#..|..#..|..#..|..#..', Z: '#####|....#|...#.|..#..|.#...|#....|#####',
  0: '.###.|#...#|#..##|#.#.#|##..#|#...#|.###.', 1: '..#..|.##..|..#..|..#..|..#..|..#..|.###.',
  2: '.###.|#...#|....#|...#.|..#..|.#...|#####', 3: '#####|...#.|..#..|...#.|....#|#...#|.###.',
  4: '...#.|..##.|.#.#.|#..#.|#####|...#.|...#.', 5: '#####|#....|####.|....#|....#|#...#|.###.',
  6: '..##.|.#...|#....|####.|#...#|#...#|.###.', 7: '#####|....#|...#.|..#..|.#...|.#...|.#...',
  8: '.###.|#...#|#...#|.###.|#...#|#...#|.###.', 9: '.###.|#...#|#...#|.####|....#|...#.|.##..',
  '.': '.....|.....|.....|.....|.....|.##..|.##..', ',': '.....|.....|.....|.....|.##..|..#..|.#...',
  ':': '.....|.##..|.##..|.....|.##..|.##..|.....', '-': '.....|.....|.....|.####|.....|.....|.....',
  '/': '....#|....#|...#.|..#..|.#...|#....|#....', '!': '..#..|..#..|..#..|..#..|..#..|.....|..#..',
  '?': '.###.|#...#|....#|...#.|..#..|.....|..#..', "'": '..#..|..#..|.#...|.....|.....|.....|.....',
  '(': '...#.|..#..|.#...|.#...|.#...|..#..|...#.', ')': '.#...|..#..|...#.|...#.|...#.|..#..|.#...',
  '>': '.#...|..#..|...#.|....#|...#.|..#..|.#...', '+': '.....|..#..|..#..|#####|..#..|..#..|.....',
  '=': '.....|.....|#####|.....|#####|.....|.....', '*': '.....|#.#.#|.###.|#####|.###.|#.#.#|.....',
  '♪': '..#..|..##.|..#.#|..#..|.##..|###..|.#...', '·': '.....|.....|.....|..#..|.....|.....|.....',
  '→': '.....|..#..|...#.|#####|...#.|..#..|.....',
  a: '.....|.....|.###.|....#|.####|#...#|.####', b: '#....|#....|####.|#...#|#...#|#...#|####.',
  c: '.....|.....|.####|#....|#....|#....|.####', d: '....#|....#|.####|#...#|#...#|#...#|.####',
  e: '.....|.....|.###.|#...#|#####|#....|.###.', f: '..##.|.#...|####.|.#...|.#...|.#...|.#...',
  g: '.....|.....|.####|#...#|#...#|#...#|.####|....#|.###.', h: '#....|#....|####.|#...#|#...#|#...#|#...#',
  i: '..#..|.....|.##..|..#..|..#..|..#..|.###.', j: '...#.|.....|..##.|...#.|...#.|...#.|...#.|#..#.|.##..',
  k: '#....|#....|#..#.|#.#..|##...|#.#..|#..#.', l: '.##..|..#..|..#..|..#..|..#..|..#..|.###.',
  m: '.....|.....|##.#.|#.#.#|#.#.#|#.#.#|#...#', n: '.....|.....|####.|#...#|#...#|#...#|#...#',
  o: '.....|.....|.###.|#...#|#...#|#...#|.###.', p: '.....|.....|####.|#...#|#...#|#...#|####.|#....|#....',
  q: '.....|.....|.####|#...#|#...#|#...#|.####|....#|....#', r: '.....|.....|#.##.|##..#|#....|#....|#....',
  s: '.....|.....|.####|#....|.###.|....#|####.', t: '.#...|.#...|####.|.#...|.#...|.#..#|..##.',
  u: '.....|.....|#...#|#...#|#...#|#...#|.####', v: '.....|.....|#...#|#...#|#...#|.#.#.|..#..',
  w: '.....|.....|#...#|#...#|#.#.#|#.#.#|.#.#.', x: '.....|.....|#...#|.#.#.|..#..|.#.#.|#...#',
  y: '.....|.....|#...#|#...#|#...#|#...#|.####|....#|.###.', z: '.....|.....|#####|...#.|..#..|.#...|#####',
};
const ADV = 6;
const rows = (ch) => {
  const g = FONT[ch];
  if (!g) throw new Error(`no glyph for ${JSON.stringify(ch)}`);
  return g.split('|');
};
const gid = (ch) => `g${ch.codePointAt(0).toString(16)}`;
const did = (ch) => `d${ch.codePointAt(0).toString(16)}`;

// solid pixel glyphs: one path per glyph, runs merged per row
const usedPix = new Set();
function pixPath(ch) {
  let d = '';
  rows(ch).forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      if (row[x] !== '#') { x++; continue; }
      let e = x;
      while (e < row.length && row[e] === '#') e++;
      d += `M${x} ${y}h${e - x}v1h${x - e}z`;
      x = e;
    }
  });
  return d;
}
// a line of pixel text as a group of <use>, unit u, top-left (x, y)
function pixLine(str, u) {
  let uses = '';
  [...str].forEach((ch, i) => {
    if (ch === ' ') return;
    rows(ch);
    usedPix.add(ch);
    uses += `<use href="#${gid(ch)}" x="${i * ADV}"/>`;
  });
  return uses;
}
const textW = (str, u) => ([...str].length * ADV - 1) * u;
let defsText = '';
let lineId = 0;
// shadowed pixel text: defined once, drawn twice (shadow, face)
function pixText(str, x, y, u, { anchor = 'start', fill = '#fff', shadow = INK, sh = 1, cls = '' } = {}) {
  const w = textW(str, u);
  const x0 = anchor === 'middle' ? x - w / 2 : anchor === 'end' ? x - w : x;
  const id = `t${lineId++}`;
  defsText += `<g id="${id}" transform="translate(${n(x0)} ${n(y)}) scale(${u})">${pixLine(str, u)}</g>`;
  const shadowUse = shadow ? `<use href="#${id}" x="${n(sh * u)}" y="${n(sh * u)}" fill="${shadow}"${typeof shadow === 'string' && shadow.length > 7 ? '' : ''}/>` : '';
  return { svg: `<g${cls ? ` class="${cls}"` : ''}>${shadowUse}<use href="#${id}" fill="${fill}"/></g>`, x0, w };
}

// dot glyphs for the scroller: (nearly) zero-length round-capped strokes, grid units;
// the tenth-of-a-dot length makes every renderer draw the cap
const usedDot = new Set();
function dotPath(ch) {
  let d = '';
  rows(ch).forEach((row, y) => {
    for (let x = 0; x < row.length; x++) if (row[x] === '#') d += `M${x - 2} ${y - 3}h.1`;
  });
  return d;
}

// ================================================================== GLENZ
const OBJ = { cx: 232, cy: 200, S: 120, D: 5.2, P: 30, F: 48, Q: 2 };   // Q: coordinate steps per px
// tetrakis hexahedron: cube corners plus a pyramid apex over every face
const PYR = 0.62;            // apex height over the face (cube half-size 1)
const verts = [];
for (const x of [-1, 1]) for (const y of [-1, 1]) for (const z of [-1, 1]) verts.push([x, y, z]);
const vIndex = (v) => verts.findIndex((w) => w[0] === v[0] && w[1] === v[1] && w[2] === v[2]);
const faces = [];
for (let ax = 0; ax < 3; ax++) {
  for (const s of [-1, 1]) {
    const apex = [0, 0, 0];
    apex[ax] = s * (1 + PYR);
    verts.push(apex);
    const ai = verts.length - 1;
    const a1 = (ax + 1) % 3, a2 = (ax + 2) % 3;
    const ring = [[-1, -1], [1, -1], [1, 1], [-1, 1]].map(([p, q]) => {
      const v = [0, 0, 0];
      v[ax] = s; v[a1] = p; v[a2] = q;
      return vIndex(v);
    });
    for (let j = 0; j < 4; j++) {
      let f = [ring[j], ring[(j + 1) % 4], ai];
      // outward winding
      const [A, B, C] = f.map((i) => verts[i]);
      const nrm = cross(sub(B, A), sub(C, A));
      const cen = [0, 1, 2].map((k) => (A[k] + B[k] + C[k]) / 3);
      if (dot(nrm, cen) < 0) f = [f[0], f[2], f[1]];
      faces.push(f);
    }
  }
}
function sub(a, b) { return [a[0] - b[0], a[1] - b[1], a[2] - b[2]]; }
function cross(a, b) { return [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]]; }
function dot(a, b) { return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]; }
function norm(a) { const l = Math.hypot(...a); return a.map((v) => v / l); }
// normalise so the farthest vertex sits on the unit sphere
const RMAX = Math.max(...verts.map((v) => Math.hypot(...v)));
for (const v of verts) for (let k = 0; k < 3; k++) v[k] /= RMAX;
// chessboard colouring: BFS over faces sharing an edge
const edgeKey = (a, b) => (a < b ? `${a}-${b}` : `${b}-${a}`);
const byEdge = new Map();
faces.forEach((f, i) => { for (let j = 0; j < 3; j++) { const k = edgeKey(f[j], f[(j + 1) % 3]); if (!byEdge.has(k)) byEdge.set(k, []); byEdge.get(k).push(i); } });
const colour = new Array(faces.length).fill(-1);
colour[0] = 0;
const queue = [0];
while (queue.length) {
  const i = queue.shift();
  const f = faces[i];
  for (let j = 0; j < 3; j++) {
    for (const o of byEdge.get(edgeKey(f[j], f[(j + 1) % 3]))) {
      if (o === i) continue;
      if (colour[o] === -1) { colour[o] = 1 - colour[i]; queue.push(o); }
      else if (colour[o] === colour[i]) throw new Error('glenz mesh is not two-colourable');
    }
  }
}

function rotAt(u0) {
  // three axes, integer turns per period so the loop closes; frame 0 starts
  // a little way in, so the first (and the reduced-motion) frame looks 3D
  const u = u0 + 0.13;
  const b = TAU * 2 * u;             // spin
  const a = TAU * 1 * u + 0.55;      // tumble
  const g = 0.32 * Math.sin(TAU * u); // sway
  const ca = Math.cos(a), sa = Math.sin(a), cb = Math.cos(b), sb = Math.sin(b), cg = Math.cos(g), sg = Math.sin(g);
  return (v) => {
    // Ry(b)
    let x = v[0] * cb + v[2] * sb, y = v[1], z = -v[0] * sb + v[2] * cb;
    // Rx(a)
    const y2 = y * ca - z * sa, z2 = y * sa + z * ca;
    y = y2; z = z2;
    // Rz(g)
    const x3 = x * cg - y * sg, y3 = x * sg + y * cg;
    return [x3, y3, z];
  };
}
const LIGHT = norm([-0.5, -0.7, 0.55]);
const GZ = [
  { op: 0.46, lit: '#ffffff', dim: '#d6f0ff', back: '#7cc6f4' },   // glass
  { op: 0.74, lit: '#ffa6bd', dim: '#ff3f7a', back: '#b02a6c' },   // coral pink
];
const proj = (p) => {
  const k = OBJ.D / (OBJ.D - p[2]);
  return [Math.round(p[0] * OBJ.S * k * OBJ.Q), Math.round(p[1] * OBJ.S * k * OBJ.Q)];
};
const frames = [];
for (let fi = 0; fi < OBJ.F; fi++) {
  const R = rotAt(fi / OBJ.F);
  const rv = verts.map(R);
  const pv = rv.map(proj);
  frames.push(faces.map((f, i) => {
    const [A, B, C] = f.map((k) => rv[k]);
    const nr = norm(cross(sub(B, A), sub(C, A)));
    const cen = [0, 1, 2].map((k) => (A[k] + B[k] + C[k]) / 3);
    const toCam = norm(sub([0, 0, OBJ.D], cen));
    const facing = dot(nr, toCam);
    const pal = GZ[colour[i]];
    let fill;
    if (facing > 0) fill = lerpHex(pal.dim, pal.lit, Math.max(0, dot(nr, LIGHT)) ** 0.8);
    else fill = lerpHex(pal.back, pal.dim, 0.25 * Math.max(0, -dot(nr, LIGHT)));
    return { pts: f.map((k) => `${pv[k][0]},${pv[k][1]}`).join(' '), fill };
  }));
}
function glenzSvg() {
  let anim = '';
  let still = '';
  const begin = T0 ? ` begin="-${n(T0, 3)}s"` : '';
  faces.forEach((f, i) => {
    const pts = frames.map((fr) => fr[i].pts);
    const fills = frames.map((fr) => fr[i].fill);
    pts.push(pts[0]); fills.push(fills[0]);
    const op = GZ[colour[i]].op;
    anim += `<polygon fill-opacity="${op}" points="${pts[0]}"><animate attributeName="points" dur="${OBJ.P}s"${begin} repeatCount="indefinite" values="${pts.join(';')}"/><animate attributeName="fill" dur="${OBJ.P}s"${begin} repeatCount="indefinite" values="${fills.join(';')}"/></polygon>`;
    still += `<polygon fill-opacity="${op}" fill="${fills[0]}" points="${pts[0]}"/>`;
  });
  return `<g class="gz">${anim}</g><g class="gzs">${still}</g>`;
}

// ================================================================== DOT RING
const RING = { N: 40, R: 4, T: 15, Rr: 188, elev: 0.26, gp: 4.5, samples: 40 };
RING.M = RING.N * RING.R;
const RING_TEXT = '♪ SHE IDLES. NOTHING HAPPENS. ♪ A BOTTLE WASHES STRAIGHT BACK. ♪ A SHARK IN HEADPHONES NODS ALONG. ♪ SHE WALKS OUT OVER THE WATER, BACK WITH AN ICED COFFEE. ';
function ringSvg() {
  const msg = [...RING_TEXT];
  if (msg.length > RING.M) throw new Error(`ring text is ${msg.length} chars, room for ${RING.M}`);
  while (msg.length < RING.M) msg.push(' ');
  const se = Math.sin(RING.elev), ce = Math.cos(RING.elev);
  const kfF = [], kfB = [];
  for (let s = 0; s <= RING.samples; s++) {
    const p = s / RING.samples;
    const th = -TAU * p;
    const c = Math.cos(th), sn = Math.sin(th);
    const x = RING.Rr * sn, y = RING.Rr * c * se;
    // the glyph's baseline follows the ellipse: tan A = -tan(th) sin(e), clamped at the edges
    let A = Math.atan((-sn * se) / (Math.abs(c) < 0.02 ? 0.02 * Math.sign(c || 1) : c)) * 180 / Math.PI;
    A = Math.max(-62, Math.min(62, A));
    const tf = `translate(${n1(x)}px,${n1(y)}px) skewY(${n1(A)}deg) scale(${n(c * RING.gp, 3)},${n(ce * RING.gp, 3)})`;
    // near half: full brightness at the front, fading towards the edges
    const oF = c > 0 ? Math.min(1, 0.15 + 1.25 * c) : 0;
    // far half: dim, gone directly behind (where glyphs are swapped)
    const phi = Math.abs(Math.atan2(sn, -c)); // 0 = straight behind
    const oB = c < 0 ? 0.62 * Math.min(1, Math.max(0, (phi - 0.18) / 0.5)) : 0;
    const pct = n(p * 100, 3);
    kfF.push(`${pct}%{transform:${tf};opacity:${n(oF, 2)}}`);
    kfB.push(`${pct}%{transform:${tf};opacity:${n(oB, 2)}}`);
  }
  const css = [
    `@keyframes rf{${kfF.join('')}}`, `@keyframes rb{${kfB.join('')}}`,
    `.rf{animation:rf ${RING.T}s linear infinite;animation-delay:var(--r)}`, `.rb{animation:rb ${RING.T}s linear infinite;animation-delay:var(--r)}`,
  ];
  // glyph j of a slot shows on its j-th turn: one keyframes per turn, the slot's own clock in --k
  const q = 100 / RING.R;
  for (let j = 0; j < RING.R; j++) {
    const kf = j === 0 ? `0%{opacity:1}${n(q, 3)}%,100%{opacity:0}`
      : j === RING.R - 1 ? `0%{opacity:0}${n(j * q, 3)}%,100%{opacity:1}`
        : `0%{opacity:0}${n(j * q, 3)}%{opacity:1}${n((j + 1) * q, 3)}%,100%{opacity:0}`;
    css.push(`@keyframes v${j}{${kf}}`, `.v${j}{animation:v${j} ${RING.T * RING.R}s step-end infinite;animation-delay:var(--k)}`);
  }
  // which character each slot shows on each turn
  const m0 = 6;   // the char at the front centre at t = 0 (front shows the start of the text)
  const slotUses = [];
  for (let k = 0; k < RING.N; k++) {
    const base = m0 + k - (k >= RING.N / 2 ? RING.N : 0);
    const t0k = RING.T * mod(k / RING.N - 0.5, 1);   // first pass behind the object
    let uses = [];
    for (let j = 0; j < RING.R; j++) {
      const ch = msg[mod(base + RING.N * j, RING.M)];
      if (ch === ' ') continue;
      usedDot.add(ch);
      uses.push(`<use href="#${did(ch)}" class="v${j}"/>`);
    }
    // turn j runs from (t0k + (j-1)T); the slot's clock starts at t0k - T
    const vars = `--r:${del(-k * RING.T / RING.N, RING.T)};--k:${del(-(t0k - RING.T), RING.T * RING.R)}`;
    slotUses.push({ k, uses: uses.join(''), vars });
  }
  const copy = (cls) => slotUses.filter((s) => s.uses).map((s) => `<g class="${cls}" style="${s.vars}">${s.uses}</g>`).join('');
  return { back: `<g class="ringB">${copy('rb')}</g>`, front: `<g class="ringF">${copy('rf')}</g>`, css };
}

// ================================================================== TITLE BALLS
const TITLE = { text: 'CASTAWAY', p: 10.6, r: 6.1, adv: 6.3, cx: 712, y: 70, flipAt: 9, stagger: BEAT / 2, flipDur: BEAT };
function titleSvg() {
  const letters = [...TITLE.text];
  const cols = (letters.length - 1) * TITLE.adv + 5;
  const x0 = TITLE.cx - ((cols - 1) * TITLE.p) / 2;
  const width = (cols - 1) * TITLE.p;
  let out = '';
  const colGroups = new Map();
  letters.forEach((ch, li) => {
    const g = rows(ch);
    const lx = x0 + li * TITLE.adv * TITLE.p;
    for (let c = 0; c < 5; c++) {
      const x = lx + c * TITLE.p;
      for (let r = 0; r < 7; r++) {
        if (g[r][c] !== '#') continue;
        const key = `${li}:${c}`;
        if (!colGroups.has(key)) colGroups.set(key, { x, li, balls: [] });
        colGroups.get(key).balls.push({ x, y: TITLE.y + r * TITLE.p, d: (c - 2) * TITLE.p, li });
      }
    }
  });
  // flip keyframes: one turn about the letter's vertical axis, depth-scaled
  const fs1 = [];
  const span = (TITLE.flipDur / LOOP) * 100;
  const steps = 16;
  for (let s = 0; s <= steps; s++) {
    const ph = (TAU * s) / steps;
    const cx = Math.cos(ph) - 1, sz = Math.sin(ph) * 0.016;
    fs1.push(`${n(span * s / steps, 3)}%{transform:translateX(calc(var(--d) * ${n(cx, 3)}px)) scale(calc(1 + var(--d) * ${n(sz, 4)}))}`);
  }
  fs1.push('100%{transform:translateX(0px) scale(1)}');
  const css = [
    `@keyframes fl{${fs1.join('')}}`,
    `.fl{animation:fl ${LOOP}s linear infinite;animation-delay:var(--f)}`,
    `@keyframes tb{0%,100%{transform:translateY(-2.4px)}50%{transform:translateY(2.4px)}}`,
    `.tb{animation:tb ${2 * BAR}s ease-in-out infinite}`,
  ];
  // order: columns left to right, balls top to bottom (each ball's shadow falls on later balls only)
  for (const [, cg] of colGroups) {
    const bob = del(((cg.x - x0) / width) * 2 * BAR, 2 * BAR);
    const flip = del(-(TITLE.flipAt + cg.li * TITLE.stagger), LOOP);
    let balls = '';
    for (const b of cg.balls) balls += `<g transform="translate(${n1(b.x)} ${n1(b.y)})"><use href="#ball" class="fl" style="--d:${n1(b.d)}"/></g>`;
    out += `<g class="tb" style="animation-delay:${bob};--f:${flip}">${balls}</g>`;
  }
  return { svg: `<g>${out}</g>`, css, x0, width };
}

// ================================================================== WRITER
const PAGES = [
  ['TEN HOURS. ONE ISLAND. ONE PALM.', 'SHE IDLES, NODDING TO THE MUSIC.', 'EVERY SO OFTEN, SOMETHING', 'HAPPENS. ALWAYS ON THE NEXT BAR.'],
  ['A BOTTLE WASHES STRAIGHT BACK.', 'A DRONE DELIVERS... HEADPHONES.', 'A STRAY CAT NAPS UP THE PALM.', 'A COCONUT WALKS OFF WITH A CRAB.'],
  ['90+ ACTIVITIES ON FOUR TIMERS:', '2-5 MIN, 12-25, 30-60, 3-6 HOURS', 'BUSY A THIRD OF THE TIME.', 'IDLE THE OTHER TWO. ON PURPOSE.'],
  ['EVERY SOUND IS MADE FROM CODE.', 'NO SAMPLES, LOOPS OR RECORDINGS.', '80 BPM, F MAJOR, KALIMBA LEAD.', 'MIXED TO -14 LUFS. HEARD: NOT YET'],
  ['> python tools/serve.py', '> open http://127.0.0.1:8765/', 'LIVE PREVIEW. EXPORT AN MP4.', 'THEN WAIT. THAT IS THE VIDEO.'],
];
const WR = { cx: 712, y: 198, u: 2.4, lh: 28, pageLen: LOOP / PAGES.length, cps: 34, lineGap: 0.25 };
function writerSvg() {
  const css = [
    `@keyframes pg{0%{opacity:1}${n(100 / PAGES.length, 3)}%,100%{opacity:0}}`,
    `.pg{animation:pg ${LOOP}s step-end infinite}`,
    `@keyframes bl{0%{opacity:1}50%,100%{opacity:0}}`,
    `.bl{animation:bl 1s step-end infinite}`,
  ];
  let out = '';
  PAGES.forEach((lines, pi) => {
    let pg = '';
    let t = pi * WR.pageLen + 0.35;
    lines.forEach((str, li) => {
      if ([...str].length > 33) throw new Error(`writer line too long: ${str}`);
      const y = WR.y + li * WR.lh;
      const tx = pixText(str, WR.cx, y, WR.u, { anchor: 'middle', sh: 0.8 });
      pg += tx.svg;
      const last = li === lines.length - 1;
      const cw = WR.u * 5, ch = WR.u * 7;
      // the cursor is currentColor, so the cover's keyframes can hide it before and after its line
      const cur = `<rect x="${n(tx.x0)}" y="${n(y)}" width="${n(cw)}" height="${n(ch)}" fill="currentColor"${last ? ' class="bl"' : ''}/>`;
      if (pi === 0) {
        // already typed at t = 0; the cursor waits at the end of the last line
        if (last) pg += `<g transform="translate(${n(tx.w + WR.u)} 0)" color="${CREAM}">${cur}</g>`;
        return;
      }
      const nch = [...str].length;
      const dur = nch / WR.cps;
      const s = t, e = t + dur;
      t = e + WR.lineGap;
      const P = (v) => n((v / LOOP) * 100, 3);
      const adv = nch * ADV * WR.u;
      const name = `ty${pi}${li}`;
      const on = `color:${CREAM}`, off = 'color:transparent';
      const tail = last
        ? `${P(e)}%,100%{transform:translateX(${n(adv)}px);${on}}`
        : `${P(e)}%{transform:translateX(${n(adv)}px);${on};animation-timing-function:step-end}${P(e + 0.12)}%,100%{transform:translateX(900px);${off}}`;
      css.push(`@keyframes ${name}{0%{transform:translateX(0px);${off};animation-timing-function:step-end}${P(s)}%{transform:translateX(0px);${on};animation-timing-function:steps(${nch},end)}${tail}}`);
      css.push(`.${name}{animation:${name} ${LOOP}s linear infinite;animation-delay:${del(0, LOOP)}}`);
      const coverW = adv + 14;
      pg += `<g class="${name}"><rect x="${n(tx.x0 - 1)}" y="${n(y - 2)}" width="${n(coverW)}" height="${n(ch + 2 + WR.u * 3)}" fill="url(#fld)"/>${cur}</g>`;
    });
    out += `<g class="pg" style="animation-delay:${del(-pi * WR.pageLen, LOOP)}">${pg}</g>`;
  });
  return { svg: `<g clip-path="url(#wrc)">${out}</g>`, css };
}

// ================================================================== STRIPS
function stripsSvg() {
  const css = [];
  let out = '';
  const u = 2;
  const top = 24, bot = 362;
  out += pixText(`${CREW} PRESENTS`, 30, top, u, { fill: CREAM, sh: 1 }).svg;
  // beat lights and bar counter (right)
  const RE = W - 30;
  const barX = RE - textW('BAR 01/20', u);
  const ballX = (i) => barX - 22 - (3 - i) * 14;
  const bpm = pixText('80 BPM', ballX(0) - 14, top, u, { anchor: 'end', fill: CREAM, sh: 1 });
  out += bpm.svg;
  css.push(`@keyframes bt{0%{opacity:1}25%,100%{opacity:0}}`, `.bt{animation:bt ${BAR}s step-end infinite}`);
  for (let i = 0; i < 4; i++) {
    const x = ballX(i), y = top + 7;
    out += `<circle cx="${x}" cy="${y}" r="4.2" fill="${INK}" fill-opacity=".35"/>`;
    out += `<use href="#mball" x="${x}" y="${y}" class="bt" style="animation-delay:${del(-i * BEAT, BAR)}"/>`;
  }
  out += pixText('BAR', barX, top, u, { fill: CREAM, sh: 1 }).svg;
  const numX = barX + textW('BAR ', u) + u;
  css.push(`@keyframes br{0%{opacity:1}${n(100 / 20, 3)}%,100%{opacity:0}}`, `.br{animation:br ${LOOP}s step-end infinite}`);
  for (let b = 0; b < 20; b++) {
    const label = String(b + 1).padStart(2, '0');
    const t = pixText(label, numX, top, u, { fill: SAND, sh: 1 });
    out += `<g class="br" style="animation-delay:${del(-b * BAR, LOOP)}">${t.svg}</g>`;
  }
  out += pixText('/20', numX + textW('00', u) + u, top, u, { fill: CREAM, sh: 1 }).svg;
  // bottom: the figure caption under the object, and the sound credit
  out += pixText('FIG. 1: A COCONUT, ROUGHLY. 24 FACES.', 30, bot, u, { fill: CREAM, sh: 1 }).svg;
  out += pixText('EVERY SOUND SYNTHESIZED FROM CODE', W - 30, bot, u, { anchor: 'end', fill: CREAM, sh: 1 }).svg;
  return { svg: out, css };
}

// ================================================================== ASSEMBLE
const ring = ringSvg();
const title = titleSvg();
const writer = writerSvg();
const strips = stripsSvg();
const subtitle = pixText('A TEN-HOUR LO-FI ISLAND VIDEO (WORKING TITLE)', TITLE.cx, 160, 2, { anchor: 'middle', fill: SAND, sh: 1 });

// ripples: one ring born on every bar, spreading for four bars (the plain field's only motion)
const RIP = { n: 4, r: 440, born: 78 };
let ripples = '';
for (let i = 0; i < RIP.n; i++) ripples += `<circle class="rp" r="${RIP.r}" style="animation-delay:${del(i * BAR, RIP.n * BAR)}"/>`;
const css = [
  `@keyframes rp{0%{transform:scale(${n(RIP.born / RIP.r, 3)});opacity:0}6%{opacity:1}100%{transform:scale(1);opacity:0}}`,
  `.rp{animation:rp ${RIP.n * BAR}s cubic-bezier(.2,.6,.4,1) infinite;fill:none;stroke:#fff;stroke-opacity:.22;stroke-width:5}`,
  `@keyframes bob{0%{transform:translateY(0px)}12%{transform:translateY(4px)}100%{transform:translateY(0px)}}`,
  `.bob{animation:bob ${BEAT}s ease-out infinite;animation-delay:${del(0, BEAT)}}`,
  `@keyframes sh{0%{transform:scale(1)}12%{transform:scale(1.05)}100%{transform:scale(1)}}`,
  `.shd{animation:sh ${BEAT}s ease-out infinite;animation-delay:${del(0, BEAT)}}`,
  ...ring.css, ...title.css, ...writer.css, ...strips.css,
  `.ringF{stroke-linecap:round;color:${INK};stroke:${CREAM};fill:none}`,
  `.ringB{stroke-linecap:round;color:transparent;stroke:#d8f3ff;fill:none}`,
  `.gzs{display:none}`,
  `@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}.gz{display:none}.gzs{display:inline}}`,
];

const pixDefs = [...usedPix].map((ch) => `<path id="${gid(ch)}" d="${pixPath(ch)}"/>`).join('');
// outline in currentColor, core in the inherited stroke (styles reach <use> clones only by inheritance)
const dotDefs = [...usedDot].map((ch) => { const d = dotPath(ch); return `<g id="${did(ch)}"><path stroke="currentColor" stroke-width="1.42" d="${d}"/><path stroke-width=".84" d="${d}"/></g>`; }).join('');

const ALT = 'CASTAWAY as a demoscene vector-object intro on a sky-to-lagoon blue field. A translucent two-tone crystal (white and coral pink, 24 faces) tumbles on the left, dipping on every beat, with a ring of dotted letters turning round its middle that tells the gags: she idles, a bottle washes straight back, a shark in headphones nods along, she walks out over the water and comes back with an iced coffee. Its caption: FIG. 1: A COCONUT, ROUGHLY. 24 FACES. On the right the title CASTAWAY in shaded sand-coloured balls floats on a slow wave and, once a minute, flips letter by letter; under it A TEN-HOUR LO-FI ISLAND VIDEO (WORKING TITLE) and a text writer typing five pages about the island, the gags, the four timers, the sound made from code, and how to run it: python tools/serve.py, then open http://127.0.0.1:8765/. Along the top: TIDEPOOL POLYGON SOCIETY PRESENTS, 80 BPM beat lights and a bar counter; bottom right: EVERY SOUND SYNTHESIZED FROM CODE.';
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-labelledby="t d">
<title id="t">CASTAWAY</title>
<desc id="d">${ALT}</desc>
<style>${css.join('\n')}</style>
<defs>
<linearGradient id="fld" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="${H}">${stops(FIELD)}</linearGradient>
<radialGradient id="bg" cx=".36" cy=".3" r=".75">${stops([[0, '#ffffff'], [0.22, '#fff6d8'], [0.62, SAND], [1, '#d98a3a']])}</radialGradient>
<radialGradient id="shg">${stops([[0, INK, 0.34], [1, INK, 0]])}</radialGradient>
<g id="ball"><circle cx="2" cy="2.6" r="${TITLE.r}" fill="${INK}" fill-opacity=".3"/><circle r="${TITLE.r}" fill="url(#bg)"/></g>
<g id="mball"><circle r="4.2" fill="url(#bg)"/></g>
<clipPath id="pn"><rect width="${W}" height="${H}" rx="18"/></clipPath>
<clipPath id="wrc"><rect x="440" y="${WR.y - 6}" width="${W - 440 - 16}" height="${PAGES[0].length * WR.lh + 10}"/></clipPath>
${pixDefs}${dotDefs}${defsText}
</defs>
<g clip-path="url(#pn)">
<rect width="${W}" height="${H}" fill="url(#fld)"/>
<g transform="translate(${OBJ.cx} ${OBJ.cy})">${ripples}</g>
<g transform="translate(${OBJ.cx} ${OBJ.cy + 138})"><ellipse class="shd" rx="122" ry="15" fill="url(#shg)"/></g>
<g transform="translate(${OBJ.cx} ${OBJ.cy})"><g class="bob">${ring.back}<g transform="scale(${n(1 / OBJ.Q, 4)})" stroke="#ffffff" stroke-opacity=".55" stroke-width="${n(0.8 * OBJ.Q)}" stroke-linejoin="round">${glenzSvg()}</g>${ring.front}</g></g>
${title.svg}
${subtitle.svg}
${writer.svg}
${strips.svg}
<rect x="1.5" y="1.5" width="${W - 3}" height="${H - 3}" rx="16.5" fill="none" stroke="#ffffff" stroke-opacity=".35" stroke-width="3"/>
</g>
</svg>
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
console.log(`${path.relative(process.cwd(), OUT)}: ${(svg.length / 1024).toFixed(1)} KB; glenz ${faces.length} faces x ${OBJ.F} frames; ring ${RING.N} slots x ${RING.R} turns (${[...RING_TEXT].length}/${RING.M} chars)`);

// ================================================================== PROPS
// A second, smaller SVG for the .md's details block: six things from the
// island as single-colour wireframes on turntables. Each one is a single
// <path> whose d is a SMIL value list, frames covering only the turn after
// which the object looks the same again (a four-fold crate repeats every 90
// degrees), so the loop is seamless and small. Same field, same font.
const OUT_PROPS = OUT.replace(/\.svg$/, '-props.svg');
defsText = '';
usedPix.clear();
{
  const PW = 1000, PH = 214;
  const SPIN = 24;                  // s per full turn, every prop
  const STEP = 10;                  // degrees per frame
  const ELEV = 0.4;                 // camera looks down by this much (rad)
  const SC = 94, DIST = 6;
  const ringPts = (r, y, k, a0 = 0) => Array.from({ length: k }, (_, i) => {
    const a = a0 + (TAU * i) / k;
    return [r * Math.cos(a), y, r * Math.sin(a)];
  });
  // a model is a list of polylines; closed ones repeat their first point
  const closed = (pts) => [...pts, pts[0]];
  function lathe(profile, k, a0 = 0) {
    const lines = profile.map(([r, y]) => closed(ringPts(r, y, k, a0)));
    for (let i = 0; i < k; i++) lines.push(profile.map(([r, y]) => ringPts(r, y, k, a0)[i]));
    return lines;
  }
  const box = (x0, x1, y0, y1, z0, z1) => [
    closed([[x0, y0, z0], [x1, y0, z0], [x1, y0, z1], [x0, y0, z1]]),
    closed([[x0, y1, z0], [x1, y1, z0], [x1, y1, z1], [x0, y1, z1]]),
    [[x0, y0, z0], [x0, y1, z0]], [[x1, y0, z0], [x1, y1, z0]], [[x1, y0, z1], [x1, y1, z1]], [[x0, y0, z1], [x0, y1, z1]],
  ];
  const props = [];
  // BOTTLE: eight-sided glass, a cork, a rolled message inside
  {
    const L = lathe([[0.22, 0], [0.25, 0.06], [0.25, 0.52], [0.15, 0.68], [0.085, 0.78], [0.085, 0.93]], 8, TAU / 16);
    L.push(...lathe([[0.065, 0.93], [0.065, 1.04]], 4, TAU / 8));
    L.push(...lathe([[0.08, 0.12], [0.08, 0.44]], 4));
    props.push({ name: 'BOTTLE', parts: [{ fold: 4, lines: L }] });
  }
  // CRATE: a slatted box with a brace across every side
  {
    const a = 0.36, h = 0.66;
    const L = box(-a, a, 0, h, -a, a);
    // boards: three to a side, and a rim round the lid
    for (const t of [-a / 3, a / 3]) L.push([[t, 0, -a], [t, h, -a]], [[a, 0, t], [a, h, t]], [[-t, 0, a], [-t, h, a]], [[-a, 0, -t], [-a, h, -t]]);
    const b = a * 0.72;
    L.push(closed([[-b, h, -b], [b, h, -b], [b, h, b], [-b, h, b]]));
    props.push({ name: 'CRATE', parts: [{ fold: 4, lines: L }] });
  }
  // PARCEL: a box tied with string and a four-loop bow
  {
    const a = 0.34, h = 0.42;
    const L = box(-a, a, 0, h, -a, a);
    L.push([[-a, 0, 0], [-a, h, 0], [a, h, 0], [a, 0, 0]], [[0, 0, -a], [0, h, -a], [0, h, a], [0, 0, a]]);
    for (let q = 0; q < 4; q++) {
      const c = Math.cos((q * TAU) / 4), s = Math.sin((q * TAU) / 4);
      const P = (u, v, y) => [u * c - v * s, y, u * s + v * c];
      L.push([P(0, 0, h), P(0.16, -0.06, h + 0.09), P(0.16, 0.06, h + 0.09), P(0, 0, h)]);
    }
    props.push({ name: 'PARCEL', parts: [{ fold: 4, lines: L }] });
  }
  // HEADPHONES: the spare pair (two cups, a padded band)
  {
    const L = [];
    const arc = (z) => Array.from({ length: 11 }, (_, i) => {
      const a = (Math.PI * i) / 10;
      return [0.33 * Math.cos(a), 0.42 + 0.44 * Math.sin(a), z];
    });
    const A = arc(-0.06), B = arc(0.06);
    L.push(A, B);
    for (let i = 0; i < A.length; i += 2) L.push([A[i], B[i]]);
    for (const sx of [-1, 1]) {
      const cup = (x) => closed(Array.from({ length: 8 }, (_, i) => {
        const a = (TAU * i) / 8 + TAU / 16;
        return [x, 0.3 + 0.17 * Math.sin(a), 0.17 * Math.cos(a)];
      }));
      const r1 = cup(sx * 0.27), r2 = cup(sx * 0.43);
      L.push(r1, r2);
      for (let i = 0; i < 8; i++) L.push([r1[i], r2[i]]);
    }
    props.push({ name: 'HEADPHONES', parts: [{ fold: 2, lines: L }] });
  }
  // ICED COFFEE: a tapered cup, a sleeve, a domed lid, a straw
  {
    const L = lathe([[0.17, 0], [0.2, 0.26], [0.205, 0.32], [0.23, 0.62], [0.255, 0.66], [0.2, 0.74], [0.07, 0.78]], 8);
    L.push([[0, 0.78, 0], [0, 1.02, 0]]);
    L.push(closed(ringPts(0.03, 1.02, 4)), closed(ringPts(0.03, 0.78, 4)));
    props.push({ name: 'ICED COFFEE', parts: [{ fold: 4, lines: L }] });
  }
  // SANDCASTLE: a stepped keep with battlements and a flag
  {
    const L = [];
    const sq = (a, y) => closed([[-a, y, -a], [a, y, -a], [a, y, a], [-a, y, a]]);
    const crenel = (a, y, hgt, k) => {
      // a square-wave battlement round a square of half-size a
      const pts = [];
      const corners = [[-a, -a], [a, -a], [a, a], [-a, a]];
      for (let s = 0; s < 4; s++) {
        const [x0, z0] = corners[s], [x1, z1] = corners[(s + 1) % 4];
        const P = (t, yy) => [x0 + (x1 - x0) * t, yy, z0 + (z1 - z0) * t];
        for (let i = 0; i < k; i++) pts.push(P(i / k, y + hgt), P((i + 0.5) / k, y + hgt), P((i + 0.5) / k, y), P((i + 1) / k, y));
      }
      return closed(pts);
    };
    L.push(sq(0.42, 0), sq(0.36, 0.3), crenel(0.36, 0.3, 0.07, 3));
    for (const [x, z] of [[-1, -1], [1, -1], [1, 1], [-1, 1]]) L.push([[x * 0.42, 0, z * 0.42], [x * 0.36, 0.3, z * 0.36]]);
    L.push(sq(0.19, 0.3), sq(0.17, 0.66), crenel(0.17, 0.66, 0.06, 2));
    for (const [x, z] of [[-1, -1], [1, -1], [1, 1], [-1, 1]]) L.push([[x * 0.19, 0.3, z * 0.19], [x * 0.17, 0.66, z * 0.17]]);
    // the keep repeats every quarter turn; only the flag needs the whole turn
    props.push({ name: 'SANDCASTLE', parts: [{ fold: 4, lines: L }, { fold: 1, lines: [[[0, 0.72, 0], [0, 1.0, 0], [0.17, 0.95, 0], [0, 0.9, 0]]] }] });
  }

  const cellW = (PW - 40) / props.length;
  const baseY = 164;
  const ce = Math.cos(ELEV), se = Math.sin(ELEV);
  const begin = T0 ? ` begin="-${n(T0, 3)}s"` : '';
  let body = '';
  let still = '';
  let defs = '';
  let pid = 0;
  props.forEach((pr, i) => {
    const cx = 20 + cellW * (i + 0.5);
    const ids = [];
    for (const part of pr.parts) {
      const sweep = 360 / part.fold;
      const nf = Math.round(sweep / STEP);
      const dur = (SPIN * sweep) / 360;
      // whole pixels, relative moves inside each polyline (smaller numbers, same shape)
      const frameD = (deg) => {
        const a = (deg * Math.PI) / 180, ca = Math.cos(a), sa = Math.sin(a);
        return part.lines.map((line) => {
          let px = 0, py = 0;
          return line.map(([x, y, z], k) => {
            const xr = x * ca + z * sa, zr = -x * sa + z * ca;
            const yv = y * ce - zr * se, zv = y * se + zr * ce;
            const kk = DIST / (DIST - zv);
            const X = Math.round(cx + xr * SC * kk), Y = Math.round(baseY - yv * SC * kk);
            const out = k ? `l${X - px} ${Y - py}` : `M${X} ${Y}`;
            px = X; py = Y;
            return out;
          }).join('');
        }).join('');
      };
      const vals = [];
      for (let f = 0; f <= nf; f++) vals.push(frameD(-25 - (f * sweep) / nf));
      defs += `<path id="w${pid}" d="${vals[0]}"><animate attributeName="d" dur="${n(dur)}s"${begin} repeatCount="indefinite" values="${vals.join(';')}"/></path>`;
      defs += `<path id="s${pid}" d="${vals[0]}"/>`;
      ids.push(pid++);
    }
    // the turntable: a flat dashed disc under the object
    const pr0 = 0.56 * SC;
    body += `<ellipse cx="${n1(cx)}" cy="${baseY}" rx="${n1(pr0)}" ry="${n1(pr0 * se)}" fill="${INK}" fill-opacity=".16" stroke="#fff" stroke-opacity=".45" stroke-dasharray="3 4"/>`;
    body += `<g class="wa">${ids.map((k) => `<use href="#w${k}" class="gl"/><use href="#w${k}" class="ln"/>`).join('')}</g>`;
    still += `<g class="ws">${ids.map((k) => `<use href="#s${k}" class="gl"/><use href="#s${k}" class="ln"/>`).join('')}</g>`;
    body += pixText(pr.name, cx, 190, 2, { anchor: 'middle', fill: SAND, sh: 1 }).svg;
  });
  const head = pixText('THE INVENTORY, AS VECTOR OBJECTS', 26, 18, 2, { fill: CREAM, sh: 1 }).svg
    + pixText('NOTHING ON THE ISLAND ACTUALLY SPINS.', PW - 26, 18, 2, { anchor: 'end', fill: CREAM, sh: 1 }).svg;
  const pdefs = [...usedPix].map((ch) => `<path id="${gid(ch)}" d="${pixPath(ch)}"/>`).join('');
  const psvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${PW} ${PH}" width="${PW}" height="${PH}" role="img" aria-labelledby="t d">
<title id="t">The inventory, as vector objects</title>
<desc id="d">Six things from the island drawn as white wireframes, each turning slowly on a dashed turntable: a bottle with a rolled message inside, a slatted crate, a parcel tied with string and a bow, a pair of headphones, an iced coffee with a straw, and a sandcastle with a flag. Header: THE INVENTORY, AS VECTOR OBJECTS. NOTHING ON THE ISLAND ACTUALLY SPINS.</desc>
<style>.gl{fill:none;stroke:#fff;stroke-opacity:.18;stroke-width:4.5;stroke-linejoin:round;stroke-linecap:round}.ln{fill:none;stroke:#fff;stroke-width:1.3;stroke-linejoin:round;stroke-linecap:round}.ws{display:none}@media (prefers-reduced-motion:reduce){.wa{display:none}.ws{display:inline}}</style>
<defs>
<linearGradient id="fld" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="${PH}">${stops(FIELD)}</linearGradient>
<clipPath id="pn"><rect width="${PW}" height="${PH}" rx="16"/></clipPath>
${pdefs}${defsText}${defs}
</defs>
<g clip-path="url(#pn)">
<rect width="${PW}" height="${PH}" fill="url(#fld)"/>
${head}
${body}${still}
<rect x="1.5" y="1.5" width="${PW - 3}" height="${PH - 3}" rx="14.5" fill="none" stroke="#ffffff" stroke-opacity=".35" stroke-width="3"/>
</g>
</svg>
`;
  fs.writeFileSync(OUT_PROPS, psvg);
  console.log(`${path.relative(process.cwd(), OUT_PROPS)}: ${(psvg.length / 1024).toFixed(1)} KB; ${props.length} props, one turn per ${SPIN}s`);
}
