// "Texture movers: rotozoomer and tunnel" README header for CASTAWAY.
//
//   node examples/castaway/src/27-texture-movers_opus_5.5.mjs
//   node examples/castaway/src/27-texture-movers_opus_5.5.mjs --at=7.5 --out=some/dir
//
// Regenerates, next to this folder:
//   ../assets/27-texture-movers_opus_5.5.svg           the tunnel banner
//   ../assets/27-texture-movers_opus_5.5-rotozoom.svg  the run-it band
// Plain Node, no deps, deterministic (no clock, no Math.random). --at bakes a
// head start (seconds) into every animation delay so late frames can be
// checked without waiting; use it only together with --out, never in place.
// (The .md beside the assets is hand-written, not generated by this script.)
//
// The style: the two "texture mover" effects of mid-90s PC intros. A tunnel
// flies you down an endless tube by shifting lookups into a wall texture; a
// rotozoomer spins and breathes one small tile repeated to infinity. Both sat
// behind a logo, with the text on a solid panel. Nothing here is copied from
// any production: the tile, letters, palette, sprites and copy are drawn for
// this file.
//
// How the SVG does it
//   TUNNEL. A per-pixel texture-mapped tunnel needs lookups an SVG cannot do,
//   so the wall is built from 16 rings instead, each a checkered annulus whose
//   inner radius is its outer radius / q. All 16 share ONE @keyframes track
//   (scale grows x16 over the ring's life, exponential, sampled at 48 points)
//   and differ only in animation-delay, so at any moment they sit at radii
//   r, rq, rq^2 ... and tile the wall with no gaps: an exponential zoom loops
//   with no seam. Timing is the theme's: one ring per beat (80 BPM), the wall
//   doubles in size every bar (3 s), a ring lives 4 bars.
//     * Twist: the same track turns each ring 90 degrees over its life, so
//       neighbours sit half a checker cell apart and the wall spirals.
//     * Depth fog: the track also animates `color`, and the ring symbol is
//       painted in currentColor, so far rings are dark and near rings bright.
//     * Wandering vanishing point: the track pushes each ring sideways by
//       D * (1 - smoothstep(depth)), so the far end sits D off-centre and the
//       near walls stay put. The whole tube then rolls (10 degrees a second),
//       which swings that bend round: the far end circles once every 36 s.
//     * The far end is not dark: it opens onto the island, in daylight, kept
//       upright by a counter-rotation. She nods on every beat.
//     * Every bar a sign flies out of the island along the tube (four slots,
//       three gags each, swapped while a slot is tiny), and a coconut with a
//       hermit crab inside walks the top of the logo in eighth-note steps.
//   ROTOZOOMER. One 48 px embossed sand tile (a C with a palm in it) as a
//   <pattern> on a huge rect, under three nested CSS animations: rotate
//   (10 degrees a second), zoom (breathing x0.75 to x1.45 every 4 bars) and a
//   slow drift of the texture centre. The run command sits on a solid plate.
//   Everything loops every 36 s (12 bars). prefers-reduced-motion pauses every
//   track at its first frame, which is already a complete picture.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const arg = (name) => {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const T0 = Number(arg('at') || 0);
const OUTDIR = arg('out') ? path.resolve(arg('out')) : path.resolve(here, '../assets');
const SLUG = '27-texture-movers_opus_5.5';

const BEAT = 0.75;          // 80 BPM
const BAR = 4 * BEAT;       // 3 s, one bar of the theme
const LOOP = 12 * BAR;      // 36 s, everything repeats

const n = (v, d = 2) => String(+(+v).toFixed(d));
const dly = (s) => `${n(s - T0, 3)}s`;

// ------------------------------------------------------------------ colour
const rgb = (c) => [1, 3, 5].map((i) => parseInt(c.slice(i, i + 2), 16));
const hex = (a) => '#' + a.map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('');
function ramp(stops, p) {
  for (let i = 0; i < stops.length - 1; i++) {
    const [p0, c0] = stops[i];
    const [p1, c1] = stops[i + 1];
    if (p <= p1 || i === stops.length - 2) {
      const t = Math.max(0, Math.min(1, (p - p0) / (p1 - p0)));
      const a = rgb(c0);
      const b = rgb(c1);
      return hex(a.map((v, k) => v + (b[k] - v) * t));
    }
  }
  return stops[stops.length - 1][1];
}

// ------------------------------------------------------------------ pixels
// Cells are [x, y] in art pixels. Merge into horizontal runs, stack equal
// runs into rects, emit one path in real px (scale S, offset ox/oy real px).
function cellsPath(cells, S, ox = 0, oy = 0) {
  const rows = new Map();
  for (const [x, y] of cells) {
    if (!rows.has(y)) rows.set(y, new Set());
    rows.get(y).add(x);
  }
  const runs = [];
  for (const [y, set] of rows) {
    const xs = [...set].sort((a, b) => a - b);
    let s = xs[0];
    let p = xs[0];
    for (let i = 1; i <= xs.length; i++) {
      if (i < xs.length && xs[i] === p + 1) { p = xs[i]; continue; }
      runs.push([s, p + 1, y]);
      if (i < xs.length) { s = xs[i]; p = xs[i]; }
    }
  }
  runs.sort((a, b) => a[2] - b[2] || a[0] - b[0]);
  const live = new Set(runs.map((r) => r.join(',')));
  let d = '';
  for (const r of runs) {
    const k0 = r.join(',');
    if (!live.has(k0)) continue;
    live.delete(k0);
    let h = 1;
    while (live.has(`${r[0]},${r[1]},${r[2] + h}`)) { live.delete(`${r[0]},${r[1]},${r[2] + h}`); h++; }
    const w = (r[1] - r[0]) * S;
    d += `M${n(ox + r[0] * S)} ${n(oy + r[2] * S)}h${n(w)}v${n(h * S)}h${n(-w)}z`;
  }
  return d;
}
// A little paint box: set(x, y, colour), then paths() groups by colour.
class Canvas {
  constructor() { this.m = new Map(); }
  set(x, y, c) { this.m.set(`${x},${y}`, [x, y, c]); }
  get(x, y) { const v = this.m.get(`${x},${y}`); return v ? v[2] : null; }
  del(x, y) { this.m.delete(`${x},${y}`); }
  paths(S, ox = 0, oy = 0, extra = '') {
    const by = new Map();
    for (const [x, y, c] of this.m.values()) {
      if (!by.has(c)) by.set(c, []);
      by.get(c).push([x, y]);
    }
    let out = '';
    for (const [c, cells] of by) out += `<path${extra} fill="${c}" d="${cellsPath(cells, S, ox, oy)}"/>`;
    return out;
  }
}
const sprite = (rows, pal, cv, ox, oy) => rows.forEach((row, y) => [...row].forEach((ch, x) => {
  if (pal[ch]) cv.set(ox + x, oy + y, pal[ch]);
}));

// ------------------------------------------------------------------ font
// 5x7 capitals (plus the few lowercase letters the run command needs, with
// two descender rows), smeared one pixel right into a bold 6x7, advance 7.
const F5 = {
  A: '.###.|#...#|#...#|#####|#...#|#...#|#...#', B: '####.|#...#|#...#|####.|#...#|#...#|####.',
  C: '.###.|#...#|#....|#....|#....|#...#|.###.', D: '####.|#...#|#...#|#...#|#...#|#...#|####.',
  E: '#####|#....|#....|####.|#....|#....|#####', F: '#####|#....|#....|####.|#....|#....|#....',
  G: '.###.|#...#|#....|#.###|#...#|#...#|.####', H: '#...#|#...#|#...#|#####|#...#|#...#|#...#',
  I: '.###.|..#..|..#..|..#..|..#..|..#..|.###.', J: '..###|...#.|...#.|...#.|#..#.|#..#.|.##..',
  K: '#...#|#..#.|#.#..|##...|#.#..|#..#.|#...#', L: '#....|#....|#....|#....|#....|#....|#####',
  M: '#...#|##.##|#.#.#|#.#.#|#...#|#...#|#...#', N: '#...#|##..#|#.#.#|#.#.#|#..##|#...#|#...#',
  O: '.###.|#...#|#...#|#...#|#...#|#...#|.###.', P: '####.|#...#|#...#|####.|#....|#....|#....',
  Q: '.###.|#...#|#...#|#...#|#.#.#|#..#.|.##.#', R: '####.|#...#|#...#|####.|#.#..|#..#.|#...#',
  S: '.###.|#...#|#....|.###.|....#|#...#|.###.', T: '#####|..#..|..#..|..#..|..#..|..#..|..#..',
  U: '#...#|#...#|#...#|#...#|#...#|#...#|.###.', V: '#...#|#...#|#...#|#...#|#...#|.#.#.|..#..',
  W: '#...#|#...#|#...#|#.#.#|#.#.#|##.##|#...#', X: '#...#|#...#|.#.#.|..#..|.#.#.|#...#|#...#',
  Y: '#...#|#...#|.#.#.|..#..|..#..|..#..|..#..', Z: '#####|....#|...#.|..#..|.#...|#....|#####',
  0: '.###.|#...#|#..##|#.#.#|##..#|#...#|.###.', 1: '..#..|.##..|..#..|..#..|..#..|..#..|.###.',
  2: '.###.|#...#|....#|..##.|.#...|#....|#####', 3: '.###.|#...#|....#|..##.|....#|#...#|.###.',
  4: '...#.|..##.|.#.#.|#..#.|#####|...#.|...#.', 5: '#####|#....|####.|....#|....#|#...#|.###.',
  6: '.###.|#....|#....|####.|#...#|#...#|.###.', 7: '#####|....#|...#.|..#..|.#...|.#...|.#...',
  8: '.###.|#...#|#...#|.###.|#...#|#...#|.###.', 9: '.###.|#...#|#...#|.####|....#|....#|.###.',
  '.': '.....|.....|.....|.....|.....|.#...|.#...', ',': '.....|.....|.....|.....|.#...|.#...|#....',
  ':': '.....|.#...|.#...|.....|.#...|.#...|.....', '/': '....#|...#.|...#.|..#..|.#...|.#...|#....',
  '-': '.....|.....|.....|.###.|.....|.....|.....', "'": '..#..|..#..|.#...|.....|.....|.....|.....',
  '(': '..#..|.#...|#....|#....|#....|.#...|..#..', ')': '..#..|...#.|....#|....#|....#|...#.|..#..',
  '!': '..#..|..#..|..#..|..#..|..#..|.....|..#..', '?': '.###.|#...#|....#|..##.|..#..|.....|..#..',
  '+': '.....|..#..|..#..|#####|..#..|..#..|.....', '=': '.....|.....|#####|.....|#####|.....|.....',
  '>': '#....|.#...|..#..|...#.|..#..|.#...|#....', '·': '.....|.....|.....|..#..|.....|.....|.....',
  '&': '.##..|#..#.|#.#..|.#...|#.#.#|#..#.|.##.#', '_': '.....|.....|.....|.....|.....|.....|#####',
  // lowercase for the run command; rows 7 and 8 are descenders
  p: '.....|.....|####.|#...#|#...#|#...#|####.|#....|#....',
  y: '.....|.....|#...#|#...#|#...#|#...#|.####|....#|.###.',
  t: '.#...|.#...|####.|.#...|.#...|.#..#|..##.',
  h: '#....|#....|####.|#...#|#...#|#...#|#...#',
  o: '.....|.....|.###.|#...#|#...#|#...#|.###.',
  n: '.....|.....|####.|#...#|#...#|#...#|#...#',
  l: '.##..|..#..|..#..|..#..|..#..|..#..|.###.',
  s: '.....|.....|.####|#....|.###.|....#|####.',
  e: '.....|.....|.###.|#...#|#####|#....|.###.',
  r: '.....|.....|#.##.|##..#|#....|#....|#....',
  v: '.....|.....|#...#|#...#|#...#|.#.#.|..#..',
};
const ADV = 7;
const gid = (ch) => `g${ch.codePointAt(0).toString(16)}`;
function glyphD(ch) {
  const rows = F5[ch].split('|');
  const cells = [];
  rows.forEach((row, y) => {
    for (let x = 0; x < 6; x++) if (row[x] === '#' || (x > 0 && row[x - 1] === '#')) cells.push([x, y]);
  });
  return cellsPath(cells, 1);
}

// One document's worth of defs, CSS and text ids.
function makeDoc() {
  const doc = { defs: [], css: [], used: new Set(), tid: 0 };
  // A line of text at font scale 1 as a <g id> in defs; returns id + width.
  doc.line = (str) => {
    let uses = '';
    [...str].forEach((ch, i) => {
      if (ch === ' ') return;
      if (!F5[ch]) throw new Error(`no glyph for ${JSON.stringify(ch)} in "${str}"`);
      doc.used.add(ch);
      uses += `<use href="#${gid(ch)}"${i ? ` x="${i * ADV}"` : ''}/>`;
    });
    const id = `t${doc.tid++}`;
    doc.defs.push(`<g id="${id}">${uses}</g>`);
    return { id, w: str.length * ADV - 1 };
  };
  // Text at scale s, optional 8-way outline and drop shadow (in font px).
  doc.text = (str, { x = 0, y = 0, s = 1, fill = '#fff', outline = null, shadow = null, anchor = 'start', cls = '' }) => {
    const { id, w } = doc.line(str);
    const x0 = anchor === 'middle' ? x - (w * s) / 2 : anchor === 'end' ? x - w * s : x;
    let inner = '';
    if (shadow) inner += `<use href="#${id}" x="2" y="2" fill="${shadow}"/>`;
    if (outline) {
      inner += `<g fill="${outline}">`;
      for (const [dx, dy] of [[-1, -1], [0, -1], [1, -1], [-1, 0], [1, 0], [-1, 1], [0, 1], [1, 1]]) {
        inner += `<use href="#${id}" x="${dx}" y="${dy}"/>`;
      }
      inner += '</g>';
    }
    inner += `<use href="#${id}" fill="${fill}"/>`;
    const tr = `translate(${n(x0)} ${n(y)})${s !== 1 ? ` scale(${n(s, 3)})` : ''}`;
    return { svg: `<g${cls ? ` class="${cls}"` : ''} transform="${tr}">${inner}</g>`, w: w * s, x0 };
  };
  doc.glyphDefs = () => [...doc.used].sort().map((ch) => `<path id="${gid(ch)}" d="${glyphD(ch)}"/>`).join('');
  return doc;
}
const textW = (str, s = 1) => (str.length * ADV - 1) * s;

// A bevelled solid panel.
function panel(x, y, w, h, { face = '#0a1d26', hi = '#3d9aa6', lo = '#020c11', edge = '#000000', r = 3 } = {}) {
  return `<rect x="${x - 1}" y="${y - 1}" width="${w + 2}" height="${h + 2}" rx="${r + 1}" fill="${edge}" opacity=".55"/>`
    + `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="${face}"/>`
    + `<path d="M${x + r} ${y + 1.5}h${w - 2 * r}M${x + 1.5} ${y + r}v${h - 2 * r}" stroke="${hi}" stroke-width="2" fill="none"/>`
    + `<path d="M${x + r} ${y + h - 1.5}h${w - 2 * r}M${x + w - 1.5} ${y + r}v${h - 2 * r}" stroke="${lo}" stroke-width="2" fill="none"/>`;
}

// ------------------------------------------------------------------ palette
const NAVY = '#071a22';
const INK = '#06141b';
const SUN = '#ffd36b';
const CORAL = '#ff8a6a';
const AQUA = '#8fe6e8';
const WHITE = '#f4fdff';

// ===================================================================== LOGO
// CASTAWAY on an 8x10 cell grid, each cell split into 2x2 sub-pixels so the
// bevel, the rounding and the outline are one sub-pixel thick.
const LOGO = {
  C: ['.#######', '########', '###.....', '##......', '##......', '##......', '##......', '###.....', '########', '.#######'],
  A: ['.######.', '########', '##....##', '##....##', '##....##', '########', '########', '##....##', '##....##', '##....##'],
  S: ['.#######', '########', '##......', '##......', '#######.', '.#######', '......##', '......##', '########', '#######.'],
  T: ['########', '########', '...##...', '...##...', '...##...', '...##...', '...##...', '...##...', '...##...', '...##...'],
  W: ['##....##', '##....##', '##....##', '##.##.##', '##.##.##', '##.##.##', '##.##.##', '##.##.##', '########', '.##..##.'],
  Y: ['##....##', '##....##', '##....##', '###..###', '.######.', '..####..', '...##...', '...##...', '...##...', '...##...'],
};
function logoSVG(word, x0, y0, sub) {
  const lit = new Set();
  const k = (x, y) => `${x},${y}`;
  [...word].forEach((ch, i) => {
    const ox = i * 18;                       // 16 sub-pixels + 2 gap
    LOGO[ch].forEach((row, y) => [...row].forEach((c, x) => {
      if (c !== '#') return;
      for (let dy = 0; dy < 2; dy++) for (let dx = 0; dx < 2; dx++) lit.add(k(ox + x * 2 + dx, y * 2 + dy));
    }));
  });
  const has = (x, y) => lit.has(k(x, y));
  // round every convex outer corner by one sub-pixel
  const cut = [];
  for (const key of lit) {
    const [x, y] = key.split(',').map(Number);
    for (const [ax, ay] of [[-1, -1], [1, -1], [-1, 1], [1, 1]]) {
      if (!has(x + ax, y) && !has(x, y + ay) && !has(x + ax, y + ay)) { cut.push(key); break; }
    }
  }
  cut.forEach((c) => lit.delete(c));
  const cells = [...lit].map((s) => s.split(',').map(Number));
  // outline = 8-neighbour ring
  const ring = new Set();
  for (const [x, y] of cells) {
    for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) if (!has(x + dx, y + dy)) ring.add(k(x + dx, y + dy));
  }
  const ringCells = [...ring].map((s) => s.split(',').map(Number));
  const body = [...cells, ...ringCells];
  const cv = new Canvas();
  const BANDS = ['#fff3d6', '#fff3d6', '#fff3d6', '#ffe7ad', '#ffe7ad', '#ffe7ad', '#ffd685', '#ffd685', '#ffd685', '#ffc070',
    '#ffc070', '#ffa865', '#ffa865', '#ff9262', '#ff9262', '#fb7d5e', '#fb7d5e', '#f06a59', '#f06a59', '#f06a59'];
  for (const [x, y] of cells) {
    let c = BANDS[y] || BANDS[19];
    if (!has(x, y - 1)) c = '#fffdf6';
    else if (!has(x, y + 1)) c = '#a83f3a';
    else if (!has(x - 1, y)) c = '#fff0cc';
    else if (!has(x + 1, y)) c = '#c9544a';
    cv.set(x, y, c);
  }
  return `<path fill="#000" opacity=".5" d="${cellsPath(body, sub, x0 + 2 * sub, y0 + 2 * sub)}"/>`
    + `<path fill="${INK}" d="${cellsPath(ringCells, sub, x0, y0)}"/>`
    + `<path fill="#ffc583" d="${cellsPath(cells, sub, x0, y0)}"/>`     // underlay: no seams between bands
    + cv.paths(sub, x0, y0);
}

// ================================================================= THE CRAB
// A coconut walking about with a hermit crab inside it. 14x9 art px.
const CRAB_TOP = [
  '.....bbbb.....',
  '...bbbbbbbb...',
  '..bhhbbbbbbb..',
  '.bhbbbbbbbbbb.',
  '.bbbbbbbbbbbb.',
  '..dddddddddd..',
  'C..kwrrrrkw..C',
  'CC..rrrrrr..CC',
];
const CRAB_LEGS = [['..r.r....r.r..'], ['.r.r......r.r.']];
const CRAB_PAL = { b: '#7b4b2a', h: '#b8804c', d: '#43260f', r: '#e2553f', C: '#ff6f55', k: '#10161a', w: '#ffffff' };

// ============================================================ THE FAR END
// The island at the end of the tunnel: 52x52 art px at 2 px, clipped round.
function islandArt(doc) {
  const A = 52;
  const sky = new Canvas();
  const SKY = [[0, '#63c0ef'], [6, '#7ccbf2'], [12, '#97d7f5'], [18, '#b3e3f8'], [23, '#cdeefa']];
  const SEA = [[28, '#43b0de'], [31, '#319cd1'], [36, '#2689c3'], [42, '#1f77b3'], [47, '#1a68a4']];
  const band = (tab, y) => { let c = tab[0][1]; for (const [y0, col] of tab) if (y >= y0) c = col; return c; };
  for (let y = 0; y < A; y++) for (let x = 0; x < A; x++) sky.set(x, y, y < 28 ? band(SKY, y) : band(SEA, y));
  // sun with a soft ring
  for (let y = 0; y < 20; y++) for (let x = 28; x < A; x++) {
    const d = Math.hypot(x - 39.5, y - 8.5);
    if (d < 3.6) sky.set(x, y, '#fffbe2');
    else if (d < 5.2) sky.set(x, y, '#e6f8ff');
  }
  // clouds
  sprite(['...ww.....', '.wwwwww.ww', 'wwwwwwwwww', '.ggggggg..'], { w: '#ffffff', g: '#dff1fa' }, sky, 6, 13);
  sprite(['..ww..', 'wwwwww', '.gggg.'], { w: '#ffffff', g: '#e4f4fb' }, sky, 34, 20);
  // horizon line and sea glints
  for (let x = 0; x < A; x++) sky.set(x, 28, '#7fd2ef');
  const R = rng(1992);
  for (let i = 0; i < 26; i++) {
    const y = 30 + Math.floor(R() * 21);
    const x = Math.floor(R() * 48);
    const len = 1 + Math.floor(R() * 3);
    for (let j = 0; j < len; j++) sky.set(x + j, y, y < 38 ? '#bfe9f8' : '#8fd0ee');
  }
  // island: foam, sand, shade
  const icx = 25.5;
  const icy = 41;
  for (let y = 34; y < 48; y++) for (let x = 6; x < 46; x++) {
    const e = ((x - icx) / 15.5) ** 2 + ((y - icy) / 5.2) ** 2;
    const f = ((x - icx) / 17.2) ** 2 + ((y - icy) / 6.4) ** 2;
    if (e <= 1) sky.set(x, y, y > icy + 1 ? '#dcb878' : '#f4daa0');
    else if (f <= 1) sky.set(x, y, '#f2fdff');
  }
  for (const [x, y] of [[14, 39], [15, 38], [16, 39], [33, 39], [34, 38], [35, 39], [36, 39]]) sky.set(x, y, '#58a94e');
  // palm trunk: a gentle curve from the sand up to the crown
  const trunk = [];
  for (let t = 0; t <= 1.0001; t += 0.02) {
    const x = (1 - t) ** 2 * 31 + 2 * (1 - t) * t * 34.5 + t * t * 28.5;
    const y = (1 - t) ** 2 * 40 + 2 * (1 - t) * t * 25 + t * t * 11;
    trunk.push([Math.round(x), Math.round(y)]);
  }
  for (const [x, y] of trunk) {
    const seg = (y >> 1) % 2 ? '#a5653d' : '#c58a58';
    sky.set(x, y, seg);
    sky.set(x + 1, y, '#8c5232');
  }
  // fronds round the crown at (29, 10)
  const frond = (pts, cols) => pts.forEach(([x, y], i) => sky.set(29 + x, 10 + y, cols[i % cols.length]));
  const DK = '#2c8a43';
  const MD = '#4fb256';
  const LT = '#8cd46e';
  frond([[-1, 0], [-2, 0], [-3, -1], [-4, -1], [-5, -1], [-6, 0], [-7, 0], [-8, 1], [-9, 2], [-9, 3]], [MD, LT]);
  frond([[-1, 1], [-2, 1], [-3, 2], [-4, 3], [-5, 4], [-5, 5], [-6, 6]], [DK, MD]);
  frond([[1, 0], [2, -1], [3, -1], [4, -1], [5, -1], [6, 0], [7, 0], [8, 1], [9, 2], [9, 3]], [MD, LT]);
  frond([[1, 1], [2, 1], [3, 2], [4, 3], [5, 4], [6, 5], [6, 6]], [DK, MD]);
  frond([[0, -1], [-1, -2], [-1, -3], [-2, -4], [-3, -4]], [LT, MD]);
  frond([[1, -1], [2, -2], [3, -3], [4, -3], [5, -3]], [LT, MD]);
  frond([[-2, -1], [-3, -2], [-4, -2]], [DK]);
  frond([[2, 0], [3, 0], [4, 0]], [DK]);
  for (const [x, y] of [[0, 0], [1, 0], [0, 1], [-1, 0], [0, -1]]) sky.set(29 + x, 10 + y, '#3b9a47');
  sky.set(28, 12, '#6b3f1f');
  sky.set(30, 12, '#6b3f1f');
  sky.set(29, 12, '#7b4b2a');
  // the raft, moored to the right
  const raft = new Canvas();
  sprite(['.bbbbbbbb', 'aRaaRaaRa', 'cccccccc.'], { a: '#9a5a30', b: '#c0814d', c: '#6d3c1d', R: '#e9cf98' }, raft, 40, 44);
  // her: brown low bun, cream headphones, coral tank top, cream shorts, bare feet
  const body = new Canvas();
  const head = new Canvas();
  // three-quarter view, facing the palm: headphone band and cup in cream,
  // the low bun at the back of her neck
  const HER_HEAD = ['..hhHh.', '.hhHhhh', '.hhHsss', '.hhHsss', '..hh.s.'];
  const HER_BODY = ['..cccc.', '.sccccs', '.s.ccc.', '...ccc.', '..wwww.', '..ww.w.', '..ss.s.', '..s..s.', '.ss..ss'];
  const HP = { h: '#5b3a22', H: '#f4ead2', s: '#f0c49c', c: '#ef7660', w: '#f1e6c8' };
  sprite(HER_HEAD, HP, head, 15, 27);
  sprite(HER_BODY, HP, body, 15, 32);
  const S = 2;
  const o = -A;   // centred: art (0..52) -> (-52..52)
  doc.defs.push(`<clipPath id="disc"><circle r="52"/></clipPath>`);
  return `<g clip-path="url(#disc)"><circle r="52" fill="#7cc8ea"/>${sky.paths(S, o, o)}`
    + `<g class="bob">${raft.paths(S, o, o)}</g>`
    + `${body.paths(S, o, o)}<g class="nod">${head.paths(S, o, o)}</g></g>`;
}

// A tiny seeded PRNG (mulberry32) for the glints.
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ============================================================= THE BANNER
function tunnelSVG() {
  const doc = makeDoc();
  const { defs, css } = doc;
  const W = 960;
  const H = 480;
  const CX = 480;
  const CY = 268;
  const N = 16;                  // rings in flight
  const P = N * BEAT;            // a ring's life: 12 s = 4 bars
  const QZ = 16;                 // it grows x16 over that life (x2 a bar)
  const RFAR = 52;               // outer radius when it leaves the far end
  const D = 30;                  // how far off-centre the far end sits
  const TW = 90;                 // twist over a ring's life, degrees
  const RO = 100;
  const RI = RO / Math.pow(QZ, 1 / N);
  const M = 32;                  // checker cells round the wall
  const smooth = (p) => p * p * (3 - 2 * p);
  const bend = (p) => D * (1 - smooth(p));
  const scale = (p) => (RFAR / RO) * Math.pow(QZ, p);
  const FOG = [[0, '#06242e'], [0.3, '#0b4252'], [0.62, '#147587'], [0.85, '#23a2ad'], [1, '#4cc6c9']];

  // --- ring symbols: a checkered annulus painted in currentColor
  const pt = (r, a) => `${n(r * Math.cos(a), 2)} ${n(r * Math.sin(a), 2)}`;
  const annulus = (r1, r0) => `M${r1} 0A${r1} ${r1} 0 1 1 ${-r1} 0A${r1} ${r1} 0 1 1 ${r1} 0ZM${r0} 0A${r0} ${r0} 0 1 0 ${-r0} 0A${r0} ${r0} 0 1 0 ${r0} 0Z`;
  const sector = (a0, a1, r0, r1) => `M${pt(r1, a0)}A${r1} ${r1} 0 0 1 ${pt(r1, a1)}L${pt(r0, a1)}A${n(r0)} ${n(r0)} 0 0 0 ${pt(r0, a0)}Z`;
  const step = (2 * Math.PI) / M;
  for (const [id, off] of [['ringA', 0], ['ringB', 1]]) {
    let dark = '';
    for (let i = off; i < M; i += 2) dark += sector(i * step, (i + 1) * step, RI, RO);
    const la = (0.5 + (off ? 1 : 0)) * step;
    const lr = (RO + RI) / 2;
    const lights = [la, la + Math.PI].map((a) => {
      const [x, y] = [lr * Math.cos(a), lr * Math.sin(a)];
      return `<circle cx="${n(x)}" cy="${n(y)}" r="5.2" fill="#ffd77a" opacity=".22"/><circle cx="${n(x)}" cy="${n(y)}" r="2.7" fill="#fff4c4"/>`;
    }).join('');
    defs.push(`<g id="${id}"><path fill="currentColor" fill-rule="evenodd" d="${annulus(RO, n(RI, 3))}"/>`
      + `<path fill="#000" opacity=".34" d="${dark}"/>`
      + `<path fill="#fff" opacity=".16" fill-rule="evenodd" d="${annulus(RO, n(RO * 0.972, 3))}"/>`
      + `<path fill="#000" opacity=".22" fill-rule="evenodd" d="${annulus(n(RI * 1.035, 3), n(RI, 3))}"/>`
      + `${lights}</g>`);
  }

  // --- the one shared ring track
  const K = 48;
  let fly = '';
  let sbend = '';
  let sgrow = '';
  for (let i = 0; i <= K; i++) {
    const p = i / K;
    const pc = n(p * 100, 3);
    fly += `${pc}%{transform:translate(${n(bend(p))}px,0) rotate(${n(TW * p)}deg) scale(${n(scale(p), 4)});color:${ramp(FOG, p)}}`;
    sbend += `${pc}%{transform:translate(${n(bend(p))}px,0)}`;
    const sg = 0.34 * Math.pow(QZ, p);
    const op = p < 0.12 ? 0 : p < 0.3 ? (p - 0.12) / 0.18 : p > 0.93 ? Math.max(0, (1 - p) / 0.07) : 1;
    sgrow += `${pc}%{transform:scale(${n(sg, 4)});opacity:${n(op, 3)}}`;
  }
  css.push(`@keyframes fly{${fly}}`, `@keyframes sbend{${sbend}}`, `@keyframes sgrow{${sgrow}}`);
  css.push(`.ring{animation:fly ${P}s linear infinite}`);
  css.push(`.roll{animation:roll ${LOOP}s linear infinite}`, `.unroll{animation:unroll ${LOOP}s linear infinite}`);
  css.push('@keyframes roll{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}');
  css.push('@keyframes unroll{from{transform:rotate(0deg)}to{transform:rotate(-360deg)}}');
  for (let j = 0; j < N; j++) css.push(`.r${j}{animation-delay:${dly(-j * BEAT)}}`);

  let rings = '';
  for (let j = 0; j < N; j++) rings += `<use href="#ring${j % 2 ? 'B' : 'A'}" class="ring r${j}"/>`;

  // --- the far end: halo (over the walls) and the island window
  defs.push(`<radialGradient id="halo"><stop offset=".42" stop-color="#ffffff" stop-opacity=".95"/>`
    + `<stop offset=".58" stop-color="#d4f7ff" stop-opacity=".55"/><stop offset=".78" stop-color="#8fe0ec" stop-opacity=".18"/>`
    + `<stop offset="1" stop-color="#5cc9d6" stop-opacity="0"/></radialGradient>`);
  const atFar = (inner) => `<g transform="translate(${CX} ${CY})"><g class="roll"><g transform="translate(${D} 0)"><g class="unroll">${inner}</g></g></g></g>`;
  const halo = atFar('<circle r="124" fill="url(#halo)"/>');
  const island = atFar(`${islandArt(doc)}<circle r="52" fill="none" stroke="#f2fdff" stroke-width="2.5"/><circle r="54.5" fill="none" stroke="#ffffff" stroke-opacity=".35" stroke-width="2"/>`);
  css.push(`.nod{animation:nod ${BEAT}s step-end infinite;animation-delay:${dly(0)}}@keyframes nod{0%{transform:translate(0,2px)}40%{transform:translate(0,0)}}`);
  css.push(`.bob{animation:bob ${BAR}s step-end infinite;animation-delay:${dly(0)}}@keyframes bob{0%{transform:translate(0,0)}50%{transform:translate(0,2px)}}`);

  // --- signs: every bar one gag flies out of the island
  const GAGS = ['COCONUT', 'BOTTLE, AGAIN', 'SEA TURTLE', 'MORE HEADPHONES', 'CAT ON A CRATE', '1 BAR OF SIGNAL',
    'SHARK, NODDING', 'SANDCASTLE', 'THE TIDE', 'HYDROFOIL SHAKA', 'ICED COFFEE', 'KUMARA'];
  const SLOT = [
    { dir: -14, tilt: -7 },     // slot 0: right, a little up
    { dir: 194, tilt: -5 },     // slot 1: left, a little up
    { dir: 14, tilt: 7 },       // slot 2: right, a little down
    { dir: 166, tilt: 5 },      // slot 3: left, a little down
  ];
  const slotOf = (nn) => (4 - (nn % 4)) % 4;
  const variants = [[], [], [], []];
  for (let nn = 0; nn < 12; nn++) {
    const k = slotOf(nn);
    const t = nn * BAR;
    const v = Math.floor((((t + k * BAR) % LOOP) + LOOP) % LOOP / P);
    variants[k][v] = GAGS[nn];
  }
  css.push(`.sb{animation:sbend ${P}s linear infinite}.sg{animation:sgrow ${P}s linear infinite}`);
  css.push(`.v0,.v1,.v2{animation:v0 ${LOOP}s step-end infinite}.v1{animation-name:v1}.v2{animation-name:v2}`);
  css.push('@keyframes v0{0%{opacity:1}33.333%{opacity:0}}@keyframes v1{0%{opacity:0}33.333%{opacity:1}66.667%{opacity:0}}@keyframes v2{0%{opacity:0}66.667%{opacity:1}}');
  for (let k = 0; k < 4; k++) css.push(`.s${k}{animation-delay:${dly(-k * BAR)}}`);
  let signs = '';
  for (let k = 0; k < 4; k++) {
    const { dir, tilt } = SLOT[k];
    let inner = '';
    variants[k].forEach((str, v) => {
      const w = textW(str);
      const R = w / 2 + 4;
      const a = (dir * Math.PI) / 180;
      const t = doc.text(str, { x: 0, y: -3.5, anchor: 'middle', fill: WHITE, outline: INK });
      inner += `<g class="v${v} s${k}"><g transform="translate(${n(R * Math.cos(a))} ${n(R * Math.sin(a))}) rotate(${tilt})">${t.svg}</g></g>`;
    });
    const a0 = (dir * Math.PI) / 180;
    const rim = `translate(${n(58 * Math.cos(a0))} ${n(58 * Math.sin(a0))})`;
    signs += `<g transform="translate(${CX} ${CY})"><g class="roll"><g class="sb s${k}"><g class="unroll"><g transform="${rim}"><g class="sg s${k}">${inner}</g></g></g></g></g></g>`;
  }

  // --- logo, crab, subtitle
  const SUB = 4;
  const LW = (8 * 18 - 2) * SUB;
  const LX = (W - LW) / 2;
  const LY = 42;
  const logo = logoSVG('CASTAWAY', LX, LY, SUB);
  const C3 = 3;
  const crabW = 14 * C3;
  const walkFrom = LX - SUB;
  const walkTo = LX + (4 * 18 + 16) * SUB + SUB - crabW;     // across C-A-S-T-A
  const crabY = LY - SUB - 9 * C3;
  const crabTop = new Canvas();
  sprite(CRAB_TOP, CRAB_PAL, crabTop, 0, 0);
  const legs = CRAB_LEGS.map((rows) => { const c = new Canvas(); sprite(rows, CRAB_PAL, c, 0, 8); return c.paths(C3); });
  const crab = `<g transform="translate(${n(walkFrom)} ${n(crabY)})"><g class="crab">${crabTop.paths(C3)}`
    + `<g class="legA">${legs[0]}</g><g class="legB">${legs[1]}</g></g></g>`;
  const steps = 48;
  css.push(`.crab{animation:crab ${LOOP / 2}s steps(${steps},jump-none) infinite alternate;animation-delay:${dly(0)}}`
    + `@keyframes crab{from{transform:translate(0,0)}to{transform:translate(${n(walkTo - walkFrom)}px,0)}}`);
  css.push(`.legA,.legB{animation:legs ${BEAT}s step-end infinite;animation-delay:${dly(0)}}.legB{animation-name:legsB}`
    + '@keyframes legs{0%{opacity:1}50%{opacity:0}}@keyframes legsB{0%{opacity:0}50%{opacity:1}}');

  const subtitle = doc.text('A TEN-HOUR LO-FI ISLAND VIDEO', { x: CX, y: LY + 92, s: 2, anchor: 'middle', fill: WHITE, outline: INK, shadow: INK }).svg;

  // --- HUD plates beside the subtitle: tempo with beat lights, and the ETA
  const hy = LY + 88;
  css.push(`.bt{fill:#1d4651;animation:bt ${BAR}s step-end infinite}@keyframes bt{0%{fill:${SUN}}25%{fill:#1d4651}}`);
  let hud = panel(16, hy, 150, 24, { r: 3 });
  hud += doc.text('80 BPM', { x: 26, y: hy + 5, s: 2, fill: AQUA }).svg;
  for (let b = 0; b < 4; b++) {
    hud += `<rect class="bt b${b}" x="${114 + b * 12}" y="${hy + 7}" width="8" height="10" rx="1"/>`;
    css.push(`.b${b}{animation-delay:${dly(-((BAR - b * BEAT) % BAR))}}`);
  }
  const eta = 'ETA 10:00:00';
  const ew = textW(eta, 2) + 20;
  hud += panel(W - 16 - ew, hy, ew, 24, { r: 3 });
  hud += doc.text(eta, { x: W - 26, y: hy + 5, s: 2, fill: SUN, anchor: 'end' }).svg;

  // --- the text panel: six pages, hard cuts, 6 s each
  const PAGES = [
    ['LOOKUP LAGOON PRESENTS, AT ONE RING PER BEAT:', 'CASTAWAY. TEN HOURS OF ONE TINY ISLAND.', 'SHE IDLES. EVERY SO OFTEN, SOMETHING HAPPENS.'],
    ['MORE THAN 90 ACTIVITIES ON FOUR TIMERS,', 'FROM EVERY 2-5 MINUTES TO EVERY 3-6 HOURS.', 'EACH ONE STARTS ON THE NEXT BAR. ON THE BEAT.'],
    ['UP THERE A GAG ARRIVES EVERY BAR.', 'THE VIDEO IS MUCH, MUCH CALMER THAN THIS.', 'MOSTLY SHE NODS. THAT IS THE WHOLE IDEA.'],
    ['EVERY SOUND IS SYNTHESIZED FROM CODE.', 'NO SAMPLES, NO LOOPS, NO RECORDINGS.', 'THEME: 60 S, 80 BPM, F MAJOR, KALIMBA LEAD.'],
    ['RUN     python tools/serve.py', 'OPEN    http://127.0.0.1:8765/', 'PREVIEW LIVE, EXPORT A YOUTUBE-READY MP4.'],
    ['DISTANCE TO THE ISLAND: STILL TEN HOURS.', 'THE WALLS MOVE. THE ISLAND DOES NOT.', 'SHE COULD LEAVE ANY TIME. SHE GETS COFFEE.'],
  ];
  const PX = 24;
  const PY = 382;
  const PW = W - 48;
  const PH = 86;
  let text = panel(PX, PY, PW, PH, { face: '#081c24', hi: '#4fb3bd', lo: '#02090d', r: 4 });
  const TS = 2.5;
  const LINE_COL = [SUN, WHITE, AQUA];
  const pageDur = LOOP / PAGES.length;
  css.push(`.pg{animation:pg ${LOOP}s step-end infinite}@keyframes pg{0%{opacity:1}${n(100 / PAGES.length, 3)}%{opacity:0}}`);
  css.push(`.pip{fill:#1d4651;animation:pip ${LOOP}s step-end infinite}@keyframes pip{0%{fill:${CORAL}}${n(100 / PAGES.length, 3)}%{fill:#1d4651}}`);
  PAGES.forEach((lines, i) => {
    let g = '';
    lines.forEach((str, li) => {
      if (textW(str, TS) > PW - 70) throw new Error(`panel line too long: ${str}`);
      g += doc.text(str, { x: PX + 22, y: PY + 13 + li * 23, s: TS, fill: LINE_COL[li] }).svg;
    });
    const d = dly(-((LOOP - i * pageDur) % LOOP));
    css.push(`.p${i}{animation-delay:${d}}`);
    text += `<g class="pg p${i}">${g}</g>`;
    text += `<rect class="pip p${i}" x="${PX + PW - 22}" y="${PY + 12 + i * 11}" width="8" height="7" rx="1"/>`;
  });

  // --- frame
  defs.push(`<clipPath id="frame"><rect width="${W}" height="${H}" rx="16"/></clipPath>`);
  css.push('@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}');

  const body = `<g clip-path="url(#frame)"><rect width="${W}" height="${H}" fill="#06242e"/>`
    + `<g transform="translate(${CX} ${CY})"><g class="roll">${rings}</g></g>`
    + halo + signs + island
    + logo + crab + subtitle + hud + text
    + `</g><rect x=".75" y=".75" width="${W - 1.5}" height="${H - 1.5}" rx="15.5" fill="none" stroke="${INK}" stroke-width="1.5"/>`;
  return wrap(doc, W, H, body, 'CASTAWAY: a checkered tunnel flies toward a tiny island');
}

// ========================================================= THE ROTOZOOMER
function rotoSVG() {
  const doc = makeDoc();
  const { defs, css } = doc;
  const W = 960;
  const H = 160;
  const BARH = 16;
  // the tile: a C with a palm in it, embossed sand on sand, 28x28 art px
  const T = 28;
  const raised = new Set();
  const k = (x, y) => `${x},${y}`;
  for (let y = 0; y < T; y++) for (let x = 0; x < T; x++) {
    const dx = x + 0.5 - 14;
    const dy = y + 0.5 - 14;
    const r = Math.hypot(dx, dy);
    const a = (Math.atan2(dy, dx) * 180) / Math.PI;
    if (r >= 7.2 && r <= 11.6 && Math.abs(a) > 40) raised.add(k(x, y));
  }
  const palm = [
    [15, 21], [15, 20], [15, 19], [14, 18], [14, 17], [14, 16], [14, 15], [14, 14], [13, 13], [13, 12],
    [12, 11], [11, 11], [10, 11], [9, 12], [8, 13], [8, 14],
    [14, 11], [15, 11], [16, 11], [17, 12], [18, 13], [18, 14],
    [12, 10], [11, 9], [10, 9], [9, 9], [14, 10], [15, 9], [16, 9], [17, 9], [13, 10], [13, 11],
    [10, 20], [11, 20], [12, 20], [13, 20], [14, 20], [16, 20], [17, 20], [18, 20], [19, 20],
    [11, 21], [12, 21], [13, 21], [14, 21], [16, 21], [17, 21], [18, 21],
  ];
  palm.forEach(([x, y]) => raised.add(k(x, y)));
  const has = (x, y) => raised.has(k(((x % T) + T) % T, ((y % T) + T) % T));
  const tile = new Canvas();
  const BG = '#dcbb7d';
  for (let y = 0; y < T; y++) for (let x = 0; x < T; x++) {
    let c = BG;
    if (has(x, y)) {
      c = '#f1daa6';
      if (!has(x, y - 1) || !has(x - 1, y)) c = '#fff2d2';
      if (!has(x, y + 1) || !has(x + 1, y)) c = '#b48a4e';
    } else if (has(x - 1, y - 1) || has(x - 1, y) || has(x, y - 1)) {
      c = '#c49f61';                     // cast shadow down-right of the relief
    } else if (x === T - 1 || y === T - 1) {
      c = '#c9a669';                     // the grid lines that sweep across
    } else if (x === 0 || y === 0) {
      c = '#e6c98f';
    }
    tile.set(x, y, c);
  }
  const TS = 2;
  defs.push(`<pattern id="tile" patternUnits="userSpaceOnUse" width="${T * TS}" height="${T * TS}" x="${-T}" y="${-T}">${tile.paths(TS)}</pattern>`);
  // rotate, breathe, drift
  css.push(`.rz-rot{animation:rzrot ${LOOP}s linear infinite;animation-delay:${dly(0)}}@keyframes rzrot{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`);
  css.push(`.rz-zoom{animation:rzzoom ${4 * BAR}s ease-in-out infinite;animation-delay:${dly(0)}}@keyframes rzzoom{0%{transform:scale(.8)}50%{transform:scale(1.45)}100%{transform:scale(.8)}}`);
  let drift = '';
  const DK = 36;
  for (let i = 0; i <= DK; i++) {
    const t = i / DK;
    const x = 40 * Math.sin(2 * Math.PI * t);
    const y = 26 * Math.sin(4 * Math.PI * t);
    drift += `${n(t * 100, 3)}%{transform:translate(${n(x)}px,${n(y)}px)}`;
  }
  css.push(`.rz-drift{animation:rzdrift ${LOOP}s linear infinite;animation-delay:${dly(0)}}@keyframes rzdrift{${drift}}`);
  const roto = `<g transform="translate(${W / 2} ${H / 2})"><g class="rz-rot"><g class="rz-zoom"><g class="rz-drift">`
    + '<rect x="-1300" y="-1300" width="2600" height="2600" fill="url(#tile)"/></g></g></g></g>';

  // the raft-log bars top and bottom
  const logBar = (y0) => {
    const cv = new Canvas();
    const LOGC = ['#4a2912', '#7e4a24', '#a3653a', '#c48a55', '#d9a46c', '#b0713f', '#8a5229', '#5e3418'];
    for (let y = 0; y < 8; y++) for (let x = 0; x < W / 2; x++) cv.set(x, y, LOGC[y]);
    for (let x = 0; x < W / 2; x += 60) {
      // a rope lashing every 120 px, and a knot in the wood between them
      for (let y = 0; y < 8; y++) for (let j = 0; j < 5; j++) cv.set(x + 28 + j, y, (j + y) % 3 === 0 ? '#bf9c5c' : '#ecd39d');
      cv.set(x + 8, 3, '#6e3f1f'); cv.set(x + 9, 3, '#6e3f1f'); cv.set(x + 9, 4, '#5a3418');
    }
    return cv.paths(2, 0, y0);
  };
  const bars = logBar(0) + logBar(H - BARH);

  // the plate with the run command
  const PW = 560;
  const PH = 80;
  const PX = (W - PW) / 2;
  const PY = (H - PH) / 2;
  let plate = panel(PX, PY, PW, PH, { face: '#0a1d26', hi: '#f0d39b', lo: '#02090d', r: 5 });
  const l1 = '> python tools/serve.py';
  const s1 = 3;
  const w1 = textW(l1, s1) + 4 * s1 + 6 * s1;
  const x1 = (W - w1) / 2;
  plate += doc.text('>', { x: x1, y: PY + 14, s: s1, fill: CORAL }).svg;
  plate += doc.text(l1.slice(2), { x: x1 + 2 * ADV * s1, y: PY + 14, s: s1, fill: SUN }).svg;
  plate += `<rect class="cur" x="${n(x1 + textW(l1, s1) + 4 * s1)}" y="${PY + 14}" width="${5 * s1}" height="${7 * s1}" fill="${SUN}"/>`;
  css.push(`.cur{animation:cur ${2 * BEAT}s step-end infinite;animation-delay:${dly(0)}}@keyframes cur{0%{opacity:1}50%{opacity:0}}`);
  plate += doc.text('THEN OPEN http://127.0.0.1:8765/', { x: W / 2, y: PY + 53, s: 2, fill: WHITE, anchor: 'middle' }).svg;

  defs.push(`<clipPath id="frame"><rect width="${W}" height="${H}" rx="14"/></clipPath>`);
  css.push('@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}');
  const body = `<g clip-path="url(#frame)"><rect width="${W}" height="${H}" fill="${BG}"/>${roto}`
    + `<rect y="${BARH}" width="${W}" height="6" fill="#000" opacity=".18"/><rect y="${H - BARH - 4}" width="${W}" height="4" fill="#000" opacity=".12"/>`
    + `${bars}${plate}</g>`
    + `<rect x=".75" y=".75" width="${W - 1.5}" height="${H - 1.5}" rx="13.5" fill="none" stroke="${INK}" stroke-width="1.5"/>`;
  return wrap(doc, W, H, body, 'CASTAWAY: run python tools/serve.py, then open http://127.0.0.1:8765/');
}

function wrap(doc, W, H, body, title) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img">`
    + `<title>${title}</title>`
    + `<style>${doc.css.join('')}</style>`
    + `<defs>${doc.glyphDefs()}${doc.defs.join('')}</defs>`
    + `${body}</svg>\n`;
}

fs.mkdirSync(OUTDIR, { recursive: true });
for (const [name, svg] of [[`${SLUG}.svg`, tunnelSVG()], [`${SLUG}-rotozoom.svg`, rotoSVG()]]) {
  const out = path.join(OUTDIR, name);
  fs.writeFileSync(out, svg);
  console.log(`${path.relative(process.cwd(), out)}  ${(svg.length / 1024).toFixed(1)} KB`);
}
