// "Bobs and dot objects" README banner for CASTAWAY.
//
//   node examples/castaway/src/32-bobs-dot-objects_opus_5.5.mjs
//   node examples/castaway/src/32-bobs-dot-objects_opus_5.5.mjs --at=21 --out=some/where.svg
//
// Regenerates ../assets/32-bobs-dot-objects_opus_5.5.svg. Plain Node, no
// deps, deterministic (no clock, no Math.random). --at bakes a head start
// (seconds) into every animation delay so late frames can be checked without
// waiting; use it only together with --out, never in place.
//
// The style: the early Amiga "bobs" and "dot object" screens (c. 1989-90).
// A black screen with one object made of many identical pieces: a chain of
// shaded blue balls snaking round a figure of eight, or a lattice of single
// dots turning in space, shut in above and below by a one-pixel rainbow rule,
// over a strip with a gradient-filled logo. Razor 1911's Liquid Bobs and
// Space Dots are the usual examples and are credited as the reference here;
// nothing of theirs is copied. The balls, dots, letters, palette, sprite and
// copy are drawn for this file.
//
// What this banner does with it
//   * Both effects at once: a dot object (a palm on a little island of dot
//     rings, turning about its trunk) and a chain of 30 bobs travelling on a
//     ring round it. Seen from the front the ring is a figure of eight: x is
//     one sine of the lap, height is another at a bit over twice the
//     frequency, so the eight slowly drifts into a smile, a frown and back
//     (the "two sine frequencies drift" of the originals). The drift repeats
//     every 60 s, which is the length of the project's theme.
//   * Depth: each bob swaps between six pre-drawn sizes as it goes round (far
//     ones small and dim, near ones big and bright), and every bob exists
//     twice, once on a layer behind the island and once in front, each copy
//     only showing its own half of the lap. So the chain passes behind the
//     palm and in front of her, which one fixed paint order could not do.
//   * Bobs move in whole Amiga pixels: each axis is ONE shared step-end
//     keyframe track, pre-quantised here, and a bob is just that track with
//     its own animation-delay (the "each ball follows the one ahead" chain).
//     The tail bob is a coconut. Nobody has mentioned it.
//   * Dots turn smoothly: a dot at radius r and angle a has x = r sin(a + wt)
//     and y = tilt * r cos(a + wt), each an eased alternate track (one per
//     whole-pixel radius) shifted by its own delay; brightness follows depth.
//   * She sits at the foot of the palm, on the axis, so she never has to turn
//     with it: a billboard sprite, small and simple, nodding on every beat
//     (80 BPM). She has not looked up once.
//   * The tagline under the logo cuts to a new line every two bars of the
//     theme (6 s), ten lines in 60 s. Hard cuts, like the project's own
//     motion rule. During two of them, once a minute, a coconut walks across
//     the front of the island on a hermit crab's legs.
//   * prefers-reduced-motion pauses every track where it starts: a full
//     chain, a turned palm and the first tagline.
// (The .md beside the assets is hand-written, not generated by this script.)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const arg = (name) => {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const T0 = Number(arg('at') || 0);
const OUT = arg('out') ? path.resolve(arg('out')) : path.resolve(here, '../assets/32-bobs-dot-objects_opus_5.5.svg');

// ------------------------------------------------------------------ screen
const S = 3;            // real px per virtual (Amiga lo-res) pixel
const VW = 320;
const VH = 124;
const W = VW * S;
const H = VH * S;
const BEAT = 0.75;      // 80 BPM
const BAR = 4 * BEAT;   // 3 s

const n = (v, d = 3) => String(+(+v).toFixed(d));
const hex = (c) => (c.length === 4 ? `#${c[1]}${c[1]}${c[2]}${c[2]}${c[3]}${c[3]}` : c);
const mod = (a, m) => ((a % m) + m) % m;
// animation-delay that puts a track of period P at `phase` seconds at t = 0
const dly = (phase, P) => `${n(-mod(phase + T0, P), 3)}s`;

const defs = [];
const css = [];

// ------------------------------------------------------------------ pixels
const key = (x, y) => `${x},${y}`;
const unkey = (k) => k.split(',').map(Number);
// Merge pixels into horizontal runs, stack identical runs, one path (real px).
function pathOf(set, ox = 0, oy = 0) {
  const rows = new Map();
  for (const k of set) {
    const [x, y] = unkey(k);
    if (!rows.has(y)) rows.set(y, []);
    rows.get(y).push(x);
  }
  const runs = [];
  for (const [y, xs] of rows) {
    xs.sort((a, b) => a - b);
    let s = xs[0];
    let p = xs[0];
    for (let i = 1; i <= xs.length; i++) {
      if (i < xs.length && xs[i] === p + 1) { p = xs[i]; continue; }
      runs.push([s, p + 1, y]);
      if (i < xs.length) { s = xs[i]; p = xs[i]; }
    }
  }
  runs.sort((a, b) => a[2] - b[2] || a[0] - b[0]);
  const live = new Set(runs.map((r) => `${r[0]},${r[1]},${r[2]}`));
  const out = [];
  for (const r of runs) {
    const k0 = `${r[0]},${r[1]},${r[2]}`;
    if (!live.has(k0)) continue;
    live.delete(k0);
    let h = 1;
    while (live.has(`${r[0]},${r[1]},${r[2] + h}`)) { live.delete(`${r[0]},${r[1]},${r[2] + h}`); h++; }
    out.push(`M${(ox + r[0]) * S} ${(oy + r[2]) * S}h${(r[1] - r[0]) * S}v${h * S}h${-(r[1] - r[0]) * S}z`);
  }
  return out.join('');
}
function ring(set, extra = []) {
  const out = new Set();
  const offs = [];
  for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) offs.push([dx, dy]);
  offs.push(...extra);
  for (const k of set) {
    const [x, y] = unkey(k);
    for (const [dx, dy] of offs) {
      const k2 = key(x + dx, y + dy);
      if (!set.has(k2)) out.add(k2);
    }
  }
  return out;
}
function colourPaths(groups) {
  return [...groups].map(([c, set]) => `<path fill="${hex(c)}" d="${pathOf(set)}"/>`).join('');
}

// ------------------------------------------------------------------ layout
const RULE1 = 3;        // top rainbow rule (row)
const RULE2 = 79;       // bottom rainbow rule
const LOGO_Y = 84;      // logo strip top
const TAG_Y = 114;      // tagline glyph top
const AX = 160;         // the axis everything turns about
const Y0 = 68;          // island disc centre (screen row)
const TILT = 0.18;      // how far we look down on the disc

// ------------------------------------------------------------------ rainbow rules
// A one-pixel rule, a 12-bit rainbow from left to right, cycling slowly; the
// top one runs left, the bottom one right.
const RAINBOW = [];
{
  const NH = 32;
  for (let i = 0; i < NH; i++) {
    const h = (i / NH) * 6;
    const f = h - Math.floor(h);
    const q = [
      [1, f, 0], [1 - f, 1, 0], [0, 1, f], [0, 1 - f, 1], [f, 0, 1], [1, 0, 1 - f],
    ][Math.floor(h)];
    const c = q.map((v) => Math.round(v * 15).toString(16)).join('');
    RAINBOW.push(`#${c}`);
  }
}
{
  const seg = 10;                       // virtual px per colour step
  const span = RAINBOW.length * seg;    // one full rainbow: 320 px
  const st = [];
  RAINBOW.forEach((c, i) => {
    st.push(`<stop offset="${n(i / RAINBOW.length, 4)}" stop-color="${hex(c)}"/><stop offset="${n((i + 1) / RAINBOW.length, 4)}" stop-color="${hex(c)}"/>`);
  });
  defs.push(`<linearGradient id="rb" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="${span * S}" y2="0" spreadMethod="repeat">${st.join('')}</linearGradient>`);
  defs.push(`<clipPath id="rc"><rect x="${4 * S}" y="0" width="${(VW - 8) * S}" height="${H}"/></clipPath>`);
  css.push(`@keyframes rl{from{transform:translateX(0)}to{transform:translateX(${-span * S}px)}}`);
  css.push(`@keyframes rr{from{transform:translateX(${-span * S}px)}to{transform:translateX(0)}}`);
  css.push(`.rl{animation:rl 16s steps(${span}) infinite;animation-delay:${dly(0, 16)}}.rr{animation:rr 16s steps(${span}) infinite;animation-delay:${dly(0, 16)}}`);
}
const rulesSvg = `<g clip-path="url(#rc)"><rect class="rl" x="0" y="${RULE1 * S}" width="${2 * W}" height="${S}" fill="url(#rb)"/><rect class="rr" x="0" y="${RULE2 * S}" width="${2 * W}" height="${S}" fill="url(#rb)"/></g>`;

// ------------------------------------------------------------------ bob sprites
// Pre-drawn balls in six sizes, lit from the upper left, quantised to a
// 12-bit ramp with a white highlight. The far sizes are drawn darker.
const BLUE = ['#001', '#012', '#124', '#236', '#248', '#35a', '#46c', '#68e', '#9bf', '#cef', '#fff'];
const NUT = ['#100', '#210', '#320', '#421', '#531', '#642', '#753', '#864', '#a86', '#cb9', '#fed'];
const SIZES = [7, 9, 11, 13, 15, 17];
const BRIGHT = [0.6, 0.7, 0.8, 0.88, 0.95, 1.0];
function ball(d, ramp, bright, fibre) {
  const groups = new Map();
  const c0 = (d - 1) / 2;
  const R = d / 2;
  const L = [-0.52, -0.62, 0.59];
  const ln = Math.hypot(...L);
  const top = ramp.length - 2;
  for (let py = 0; py < d; py++) {
    for (let px = 0; px < d; px++) {
      const dx = (px + 0.5 - R) / R;
      const dy = (py + 0.5 - R) / R;
      const rr = dx * dx + dy * dy;
      if (rr > 1.02) continue;
      const nz = Math.sqrt(Math.max(0, 1 - rr));
      const lam = Math.max(0, (dx * L[0] + dy * L[1] + nz * L[2]) / ln);
      let I = 0.16 + 0.84 * lam;
      // a little rim light from below right, the way bobs were hand-shaded
      if (dx + dy > 0.9 && rr > 0.55) I = Math.max(I, 0.3);
      let idx = Math.round(I * bright * top);
      if (fibre && idx > 2 && (px * 7 + py * 3) % 5 === 0) idx -= 2;   // husk
      const hx = dx + 0.42;
      const hy = dy + 0.46;
      let c = ramp[Math.max(0, Math.min(top, idx))];
      if (hx * hx + hy * hy < (d >= 11 ? 0.05 : 0.09)) c = bright > 0.8 ? ramp[top + 1] : ramp[top];
      const k = key(px - c0, py - c0);
      if (!groups.has(c)) groups.set(c, new Set());
      groups.get(c).add(k);
    }
  }
  return colourPaths(groups);
}
SIZES.forEach((d, i) => {
  defs.push(`<g id="b${i}">${ball(d, BLUE, BRIGHT[i], false)}</g>`);
  defs.push(`<g id="c${i}">${ball(d, NUT, BRIGHT[i], true)}</g>`);
});

// ------------------------------------------------------------------ bob chain
// One lap of the ring is 12 s (four bars). x = A sin(wt); the ring is tilted
// towards us, so its near side is lower: y2 = K cos(wt); and it bobs up and
// down a little over twice a lap: y1 = B sin(w1 t) with w1 = 2w + 2pi/60, so
// the figure of eight drifts through its shapes once every 60 s.
const LAP = 4 * BAR;                 // 12 s
const T1 = 60 / 11;                  // 5.4545 s: 11 of these per 60 s, 5 laps
const A = 104;
const K = 3;
const B = 14;
const YC = 33;
const NB = 30;
const GAPT = 0.15;                   // seconds between bobs
const NS = SIZES.length;
const sizeAt = (u) => Math.min(NS - 1, Math.floor(((Math.cos(2 * Math.PI * u) + 1) / 2) * NS));
function quantTrack(name, P, f, prop) {
  const N = 9600;
  const frames = [];
  let last = null;
  for (let i = 0; i < N; i++) {
    const v = f(i / N);
    if (v !== last) {
      frames.push(`${n((i / N) * 100, 3)}%{${prop(v)}}`);
      last = v;
    }
  }
  css.push(`@keyframes ${name}{${frames.join('')}}.${name}{animation:${name} ${n(P, 4)}s step-end infinite}`);
}
const tx = (v) => `transform:translateX(${v * S}px)`;
const ty = (v) => `transform:translateY(${v * S}px)`;
quantTrack('X', LAP, (u) => Math.round(A * Math.sin(2 * Math.PI * u)), tx);
quantTrack('Y', T1, (u) => Math.round(B * Math.sin(2 * Math.PI * u)), ty);
quantTrack('Z', LAP, (u) => Math.round(K * Math.cos(2 * Math.PI * u)), ty);
for (let s = 0; s < NS; s++) quantTrack(`s${s}`, LAP, (u) => (sizeAt(u) === s ? 1 : 0), (v) => `opacity:${v}`);
for (let i = 0; i < NB; i++) {
  css.push(`.p${i}{animation-delay:${dly(-i * GAPT, LAP)}}.q${i}{animation-delay:${dly(-i * GAPT, T1)}}`);
}
function chainLayer(sizes) {
  const out = [];
  for (let i = NB - 1; i >= 0; i--) {     // head painted last, on top
    const sym = i === NB - 1 ? 'c' : 'b';
    const uses = sizes.map((s) => `<use href="#${sym}${s}" class="s${s} p${i}"/>`).join('');
    out.push(`<g class="X p${i}"><g class="Y q${i}"><g class="Z p${i}">${uses}</g></g></g>`);
  }
  return `<g transform="translate(${AX * S} ${YC * S})">${out.join('')}</g>`;
}
const backBobs = chainLayer([0, 1, 2]);
const frontBobs = chainLayer([3, 4, 5]);

// ------------------------------------------------------------------ dot object
// A palm on an island of dot rings, turning about the trunk. Object space:
// (X, Z) on the ground, h up. A dot at radius r, angle a shows at
// x = AX + r sin(a + wt), y = Y0 - h + TILT r cos(a + wt), brighter near us.
const TURN = 20;                     // seconds per revolution
const EASE = 'cubic-bezier(.37,0,.63,1)';   // half a cosine
const dots = [];
const dot = (X, Z, h, c, size = 1) => dots.push({ X, Z, h, c, size });
// the island: a ring of surf, two rings of sand
const RINGS = [[43, 52, '#bdf'], [35, 42, '#fe9'], [27, 32, '#db7'], [19, 22, '#b95']];
RINGS.forEach(([r, cnt, c], j) => {
  for (let i = 0; i < cnt; i++) {
    const a = ((i + (j % 2) * 0.5) / cnt) * 2 * Math.PI;
    dot(r * Math.sin(a), r * Math.cos(a), 0, c);
  }
});
// the trunk: leans away and to the right, fat 2x2 dots in segmented bark
const TRUNK_H = 51;
const LEAN_A = 2.3;                  // lean direction (object angle)
const LEAN = 10;
const lean = (h) => LEAN * Math.pow(h / TRUNK_H, 1.7);
for (let k = 0; k * 2 + 2 <= TRUNK_H - 2; k++) {
  const h = 2 + k * 2;
  const o = lean(h);
  dot(o * Math.sin(LEAN_A), o * Math.cos(LEAN_A), h, (k >> 1) % 2 ? '#c86' : '#953', 2);
}
// the crown: three coconuts and eight fronds that arch and droop, each a
// spine of dots with leaflets hanging off both sides
const CRX = lean(TRUNK_H) * Math.sin(LEAN_A);
const CRZ = lean(TRUNK_H) * Math.cos(LEAN_A);
const FRONDS = 8;
const FROND_L = 33;
const GREENS = ['#3b4', '#4c4', '#5d5', '#6e5', '#8f6', '#bf8'];
const gAt = (u, dk = 0) => GREENS[Math.max(0, Math.min(GREENS.length - 1, Math.floor(u * GREENS.length) + dk))];
let seed = 1992;                     // the project's default seed
const rnd = () => {                  // mulberry32
  seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
for (let f = 0; f < FRONDS; f++) {
  const al0 = (f / FRONDS) * 2 * Math.PI + 0.35 + (rnd() - 0.5) * 0.5;
  const curl = (rnd() - 0.5) * 0.7;
  const len = FROND_L - rnd() * 9;
  const lift = 6 + rnd() * 8;
  const droop = lift + 11 + rnd() * 8;
  for (let s = 1.8, j = 0; s <= len; s += 1.8, j++) {
    const u = s / len;
    const al = al0 + curl * u * u;
    const h = TRUNK_H + lift * u - droop * u * u;
    const X = CRX + s * Math.sin(al0 + curl * u * u / 2);
    const Z = CRZ + s * Math.cos(al0 + curl * u * u / 2);
    dot(X, Z, h, gAt(u));
    if (u > 0.15 && u < 0.97 && j % 2 === 0) {
      const w = 2.4 * Math.sin(Math.PI * Math.min(1, u * 1.1));
      for (const side of [1, -1]) {
        dot(X + Math.cos(al) * side * w, Z - Math.sin(al) * side * w, h - 1.5 - u * 1.5, gAt(u, -1));
      }
    }
  }
}
dot(CRX + 1.6, CRZ + 0.6, TRUNK_H - 1.5, '#753', 2);
dot(CRX - 1.6, CRZ + 0.6, TRUNK_H - 1.5, '#864', 2);
dot(CRX, CRZ - 1.4, TRUNK_H - 2.5, '#642', 2);
// tracks: per whole-pixel radius, x from -r to r and y from +TILT r to -TILT r
const usedX = new Set();
const usedY = new Map();
const usedD = new Set();
const rq = (v) => Math.round(v);
const rname = (r) => String(r);
const PH = 160;                       // phase steps per revolution
const dotSvg = [];
const dotSyms = new Set();
// paint far rings first so near dots land on top (static order, close enough)
const order = dots.map((d, i) => i);
for (const i of order) {
  const d = dots[i];
  const r = rq(Math.hypot(d.X, d.Z));
  const a = Math.atan2(d.X, d.Z);
  const xPhase = Math.round((mod(a + Math.PI / 2, 2 * Math.PI) / (2 * Math.PI)) * PH) % PH;
  const yPhase = Math.round((mod(a, 2 * Math.PI) / (2 * Math.PI)) * PH) % PH;
  const lo = r < 0.5 ? 1 : Math.max(0.28, 1 - 0.72 * Math.min(1, r / 18));
  const ob = Math.round(lo * 20);
  const sz = d.size * S;
  const x0 = AX * S + (S - sz) / 2;
  const y0 = (Y0 - d.h) * S;
  const sk = `${d.c.slice(1)}${d.size}`;
  if (!dotSyms.has(sk)) {
    dotSyms.add(sk);
    defs.push(`<rect id="k${sk}" x="${n(x0, 1)}" width="${sz}" height="${sz}" fill="${hex(d.c)}"/>`);
  }
  const rect = `<use href="#k${sk}" y="${n(y0, 1)}"/>`;
  if (r < 0.5) { dotSvg.push(rect); continue; }
  usedX.add(r);
  usedY.set(`${rname(r)}_${ob}`, [r, ob]);
  usedD.add(xPhase);
  usedD.add(yPhase);
  dotSvg.push(`<g class="x${rname(r)} d${xPhase}"><g class="y${rname(r)}_${ob} d${yPhase}">${rect}</g></g>`);
}
for (const r of usedX) {
  css.push(`@keyframes x${rname(r)}{from{transform:translateX(${n(-r * S, 2)}px)}to{transform:translateX(${n(r * S, 2)}px)}}.x${rname(r)}{animation:x${rname(r)} ${TURN / 2}s ${EASE} infinite alternate}`);
}
const obs = new Set();
for (const [name, [r, ob]] of usedY) {
  const a = n(TILT * r * S, 2);
  css.push(`@keyframes y${name}{from{transform:translateY(${a}px)}to{transform:translateY(${-a}px)}}`);
  css.push(`.y${name}{animation:y${name} ${TURN / 2}s ${EASE} infinite alternate,o${ob} ${TURN / 2}s ${EASE} infinite alternate}`);
  obs.add(ob);
}
for (const ob of obs) css.push(`@keyframes o${ob}{from{opacity:1}to{opacity:${n(ob / 20, 2)}}}`);
for (const p of [...usedD].sort((a, b) => a - b)) css.push(`.d${p}{animation-delay:${dly((p / PH) * TURN, TURN)}}`);

// ------------------------------------------------------------------ her
// Small and simple, cross-legged at the foot of the palm, on the axis, so the
// island can turn under her without her turning. Cream headphones, brown
// hair in a low bun, coral tank top, cream shorts, bare feet. Eyes closed,
// nodding on every beat.
const HER_HEAD = [
  '....PPPPP....',
  '...PHHHHHP...',
  '..PHHHHHHHP..',
  '..CHHHHHHHC..',
  '.CCHSSSSSHCC.',
  '.CcHESSSESCc.',
  '..CHSSSSSHC..',
  '...HhSSSHH...',
];
const HER_BODY = [
  '.....sSs.....',
  '...STTTTTS...',
  '..SSTTTTTSS..',
  '..SsTTTTTsS..',
  '..Ss.TTT.sS..',
  '..WWWWWWWWW..',
  '.SWWWwwwWWWS.',
  'FSSSSSsSSSSSF',
];
const HER_COL = {
  P: '#e8dcc0', C: '#fbf3dc', c: '#b0a488', H: '#6a4128', h: '#4b2c1a', S: '#f2b98f', s: '#cf8f6a',
  E: '#4a2c1c', T: '#ec725c', W: '#f4ead0', w: '#cdbf9c', F: '#f6c9a6',
};
function sprite(rows, ox, oy) {
  const groups = new Map();
  const all = new Set();
  rows.forEach((row, y) => [...row].forEach((c, x) => {
    if (c === '.') return;
    const k = key(ox + x, oy + y);
    all.add(k);
    const col = HER_COL[c];
    if (!groups.has(col)) groups.set(col, new Set());
    groups.get(col).add(k);
  }));
  return { all, paths: colourPaths(groups) };
}
const HW = HER_HEAD[0].length;
const HX = AX - (HW - 1) / 2;
const HY = Y0 + 2 - HER_HEAD.length - HER_BODY.length;
const head = sprite(HER_HEAD, HX, HY);
const body = sprite(HER_BODY, HX, HY + HER_HEAD.length);
const herSvg = [
  `<path fill="#000" d="${pathOf(ring(body.all))}"/>`,
  `<g class="nod"><path fill="#000" d="${pathOf(ring(head.all))}"/></g>`,
  body.paths,
  `<g class="nod">${head.paths}</g>`,
].join('');
css.push(`@keyframes nod{0%{transform:translateY(${S}px)}45%{transform:translateY(0)}100%{transform:translateY(0)}}.nod{animation:nod ${BEAT}s step-end infinite;animation-delay:${dly(0, BEAT)}}`);

// ------------------------------------------------------------------ the crab
// Once a minute (the length of the theme), during the two taglines that
// mention it, a coconut walks across the front of the island with a hermit
// crab underneath, wearing it. Legs swap every half beat; it moves in whole
// pixels, and pops in and out with hard cuts.
const CRAB_COL = { r: '#e53', R: '#a32', l: '#f97', w: '#fff', k: '#000' };
const CRAB_BODY = [
  // x from -6 to 7 (14 wide), rows from y = 3 to 5 relative to the shell centre
  '..R........ll.',
  '..rrrrrrrrrrl.',
  '...RrrrrrrrR..',
];
const CRAB_EYES = [ // rows y = -1 to 2, x from 4 to 7
  '.ww.',
  '.kk.',
  '.rr.',
  '.r..',
];
const CRAB_LEGS = [
  ['.r.r.r..r.r.r.', 'r.r.r....r.r.r'],
  ['r.r.r....r.r.r', '.r.r.r..r.r.r.'],
];
function crabPix(rows, ox, oy) {
  const groups = new Map();
  rows.forEach((row, y) => [...row].forEach((c, x) => {
    if (c === '.') return;
    const col = CRAB_COL[c];
    if (!groups.has(col)) groups.set(col, new Set());
    groups.get(col).add(key(ox + x, oy + y));
  }));
  return colourPaths(groups);
}
const CRAB_Y = Y0 + 2;
const crabShell = `<g transform="translate(${AX * S} ${CRAB_Y * S})">${ball(9, NUT, 1, true)}</g>`;
const crabSvg = [
  '<g class="cw"><g class="cx">',
  crabPix(CRAB_EYES, AX + 4, CRAB_Y - 2),
  crabPix(CRAB_BODY, AX - 6, CRAB_Y + 3),
  `<g class="lg0">${crabPix(CRAB_LEGS[0], AX - 6, CRAB_Y + 6)}</g>`,
  `<g class="lg1">${crabPix(CRAB_LEGS[1], AX - 6, CRAB_Y + 6)}</g>`,
  crabShell,
  '</g></g>',
].join('');
{
  const CYC = 20 * BAR;              // 60 s, once per theme
  const on = (6 * 2 * BAR) / CYC;    // shown with taglines 6 and 7
  const off = (8 * 2 * BAR) / CYC;
  const walk = 50;                   // virtual px either side of the axis
  const steps = Math.round(2 * walk);
  css.push(`@keyframes cw{0%{opacity:0}${n(on * 100)}%{opacity:1}${n(off * 100)}%{opacity:0}}.cw{animation:cw ${CYC}s step-end infinite;animation-delay:${dly(0, CYC)}}`);
  css.push(`@keyframes cx{0%,${n(on * 100)}%{transform:translateX(${-walk * S}px);animation-timing-function:steps(${steps},end)}${n(off * 100)}%,100%{transform:translateX(${walk * S}px)}}.cx{animation:cx ${CYC}s linear infinite;animation-delay:${dly(0, CYC)}}`);
  css.push(`@keyframes lg{0%{opacity:1}50%{opacity:0}}.lg0{animation:lg ${BEAT / 2}s step-end infinite;animation-delay:${dly(0, BEAT / 2)}}.lg1{animation:lg ${BEAT / 2}s step-end infinite;animation-delay:${dly(BEAT / 4, BEAT / 2)}}`);
}

// ------------------------------------------------------------------ logo
// Wide geometric capitals on a 2-px module, 15 x 13 modules each, filled with
// a vertical 12-bit gradient: midday sky over a white horizon over the sea.
const LOGO = {
  C: [
    '..#############', '.##############', '###############', '###............', '###............',
    '###............', '###............', '###............', '###............', '###............',
    '###############', '.##############', '..#############',
  ],
  A: [
    '..###########..', '.#############.', '###############', '###.........###', '###.........###',
    '###############', '###############', '###############', '###.........###', '###.........###',
    '###.........###', '###.........###', '###.........###',
  ],
  S: [
    '..#############', '.##############', '###############', '###............', '###............',
    '###############', '###############', '###############', '............###', '............###',
    '###############', '##############.', '#############..',
  ],
  T: [
    '###############', '###############', '###############', '......###......', '......###......',
    '......###......', '......###......', '......###......', '......###......', '......###......',
    '......###......', '......###......', '......###......',
  ],
  W: [
    '###.........###', '###.........###', '###.........###', '###.........###', '###...###...###',
    '###...###...###', '###...###...###', '###...###...###', '###...###...###', '###...###...###',
    '###############', '.#############.', '..###########..',
  ],
  Y: [
    '###.........###', '###.........###', '###.........###', '###.........###', '###.........###',
    '###############', '.#############.', '..###########..', '......###......', '......###......',
    '......###......', '......###......', '......###......',
  ],
};
const MOD = 2;
const LGAP = 2;
const NAME = 'CASTAWAY';
const LROWS = 13 * MOD;
const lset = new Set();
let lw = 0;
const lcells = [];
for (const ch of NAME) {
  LOGO[ch].forEach((row, y) => [...row].forEach((c, x) => { if (c === '#') lcells.push([lw + x, y]); }));
  lw += 15 + LGAP;
}
lw -= LGAP;
const LX = Math.round((VW - lw * MOD) / 2);
for (const [x, y] of lcells) {
  for (let dy = 0; dy < MOD; dy++) for (let dx = 0; dx < MOD; dx++) lset.add(key(LX + x * MOD + dx, LOGO_Y + y * MOD + dy));
}
// one colour per pixel row: warm sky darkening to the horizon line, then sea
const LOGO_RAMP = [
  '#fe8', '#fe8', '#fd6', '#fd6', '#fc5', '#fb4', '#fa4', '#f94', '#e84', '#e75', '#d65', '#c56',
  '#fff', '#cff',
  '#9ef', '#7de', '#6cd', '#5bc', '#4ac', '#39b', '#38a', '#279', '#268', '#257', '#146', '#135',
];
const lrows = new Map();
const lhas = (x, y) => lset.has(key(x, y));
for (const k of lset) {
  const [x, y] = unkey(k);
  let c = LOGO_RAMP[y - LOGO_Y];
  // a lit pixel along every top edge, a dark one along every bottom edge
  if (!lhas(x, y - 1)) c = y - LOGO_Y < 12 ? '#ffe' : '#eff';
  else if (!lhas(x, y + 1)) c = y - LOGO_Y < 12 ? '#a45' : '#024';
  if (!lrows.has(c)) lrows.set(c, new Set());
  lrows.get(c).add(k);
}
// a deep shadow two pixels down and right, and a lit pixel on top edges
const shadow = new Set();
for (const k of lset) {
  const [x, y] = unkey(k);
  for (let d = 1; d <= 2; d++) if (!lhas(x + d, y + d)) shadow.add(key(x + d, y + d));
}
const logoSvg = [
  `<path fill="#213" d="${pathOf(shadow)}"/>`,
  colourPaths(lrows),
].join('');

// ------------------------------------------------------------------ tagline
// 5x7 capitals, white over ice blue, one line every two bars (6 s).
const FONT5 = {
  A: '.###.|#...#|#...#|#####|#...#|#...#|#...#', B: '####.|#...#|#...#|####.|#...#|#...#|####.',
  C: '.###.|#...#|#....|#....|#....|#...#|.###.', D: '####.|#...#|#...#|#...#|#...#|#...#|####.',
  E: '#####|#....|#....|####.|#....|#....|#####', F: '#####|#....|#....|####.|#....|#....|#....',
  G: '.###.|#...#|#....|#.###|#...#|#...#|.####', H: '#...#|#...#|#...#|#####|#...#|#...#|#...#',
  I: '.###.|..#..|..#..|..#..|..#..|..#..|.###.', J: '..###|...#.|...#.|...#.|...#.|#..#.|.##..',
  K: '#...#|#..#.|#.#..|##...|#.#..|#..#.|#...#', L: '#....|#....|#....|#....|#....|#....|#####',
  M: '#...#|##.##|#.#.#|#.#.#|#...#|#...#|#...#', N: '#...#|#...#|##..#|#.#.#|#..##|#...#|#...#',
  O: '.###.|#...#|#...#|#...#|#...#|#...#|.###.', P: '####.|#...#|#...#|####.|#....|#....|#....',
  Q: '.###.|#...#|#...#|#...#|#.#.#|#..#.|.##.#', R: '####.|#...#|#...#|####.|#.#..|#..#.|#...#',
  S: '.####|#....|#....|.###.|....#|....#|####.', T: '#####|..#..|..#..|..#..|..#..|..#..|..#..',
  U: '#...#|#...#|#...#|#...#|#...#|#...#|.###.', V: '#...#|#...#|#...#|#...#|#...#|.#.#.|..#..',
  W: '#...#|#...#|#...#|#.#.#|#.#.#|#.#.#|.#.#.', X: '#...#|#...#|.#.#.|..#..|.#.#.|#...#|#...#',
  Y: '#...#|#...#|.#.#.|..#..|..#..|..#..|..#..', Z: '#####|....#|...#.|..#..|.#...|#....|#####',
  0: '.###.|#...#|#..##|#.#.#|##..#|#...#|.###.', 1: '..#..|.##..|..#..|..#..|..#..|..#..|.###.',
  2: '.###.|#...#|....#|...#.|..#..|.#...|#####', 3: '#####|...#.|..#..|...#.|....#|#...#|.###.',
  4: '...#.|..##.|.#.#.|#..#.|#####|...#.|...#.', 5: '#####|#....|####.|....#|....#|#...#|.###.',
  6: '..##.|.#...|#....|####.|#...#|#...#|.###.', 7: '#####|....#|...#.|..#..|.#...|.#...|.#...',
  8: '.###.|#...#|#...#|.###.|#...#|#...#|.###.', 9: '.###.|#...#|#...#|.####|....#|...#.|.##..',
  '.': '.....|.....|.....|.....|.....|.##..|.##..', ',': '.....|.....|.....|.....|.##..|..#..|.#...',
  ':': '.....|.##..|.##..|.....|.##..|.##..|.....', '-': '.....|.....|.....|.###.|.....|.....|.....',
  "'": '..#..|..#..|.#...|.....|.....|.....|.....', '!': '..#..|..#..|..#..|..#..|..#..|.....|..#..',
  '/': '....#|....#|...#.|..#..|.#...|#....|#....', '?': '.###.|#...#|....#|...#.|..#..|.....|..#..',
  '+': '.....|..#..|..#..|#####|..#..|..#..|.....', '>': '.#...|..#..|...#.|....#|...#.|..#..|.#...',
};
const TAGS = [
  'SHE IDLES. EVERY SO OFTEN, SOMETHING HAPPENS.',
  'A TEN-HOUR LO-FI ISLAND VIDEO. ALWAYS DAYTIME.',
  '29 BOBS AND A COCONUT. NOBODY HAS SAID A WORD.',
  'MORE THAN 90 GAGS, EACH ONE ON THE NEXT BAR.',
  'THE PALM TURNS. THE BOBS ORBIT. SHE NODS.',
  'EVERY SOUND IS SYNTHESIZED FROM CODE.',
  'SOMETHING IS HAPPENING. PLEASE STAY CALM.',
  'A COCONUT WALKS OFF. A HERMIT CRAB IS WEARING IT.',
  'RUN PYTHON TOOLS/SERVE.PY, OPEN 127.0.0.1:8765',
  'DRIFTWOOD BLITTER CO. HAS NOTHING ELSE PLANNED.',
];
const HOLD = 2 * BAR;
const TCYC = HOLD * TAGS.length;
defs.push(`<linearGradient id="tg" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="${7 * S}">${
  ['#fff', '#fff', '#eff', '#cef', '#adf', '#8be', '#69c'].map((c, i) => `<stop offset="${n(i / 7, 4)}" stop-color="${hex(c)}"/><stop offset="${n((i + 1) / 7, 4)}" stop-color="${hex(c)}"/>`).join('')
}</linearGradient>`);
css.push(`@keyframes tl{0%{opacity:1}${n(100 / TAGS.length, 4)}%{opacity:0}100%{opacity:0}}.tl{animation:tl ${TCYC}s step-end infinite}`);
// one symbol per glyph: a navy drop shadow one pixel down and right, then
// the letter in white over ice blue
const glyphs = new Set();
const tagSvg = [];
TAGS.forEach((line, i) => {
  if (line.length > 52) throw new Error(`tagline too long: ${line}`);
  const x0 = Math.round((VW - (line.length * 6 - 1)) / 2);
  const uses = [];
  [...line].forEach((ch, j) => {
    if (ch === ' ') return;
    if (!FONT5[ch]) throw new Error(`no glyph for ${JSON.stringify(ch)}`);
    glyphs.add(ch);
    uses.push(`<use href="#g${ch.codePointAt(0)}" x="${(x0 + j * 6) * S}"/>`);
  });
  css.push(`.t${i}{animation-delay:${dly(-i * HOLD, TCYC)}}`);
  tagSvg.push(`<g class="tl t${i}" transform="translate(0 ${TAG_Y * S})">${uses.join('')}</g>`);
});
for (const ch of glyphs) {
  const set = new Set();
  FONT5[ch].split('|').forEach((row, y) => [...row].forEach((c, x) => { if (c === '#') set.add(key(x, y)); }));
  const sh = new Set();
  for (const k of set) {
    const [x, y] = unkey(k);
    if (!set.has(key(x + 1, y + 1))) sh.add(key(x + 1, y + 1));
  }
  defs.push(`<g id="g${ch.codePointAt(0)}"><path fill="#226" d="${pathOf(sh)}"/><path fill="url(#tg)" d="${pathOf(set)}"/></g>`);
}

// ------------------------------------------------------------------ assemble
css.push('@media (prefers-reduced-motion: reduce){*{animation-play-state:paused!important}}');
const alt = 'CASTAWAY: an Amiga-style bobs and dot-object screen. A chain of blue shaded balls, with a coconut at the tail, loops round a palm made of turning dots while a small woman in cream headphones sits at its foot, nodding.';
const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="${alt}">
<title>${alt}</title>
<style>
svg{shape-rendering:crispEdges}
${css.join('\n')}
</style>
<defs>
<clipPath id="panel"><rect width="${W}" height="${H}" rx="${3 * S}"/></clipPath>
${defs.join('\n')}
</defs>
<rect width="${W}" height="${H}" rx="${3 * S}" fill="#000"/>
<g clip-path="url(#panel)">
${rulesSvg}
<g>${backBobs}</g>
<g>${dotSvg.join('')}</g>
<g>${herSvg}</g>
<g>${crabSvg}</g>
<g>${frontBobs}</g>
<g>${logoSvg}</g>
<g>${tagSvg.join('')}</g>
</g>
</svg>
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
console.log(`${path.relative(process.cwd(), OUT)}  ${(svg.length / 1024).toFixed(1)} KB  (${dots.length} dots, ${NB} bobs)`);
