// "Copper-only screen" README banner for CASTAWAY.
//
//   node examples/castaway/src/33-copper-only-screen_opus_5.5.mjs
//   node examples/castaway/src/33-copper-only-screen_opus_5.5.mjs --at=7.5 --out=some/where.svg
//   node examples/castaway/src/33-copper-only-screen_opus_5.5.mjs --sprite=some/where.svg
//
// Regenerates ../assets/33-copper-only-screen_opus_5.5.svg. Plain Node, no
// deps, deterministic (no clock, no Math.random). --at bakes a head start (in
// seconds) into every animation delay so later frames can be checked without
// waiting; use it only together with --out, never in place. --sprite writes a
// big contact sheet of her sprite and the title letters, for pixel work.
//
// The style: the Amiga "copper-only" screen of 1990 (catalogue entry c64-09).
// The copper is the co-processor that waits for the video beam to reach a
// position and then moves a value into a colour register. Do that on every
// scanline, and several times along each line, and you get a picture made of
// nothing but colour changes: no bitplanes at all. Colour can change on every
// line, but only every few pixels along a line, so the texture is wide and
// short. Each effect sits in its own window with a thin light frame. Copper
// Master (Angels) and Look! No bitplanes (Razor 1911), both October 1990, are
// the credited references; nothing of theirs is copied. The windows, palettes,
// letters, sprite and words here are all drawn and written for this file.
//
// How the SVG does it (the real mechanism, not a picture of it)
//   * Hero window, diagonal bands: 39 columns, each 8 px wide (one copper
//     MOVE along a line), filled with ONE hard-stop gradient of 64 colours
//     (four triangular 16-step ramps: palm green, sand, sea, foam), two
//     scanlines per colour. Each column is offset 4 scanlines from its
//     neighbour, which is what makes the bands diagonal. The whole group then
//     rolls down one scanline per step, 128 steps in 12 s (four bars of the
//     theme at 80 BPM).
//   * SUN window, the diamond: every 8 px x 1 line cell gets a level
//     4 * |column| + |line| from the centre. Cells of one level share a class
//     and the class cycles through a 32-colour palette (step-end), each level
//     one step behind the last, so the rings pulse outward: palette cycling,
//     6 s per cycle, no script.
//   * ISLAND window: a copper sky (one colour per line), a sea of cyan lines
//     whose phase is 1/distance from the horizon so the waves come in with
//     perspective, a sand mound whose edges move only in 4 px steps (the
//     copper's horizontal resolution), and a twisted ribbon for a palm trunk:
//     one rect per line, swayed and twisted by two shared keyframe tracks
//     with a per-line delay, red-tan and grey stripes over the cyan lines.
//   * LANES window, the plaid: vertical bars shaded in chunky 4 px steps,
//     horizontal bars shaded per scanline, sliding in opposite directions;
//     the upper group uses mix-blend-mode:screen so red and green cross to
//     yellow, red and blue to magenta, green and blue to cyan.
//   * The title is eight 16 px wide sprites, one letter each (the Amiga has
//     exactly eight hardware sprites, and CASTAWAY has exactly eight
//     letters), three colours each, recoloured per scanline. She is one more
//     sprite pair further down, nodding once per beat.
//   * prefers-reduced-motion pauses every track where it starts, which is a
//     complete frame: all four effects, the title and every line of text.
//   * Slowest flicker rule: no area changes colour faster than one ramp step
//     per 0.09 s, and every ramp is smooth, so nothing flashes.
// (The .md beside the assets is hand-written, not generated by this script.)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const arg = (name) => {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const T0 = Number(arg('at') || 0);
const OUT = arg('out') ? path.resolve(arg('out')) : path.resolve(here, '../assets/33-copper-only-screen_opus_5.5.svg');
const SPRITE_SHEET = arg('sprite') ? path.resolve(arg('sprite')) : null;

// ------------------------------------------------------------------ screen
// Everything is drawn in virtual Amiga lo-res pixels; the viewBox does the 3x.
const VW = 320;
const VH = 150;
const S = 3;
const BEAT = 0.75; // 80 BPM
const BAR = 4 * BEAT; // 3 s, one bar of the theme

const n = (v, d = 3) => String(+(+v).toFixed(d));
const dly = (s) => `${n(s - T0, 4)}s`;
const mod = (a, m) => ((a % m) + m) % m;

// 12-bit colour helpers: every colour on this screen is one of the 4096.
const nib = (v) => Math.max(0, Math.min(15, Math.round(v))).toString(16);
const c12 = (r, g, b) => `#${nib(r)}${nib(g)}${nib(b)}`;
const p12 = (s) => [...s.slice(1)].map((ch) => parseInt(ch, 16));
const mix = (a, b, t) => {
  const A = p12(a);
  const B = p12(b);
  return c12(...A.map((v, i) => v + (B[i] - v) * t));
};

const defs = [];
const css = [];
const body = [];

// ------------------------------------------------------------------ pixels
const key = (x, y) => `${x},${y}`;
const unkey = (k) => k.split(',').map(Number);
// Merge a pixel set into horizontal runs, stack identical runs, emit a path.
function pathOf(set, ox = 0, oy = 0) {
  const rows = new Map();
  for (const k of set) {
    const [x, y] = unkey(k);
    if (!rows.has(y)) rows.set(y, []);
    rows.get(y).push(x);
  }
  const runs = [];
  for (const [y, xs] of rows) {
    xs.sort((a, b) => a - b);
    let s = xs[0];
    let p = xs[0];
    for (let i = 1; i <= xs.length; i++) {
      if (i < xs.length && xs[i] === p + 1) { p = xs[i]; continue; }
      runs.push([s, p + 1, y]);
      if (i < xs.length) { s = xs[i]; p = xs[i]; }
    }
  }
  runs.sort((a, b) => a[2] - b[2] || a[0] - b[0]);
  const live = new Set(runs.map((r) => `${r[0]},${r[1]},${r[2]}`));
  const out = [];
  for (const r of runs) {
    const k0 = `${r[0]},${r[1]},${r[2]}`;
    if (!live.has(k0)) continue;
    live.delete(k0);
    let h = 1;
    while (live.has(`${r[0]},${r[1]},${r[2] + h}`)) { live.delete(`${r[0]},${r[1]},${r[2] + h}`); h++; }
    out.push(`M${ox + r[0]} ${oy + r[2]}h${r[1] - r[0]}v${h}h${r[0] - r[1]}z`);
  }
  return out.join('');
}
// 4- or 8-neighbour ring around a set.
function ring(set, eight = true) {
  const out = new Set();
  const offs = eight
    ? [[-1, -1], [0, -1], [1, -1], [-1, 0], [1, 0], [-1, 1], [0, 1], [1, 1]]
    : [[0, -1], [-1, 0], [1, 0], [0, 1]];
  for (const k of set) {
    const [x, y] = unkey(k);
    for (const [dx, dy] of offs) {
      const k2 = key(x + dx, y + dy);
      if (!set.has(k2)) out.add(k2);
    }
  }
  return out;
}
// A hard-stop gradient: one colour per step, `len` user units per step.
function stepGradient(id, colours, { vertical = true, len = 1, repeat = false, x0 = 0, units = 'userSpaceOnUse' } = {}) {
  const N = colours.length;
  const stops = [];
  colours.forEach((c, i) => {
    stops.push(`<stop offset="${n(i / N, 5)}" stop-color="${c}"/><stop offset="${n((i + 1) / N, 5)}" stop-color="${c}"/>`);
  });
  const total = N * len;
  const geom = units === 'objectBoundingBox'
    ? (vertical ? 'x1="0" y1="0" x2="0" y2="1"' : 'x1="0" y1="0" x2="1" y2="0"')
    : (vertical ? `x1="0" y1="${x0}" x2="0" y2="${x0 + total}"` : `x1="${x0}" y1="0" x2="${x0 + total}" y2="0"`);
  defs.push(`<linearGradient id="${id}" gradientUnits="${units}" ${geom}${repeat ? ' spreadMethod="repeat"' : ''}>${stops.join('')}</linearGradient>`);
}
// Keyframes that step through a list of values (step-end timing).
function stepFrames(name, values, prop) {
  const N = values.length;
  const fr = values.map((v, i) => `${n((i / N) * 100, 3)}%{${prop}:${v}}`);
  fr.push(`100%{${prop}:${values[0]}}`);
  css.push(`@keyframes ${name}{${fr.join('')}}`);
}

// ------------------------------------------------------------------ small font
// Drawn for this file: plain capitals, six pixels wide and seven high, with
// two-pixel verticals and one-pixel horizontals, 7 px advance (M and W
// borrow the gap column).
const FONT = {
  A: '.####.|##..##|##..##|######|##..##|##..##|##..##', B: '#####.|##..##|##..##|#####.|##..##|##..##|#####.',
  C: '.#####|##....|##....|##....|##....|##....|.#####', D: '####..|##.##.|##..##|##..##|##..##|##.##.|####..',
  E: '######|##....|##....|#####.|##....|##....|######', F: '######|##....|##....|#####.|##....|##....|##....',
  G: '.#####|##....|##....|##.###|##..##|##..##|.#####', H: '##..##|##..##|##..##|######|##..##|##..##|##..##',
  I: '######|..##..|..##..|..##..|..##..|..##..|######', J: '....##|....##|....##|....##|....##|##..##|.####.',
  K: '##..##|##.##.|####..|###...|####..|##.##.|##..##', L: '##....|##....|##....|##....|##....|##....|######',
  M: '##...##|###.###|##.#.##|##.#.##|##...##|##...##|##...##', N: '##..##|###.##|######|##.###|##..##|##..##|##..##',
  O: '.####.|##..##|##..##|##..##|##..##|##..##|.####.', P: '#####.|##..##|##..##|#####.|##....|##....|##....',
  Q: '.####.|##..##|##..##|##..##|##.###|##..##|.###.#', R: '#####.|##..##|##..##|#####.|##.##.|##..##|##..##',
  S: '.#####|##....|##....|.####.|....##|....##|#####.', T: '######|..##..|..##..|..##..|..##..|..##..|..##..',
  U: '##..##|##..##|##..##|##..##|##..##|##..##|.####.', V: '##..##|##..##|##..##|##..##|##..##|.####.|..##..',
  W: '##...##|##...##|##...##|##.#.##|##.#.##|###.###|##...##', X: '##..##|##..##|.####.|..##..|.####.|##..##|##..##',
  Y: '##..##|##..##|##..##|.####.|..##..|..##..|..##..', Z: '######|....##|...##.|..##..|.##...|##....|######',
  0: '.####.|##..##|##.###|######|###.##|##..##|.####.', 1: '..##..|.###..|..##..|..##..|..##..|..##..|######',
  2: '.####.|##..##|....##|..###.|.##...|##....|######', 3: '#####.|....##|....##|.####.|....##|....##|#####.',
  4: '...##.|..###.|.####.|##.##.|######|...##.|...##.', 5: '######|##....|#####.|....##|....##|##..##|.####.',
  6: '.####.|##....|##....|#####.|##..##|##..##|.####.', 7: '######|....##|...##.|..##..|..##..|..##..|..##..',
  8: '.####.|##..##|##..##|.####.|##..##|##..##|.####.', 9: '.####.|##..##|##..##|.#####|....##|....##|.####.',
  '.': '......|......|......|......|......|..##..|..##..', ',': '......|......|......|......|..##..|..##..|.##...',
  '-': '......|......|......|.####.|......|......|......', ':': '......|..##..|..##..|......|..##..|..##..|......',
  '·': '......|......|......|..##..|..##..|......|......', "'": '..##..|..##..|.##...|......|......|......|......',
  '!': '..##..|..##..|..##..|..##..|..##..|......|..##..', '/': '....##|....##|...##.|..##..|.##...|##....|##....',
};
const ADV = 7;
const usedGlyphs = new Set();
function glyphId(ch) {
  if (!FONT[ch]) throw new Error(`no glyph for "${ch}"`);
  usedGlyphs.add(ch);
  return `s${ch.codePointAt(0).toString(36)}`;
}
// <use> elements for a line of small text at virtual (x, y).
function text(str, x, y) {
  const out = [];
  [...str].forEach((ch, i) => {
    if (ch === ' ') return;
    out.push(`<use href="#${glyphId(ch)}" x="${x + i * ADV}" y="${y}"/>`);
  });
  return out.join('');
}
const textW = (str) => str.length * ADV - 1;

// Blue chrome for the small text: one colour per scanline, as the copper
// would recolour a line of text.
stepGradient('chr', ['#cef', '#fff', '#bdf', '#69d', '#47b', '#8be', '#cef'], { len: 1 });
// A paler chrome for text that sits on a copper bar.
stepGradient('chl', ['#fff', '#fff', '#eef', '#cdf', '#bce', '#def', '#fff'], { len: 1 });
// Warm chrome for the crew line.
stepGradient('chw', ['#fe9', '#fff', '#fd8', '#e95', '#c63', '#e96', '#fc9'], { len: 1 });

// ------------------------------------------------------------------ frames
// Thin light frame round an inner rect: lighter top-left, darker bottom-right.
function frame(x, y, w, h) {
  return `<path fill="#dde" d="M${x - 1} ${y - 1}h${w + 2}v1h${-(w + 1)}v${h + 1}h-1z"/>`
    + `<path fill="#889" d="M${x + w} ${y}h1v${h + 1}h${-(w + 1)}v-1h${w}z"/>`;
}
function clip(id, x, y, w, h) {
  defs.push(`<clipPath id="${id}"><rect x="${x}" y="${y}" width="${w}" height="${h}"/></clipPath>`);
}
// A caption tab sitting on a window's top frame line.
function tab(label, x, frameY) {
  const w = textW(label) + 6;
  return `<rect x="${x}" y="${frameY - 4}" width="${w}" height="9" fill="#000"/>`
    + `<path fill="#dde" d="M${x} ${frameY - 4}h1v9h-1zM${x + w - 1} ${frameY - 4}h1v9h-1z"/>`
    + `<g fill="url(#chr)">${text(label, x + 3, frameY - 3)}</g>`;
}

// ------------------------------------------------------------------ layout
const HX = 7, HY = 16, HW = 306, HH = 69; // hero window (inner)
const WY = 103, WH = 42; // bottom windows (inner)
const SUN = { x: 7, w: 78 };
const ISL = { x: 93, w: 134 };
const LAN = { x: 235, w: 78 };

// ================================================================== HERO
// Four triangular ramps of 16 steps, two scanlines per step.
const RAMPS = [
  ['#021', '#2a3', '#bf8'], // palm green
  ['#310', '#b62', '#fd9'], // sand
  ['#014', '#06d', '#9ef'], // sea
  ['#223', '#99b', '#fff'], // foam
];
const BAND = [];
for (const [d, m, l] of RAMPS) {
  for (let k = 0; k < 16; k++) {
    const u = k < 8 ? k / 7 : (15 - k) / 7;
    BAND.push(u < 0.6 ? mix(d, m, u / 0.6) : mix(m, l, (u - 0.6) / 0.4));
  }
}
const E = 2; // scanlines per palette step
const P = BAND.length * E; // 128 scanlines per period
const SHIFT = 4; // scanlines of phase per 8 px column: the diagonal
stepGradient('gb', BAND, { len: E, repeat: true });
defs.push(`<rect id="hc" width="8" height="${HH + 2 * P}" fill="url(#gb)"/>`);
clip('ch', HX, HY, HW, HH);
{
  const cols = [];
  for (let c = 0; c * 8 < HW; c++) {
    cols.push(`<use href="#hc" x="${HX + c * 8}" y="${HY - P - mod(c * SHIFT, P)}"/>`);
  }
  css.push(`@keyframes roll{from{transform:translateY(0)}to{transform:translateY(${P}px)}}`);
  css.push(`.roll{animation:roll ${4 * BAR}s steps(${P}) infinite;animation-delay:${dly(0)}}`);
  body.push(`<g clip-path="url(#ch)"><g class="roll">${cols.join('')}</g></g>`);
}

// ------------------------------------------------------------------ title
// Eight sprites, 16 px wide: 14 px letter + 1 px outline each side, 28 px
// tall + outline + a 2 px shadow below = 32 lines. Three colours per sprite:
// outline, fill, inner shade, the last two recoloured per scanline.
const LW = 14, LH = 28;
function letterMask(ops) {
  const m = new Set();
  for (const op of ops) {
    const [kind, x, y, w = 1, h = 1] = op;
    for (let yy = y; yy < y + h; yy++) for (let xx = x; xx < x + w; xx++) {
      if (xx < 0 || yy < 0 || xx >= LW || yy >= LH) continue;
      if (kind === '+') m.add(key(xx, yy)); else m.delete(key(xx, yy));
    }
  }
  return m;
}
const LETTERS = {
  C: [['+', 0, 0, 14, 4], ['+', 0, 24, 14, 4], ['+', 0, 0, 4, 28], ['+', 10, 4, 4, 3], ['+', 10, 21, 4, 3],
    ['-', 0, 0], ['-', 0, 27], ['-', 13, 0], ['-', 13, 27]],
  A: [['+', 0, 0, 14, 4], ['+', 0, 0, 4, 28], ['+', 10, 0, 4, 28], ['+', 4, 13, 6, 4], ['-', 0, 0], ['-', 13, 0]],
  S: [['+', 0, 0, 14, 4], ['+', 0, 0, 4, 16], ['+', 0, 12, 14, 4], ['+', 10, 12, 4, 16], ['+', 0, 24, 14, 4],
    ['+', 10, 4, 4, 3], ['+', 0, 21, 4, 3], ['-', 0, 0], ['-', 13, 0], ['-', 0, 27], ['-', 13, 27]],
  T: [['+', 0, 0, 14, 4], ['+', 5, 0, 4, 28]],
  W: [['+', 0, 0, 4, 28], ['+', 10, 0, 4, 28], ['+', 5, 10, 4, 18], ['+', 0, 24, 14, 4], ['-', 0, 27], ['-', 13, 27],
    ['-', 4, 24, 1, 1], ['-', 9, 24, 1, 1]],
  Y: [['+', 0, 0, 4, 12], ['+', 10, 0, 4, 12], ['+', 0, 10, 14, 4], ['+', 5, 10, 4, 18], ['-', 0, 13], ['-', 13, 13]],
};
const TITLE = 'CASTAWAY';
const TITLE_PITCH = 21;
const TX = HX + Math.floor((HW - (7 * TITLE_PITCH + 16)) / 2);
const TY = HY + 7;
// Per-scanline sprite colours (the copper rewriting sprite colour registers).
const FILL_ROWS = [];
const SHADE_ROWS = [];
for (let y = 0; y < 32; y++) {
  const t = Math.max(0, Math.min(1, (y - 1) / 29));
  FILL_ROWS.push(t < 0.5 ? mix('#fff', '#eef', t / 0.5) : mix('#eef', '#bdf', (t - 0.5) / 0.5));
  SHADE_ROWS.push(mix('#aac', '#58a', t));
}
stepGradient('tf', FILL_ROWS, { len: 1 });
stepGradient('ts', SHADE_ROWS, { len: 1 });
const letterSets = {};
for (const ch of Object.keys(LETTERS)) {
  const inner = new Set([...letterMask(LETTERS[ch])].map((k) => { const [x, y] = unkey(k); return key(x + 1, y + 1); }));
  const outline = ring(inner, true);
  const solid = new Set([...inner, ...outline]);
  const shadow = new Set();
  for (const k of solid) {
    const [x, y] = unkey(k);
    for (const dy of [1, 2]) if (!solid.has(key(x, y + dy))) shadow.add(key(x, y + dy));
  }
  const dark = new Set([...outline, ...shadow]);
  const shade = new Set();
  for (const k of inner) {
    const [x, y] = unkey(k);
    if (!inner.has(key(x + 1, y)) || !inner.has(key(x, y + 1))) shade.add(k);
  }
  const fill = new Set([...inner].filter((k) => !shade.has(k)));
  letterSets[ch] = { dark, shade, fill };
  defs.push(`<g id="L${ch}"><path fill="#102" d="${pathOf(dark)}"/><path fill="url(#ts)" d="${pathOf(shade)}"/><path fill="url(#tf)" d="${pathOf(fill)}"/></g>`);
}
body.push(`<g>${[...TITLE].map((ch, i) => `<use href="#L${ch}" x="${TX + i * TITLE_PITCH}" y="${TY}"/>`).join('')}</g>`);

// ------------------------------------------------------------------ WAIT WAIT WAIT MOVE
// The copper knows WAIT and MOVE. So does she. A copper bar steps along the
// words, one per beat: three beats waiting, one beat moving.
{
  const words = ['WAIT', 'WAIT', 'WAIT', 'MOVE'];
  const line = words.join(' ');
  const w = textW(line);
  const x0 = HX + Math.floor((HW - w) / 2);
  const y0 = TY + 32 + 6;
  stepGradient('bw', ['#002', '#014', '#127', '#239', '#34b', '#239', '#127', '#014', '#002'], { units: 'objectBoundingBox' });
  stepGradient('bm', ['#200', '#411', '#722', '#a33', '#b43', '#a33', '#722', '#411', '#200'], { units: 'objectBoundingBox' });
  const out = [`<rect x="${x0 - 5}" y="${y0 - 2}" width="${w + 10}" height="11" fill="#000"/>`];
  css.push('@keyframes on{0%{opacity:1}25%{opacity:0}100%{opacity:0}}');
  css.push(`.on{animation:on ${BAR}s step-end infinite}`);
  words.forEach((wd, i) => {
    const d = -mod(BAR - i * BEAT, BAR);
    out.push(`<rect class="on" style="animation-delay:${dly(d)}" x="${x0 + i * 5 * ADV - 3}" y="${y0 - 1}" width="${4 * ADV + 5}" height="9" fill="url(#${i === 3 ? 'bm' : 'bw'})"/>`);
  });
  out.push(`<g fill="url(#chl)">${text(line, x0, y0)}</g>`);
  body.push(out.join(''));
}
body.push(frame(HX, HY, HW, HH));

// ------------------------------------------------------------------ top strip
body.push(`<g fill="url(#chw)">${text('MID-LINE MOVERS PRESENTS', HX, 4)}</g>`);
body.push(`<g fill="url(#chr)">${text('ZERO BITPLANES', HX + HW - textW('ZERO BITPLANES'), 4)}</g>`);

// Rainbow copper lines, 8 px cells cycling through 16 hues.
{
  const hues = [];
  for (let i = 0; i < 16; i++) {
    const h = i / 16;
    const f = (o) => { const v = Math.abs(mod(h * 6 + o, 6) - 3) - 1; return Math.max(0, Math.min(1, v)) * 15; };
    hues.push(c12(f(0), f(4), f(2)));
  }
  stepGradient('rb', hues, { vertical: false, len: 8, repeat: true });
  clip('crb', HX - 1, 0, HW + 2, VH);
  css.push('@keyframes rbl{from{transform:translateX(0)}to{transform:translateX(-128px)}}');
  css.push('@keyframes rbr{from{transform:translateX(-128px)}to{transform:translateX(0)}}');
  css.push(`.rbl{animation:rbl ${BAR}s steps(16) infinite;animation-delay:${dly(0)}}.rbr{animation:rbr ${BAR}s steps(16) infinite;animation-delay:${dly(0)}}`);
  body.push(`<g clip-path="url(#crb)"><g class="rbl"><rect x="${HX - 1}" y="12" width="${HW + 2 + 128}" height="1" fill="url(#rb)"/></g>`
    + `<g class="rbr"><rect x="${HX - 1}" y="147" width="${HW + 2 + 128}" height="1" fill="url(#rb)"/></g></g>`);
}

// ------------------------------------------------------------------ tagline
{
  const tag = 'A TEN-HOUR LO-FI ISLAND. SHE MOSTLY WAITS.';
  body.push(`<g fill="url(#chr)">${text(tag, HX + Math.floor((HW - textW(tag)) / 2), 89)}</g>`);
}

// ================================================================== SUN
// The diamond: level = 4 * |cell column| + |line| from the centre.
{
  const N = 32;
  const STEP = 6 / N; // 6 s per cycle
  // Spatial order, core to edge: a blue core, white, yellow, orange, red,
  // then dark, and round again. Cyclic, smooth all the way round.
  const SP = ['#00c', '#02d', '#04e', '#26f', '#48f', '#6af', '#8cf', '#aef', '#dff', '#ffe', '#ffb', '#ff8',
    '#ff4', '#fe0', '#fc0', '#fa0', '#f80', '#f60', '#f40', '#f20', '#e00', '#c00', '#a00', '#800',
    '#600', '#400', '#200', '#100', '#001', '#003', '#006', '#009'];
  const PAL = SP.map((_, j) => SP[mod(N - j, N)]);
  stepFrames('dc', PAL, 'fill');
  const cx = SUN.x + SUN.w / 2; // 46
  const cy = WY + WH / 2; // 124
  const byClass = Array.from({ length: N }, () => new Set());
  for (let y = WY; y < WY + WH; y++) {
    const dy = Math.floor(Math.abs(y + 0.5 - cy));
    for (let x = SUN.x; x < SUN.x + SUN.w; x++) {
      const dx = Math.floor(Math.abs(x + 0.5 - cx) / 8 + 0.5); // centre cell straddles the axis
      const L = 4 * dx + dy;
      byClass[mod(L, N)].add(key(x, y));
    }
  }
  const out = [];
  byClass.forEach((set, k) => {
    if (!set.size) return;
    css.push(`.d${k}{animation:dc 6s step-end infinite;animation-delay:${dly(-mod(N - k, N) * STEP)}}`);
    out.push(`<path class="d${k}" fill="${SP[k]}" d="${pathOf(set)}"/>`);
  });
  body.push(`<g>${out.join('')}</g>`);
  body.push(frame(SUN.x, WY, SUN.w, WH));
}

// ------------------------------------------------------------------ her sprite
const HER_COL = {
  K: '#211', h: '#842', H: '#521', p: '#fec', P: '#ca8', s: '#fca', S: '#d97', e: '#421',
  t: '#f76', T: '#c54', c: '#edb', C: '#ba8',
};
const HER_HEAD = [
  '..ppppp..',
  '.phhhhhp.',
  '.hhhhhhh.',
  'phssssshp',
  'PhseseshP',
  '.hsssssh.',
  '..sssss.H',
  '...sss.HH',
];
const HER_BODY = [
  '..tssst..',
  '.sttttts.',
  '.sttttts.',
  '.sttttts.',
  '.sTTTTTs.',
  '.scccccs.',
  '.scccccs.',
  '..ccCcc..',
  '..cc.cc..',
  '..ss.ss..',
  '..ss.ss..',
  '..SS.SS..',
  '.sss.sss.',
];
let HER_SVG = '';
function spriteParts(rows, oy, cutBelow = Infinity) {
  const byCol = new Map();
  const solid = new Set();
  rows.forEach((row, y) => [...row].forEach((ch, x) => {
    if (ch === '.') return;
    const k = key(x + 1, y + oy);
    solid.add(k);
    if (!byCol.has(ch)) byCol.set(ch, new Set());
    byCol.get(ch).add(k);
  }));
  const outline = new Set([...ring(solid, false)].filter((k) => unkey(k)[1] < cutBelow));
  const parts = [`<path fill="${HER_COL.K}" d="${pathOf(outline)}"/>`];
  for (const [ch, set] of byCol) parts.push(`<path fill="${HER_COL[ch]}" d="${pathOf(set)}"/>`);
  return parts.join('');
}
{
  const headTop = 1;
  const bodyTop = headTop + HER_HEAD.length;
  css.push('@keyframes nod{0%{transform:translateY(1px)}25%{transform:translateY(0)}}');
  css.push(`.nod{animation:nod ${BEAT}s step-end infinite;animation-delay:${dly(0)}}`);
  HER_SVG = `${spriteParts(HER_BODY, bodyTop)}<g class="nod">${spriteParts(HER_HEAD, headTop, bodyTop)}</g>`;
}

// ================================================================== ISLAND
{
  const X = ISL.x, W = ISL.w;
  clip('ci', X, WY, W, WH);
  const out = [];
  // Sky: one colour per line, deep at the top, pale at the horizon.
  const SKY_ROWS = 16;
  for (let r = 0; r < SKY_ROWS; r++) {
    const t = r / (SKY_ROWS - 1);
    const c = t < 0.55 ? mix('#38c', '#7be', t / 0.55) : mix('#7be', '#cef', (t - 0.55) / 0.45);
    out.push(`<rect x="${X}" y="${WY + r}" width="${W}" height="1" fill="${c}"/>`);
  }
  // A few clouds: copper can only start and stop a colour at 4 px steps.
  const cloud = new Set();
  const cloudRuns = [[12, 3, 16], [8, 4, 28], [4, 5, 36], [60, 6, 12], [56, 7, 24], [108, 2, 12], [104, 3, 20]];
  for (const [x, y, w] of cloudRuns) for (let i = 0; i < w; i++) cloud.add(key(X + x + i, WY + y));
  out.push(`<path fill="#eff" d="${pathOf(cloud)}"/>`);
  // Sea: cyan lines whose phase is 1/distance from the horizon, palette-cycled,
  // so each crest travels down the screen and spreads out as it comes in.
  const SEA = ['#5df', '#3bf', '#29d', '#17b', '#06a', '#059', '#048', '#048',
    '#059', '#059', '#06a', '#06a', '#17b', '#17b', '#29d', '#3bf'];
  const NS = SEA.length;
  stepFrames('sea', SEA, 'fill');
  css.push(`.sea{animation:sea ${BAR}s step-end infinite}`);
  for (let r = SKY_ROWS; r < WH; r++) {
    const z = 30 / (r - SKY_ROWS + 2);
    const ph = mod(z, NS);
    const k = Math.floor(ph);
    out.push(`<rect class="sea" style="animation-delay:${dly(-mod(NS - ph, NS) * (BAR / NS))}" x="${X}" y="${WY + r}" width="${W}" height="1" fill="${SEA[mod(NS - k, NS) % NS]}"/>`);
  }
  out.push(`<rect x="${X}" y="${WY + SKY_ROWS}" width="${W}" height="1" fill="#dff"/>`);
  // Glints: one short streak per line moving at its own speed (a copper
  // starfield, in daylight).
  css.push(`@keyframes gl{from{transform:translateX(0)}to{transform:translateX(-${W}px)}}`);
  const glints = [[18, 30, 12], [21, 90, 6], [25, 50, 12], [29, 116, 6], [34, 20, 6], [38, 74, 6], [40, 104, 12]];
  for (const [r, x, dur] of glints) {
    const steps = Math.round(W / 2);
    out.push(`<g style="animation:gl ${dur}s steps(${steps}) infinite;animation-delay:${dly(-(x / W) * dur)}"><rect x="${X + 60}" y="${WY + r}" width="4" height="1" fill="#eff"/><rect x="${X + 60 + W}" y="${WY + r}" width="4" height="1" fill="#eff"/></g>`);
  }
  // Island: a sand mound, edges in 4 px steps, one sand colour per line,
  // foam at both ends of every line flipping on the half bar.
  const IC = X + 76; // centre
  const ITOP = 31;
  const sandRows = [];
  for (let r = ITOP; r < WH; r++) {
    const half = 4 * Math.round((22 + (r - ITOP) * 2.2) / 4);
    sandRows.push([r, IC - half, IC + half]);
  }
  sandRows.forEach(([r, a, b], i) => {
    const t = i / (sandRows.length - 1);
    const c = t < 0.4 ? mix('#fe9', '#ec8', t / 0.4) : mix('#ec8', '#b96', (t - 0.4) / 0.6);
    out.push(`<rect x="${a}" y="${WY + r}" width="${b - a}" height="1" fill="${c}"/>`);
  });
  css.push('@keyframes foam{0%{fill:#fff}50%{fill:#9ef}}');
  css.push(`.fo{animation:foam ${2 * BEAT}s step-end infinite}`);
  const foamA = new Set();
  const foamB = new Set();
  sandRows.forEach(([r, a, b], i) => {
    const set = i % 2 ? foamB : foamA;
    for (let x = 0; x < 4; x++) { set.add(key(a - 4 + x, WY + r)); set.add(key(b + x, WY + r)); }
  });
  out.push(`<path class="fo" style="animation-delay:${dly(0)}" fill="#fff" d="${pathOf(foamA)}"/>`);
  out.push(`<path class="fo" style="animation-delay:${dly(-BEAT)}" fill="#9ef" d="${pathOf(foamB)}"/>`);

  // The raft: four logs, bobbing a line on the half bar.
  {
    const rx = IC - 64;
    const logs = [];
    for (let i = 0; i < 5; i++) {
      logs.push(`<rect x="${rx + i * 4}" y="${WY + 34}" width="4" height="1" fill="${i % 2 ? '#b85' : '#ca6'}"/>`);
      logs.push(`<rect x="${rx + i * 4}" y="${WY + 35}" width="4" height="2" fill="${i % 2 ? '#753' : '#864'}"/>`);
    }
    logs.push(`<rect x="${rx - 2}" y="${WY + 37}" width="24" height="1" fill="#cff"/>`);
    css.push('@keyframes bob{0%{transform:translateY(0)}50%{transform:translateY(1px)}}');
    css.push(`.bob{animation:bob ${BAR}s step-end infinite;animation-delay:${dly(0)}}`);
    out.push(`<g class="bob">${logs.join('')}</g>`);
  }

  // Palm: a twisted ribbon, one rect per line, red-tan and grey stripes.
  const PB = 31; // base line (window-local)
  const PT = 7; // top line
  const PX = IC + 20; // base x
  const TWIST_T = BAR;
  const SWAY_T = 2 * BAR;
  const TS = 16;
  const swayVals = [];
  const twistVals = [];
  for (let i = 0; i < 24; i++) swayVals.push(`translateX(${n(Math.sin((2 * Math.PI * i) / 24), 3)}px)`);
  for (let i = 0; i < TS; i++) twistVals.push(`scaleX(${n(0.35 + 0.65 * Math.abs(Math.cos((Math.PI * i) / TS)), 3)})`);
  stepFrames('sway', swayVals, 'transform');
  stepFrames('twist', twistVals, 'transform');
  css.push(`.sw{animation:sway ${SWAY_T}s step-end infinite}.tw{animation:twist ${TWIST_T}s step-end infinite}`);
  const palm = [];
  const rows = PB - PT + 1;
  const topInfo = {};
  for (let r = PT; r <= PB; r++) {
    const u = (PB - r) / (rows - 1); // 0 at base, 1 at top
    const cx = PX + 9 * Math.pow(u, 1.7) - 2 * u; // a gentle curve to the right
    const wb = 7 - 2.5 * u;
    const amp = Math.max(0.15, 2.6 * u * u);
    const swayD = -mod((u * 0.35) * SWAY_T, SWAY_T);
    const twistD = -mod(((PB - r) * 0.07) * TWIST_T, TWIST_T);
    const stripe = Math.floor((PB - r) / 2) % 2 ? '#a98' : '#c64';
    palm.push(`<g transform="translate(${n(cx, 2)} ${WY + r}) scale(${n(amp, 3)} 1)"><g class="sw" style="animation-delay:${dly(swayD)}"><g transform="scale(${n(1 / amp, 3)} 1)">`
      + `<rect class="tw" style="animation-delay:${dly(twistD)}" x="${n(-wb / 2, 2)}" y="0" width="${n(wb, 2)}" height="1" fill="${stripe}"/></g></g></g>`);
    if (r === PT) Object.assign(topInfo, { cx, amp, swayD });
  }
  // Crown: green copper runs drooping both ways, one green per line, plus two
  // coconuts. It sways with the top of the trunk.
  const crown = [
    [-5, [[-2, 3]]],
    [-4, [[-7, -1], [1, 8]]],
    [-3, [[-12, -5], [-1, 2], [5, 13]]],
    [-2, [[-16, -9], [-4, 4], [9, 17]]],
    [-1, [[-20, -13], [-7, 7], [13, 21]]],
    [0, [[-23, -17], [-10, -4], [4, 10], [17, 24]]],
    [1, [[-25, -21], [-13, -8], [8, 14], [21, 26]]],
    [2, [[-26, -23], [-15, -12], [12, 16], [23, 27]]],
    [3, [[-27, -25], [-16, -14], [14, 17], [25, 28]]],
    [4, [[-27, -26], [16, 17], [26, 28]]],
  ];
  const GREENS = { '-5': '#ae6', '-4': '#9e5', '-3': '#8d4', '-2': '#7c4', '-1': '#6c3', 0: '#5b3', 1: '#4a2', 2: '#392', 3: '#381', 4: '#271' };
  const crownParts = [];
  for (const [dy, runs] of crown) {
    for (const [a, b] of runs) crownParts.push(`<rect x="${a}" y="${dy}" width="${b - a}" height="1" fill="${GREENS[dy]}"/>`);
  }
  crownParts.push('<rect x="-4" y="1" width="3" height="2" fill="#753"/><rect x="1" y="1" width="3" height="2" fill="#642"/><rect x="-2" y="3" width="3" height="2" fill="#531"/>');
  const { cx: tcx, amp: tamp, swayD: tsd } = topInfo;
  palm.push(`<g transform="translate(${n(tcx, 2)} ${WY + PT}) scale(${n(tamp, 3)} 1)"><g class="sw" style="animation-delay:${dly(tsd)}"><g transform="scale(${n(1 / tamp, 3)} 1)">${crownParts.join('')}</g></g></g>`);
  out.push(palm.join(''));

  // Her: a sprite pair (15 colours), standing on the sand, nodding on every
  // beat. Coral tank top, cream shorts, cream headphones, brown hair in a low
  // bun, bare feet. Eyes closed: she is listening.
  out.push(`<g transform="translate(${IC - 18} ${WY + ITOP - 21})">${HER_SVG}</g>`);
  body.push(`<g clip-path="url(#ci)">${out.join('')}</g>`);
  body.push(frame(X, WY, W, WH));
}

// ================================================================== LANES
{
  const X = LAN.x, W = LAN.w;
  clip('cl', X, WY, W, WH);
  // Vertical bars: shaded across in chunky 4 px steps (mid-line moves).
  const VB = {
    r: ['#300', '#900', '#f22', '#f88', '#f22', '#900', '#300'],
    g: ['#030', '#090', '#2f2', '#8f8', '#2f2', '#090', '#030'],
    b: ['#003', '#00a', '#22f', '#88f', '#22f', '#00a', '#003'],
  };
  for (const [k, cols] of Object.entries(VB)) stepGradient(`v${k}`, cols, { vertical: false, units: 'objectBoundingBox' });
  // Horizontal bars: shaded per scanline, 13 lines each.
  const ramp = (hi, lo) => Array.from({ length: 13 }, (_, i) => {
    const u = 1 - Math.abs(i - 6) / 6;
    return u < 0.7 ? mix(lo, hi, u / 0.7) : mix(hi, '#fff', ((u - 0.7) / 0.3) * 0.45);
  });
  stepGradient('hr', ramp('#f00', '#100'), { units: 'objectBoundingBox' });
  stepGradient('hg', ramp('#0f0', '#010'), { units: 'objectBoundingBox' });
  stepGradient('hb', ramp('#00f', '#001'), { units: 'objectBoundingBox' });
  const VP = 84; // period of three vertical bars
  const HP = 42; // period of three horizontal bars
  const vbars = [];
  for (let i = 0; i < 7; i++) {
    const kind = ['r', 'g', 'b'][i % 3];
    vbars.push(`<rect x="${X - VP + i * 28 + 2}" y="${WY}" width="28" height="${WH}" fill="url(#v${kind})"/>`);
  }
  const hbars = [];
  for (let i = 0; i < 6; i++) {
    const kind = ['g', 'b', 'r'][i % 3];
    hbars.push(`<rect x="${X}" y="${WY + i * 14}" width="${W}" height="13" fill="url(#h${kind})"/>`);
  }
  css.push(`@keyframes pv{from{transform:translateX(0)}to{transform:translateX(${VP}px)}}`);
  css.push(`@keyframes ph{from{transform:translateY(0)}to{transform:translateY(-${HP}px)}}`);
  css.push(`.pv{animation:pv ${2 * BAR}s steps(${VP / 4}) infinite;animation-delay:${dly(0)}}.ph{animation:ph ${2 * BAR}s steps(${HP}) infinite;animation-delay:${dly(0)}}`);
  css.push('.scr{mix-blend-mode:screen}');
  body.push(`<g clip-path="url(#cl)" style="isolation:isolate"><rect x="${X}" y="${WY}" width="${W}" height="${WH}" fill="#000"/>`
    + `<g class="pv">${vbars.join('')}</g><g class="scr"><g class="ph">${hbars.join('')}</g></g></g>`);
  body.push(frame(X, WY, W, WH));
}

// ------------------------------------------------------------------ tabs
body.push(tab('SUN', SUN.x + 4, WY - 1));
body.push(tab('ISLAND', ISL.x + 4, WY - 1));
body.push(tab('LANES', LAN.x + 4, WY - 1));

// ------------------------------------------------------------------ glyphs
for (const ch of usedGlyphs) {
  const set = new Set();
  FONT[ch].split('|').forEach((row, y) => [...row].forEach((c, x) => { if (c === '#') set.add(key(x, y)); }));
  defs.push(`<path id="${glyphId(ch)}" d="${pathOf(set)}"/>`);
}

css.push('@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}');

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${VW} ${VH}" width="${VW * S}" height="${VH * S}" shape-rendering="crispEdges">
<title>CASTAWAY: a copper-only screen. One island, ten hours, no bitplanes.</title>
<style>${css.join('')}</style>
<defs>${defs.join('')}</defs>
<rect width="${VW}" height="${VH}" rx="4" fill="#000"/>
${body.join('\n')}
</svg>
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
console.log(`wrote ${path.relative(process.cwd(), OUT)} (${(svg.length / 1024).toFixed(1)} KB)`);

// ------------------------------------------------------------------ contact sheet
if (SPRITE_SHEET) {
  const Z = 12;
  const cells = [];
  const herSvg = `<g transform="scale(${Z})">${HER_SVG}</g>`;
  cells.push(herSvg);
  [...'CASTWY'].forEach((ch, i) => cells.push(`<g transform="translate(${(14 + i * 18) * Z} 0) scale(${Z})"><use href="#L${ch}" x="1" y="1"/></g>`));
  const sheet = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${130 * Z} ${36 * Z}" width="${130 * Z}" height="${36 * Z}" shape-rendering="crispEdges"><style>${css.join('')}</style><defs>${defs.join('')}</defs><rect width="100%" height="100%" fill="#7be"/>${cells.join('')}</svg>`;
  fs.writeFileSync(SPRITE_SHEET, sheet);
  console.log(`wrote ${SPRITE_SHEET}`);
}
