// Shared drawing and output helpers for the README.NFO candidates. Original 5x7 glyphs,
// inline geometry and CSS animation only: no fonts, scripts or external SVG resources.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DRAWS = ['draw.json', 'draw-2.json'].map(file => JSON.parse(fs.readFileSync(path.join(DIR, file), 'utf8')));
export const DRAW = { project: 'README.NFO', options: DRAWS.flatMap(draw => draw.options) };
export const INFO = Object.freeze({ name: 'README.NFO', styles: 152, families: 13, candidates: DRAW.options.length,
  tagline: 'RETRO HEADERS / TEXT + SVG', license: 'MIT' });
export const esc = (value) => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
export const option = (number) => {
  const result = DRAW.options.find((pick) => pick.number === number);
  if (!result) throw new Error(`Unknown candidate ${number}`);
  return result;
};

const FONT = {
  A:[14,17,17,31,17,17,17], B:[30,17,17,30,17,17,30], C:[15,16,16,16,16,16,15],
  D:[30,17,17,17,17,17,30], E:[31,16,16,30,16,16,31], F:[31,16,16,30,16,16,16],
  G:[15,16,16,23,17,17,15], H:[17,17,17,31,17,17,17], I:[31,4,4,4,4,4,31],
  J:[7,2,2,2,18,18,12], K:[17,18,20,24,20,18,17], L:[16,16,16,16,16,16,31],
  M:[17,27,21,21,17,17,17], N:[17,25,25,21,19,19,17], O:[14,17,17,17,17,17,14],
  P:[30,17,17,30,16,16,16], Q:[14,17,17,17,21,18,13], R:[30,17,17,30,20,18,17],
  S:[15,16,16,14,1,1,30], T:[31,4,4,4,4,4,4], U:[17,17,17,17,17,17,14],
  V:[17,17,17,17,17,10,4], W:[17,17,17,21,21,21,10], X:[17,17,10,4,10,17,17],
  Y:[17,17,10,4,4,4,4], Z:[31,1,2,4,8,16,31],
  '0':[14,17,19,21,25,17,14], '1':[4,12,4,4,4,4,14], '2':[14,17,1,2,4,8,31],
  '3':[30,1,1,14,1,1,30], '4':[2,6,10,18,31,2,2], '5':[31,16,16,30,1,1,30],
  '6':[14,16,16,30,17,17,14], '7':[31,1,2,4,8,8,8], '8':[14,17,17,14,17,17,14],
  '9':[14,17,17,15,1,1,14], '.':[0,0,0,0,0,12,12], ',':[0,0,0,0,0,12,8],
  ':':[0,12,12,0,12,12,0], ';':[0,12,12,0,12,12,8], '-':[0,0,0,31,0,0,0],
  '_':[0,0,0,0,0,0,31], '/':[1,2,2,4,8,8,16], '\\':[16,8,8,4,2,2,1],
  '+':[0,4,4,31,4,4,0], '=':[0,0,31,0,31,0,0], '>':[16,8,4,2,4,8,16],
  '<':[1,2,4,8,4,2,1], '[':[14,8,8,8,8,8,14], ']':[14,2,2,2,2,2,14],
  '(':[2,4,8,8,8,4,2], ')':[8,4,2,2,2,4,8], '!':[4,4,4,4,4,0,4],
  '?':[14,17,1,2,4,0,4], '#':[10,31,10,10,31,10,0], '*':[0,21,14,31,14,21,0],
  '|':[4,4,4,4,4,4,4], '%':[25,25,2,4,8,19,19], ' ':[0,0,0,0,0,0,0],
};
export const width = (text, scale = 2) => Math.max(0, String(text).length * 6 - 1) * scale;
export function px(text, x, y, scale = 2, fill = '#ffffff', attrs = '') {
  let d = '';
  for (const [index, character] of [...String(text).toUpperCase()].entries()) {
    const glyph = FONT[character] || FONT['?'];
    for (let row = 0; row < 7; row++) for (let col = 0; col < 5; col++) {
      if (glyph[row] & (1 << (4-col))) d += `M${index*6+col} ${row}h1v1h-1z`;
    }
  }
  return `<g transform="translate(${x} ${y}) scale(${scale})" ${attrs}><path d="${d}" fill="${fill}"/></g>`;
}
export const center = (text, y, scale = 4, fill = '#ffffff', canvas = 960, attrs = '') => px(text, (canvas-width(text,scale))/2, y, scale, fill, attrs);
export function svg({ width: w = 960, height: h = 360, background = '#080e18', defs = '', css = '', body, title = INFO.name, description = '' }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="title desc">
<title id="title">${esc(title)}</title><desc id="desc">${esc(description)}</desc>
<defs>${defs}</defs><style>${css}\n@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}</style>
<rect width="${w}" height="${h}" fill="${background}"/>${body}</svg>\n`;
}

export function writeHeader(number, { image, markdown, alt, summary }) {
  const pick = option(number);
  const padded = String(number).padStart(2,'0');
  fs.mkdirSync(path.join(DIR,'assets'),{recursive:true});
  if (image) fs.writeFileSync(path.join(DIR,'assets',`${pick.slug}.svg`),image);
  const header = markdown ?? [
    '<p align="center">',
    `  <img src="assets/${pick.slug}.svg" width="100%" alt="${esc(alt || summary)}">`,
    '</p>', '',
    '<p align="center"><b>README.NFO</b> — retro headers for your next repository.<br>',
    '152 styles, thirteen families, text art and animated SVG. Pick a look. Make it yours.</p>', '',
    '<p align="center"><a href="../../styles/INDEX.md">Style catalogue</a> · <a href="../README.md">Example galleries</a> · <a href="../../LICENSE">MIT licence</a></p>',
  ].join('\n');
  const body = [
    `<!-- README.NFO candidate ${padded}; generated by src/${pick.slug}.mjs. -->`, '', header, '',
    `> **Candidate ${padded}** · [${pick.id}](../../styles/${pick.family}.md#${pick.id}) · ${summary}`, '',
    `[Generator](src/${pick.slug}.mjs) · [All candidates](README.md)`, '',
  ].join('\n');
  fs.writeFileSync(path.join(DIR,`${pick.slug}.md`),body);
  console.log(`wrote candidate ${padded}: ${pick.slug}`);
}
