// Amiga demoscene-intro ("cracktro" style) README banner for ULTRA-SATISFACTORY.
//
//   node examples/ultra-satisfactory/src/02-amiga-cracktro_opus_5.5.mjs
//
// Regenerates ../assets/02-amiga-cracktro_opus_5.5.svg (the banner) and
// ../assets/02-amiga-cracktro_opus_5.5-rule.svg (a conveyor-belt divider).
// Plain Node, no deps, deterministic (seeded PRNG, no clock). Everything is
// drawn on a 320x168 "lowres" pixel grid: two rows of chrome logo, copper
// bars, parallax stars, a distant factory skyline, a production line (SMELTER
// -> CONSTRUCTOR -> ASSEMBLER -> Space Elevator), the hex-cog emblem and a sine
// scroller. All lettering comes
// from the bitmap fonts below, so no viewer ever sees a fallback system font.
// All art is original: generic pixel items and machines, no game assets.
// (The .md beside the assets is hand-edited, not generated by this script.)
//
// Loop maths
//   Scroller: moves at SPEED px/s through a stationary sine of WAVE px. A
//   character at screen x has y = AMP*sin(2*pi*x/WAVE), so every character
//   bobs with period WAVE/SPEED and a phase set by its index modulo WAVE/8.
//   Characters that share a phase share one animated <g>. The text is padded
//   to a whole number of wavelengths, so after one full scroll the duplicated
//   head of the text sits exactly where the original started, in the same
//   phase: no jump at the loop point.
//   Belt: every segment carries a repeating pattern of items and slides by
//   exactly one pattern length per loop, so the wrap is invisible.
//   Cogs: an N-tooth cog is drawn at 4 angles across one tooth pitch and the
//   frames are flipped through, which loops every tooth.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '../assets/02-amiga-cracktro_opus_5.5.svg');
const RULE = OUT.replace(/\.svg$/, '-rule.svg');

const W = 320;
const H = 168;
const BG = '#05040d';
const BEAT = 0.5; // 120 BPM: everything in the factory moves on the beat

// Vertical layout (pixel rows)
const RAIN_TOP = 2;
const PRESENTS_Y = 5;
const LY1 = 13; // ULTRA
const LY2 = 49; // SATISFACTORY
const SUB_Y = 79;
const BELT_Y = 120; // belt surface row; items stand on it
const FLOOR_Y = 127;
const SCROLL_Y = 139; // glyph top at rest
const STATUS_Y = 158;
const RAIN_BOTTOM = H - 3;
// Stars keep out of the small-print rows and the belt, so nothing ever gets a
// stray pixel through a letter or mistakes a star for a screw.
const STAR_BANDS = [[0, PRESENTS_Y + 6], [SUB_Y - 2, SUB_Y + 6], [BELT_Y - 11, FLOOR_Y], [STATUS_Y - 2, H]];
const FACTORY_BAND = [SUB_Y + 6, FLOOR_Y]; // the big white stars keep clear of the machines too
const SCROLL_BAND = [FLOOR_Y + 1, STATUS_Y - 2]; // ... and of the scroller, where they read as stray hyphens

// App palette (the app's own neon): cyan title, gold accent, tab colours.
const CYAN = '#00cfff';
const GOLD = '#e8d44d';
const PURPLE = '#a855f7';
const PINK = '#ec4899';
const BLUE = '#38bdf8';

// ---------------------------------------------------------------- utilities
function mulberry32(seed) {
  return () => {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(0xfac7);
const n = (v) => (Number.isInteger(v) ? String(v) : String(+v.toFixed(3)));

class Grid {
  constructor(w, h) { this.w = w; this.h = h; this.a = new Uint8Array(w * h); }
  get(x, y) { return x >= 0 && y >= 0 && x < this.w && y < this.h ? this.a[y * this.w + x] : 0; }
  set(x, y, v = 1) { if (x >= 0 && y >= 0 && x < this.w && y < this.h) this.a[y * this.w + x] = v; }
}

// Turn lit cells into a compact path: horizontal runs, merged down rows.
// Subpaths are left open (no "z"): fills close them implicitly, and it saves
// a byte on each of several thousand rects.
function cellsToPath(isOn, w, h, ox = 0, oy = 0) {
  const rects = [];
  let active = new Map();
  for (let y = 0; y < h; y++) {
    const next = new Map();
    let x = 0;
    while (x < w) {
      if (!isOn(x, y)) { x++; continue; }
      let x1 = x;
      while (x1 < w && isOn(x1, y)) x1++;
      const key = `${x},${x1}`;
      const r = active.get(key);
      if (r) { r.h++; next.set(key, r); } else { const nr = { x, y, w: x1 - x, h: 1 }; rects.push(nr); next.set(key, nr); }
      x = x1;
    }
    active = next;
  }
  return rects.map((r) => `M${n(r.x + ox)} ${n(r.y + oy)}h${r.w}v${r.h}h${-r.w}`).join('');
}
const gridPath = (g, pred = (v) => v) => cellsToPath((x, y) => pred(g.get(x, y)), g.w, g.h);

function lerpHex(a, b, t) {
  const pa = [1, 3, 5].map((i) => parseInt(a.slice(i, i + 2), 16));
  const pb = [1, 3, 5].map((i) => parseInt(b.slice(i, i + 2), 16));
  return `#${pa.map((v, i) => Math.round(v + (pb[i] - v) * t).toString(16).padStart(2, '0')).join('')}`;
}
function ramp(keys, count) { // keys: [[row, '#hex'], ...] sorted by row
  const out = [];
  for (let r = 0; r < count; r++) {
    let k = 0;
    while (k < keys.length - 2 && r > keys[k + 1][0]) k++;
    const [r0, c0] = keys[k];
    const [r1, c1] = keys[k + 1];
    out.push(r <= r0 ? c0 : r >= r1 ? c1 : lerpHex(c0, c1, (r - r0) / (r1 - r0)));
  }
  return out;
}
// Hard-edged vertical gradient: one flat colour per pixel row.
function rowGradient(id, y0, colors) {
  const h = colors.length;
  const stops = colors.map((c, i) => `<stop offset="${n(i / h)}" stop-color="${c}"/><stop offset="${n((i + 1) / h)}" stop-color="${c}"/>`).join('');
  return `<linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="0" y1="${y0}" x2="0" y2="${y0 + h}">${stops}</linearGradient>`;
}

// ------------------------------------------------------------ 8x8 scroll font
// Bold Topaz-ish capitals. '$' is a cog, '^' a lightning bolt.
const F8 = {
  A: ['..###..', '.##.##.', '##...##', '##...##', '#######', '##...##', '##...##'],
  B: ['######.', '##...##', '##...##', '######.', '##...##', '##...##', '######.'],
  C: ['.#####.', '##...##', '##.....', '##.....', '##.....', '##...##', '.#####.'],
  D: ['#####..', '##..##.', '##...##', '##...##', '##...##', '##..##.', '#####..'],
  E: ['#######', '##.....', '##.....', '######.', '##.....', '##.....', '#######'],
  F: ['#######', '##.....', '##.....', '######.', '##.....', '##.....', '##.....'],
  G: ['.#####.', '##...##', '##.....', '##.####', '##...##', '##...##', '.######'],
  H: ['##...##', '##...##', '##...##', '#######', '##...##', '##...##', '##...##'],
  I: ['######', '..##..', '..##..', '..##..', '..##..', '..##..', '######'],
  J: ['....###', '.....##', '.....##', '.....##', '##...##', '##...##', '.#####.'],
  K: ['##...##', '##..##.', '##.##..', '####...', '##.##..', '##..##.', '##...##'],
  L: ['##.....', '##.....', '##.....', '##.....', '##.....', '##.....', '#######'],
  M: ['##...##', '###.###', '#######', '##.#.##', '##...##', '##...##', '##...##'],
  N: ['##...##', '###..##', '####.##', '##.####', '##..###', '##...##', '##...##'],
  O: ['.#####.', '##...##', '##...##', '##...##', '##...##', '##...##', '.#####.'],
  P: ['######.', '##...##', '##...##', '######.', '##.....', '##.....', '##.....'],
  Q: ['.#####.', '##...##', '##...##', '##...##', '##.#.##', '##..##.', '.###.##'],
  R: ['######.', '##...##', '##...##', '######.', '##.##..', '##..##.', '##...##'],
  S: ['.#####.', '##...##', '##.....', '.#####.', '.....##', '##...##', '.#####.'],
  T: ['######', '..##..', '..##..', '..##..', '..##..', '..##..', '..##..'],
  U: ['##...##', '##...##', '##...##', '##...##', '##...##', '##...##', '.#####.'],
  V: ['##...##', '##...##', '##...##', '##...##', '.##.##.', '..###..', '...#...'],
  W: ['##...##', '##...##', '##...##', '##.#.##', '#######', '###.###', '##...##'],
  X: ['##...##', '##...##', '.##.##.', '..###..', '.##.##.', '##...##', '##...##'],
  Y: ['##..##', '##..##', '##..##', '.####.', '..##..', '..##..', '..##..'],
  Z: ['#######', '....##.', '...##..', '..##...', '.##....', '##.....', '#######'],
  0: ['.#####.', '##..###', '##.####', '####.##', '###..##', '##...##', '.#####.'],
  1: ['..##..', '.###..', '..##..', '..##..', '..##..', '..##..', '######'],
  2: ['.#####.', '##...##', '.....##', '..####.', '.##....', '##.....', '#######'],
  3: ['.#####.', '##...##', '.....##', '..####.', '.....##', '##...##', '.#####.'],
  4: ['...###.', '..####.', '.##.##.', '##..##.', '#######', '....##.', '....##.'],
  5: ['#######', '##.....', '######.', '.....##', '.....##', '##...##', '.#####.'],
  6: ['.#####.', '##.....', '##.....', '######.', '##...##', '##...##', '.#####.'],
  7: ['#######', '.....##', '....##.', '...##..', '..##...', '..##...', '..##...'],
  8: ['.#####.', '##...##', '##...##', '.#####.', '##...##', '##...##', '.#####.'],
  9: ['.#####.', '##...##', '##...##', '.######', '.....##', '.....##', '.#####.'],
  '.': ['...', '...', '...', '...', '...', '.##', '.##'],
  ',': ['...', '...', '...', '...', '...', '.##', '.##', '##.'],
  '!': ['..##', '..##', '..##', '..##', '..##', '....', '..##'],
  '?': ['.#####.', '##...##', '....##.', '...##..', '...##..', '.......', '...##..'],
  "'": ['..##', '..##', '.##.'],
  '"': ['.##.##', '.##.##', '.#..#.'],
  '-': ['......', '......', '......', '.#####', '.#####'],
  ':': ['...', '.##', '.##', '...', '.##', '.##'],
  '/': ['.....##', '....##.', '...##..', '..##...', '.##....', '##.....', '#......'],
  '(': ['...##', '..##.', '.##..', '.##..', '.##..', '..##.', '...##'],
  ')': ['##...', '.##..', '..##.', '..##.', '..##.', '.##..', '##...'],
  '*': ['.......', '.##.##.', '..###..', '#######', '..###..', '.##.##.'],
  '+': ['......', '..##..', '..##..', '######', '..##..', '..##..'],
  '=': ['......', '......', '######', '......', '######'],
  '&': ['.###...', '##.##..', '.###...', '.###.##', '##.###.', '##..##.', '.###.##'],
  '>': ['.##....', '..##...', '...##..', '....##.', '...##..', '..##...', '.##....'],
  '<': ['....##.', '...##..', '..##...', '.##....', '..##...', '...##..', '....##.'],
  $: ['#.###.#', '.#####.', '###.###', '##...##', '###.###', '.#####.', '#.###.#'],
  '^': ['...###.', '..###..', '.###...', '######.', '..###..', '.###...', '.#.....'],
};

// ---------------------------------------------------------- 5px tiny font
const F5 = {
  A: ['.#.', '#.#', '###', '#.#', '#.#'], B: ['##.', '#.#', '##.', '#.#', '##.'],
  C: ['.##', '#..', '#..', '#..', '.##'], D: ['##.', '#.#', '#.#', '#.#', '##.'],
  E: ['###', '#..', '##.', '#..', '###'], F: ['###', '#..', '##.', '#..', '#..'],
  G: ['.##', '#..', '#.#', '#.#', '.##'], H: ['#.#', '#.#', '###', '#.#', '#.#'],
  I: ['###', '.#.', '.#.', '.#.', '###'], J: ['..#', '..#', '..#', '#.#', '.#.'],
  K: ['#.#', '#.#', '##.', '#.#', '#.#'], L: ['#..', '#..', '#..', '#..', '###'],
  M: ['#...#', '##.##', '#.#.#', '#...#', '#...#'], N: ['#..#', '##.#', '#.##', '#..#', '#..#'],
  O: ['.#.', '#.#', '#.#', '#.#', '.#.'], P: ['##.', '#.#', '##.', '#..', '#..'],
  Q: ['.#.', '#.#', '#.#', '##.', '.##'], R: ['##.', '#.#', '##.', '#.#', '#.#'],
  S: ['.##', '#..', '.#.', '..#', '##.'], T: ['###', '.#.', '.#.', '.#.', '.#.'],
  U: ['#.#', '#.#', '#.#', '#.#', '###'], V: ['#...#', '#...#', '.#.#.', '.#.#.', '..#..'],
  W: ['#...#', '#...#', '#.#.#', '##.##', '#...#'], X: ['#.#', '#.#', '.#.', '#.#', '#.#'],
  Y: ['#.#', '#.#', '.#.', '.#.', '.#.'], Z: ['####', '...#', '.##.', '#...', '####'],
  0: ['###', '#.#', '#.#', '#.#', '###'], 1: ['.#.', '##.', '.#.', '.#.', '###'],
  2: ['##.', '..#', '.#.', '#..', '###'], 3: ['##.', '..#', '.#.', '..#', '##.'],
  4: ['#.#', '#.#', '###', '..#', '..#'], 5: ['###', '#..', '##.', '..#', '##.'],
  6: ['.##', '#..', '###', '#.#', '###'], 7: ['###', '..#', '.#.', '.#.', '.#.'],
  8: ['###', '#.#', '###', '#.#', '###'], 9: ['###', '#.#', '###', '..#', '##.'],
  '.': ['.', '.', '.', '.', '#'], ',': ['.', '.', '.', '#', '#'], ':': ['.', '#', '.', '#', '.'],
  '!': ['#', '#', '#', '.', '#'], "'": ['#', '#', '.', '.', '.'], '-': ['...', '...', '###', '...', '...'],
  '>': ['#..', '.#.', '..#', '.#.', '#..'], '<': ['..#', '.#.', '#..', '.#.', '..#'],
  '/': ['..#', '..#', '.#.', '#..', '#..'], '*': ['...', '#.#', '.#.', '#.#', '...'],
  '=': ['...', '###', '...', '###', '...'], '+': ['...', '.#.', '###', '.#.', '...'],
  '(': ['.#', '#.', '#.', '#.', '.#'], ')': ['#.', '.#', '.#', '.#', '#.'],
  '?': ['##.', '..#', '.#.', '...', '.#.'],
};
const tinyWidth = (s) => [...s].reduce((w, ch) => w + (ch === ' ' ? 3 : (F5[ch] ? F5[ch][0].length + 1 : 4)), 0) - 1;
function drawTiny(set, s, x, y) {
  for (const ch of s) {
    if (ch === ' ') { x += 3; continue; }
    const g = F5[ch];
    if (!g) throw new Error(`tiny font lacks ${JSON.stringify(ch)}`);
    g.forEach((row, r) => [...row].forEach((c, k) => { if (c === '#') set(x + k, y + r); }));
    x += g[0].length + 1;
  }
  return x;
}
function tinyPath(s, x, y) {
  const g = new Grid(W, H);
  const end = drawTiny((px, py) => g.set(px, py), s, x, y);
  return { d: gridPath(g), end };
}

// ------------------------------------------------ colour-indexed pixel sprites
class Sprite {
  constructor(w, h) { this.w = w; this.h = h; this.c = new Array(w * h).fill(null); }
  get(x, y) { return x >= 0 && y >= 0 && x < this.w && y < this.h ? this.c[y * this.w + x] : null; }
  px(x, y, col) { if (x >= 0 && y >= 0 && x < this.w && y < this.h) this.c[y * this.w + x] = col; return this; }
  rect(x, y, w, h, col) { for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) this.px(x + i, y + j, col); return this; }
  // A bevelled panel: lit from the top-left.
  panel(x, y, w, h, [base, hi, lo]) {
    this.rect(x, y, w, h, base).rect(x, y, w, 1, hi).rect(x, y, 1, h, hi).rect(x + w - 1, y, 1, h, lo).rect(x, y + h - 1, w, 1, lo);
    return this;
  }
  map(rows, pal, ox = 0, oy = 0) {
    rows.forEach((row, r) => [...row].forEach((ch, k) => { if (pal[ch]) this.px(ox + k, oy + r, pal[ch]); }));
    return this;
  }
  text(s, x, y, col) { drawTiny((px, py) => this.px(px, py, col), s, x, y); return this; }
  svg(ox = 0, oy = 0) {
    const cols = [...new Set(this.c.filter(Boolean))];
    return cols.map((col) => `<path fill="${col}" d="${cellsToPath((x, y) => this.get(x, y) === col, this.w, this.h, ox, oy)}"/>`).join('');
  }
}
const mapSprite = (rows, pal) => new Sprite(Math.max(...rows.map((r) => r.length)), rows.length).map(rows, pal);

// ------------------------------------------------------------- chrome logo
// Chunky chamfered capitals built from polygons, rasterised to the grid.
const rect = (x0, y0, x1, y1) => [[x0, y0], [x1, y0], [x1, y1], [x0, y1]];
function makeLetters(LW, LH, ST, CH, ch) {
  const Y1 = Math.floor((LH - ST) / 2); // middle bar top (S, F)
  const Y2 = Y1 + ST; // middle bar bottom
  const m0 = Math.floor((LW - ST) / 2); // centre stem (T, Y)
  const m1 = m0 + ST;
  const ab = Y2 + 2; // A crossbar bottom
  const at = ab - (ST - 1);
  const rb = Y2 + 1; // R bowl bottom
  const rc = rb - (ST - 1);
  const fw = LW - 1;
  const lw = LW - 3;
  return {
    U: { w: LW, add: [[[0, 0], [ST, 0], [ST, LH - ST - ch], [ST + ch, LH - ST], [LW - ST - ch, LH - ST], [LW - ST, LH - ST - ch], [LW - ST, 0], [LW, 0], [LW, LH - CH], [LW - CH, LH], [CH, LH], [0, LH - CH]]], sub: [] },
    L: { w: lw, add: [[[0, 0], [ST, 0], [ST, LH - ST], [lw, LH - ST], [lw, LH], [CH, LH], [0, LH - CH]]], sub: [] },
    T: { w: LW, add: [[[0, 0], [LW, 0], [LW, ST], [m1, ST], [m1, LH], [m0, LH], [m0, ST], [0, ST]]], sub: [] },
    R: { w: LW, add: [[[0, 0], [LW - CH, 0], [LW, CH], [LW, rb - 4], [LW - 4, rb], [LW, LH], [LW - ST, LH], [LW - ST - 4, rb], [ST, rb], [ST, LH], [0, LH]]],
      sub: [[[ST, ST], [LW - ST - ch, ST], [LW - ST, ST + ch], [LW - ST, rc - ch], [LW - ST - ch, rc], [ST, rc]]] },
    A: { w: LW, add: [[[0, CH], [CH, 0], [LW - CH, 0], [LW, CH], [LW, LH], [LW - ST, LH], [LW - ST, ab], [ST, ab], [ST, LH], [0, LH]]],
      sub: [[[ST + ch, ST], [LW - ST - ch, ST], [LW - ST, ST + ch], [LW - ST, at], [ST, at], [ST, ST + ch]]] },
    S: { w: LW, add: [[[CH, 0], [LW, 0], [LW, ST], [ST, ST], [ST, Y1], [LW - CH, Y1], [LW, Y1 + CH], [LW, LH - CH], [LW - CH, LH], [0, LH], [0, LH - ST], [LW - ST, LH - ST], [LW - ST, Y2], [CH, Y2], [0, Y2 - CH], [0, CH]]], sub: [] },
    I: { w: ST, add: [rect(0, 0, ST, LH)], sub: [] },
    F: { w: fw, add: [[[CH, 0], [fw, 0], [fw, ST], [ST, ST], [ST, Y1], [fw - 4, Y1], [fw - 4, Y2], [ST, Y2], [ST, LH], [0, LH], [0, CH]]], sub: [] },
    C: { w: LW, add: [[[CH, 0], [LW, 0], [LW, ST], [ST + ch, ST], [ST, ST + ch], [ST, LH - ST - ch], [ST + ch, LH - ST], [LW, LH - ST], [LW, LH], [CH, LH], [0, LH - CH], [0, CH]]], sub: [] },
    O: { w: LW, add: [[[CH, 0], [LW - CH, 0], [LW, CH], [LW, LH - CH], [LW - CH, LH], [CH, LH], [0, LH - CH], [0, CH]]],
      sub: [[[ST + ch, ST], [LW - ST - ch, ST], [LW - ST, ST + ch], [LW - ST, LH - ST - ch], [LW - ST - ch, LH - ST], [ST + ch, LH - ST], [ST, LH - ST - ch], [ST, ST + ch]]] },
    Y: { w: LW, add: [[[0, 0], [ST, 0], [ST, Y1 - ch], [ST + ch, Y1], [LW - ST - ch, Y1], [LW - ST, Y1 - ch], [LW - ST, 0], [LW, 0], [LW, Y2 - CH], [LW - CH, Y2], [m1, Y2], [m1, LH], [m0, LH], [m0, Y2], [CH, Y2], [0, Y2 - CH]]], sub: [] },
  };
}
function inPoly(px, py, poly) {
  let inside = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i];
    const [xj, yj] = poly[j];
    if ((yi > py) !== (yj > py) && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}
function rasterWord(text, L, LH, gap, y0, depth) {
  const width = [...text].reduce((w, c, i) => w + L[c].w + (i < text.length - 1 ? gap : 0), 0);
  const x0 = Math.round((W - width - depth) / 2);
  const face = new Grid(W, H);
  const boxes = [];
  let x = x0;
  for (const c of text) {
    const l = L[c];
    boxes.push({ c, x, w: l.w });
    for (let yy = 0; yy < LH; yy++) {
      for (let xx = 0; xx < l.w; xx++) {
        const px = xx + 0.5;
        const py = yy + 0.5;
        if (l.add.some((p) => inPoly(px, py, p)) && !l.sub.some((p) => inPoly(px, py, p))) face.set(x + xx, y0 + yy);
      }
    }
    x += l.w + gap;
  }
  // 3D extrusion down-right.
  const extrude = new Grid(W, H);
  for (let d = 1; d <= depth; d++) {
    for (let y = 0; y < H; y++) for (let xx = 0; xx < W; xx++) {
      if (face.get(xx, y) && !face.get(xx + d, y + d) && !extrude.get(xx + d, y + d)) extrude.set(xx + d, y + d, d);
    }
  }
  return { face, extrude, boxes, x0, width, y0, LH, depth };
}

const ULTRA = rasterWord('ULTRA', makeLetters(25, 28, 7, 6, 2), 28, 4, LY1, 3);
const SATIS = rasterWord('SATISFACTORY', makeLetters(20, 22, 6, 5, 2), 22, 4, LY2, 2);
const WORDS = [ULTRA, SATIS];

// ULTRA: ice-cyan chrome (the app's neon cyan). SATISFACTORY: silver over gold.
const CHROME_U = ramp([
  [0, '#ffffff'], [3, '#c4f4ff'], [8, '#4fd8ff'], [12, '#009fe0'], [13, '#0a4fa0'], [14, '#04123c'],
  [15, '#0a2a6a'], [18, '#0a78c8'], [22, '#00cfff'], [25, '#d8fbff'], [27, '#7fdcf0'],
], 28);
const CHROME_S = ramp([
  [0, '#ffffff'], [2, '#e6ecff'], [6, '#a6b4dc'], [9, '#5a6aa0'], [10, '#1c2450'],
  [11, '#2a1a06'], [13, '#7a5410'], [17, '#e8d44d'], [20, '#fffbd0'], [21, '#d8b84a'],
], 22);
const EXTRUDE_U = ['#ec4899', '#b0246a', '#6a0f40'];
const EXTRUDE_S = ['#a855f7', '#5e22a8'];

// ---------------------------------------------------------- hex-cog emblem
// The app's emblem redrawn as pixels: a hexagon, a cog with a centre hole and
// a node on each corner. The cog turns one tooth per beat.
const EM = 31; // emblem box
const EMC = (EM - 1) / 2; // centre
const hexPoly = (r) => Array.from({ length: 6 }, (_, k) => {
  const a = ((-90 + 60 * k) * Math.PI) / 180;
  return [EMC + 0.5 + r * Math.cos(a), EMC + 0.5 + r * Math.sin(a)];
});
function cogGrid(size, cx, cy, teeth, rBody, rTeeth, rHole, toothDeg, rotDeg) {
  const g = new Grid(size, size);
  const pitch = 360 / teeth;
  for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
    const dx = x - cx;
    const dy = y - cy;
    const r = Math.hypot(dx, dy);
    if (r < rHole) continue;
    const a = (((Math.atan2(dy, dx) * 180) / Math.PI - rotDeg) % pitch + pitch) % pitch;
    const tooth = a < toothDeg / 2 || a > pitch - toothDeg / 2;
    if (r <= rBody || (r <= rTeeth && tooth)) g.set(x, y);
  }
  return g;
}
// Shade a cog: highlight on the top-left rim, shadow on the bottom-right rim.
function cogSprite(g, [base, hi, lo]) {
  const s = new Sprite(g.w, g.h);
  for (let y = 0; y < g.h; y++) for (let x = 0; x < g.w; x++) {
    if (!g.get(x, y)) continue;
    s.px(x, y, !g.get(x + 1, y + 1) ? lo : !g.get(x - 1, y - 1) ? hi : base);
  }
  return s;
}
const hexOuter = hexPoly(15.2);
const hexInner = hexPoly(13.2);
const hexCore = hexPoly(11.6);
const emblemSolid = new Grid(EM, EM); // footprint, for the outline/halo pass
const emblemBase = new Sprite(EM, EM);
for (let y = 0; y < EM; y++) for (let x = 0; x < EM; x++) {
  const px = x + 0.5;
  const py = y + 0.5;
  if (!inPoly(px, py, hexOuter)) continue;
  emblemSolid.set(x, y);
  emblemBase.px(x, y, !inPoly(px, py, hexInner) ? '#ffffff' : !inPoly(px, py, hexCore) ? '#0a86c4' : '#070914');
}
hexPoly(13.6).forEach(([vx, vy]) => { // corner nodes
  const x = Math.round(vx - 0.5);
  const y = Math.round(vy - 0.5);
  emblemBase.rect(x - 1, y - 1, 3, 3, GOLD).px(x, y, '#ffffff');
  for (let j = -1; j <= 1; j++) for (let i = -1; i <= 1; i++) emblemSolid.set(x + i, y + j);
});
const COG_GOLD = [GOLD, '#fff9c4', '#9a7d14'];
const EMBLEM_FRAMES = [0, 1, 2, 3].map((k) => cogSprite(cogGrid(EM, EMC, EMC, 8, 6.3, 9.4, 2.6, 21, k * 11.25), COG_GOLD));

const EMBLEM_GAP = 9;
const EMB_L = { x: ULTRA.x0 - EMBLEM_GAP - EM, y: LY1 };
const EMB_R = { x: ULTRA.x0 + ULTRA.width + ULTRA.depth + EMBLEM_GAP, y: LY1 };

// Black outline around every logo shape, then a dark halo round the outside so
// the copper bars never bleed into the lettering at phone size.
const solid = new Grid(W, H);
for (const wd of WORDS) for (let i = 0; i < W * H; i++) if (wd.face.a[i] || wd.extrude.a[i]) solid.a[i] = 1;
for (const e of [EMB_L, EMB_R]) for (let y = 0; y < EM; y++) for (let x = 0; x < EM; x++) if (emblemSolid.get(x, y)) solid.set(e.x + x, e.y + y);
const outline = new Grid(W, H);
for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
  if (solid.get(x, y)) continue;
  let near = false;
  for (let dy = -1; dy <= 1 && !near; dy++) for (let dx = -1; dx <= 1; dx++) if (solid.get(x + dx, y + dy)) near = true;
  if (near) outline.set(x, y);
}
const HALO = 2;
const halo = new Grid(W, H);
const slots = new Grid(W, H);
{
  const filled = (x, y) => solid.get(x, y) || outline.get(x, y);
  const outside = new Grid(W, H);
  const stack = [[0, 0]];
  while (stack.length) {
    const [x, y] = stack.pop();
    if (x < 0 || y < 0 || x >= W || y >= H || outside.get(x, y) || filled(x, y)) continue;
    outside.set(x, y);
    stack.push([x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]);
  }
  let ring = outline;
  for (let r = 0; r < HALO; r++) {
    const next = new Grid(W, H);
    for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
      if (!outside.get(x, y) || halo.get(x, y)) continue;
      if (ring.get(x - 1, y) || ring.get(x + 1, y) || ring.get(x, y - 1) || ring.get(x, y + 1)) next.set(x, y);
    }
    for (let i = 0; i < next.a.length; i++) if (next.a[i]) halo.a[i] = 1;
    ring = next;
  }
  // Black out everything between the first and last letter of each word too
  // (slots and chamfer notches) and every enclosed counter, or slivers of
  // copper show through and read as stray serifs.
  for (const wd of WORDS) {
    const first = wd.boxes[0];
    const last = wd.boxes[wd.boxes.length - 1];
    for (let y = wd.y0 - 1 - HALO; y < wd.y0 + wd.LH + wd.depth + 1 + HALO; y++) {
      for (let x = first.x + 6; x < last.x + last.w - 6; x++) if (outside.get(x, y)) slots.set(x, y);
    }
  }
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) if (!outside.get(x, y) && !solid.get(x, y)) slots.set(x, y);
}

// ---------------------------------------------------------------- starfield
function starLayer(count, w = 1, bands = STAR_BANDS) {
  const g = new Grid(W * 2, H);
  for (let i = 0; i < count; i++) {
    const x = Math.floor(rand() * W);
    const y = 3 + Math.floor(rand() * (H - 6));
    if (bands.some(([a, b]) => y >= a && y <= b)) { i--; continue; }
    for (let k = 0; k < w; k++) { g.set(x + k, y); g.set(x + k + W, y); }
  }
  return gridPath(g);
}
const STARS = [
  { cls: 'st1', color: '#34386e', d: starLayer(80) },
  { cls: 'st2', color: '#7c86c8', d: starLayer(38) },
  { cls: 'st3', color: '#ffffff', d: starLayer(16, 2, [...STAR_BANDS, FACTORY_BAND, SCROLL_BAND]) },
];

// ------------------------------------------------- distant factory skyline
// The rest of the factory, a long way off: two layers of silhouette standing
// on the horizon behind the production line, a few lit windows and a red
// beacon on every chimney. It has its own PRNG, so the stars and the furnace
// fire keep their seeds.
const SKYLINE = (() => {
  const r = mulberry32(0x51de);
  const ri = (a, b) => a + Math.floor(r() * (b - a + 1));
  const far = new Grid(W, H);
  const near = new Grid(W, H);
  const lit = [];
  const beacons = [];
  const col = (g, x, top) => { for (let y = top; y < FLOOR_Y; y++) g.set(x, y); };
  for (let x = -3; x < W;) { // far: tall halls, stepped roofs, chimneys
    const w = ri(10, 24);
    const top = FLOOR_Y - ri(16, 27);
    for (let i = 0; i < w; i++) col(far, x + i, top);
    const kind = r();
    if (kind < 0.45) {
      const cx = x + ri(1, w - 4);
      const ct = top - ri(4, 8);
      col(far, cx, ct); col(far, cx + 1, ct);
      beacons.push([cx, ct - 1]);
    } else if (kind < 0.75) {
      for (let i = 3; i < w - 3; i++) col(far, x + i, top - 2);
    }
    x += w + (r() < 0.35 ? ri(4, 10) : 0);
  }
  for (let x = -2; x < W;) { // near: sheds, domed tanks, pipe racks
    const kind = r();
    const w = ri(7, 16);
    const top = FLOOR_Y - ri(9, 17);
    if (kind < 0.3) { // tank: a dome with its corners knocked off
      for (let i = 0; i < w; i++) col(near, x + i, top + (i === 0 || i === w - 1 ? 2 : i === 1 || i === w - 2 ? 1 : 0));
    } else if (kind < 0.5) { // pipe rack: a line on legs
      for (let i = 0; i < w; i++) { near.set(x + i, top + 2); near.set(x + i, top + 4); if (i % 4 === 0) col(near, x + i, top + 2); }
    } else { // shed, maybe with a lit window or two
      for (let i = 0; i < w; i++) col(near, x + i, top);
      for (let i = 2; i < w - 2; i += 3) if (r() < 0.45 && top + 2 < BELT_Y - 2) lit.push([x + i, top + 2]);
    }
    x += w + ri(0, 7);
  }
  return { far: gridPath(far), near: gridPath(near), lit, beacons };
})();

// ------------------------------------------------------------- copper bars
const copperRamp = (c) => [lerpHex('#000000', c, 0.22), lerpHex('#000000', c, 0.55), c, lerpHex(c, '#ffffff', 0.45), lerpHex(c, '#ffffff', 0.86)];
const COPPER = [PINK, '#ff8a3c', GOLD, CYAN, '#3f6cff', PURPLE].map(copperRamp);
const BAR_TOP = 11;
const BAR_TRAVEL = 56; // sweeps the full height of both logo rows
const BAR_PERIOD = 4.4; // one sweep down and back up
const BAR_STAGGER = 0.24;

// 16-step colour cycle for the raster lines, built from the app's own neon.
const RING = [CYAN, '#3f6cff', PURPLE, PINK, '#ff8a3c', GOLD];
const HUES = Array.from({ length: 16 }, (_, i) => {
  const t = (i / 16) * RING.length;
  const k = Math.floor(t);
  return lerpHex(RING[k], RING[(k + 1) % RING.length], t - k);
});

// ------------------------------------------------------------ the factory
// Original pixel items: generic shapes, nothing lifted from the game.
const FE = { h: '#f4f6ff', b: '#a9b2c9', s: '#5c6478' };
const CU = { h: '#ffd9ae', b: '#ea8a3e', s: '#8c4414' };
const AU = { h: '#fff9c4', b: GOLD, s: '#9a7d14' };
const FR = { h: '#c6ecff', b: '#4aa8ea', s: '#1c5a9a' };
const ITEMS = {
  ingotFe: mapSprite(['.hhhhhh.', 'hbbbbbbs', 'hbbbbbbs', 'ssssssss'], FE),
  ingotCu: mapSprite(['.hhhhhh.', 'hbbbbbbs', 'hbbbbbbs', 'ssssssss'], CU),
  plate: mapSprite(['..hhhhhhh', '.hbbbbbs.', 'hbbbbbs..', 'sssssss..'], FE),
  rods: mapSprite(['.hhhhhhh.', 'sbbbbbbbs', '.........', '.hhhhhhh.', 'sbbbbbbbs'], FE),
  screw: mapSprite(['hhhhh', 'sbbbs', '.hb..', '.bs..', '.hb..', '.bs..', '..s..'], AU),
  coil: mapSprite(['.hhhhh.', 'hb...bs', 'h.....s', 'hb...bs', '.sssss.'], CU),
  frame: mapSprite(['hhhhhhhhh', 'hb.....bs', 'h.b...b.s', 'h..b.b..s', 'h...b...s', 'h..b.b..s', 'h.b...b.s', 'hb.....bs', 'sssssssss'], FR),
};
const BELT_SPEED = 32; // px per second: one 16px slot per beat
const SLOT = 16;

// Machines. Local coords: rows 0-7 roof gear, 8-25 body, 26-32 nameplate.
// Row 26 of a machine is the belt surface row.
const MH = 33;
const MY = BELT_Y - 26;
const SML = { x: 0, w: 32 };
const CON = { x: 62, w: 48 };
const ASM = { x: 172, w: 44 };
const ELV = { x: 286, w: 34, h: 45, y: BELT_Y - 38 };
const PORT = 4; // how far an item slides into a machine before it vanishes
const DARK = '#080a12';
const PLATE = '#0b0d18';
const STEEL = ['#3d4a6b', '#8296c8', '#232b44'];
const STEEL_LT = ['#55648e', '#a9bcea', '#2c3656'];
const VIOLET = ['#4a3a72', '#9582d0', '#281e48'];
const VIOLET_LT = ['#65529a', '#b9a8ee', '#33275a'];
const RUST = ['#6e4632', '#d09868', '#38201a'];
const HULL = ['#7f89a8', '#e4eaff', '#3c4360'];
// body shell shared by both machines: bevelled panel, hazard trim, see-through
// belt ports with a gold lip, nameplate
function shell(s, tone, label, labelX, labelCol) {
  const w = s.w;
  s.panel(0, 8, w, 18, tone);
  for (let x = 1; x < w - 1; x++) s.px(x, 9, (x >> 1) % 2 ? GOLD : '#14161f'); // hazard trim
  for (const px of [0, w - 5]) s.rect(px, 16, 5, 10, null);
  s.rect(0, 15, 6, 1, GOLD).rect(5, 16, 1, 10, tone[2]).rect(w - 6, 15, 6, 1, GOLD).rect(w - 6, 16, 1, 10, tone[2]);
  s.rect(0, 26, w, 7, PLATE).rect(0, 26, w, 1, '#1d2236');
  s.text(label, labelX, 27, labelCol);
}
// a viewing window: bevelled frame, dark glass
function windowAt(s, x, y, w, h, tone) {
  s.rect(x - 1, y - 1, w + 2, h + 2, tone[2]).rect(x - 1, y - 1, w + 1, 1, tone[1]).rect(x - 1, y - 1, 1, h + 1, tone[1]).rect(x, y, w, h, DARK);
}

const sml = new Sprite(SML.w, MH);
{
  sml.panel(5, 0, 6, 8, ['#2a3148', '#56618a', '#161a2a']).rect(5, 2, 6, 1, GOLD).rect(5, 5, 6, 1, '#14161f'); // stack
  sml.panel(15, 4, 9, 4, RUST).rect(17, 2, 2, 2, '#8a90a8').rect(16, 1, 4, 1, '#c8cee4'); // hopper + valve
  shell(sml, RUST, 'SMELTER', 2, GOLD);
  windowAt(sml, 10, 11, 12, 12, RUST); // furnace mouth (the fire is animated on top)
  sml.rect(10, 22, 12, 1, '#5a1608');
}
const con = new Sprite(CON.w, MH);
{
  con.panel(5, 4, 9, 4, ['#2a7fb4', '#8fd8ff', '#134a70']).px(5, 4, null).px(13, 4, null); // coolant tank
  con.panel(19, 3, 10, 5, STEEL_LT); // press cylinder
  con.panel(35, 1, 5, 7, ['#2a3148', '#56618a', '#161a2a']).rect(35, 3, 5, 1, GOLD); // exhaust
  shell(con, STEEL, 'CONSTRUCTOR', 2, BLUE);
  windowAt(con, 17, 11, 14, 12, STEEL);
  con.rect(20, 21, 8, 2, '#5c6478').rect(20, 21, 8, 1, '#a9b2c9'); // anvil
  con.rect(22, 19, 4, 2, '#ff8a3c').rect(22, 19, 4, 1, '#ffe08a'); // the part being pressed, still hot
  for (const ly of [11, 14, 17]) con.rect(9, ly, 2, 2, '#1a2036'); // lamp sockets
  for (const vy of [11, 13, 15, 17, 19, 21]) con.rect(35, vy, 6, 1, STEEL[2]); // vents
}
const asm = new Sprite(ASM.w, MH);
{
  for (const cx of [9, 29]) asm.panel(cx, 4, 6, 4, VIOLET_LT).rect(cx - 1, 3, 8, 1, VIOLET_LT[1]); // twin cylinders
  asm.rect(40, 2, 1, 6, '#8a90a8'); // mast
  shell(asm, VIOLET, 'ASSEMBLER', 4, '#ff6bb5');
  for (const wx of [7, 27]) {
    windowAt(asm, wx, 11, 10, 12, VIOLET);
    asm.rect(wx + 1, 21, 8, 2, '#5c6478').rect(wx + 1, 21, 8, 1, '#a9b2c9');
    asm.rect(wx + 3, 19, 4, 2, FR.b).rect(wx + 3, 19, 4, 1, FR.h);
  }
  for (const ly of [11, 14, 17, 20]) asm.rect(21, ly, 2, 2, '#1e1836');
}
// The Space Elevator: a stepped tower on a nameplate, tether out of the top.
// Rows 38-44 nameplate, row 38 = belt surface.
const elv = new Sprite(ELV.w, ELV.h);
{
  elv.rect(15, 0, 4, 8, HULL[0]).rect(15, 0, 1, 8, HULL[1]).rect(18, 0, 1, 8, HULL[2]); // spire
  elv.rect(14, 3, 6, 2, GOLD).rect(14, 4, 6, 1, '#9a7d14'); // tether clamp
  elv.panel(12, 8, 10, 8, HULL);
  elv.rect(14, 10, 6, 3, DARK).rect(14, 10, 6, 1, '#16384a'); // beacon window (lit by the animation)
  elv.panel(8, 16, 18, 10, HULL).rect(9, 19, 16, 1, PURPLE).rect(9, 20, 16, 1, '#5e22a8');
  for (const rx of [10, 14, 18, 22]) elv.rect(rx, 23, 2, 1, HULL[2]); // rivets
  elv.panel(4, 26, 26, 12, HULL);
  for (let x = 5; x < 29; x++) elv.px(x, 27, (x >> 1) % 2 ? GOLD : '#14161f'); // hazard trim
  elv.rect(4, 28, 4, 10, null).rect(8, 28, 1, 10, HULL[2]); // belt port
  windowAt(elv, 15, 30, 5, 6, HULL); // hatch
  for (const lx of [11, 23, 26]) elv.rect(lx, 31, 2, 2, '#2a1e46');
}
// Its nameplate is two pixels wider than the tower (the label needs the room).
const ELV_PLATE = { x: ELV.x - 2, w: W - ELV.x + 2 };
const elvPlate = new Sprite(ELV_PLATE.w, 7);
elvPlate.rect(0, 0, ELV_PLATE.w, 7, PLATE).rect(0, 0, ELV_PLATE.w, 1, '#1d2236').text('ELEVATOR', 2, 1, '#c89bff');
const TETHER_X = ELV.x + 16;
const pod = mapSprite(['...hh...', '..hhhs..', '.hhcchs.', '.hccccs.', 'hhccccss', 'hppppppd', 'hhhhhsss', '.hhhsss.', '..f..f..'], { h: '#f4f6ff', c: CYAN, s: '#8e98b8', p: PURPLE, d: '#5e22a8', f: '#ffb04a' });

// ------------------------------------------------------------ sine scroller
const SCROLL = [
  'EVERY RECIPE, ONE CLICK APART!          ',
  'YO PIONEERS! MANIFOLD DESTINY PROUDLY PRESENTS ... ULTRA-SATISFACTORY!  $ $ $  ',
  'A COMPANION APP FOR THE FACTORY GAME SATISFACTORY: EVERY RECIPE, EVERY BUILDING AND EVERY SPACE ELEVATOR OBJECTIVE, ONE CLICK APART.  ',
  'PARK IT ON THE SECOND MONITOR, THE PHONE, OR ONE ALT-TAB AWAY.  ',
  '140 CRAFTABLE ITEMS. 211 MACHINE RECIPES, 88 OF THEM ALTERNATES. 477 BUILDINGS. 5 SPACE ELEVATOR PHASES. ZERO EXCUSES.  ',
  'IT IS 3 A.M. YOU ALT-TAB OUT TO CHECK ONE RECIPE. MODULAR FRAME: 3 REINFORCED IRON PLATE + 12 IRON ROD = 2 FRAMES, ONE ASSEMBLER, 60 SECONDS, 15 MW. ',
  'YOU ALT-TAB BACK IN. SOMEHOW IT IS 5 A.M.  ',
  'THREE TABS: OBJECTIVES, ITEMS, BUILDINGS. CLICK AN INGREDIENT, GET ITS RECIPE. CLICK THE MACHINE, GET THE BUILDING. CLICK AGAIN. WE BOTH KNOW YOU WILL.  ',
  'JUST ONE MORE BELT ... JUST ONE MORE BELT ... JUST ONE MORE BELT ...  ',
  'YOUR SPAGHETTI IS NOT A MESS. IT IS LOAD-BEARING.  ',
  'QUICK START: PYTHON -M PIP INSTALL -R REQUIREMENTS.TXT  THEN  PYTHON -M STREAMLIT RUN APP/APP.PY  ',
  'OR SKIP THE INSTALL: LUKEXYZ.GITHUB.IO/ULTRA-SATISFACTORY RUNS THE LOT IN YOUR BROWSER.  ',
  'PROTECTION: NONE, IT IS APACHE 2.0. SUPPLIED BY: GAME DATA FROM GREENY/SATISFACTORYTOOLS. ',
  'UNOFFICIAL FAN PROJECT, NOT AFFILIATED WITH COFFEE STAIN STUDIOS. THEY MADE THE GAME. WE JUST READ YOU THE RECIPE BOOK.  ',
  'GREETZ: THE SPAGHETTI LOGISTICS UNION * BUS LANE BANDITS * OVERCLOCKERS ANONYMOUS * THE LOAD BALANCER LADS * ',
  'EVERYONE WHOSE "TEMPORARY" BELT IS STILL THERE 200 HOURS LATER * WHOEVER IS STILL HAND-FEEDING A CONSTRUCTOR. WE SEE YOU.  ',
  'NO GREETZ: BELTS THAT CLIP THROUGH OTHER BELTS. YOU KNOW WHAT YOU DID.  ',
  "EFFICIENCY IS MANDATORY. SLEEP IS AN ALTERNATE RECIPE.  ^ ^ ^  LET'S WRAP ...        ",
].join('');
const SPEED = 80; // px per second
const WAVE = 160; // wavelength in px
const AMP = 7;
const PHASES = WAVE / 8;
const PERIOD = WAVE / SPEED; // bob period (s)
const scrollChars = [...SCROLL];
while (scrollChars.length % PHASES) scrollChars.push(' ');
const SCROLL_LEN = scrollChars.length * 8;
const SCROLL_T = SCROLL_LEN / SPEED;
const SCROLL_X0 = 4;
const SCROLL_COLORS = ['#ffffff', '#d2f7ff', '#86e6ff', '#38bdf8', '#5a8cff', '#8a62f7', '#c050e0', '#ec4899'];

// ---------------------------------------------------------------- assemble
const css = [];
const defs = [];
const body = [];

css.push(
  '.st1{animation:sx 72s linear infinite}.st2{animation:sx 36s linear infinite}.st3{animation:sx 14s linear infinite}',
  `@keyframes sx{from{transform:translateX(0)}to{transform:translateX(-${W}px)}}`,
  `.cb{animation:cb ${n(BAR_PERIOD / 2)}s cubic-bezier(.37,0,.63,1) infinite alternate}`,
  `@keyframes cb{from{transform:translateY(0)}to{transform:translateY(${BAR_TRAVEL}px)}}`,
  '.rb{animation:rb 1.6s linear infinite}@keyframes rb{from{transform:translateX(0)}to{transform:translateX(-64px)}}',
  '.spk{transform-box:fill-box;transform-origin:center;opacity:0;animation:spk 5.6s ease-in-out infinite}',
  '@keyframes spk{0%,100%{opacity:0;transform:scale(.2)}6%{opacity:1;transform:scale(1)}13%{opacity:0;transform:scale(.2)}}',
  // 4-frame flipbooks (cogs): each frame shows for a quarter of the cycle
  `.fr{animation:fr ${BEAT}s step-end infinite}.f1,.f2,.f3{opacity:0}`,
  '@keyframes fr{0%{opacity:1}25%{opacity:0}100%{opacity:0}}',
  `.scr{animation:scr ${n(SCROLL_T)}s linear infinite}`,
  `@keyframes scr{from{transform:translateX(0)}to{transform:translateX(-${SCROLL_LEN}px)}}`,
  `@keyframes sw{from{transform:translateY(${-AMP}px)}to{transform:translateY(${AMP}px)}}`,
);

// panel
defs.push(`<clipPath id="panel"><rect width="${W}" height="${H}" rx="6"/></clipPath>`);
body.push(`<rect width="${W}" height="${H}" fill="${BG}"/>`);

// stars
STARS.forEach((s) => body.push(`<path class="${s.cls}" fill="${s.color}" d="${s.d}"/>`));

// distant skyline (the stars slide behind it). Lights that would sit right
// beside a machine are dropped: up close they read as stray pixels on it.
const clearOfMachines = ([x]) => x > 2 && x < W - 4 && [SML, CON, ASM, ELV].every((m) => x < m.x - 4 || x > m.x + m.w + 3);
body.push(`<path fill="#0c0c25" d="${SKYLINE.far}"/><path fill="#141638" d="${SKYLINE.near}"/>`);
body.push(`<path fill="#6a5c20" d="${SKYLINE.lit.filter(clearOfMachines).map(([x, y]) => `M${x} ${y}h1v1h-1z`).join('')}"/>`);

// copper bars (drawn last-first so bar 0 leads on top)
const barPaths = COPPER.map((rampC) => {
  const rows = [0, 1, 2, 3, 4, 3, 2, 1, 0];
  const byColor = new Map();
  rows.forEach((ri, y) => { const c = rampC[ri]; byColor.set(c, (byColor.get(c) || '') + `M0 ${BAR_TOP + y}h${W}v1h-${W}z`); });
  return [...byColor].map(([c, d]) => `<path fill="${c}" d="${d}"/>`).join('');
});
[...barPaths.keys()].reverse().forEach((i) => {
  const still = Math.round(BAR_TRAVEL * (0.5 - 0.5 * Math.cos((Math.PI * i) / (COPPER.length - 1))));
  body.push(`<g class="cb" style="animation-delay:${n(-i * BAR_STAGGER)}s" transform="translate(0 ${still})">${barPaths[i]}</g>`);
});

// Space Elevator tether: rises out of the top of the frame, with light pulses
// climbing it. Pitch 24px, so a 24px slide loops invisibly.
{
  const top = -24;
  const len = ELV.y - top;
  let pulses = '';
  for (let y = top; y < ELV.y + 24; y += 24) pulses += `M${TETHER_X} ${y}h2v3h-2z`;
  defs.push(`<clipPath id="tclip"><rect x="${TETHER_X}" y="0" width="2" height="${ELV.y}"/></clipPath>`);
  css.push('.tp{animation:tp 1s linear infinite}@keyframes tp{from{transform:translateY(0)}to{transform:translateY(-24px)}}');
  body.push(`<path fill="#000000" fill-opacity=".55" d="M${TETHER_X - 1} 0h4v${ELV.y}h-4z"/>`);
  body.push(`<path fill="#9aa4c4" d="M${TETHER_X} ${top}h1v${len}h-1z"/><path fill="#565e7c" d="M${TETHER_X + 1} ${top}h1v${len}h-1z"/>`);
  body.push(`<g clip-path="url(#tclip)"><path class="tp" fill="#e8fbff" d="${pulses}"/></g>`);
}

// colour-cycling raster lines: top, factory floor, bottom
{
  const rows = [RAIN_TOP, FLOOR_Y, RAIN_BOTTOM];
  const paths = HUES.map((c, h) => {
    let d = '';
    for (let m = 0; m < 7; m++) for (const y of rows) d += `M${h * 4 + m * 64} ${y}h4v1h-4z`;
    return `<path fill="${c}" d="${d}"/>`;
  }).join('');
  defs.push(`<clipPath id="rbclip">${rows.map((y) => `<rect x="${y === FLOOR_Y ? 0 : 8}" y="${y}" width="${y === FLOOR_Y ? W : W - 16}" height="1"/>`).join('')}</clipPath>`);
  body.push(`<g clip-path="url(#rbclip)"><g class="rb">${paths}</g></g>`);
}

// tiny text lines
{
  const presents = '-=*  MANIFOLD DESTINY PRESENTS  *=-';
  body.push(`<path class="aa" fill="#8c9cff" d="${tinyPath(presents, Math.round((W - tinyWidth(presents)) / 2), PRESENTS_Y).d}"/>`);

  // the three tabs in their own tab colours, in the app's "// HEADER //" style
  const DIM = '#5a6288';
  const sub = [['//', DIM], [' OBJECTIVES ', '#c089ff'], ['//', DIM], [' ITEMS ', '#ff6bb5'], ['//', DIM], [' BUILDINGS ', '#5ccbff'], ['//', DIM], [' EVERY RECIPE ONE CLICK APART ', GOLD], ['//', DIM]];
  let x = Math.round((W - tinyWidth(sub.map((p) => p[0]).join(''))) / 2);
  const byCol = new Map();
  for (const [s, c] of sub) {
    const t = tinyPath(s, x, SUB_Y);
    byCol.set(c, (byCol.get(c) || '') + t.d);
    x = t.end;
  }
  body.push(`<g class="aa">${[...byCol].map(([c, d]) => `<path fill="${c}" d="${d}"/>`).join('')}</g>`);

  // bottom status bar: the no-install link, flanked by tracker VU meters
  const parts = [['LIVE IN YOUR BROWSER', '#ffffff'], ['  ->  ', '#ff6bb5'], ['LUKEXYZ.GITHUB.IO/ULTRA-SATISFACTORY', '#7fe8ff']];
  const qw = tinyWidth(parts.map((p) => p[0]).join(''));
  let qx = Math.round((W - qw) / 2);
  const left = qx;
  for (const [s, c] of parts) {
    const t = tinyPath(s, qx, STATUS_Y);
    body.push(`<path class="aa" fill="${c}" d="${t.d}"/>`);
    qx = t.end;
  }
  const right = left + qw;
  const VU_ROWS = ['#ff4a6a', '#ff9a3c', GOLD, '#7fe8ff', CYAN];
  const VU_PATTERNS = ['53425342', '42515324', '35243152', '52315432'];
  VU_PATTERNS.forEach((pat, i) => {
    const frames = [...pat].map((lv, k) => `${n((k / pat.length) * 100)}%{transform:scaleY(${n(Number(lv) / 5)})}`).join('');
    css.push(`@keyframes vu${i}{${frames}100%{transform:scaleY(${n(Number(pat[0]) / 5)})}}.vu${i}{transform-box:fill-box;transform-origin:50% 100%;animation:vu${i} ${BEAT * 2}s step-end infinite}`);
    const bar = VU_ROWS.map((c, r) => `<path fill="${c}" d="M0 ${r}h3v1h-3z"/>`).join('');
    for (const vx of [left - 9 - i * 5, right + 6 + i * 5]) body.push(`<g transform="translate(${vx} ${STATUS_Y})"><g class="vu${i}">${bar}</g></g>`);
  });
}

// logo: halo, outline, extrusion, chrome faces, bevel edges
body.push(`<path fill="${BG}" fill-opacity=".85" d="${gridPath(halo)}"/>`);
for (let i = 0; i < W * H; i++) if (slots.a[i]) outline.a[i] = 1;
body.push(`<path fill="#000000" d="${gridPath(outline)}"/>`);
const allFace = new Grid(W, H);
[[ULTRA, 'chromeU', CHROME_U, EXTRUDE_U], [SATIS, 'chromeS', CHROME_S, EXTRUDE_S]].forEach(([wd, id, chrome, ext]) => {
  defs.push(rowGradient(id, wd.y0, chrome));
  ext.forEach((c, k) => body.push(`<path fill="${c}" d="${gridPath(wd.extrude, (v) => v === k + 1)}"/>`));
  body.push(`<path fill="url(#${id})" d="${gridPath(wd.face)}"/>`);
  for (let i = 0; i < W * H; i++) if (wd.face.a[i]) allFace.a[i] = 1;
});
const edge = (dx, dy) => cellsToPath((x, y) => allFace.get(x, y) && !allFace.get(x + dx, y + dy), W, H);
body.push(`<path fill="#ffffff" fill-opacity=".45" d="${edge(-1, 0)}"/>`);
body.push(`<path fill="#ffffff" fill-opacity=".8" d="${edge(0, -1)}"/>`);
body.push(`<path fill="#000000" fill-opacity=".35" d="${edge(1, 0)}"/>`);
body.push(`<path fill="#000000" fill-opacity=".4" d="${edge(0, 1)}"/>`);
{
  // one shine sweeps both rows every 7s
  defs.push(`<clipPath id="faceclip"><path d="${gridPath(allFace)}"/></clipPath>`);
  const top = LY1;
  const hgt = LY2 + SATIS.LH - LY1;
  const slant = Math.round(hgt * 0.42);
  const from = SATIS.x0 - 20;
  const to = SATIS.x0 + SATIS.width + slant + 20;
  css.push(`.shine{animation:shine 7s linear infinite}@keyframes shine{0%{transform:translateX(${from}px)}24%{transform:translateX(${to}px)}100%{transform:translateX(${to}px)}}`);
  body.push(`<g clip-path="url(#faceclip)"><path class="shine" fill="#ffffff" fill-opacity=".7" shape-rendering="auto" d="M0 ${top}h8l-${slant} ${hgt}h-8zM13 ${top}h3l-${slant} ${hgt}h-3z"/></g>`);

  const sparkle = 'M2 0h1v2h2v1h-2v2h-1v-2h-2v-1h2z';
  const ub = ULTRA.boxes;
  const sb = SATIS.boxes;
  const spots = [
    [ub[0].x + 1, LY1 - 1], [ub[4].x + ub[4].w - 3, LY1 - 1], [sb[0].x + 2, LY2 - 1],
    [sb[6].x + sb[6].w - 3, LY2 + 21], [sb[11].x + sb[11].w - 2, LY2 - 1], [ub[2].x + ub[2].w - 2, LY1 + 6], [sb[3].x + 3, LY2 + 21],
  ];
  spots.forEach(([x, y], i) => body.push(`<g transform="translate(${x - 2} ${y - 2})"><path class="spk" style="animation-delay:${n(i * 0.8)}s" fill="#ffffff" d="${sparkle}"/></g>`));
}

// hex-cog emblems either side of ULTRA; the right one turns the other way
{
  defs.push(`<g id="emb">${emblemBase.svg()}</g>`);
  EMBLEM_FRAMES.forEach((f, k) => defs.push(`<g id="cog${k}">${f.svg()}</g>`));
  [[EMB_L, [0, 1, 2, 3]], [EMB_R, [0, 3, 2, 1]]].forEach(([e, order]) => {
    const frames = order.map((f, k) => `<use class="fr f${k}" style="animation-delay:${n((k * BEAT) / 4 - BEAT)}s" href="#cog${f}"/>`).join('');
    body.push(`<g transform="translate(${e.x} ${e.y})"><use href="#emb"/>${frames}</g>`);
  });
}

// ---------------------------------------------------------------- factory
{
  const beltEnd = ELV.x + 4;
  // dark recesses behind the ports, so items slide into shadow
  let ports = '';
  for (const m of [SML, CON, ASM]) for (const px of [m.x, m.x + m.w - 5]) ports += `M${px} ${MY + 16}h5v10h-5z`;
  ports += `M${ELV.x + 4} ${ELV.y + 28}h4v10h-4z`;
  body.push(`<path fill="${DARK}" d="${ports}"/>`);

  // belt: lit surface, dark body with travelling cleats, struts to the floor
  let struts = '';
  for (let x = 12; x < beltEnd; x += 22) struts += `M${x} ${BELT_Y + 4}h2v${FLOOR_Y - BELT_Y - 4}h-2z`;
  body.push(`<path fill="#343a54" d="${struts}"/>`);
  body.push(`<path fill="#b4bedc" d="M0 ${BELT_Y}h${beltEnd}v1h-${beltEnd}z"/><path fill="#262b40" d="M0 ${BELT_Y + 1}h${beltEnd}v2h-${beltEnd}z"/><path fill="#10121c" d="M0 ${BELT_Y + 3}h${beltEnd}v1h-${beltEnd}z"/>`);
  let cleats = '';
  for (let x = -8; x < beltEnd; x += 8) cleats += `M${x} ${BELT_Y + 1}h2v2h-2z`;
  defs.push(`<clipPath id="bclip"><rect x="0" y="${BELT_Y}" width="${beltEnd}" height="4"/></clipPath>`);
  css.push(`.bt{animation:bt ${n(8 / BELT_SPEED)}s linear infinite}@keyframes bt{from{transform:translateX(0)}to{transform:translateX(8px)}}`);
  body.push(`<g clip-path="url(#bclip)"><path class="bt" fill="#5d6688" d="${cleats}"/></g>`);

  // items: three segments, each a repeating pattern that slides one pattern
  // length per loop
  for (const [name, s] of Object.entries(ITEMS)) defs.push(`<g id="i-${name}">${s.svg()}</g>`);
  const segments = [
    { id: 'a', x0: SML.x + SML.w - PORT, x1: CON.x + PORT, pattern: ['ingotFe', 'ingotCu'], pitch: SLOT },
    { id: 'b', x0: CON.x + CON.w - PORT, x1: ASM.x + PORT, pattern: ['plate', 'rods', 'screw', 'coil'], pitch: SLOT },
    { id: 'c', x0: ASM.x + ASM.w - PORT, x1: ELV.x + 8, pattern: ['frame'], pitch: SLOT * 2 },
  ];
  segments.forEach((seg) => {
    const period = seg.pattern.length * seg.pitch;
    let uses = '';
    for (let k = 0, x = seg.x1 - seg.pitch; x > seg.x0 - period - seg.pitch; k++, x -= seg.pitch) {
      const name = seg.pattern[((seg.pattern.length - 1 - k) % seg.pattern.length + seg.pattern.length) % seg.pattern.length];
      const s = ITEMS[name];
      uses += `<use href="#i-${name}" x="${x + Math.floor((seg.pitch - s.w) / 2)}" y="${BELT_Y - s.h}"/>`;
    }
    defs.push(`<clipPath id="seg${seg.id}"><rect x="${seg.x0}" y="${BELT_Y - 12}" width="${seg.x1 - seg.x0}" height="12"/></clipPath>`);
    css.push(`.b${seg.id}{animation:b${seg.id} ${n(period / BELT_SPEED)}s linear infinite}@keyframes b${seg.id}{from{transform:translateX(0)}to{transform:translateX(${period}px)}}`);
    body.push(`<g clip-path="url(#seg${seg.id})"><g class="b${seg.id}">${uses}</g></g>`);
  });

  // far-off chimney beacons, blinking out of step with each other
  SKYLINE.beacons.filter(clearOfMachines).forEach(([x, y], k) => body.push(`<path class="bl" style="animation-delay:${n(-((k * 0.37) % 1))}s" fill="#c8324e" d="M${x} ${y}h2v1h-2z"/>`));

  // behind the machines: the elevator pod
  {
    // the pod launches up the tether every 8 beats and leaves the frame
    const py = ELV.y + 9;
    const rise = py + 12;
    css.push(`.pod{animation:pod ${BEAT * 8}s cubic-bezier(.55,0,.9,.55) infinite}@keyframes pod{0%{transform:translateY(0)}12%{transform:translateY(0)}100%{transform:translateY(-${rise}px)}}`);
    body.push(`<g class="pod">${pod.svg(TETHER_X - 3, py)}</g>`);
  }

  body.push(`<g>${sml.svg(SML.x, MY)}${con.svg(CON.x, MY)}${asm.svg(ASM.x, MY)}${elv.svg(ELV.x, ELV.y)}${elvPlate.svg(ELV_PLATE.x, ELV.y + 38)}</g>`);

  css.push(
    `.lt{opacity:.12;animation:lt ${BEAT * 3}s step-end infinite}@keyframes lt{0%{opacity:1}33.33%{opacity:.12}100%{opacity:.12}}`,
    `.bl{animation:bl ${BEAT * 2}s step-end infinite}@keyframes bl{0%{opacity:1}50%{opacity:.15}100%{opacity:.15}}`,
  );
  const press = (x, y, w) => `<path fill="#7d88aa" d="M${x + w / 2 - 1} ${y - 9}h2v9h-2z"/><path fill="#e6ecff" d="M${x} ${y}h${w}v1h-${w}z"/><path fill="#8e9ac0" d="M${x} ${y + 1}h${w}v1h-${w}z"/>`;
  const puff = 'M1 0h2v1h1v2h-1v1h-2v-1h-1v-2h1z';
  css.push('.smk{opacity:0;animation:smk 1.8s linear infinite}@keyframes smk{0%{opacity:0;transform:translate(0,0)}12%{opacity:.75}100%{opacity:0;transform:translate(3px,-5px)}}');
  const smoke = (x, y, col) => [0, 0.6, 1.2].map((d) => `<g transform="translate(${x} ${y})"><path class="smk" style="animation-delay:${n(-d)}s" fill="${col}" d="${puff}"/></g>`).join('');
  // SMELTER: a furnace mouth full of fire (4-frame flipbook, seeded), a glow
  // that breathes on the beat and a smoking stack
  {
    const fw = 12;
    const fh = 11;
    const base = Array.from({ length: fw }, (_, x) => 4 + 4 * Math.sin(((x + 0.5) / fw) * Math.PI));
    const frames = [0, 1, 2, 3].map(() => {
      const f = new Sprite(fw, fh);
      for (let x = 0; x < fw; x++) {
        const hgt = Math.max(2, Math.min(fh, Math.round(base[x] + (rand() - 0.5) * 5)));
        for (let k = 0; k < hgt; k++) {
          const t = k / hgt;
          f.px(x, fh - 1 - k, t < 0.25 ? '#fff6c0' : t < 0.5 ? '#ffd23c' : t < 0.8 ? '#ff8a1e' : '#e0401a');
        }
      }
      return f;
    });
    body.push(`<g transform="translate(${SML.x + 10} ${MY + 11})">${frames.map((f, k) => `<g class="fr f${k}" style="animation-delay:${n((k * BEAT) / 4 - BEAT)}s">${f.svg()}</g>`).join('')}</g>`);
    css.push(`.glow{animation:glow ${BEAT}s ease-in-out infinite alternate}@keyframes glow{from{opacity:.25}to{opacity:.8}}`);
    body.push(`<path class="glow" fill="#ff8a1e" d="M${SML.x + 9} ${MY + 10}h14v1h-14zM${SML.x + 9} ${MY + 11}h1v12h-1zM${SML.x + 22} ${MY + 11}h1v12h-1z"/>`);
    body.push(smoke(SML.x + 6, MY - 5, '#8a93b4'));
  }
  // CONSTRUCTOR: a press that slams once per beat, a cap that jumps, sparks,
  // chasing lamps and chimney smoke
  {
    defs.push(`<clipPath id="cwin"><rect x="${CON.x + 17}" y="${MY + 11}" width="14" height="12"/></clipPath>`);
    css.push(
      `.pr{animation:pr ${BEAT}s linear infinite}@keyframes pr{0%{transform:translateY(0)}14%{transform:translateY(5px)}32%{transform:translateY(5px)}72%{transform:translateY(0)}100%{transform:translateY(0)}}`,
      `.cap{animation:cap ${BEAT}s linear infinite}@keyframes cap{0%{transform:translateY(0)}14%{transform:translateY(1px)}40%{transform:translateY(0)}100%{transform:translateY(0)}}`,
      `.sp{opacity:0;animation:sp ${BEAT}s linear infinite}@keyframes sp{0%{opacity:0}13%{opacity:0}15%{opacity:1}30%{opacity:1}40%{opacity:0}100%{opacity:0}}`,
    );
    body.push(`<g clip-path="url(#cwin)"><g class="pr">${press(CON.x + 20, MY + 12, 8)}</g></g>`);
    body.push(`<path class="sp" fill="#fff6a0" d="M${CON.x + 18} ${MY + 19}h1v1h-1zM${CON.x + 19} ${MY + 17}h1v1h-1zM${CON.x + 29} ${MY + 19}h1v1h-1zM${CON.x + 28} ${MY + 17}h1v1h-1z"/>`);
    body.push(`<path class="cap" fill="${STEEL_LT[1]}" d="M${CON.x + 18} ${MY + 2}h12v1h-12z"/>`);
    ['#5dff9a', GOLD, '#ff5a6e'].forEach((c, k) => body.push(`<path class="lt" style="animation-delay:${n(k * BEAT - BEAT * 3)}s" fill="${c}" d="M${CON.x + 9} ${MY + 11 + k * 3}h2v2h-2z"/>`));
  }
  // ASSEMBLER: two arms taking turns (one per beat), a 6-tooth flywheel that
  // turns one tooth per beat, lamps and a blinking mast
  {
    const frames = [0, 1, 2, 3].map((k) => cogSprite(cogGrid(15, 7, 7, 6, 4.6, 7.3, 1.8, 30, k * 15), ['#ff6bb5', '#ffd0ea', '#9a1f62']));
    body.push(`<g transform="translate(${ASM.x + 15} ${MY - 7})">${frames.map((f, k) => `<g class="fr f${k}" style="animation-delay:${n((k * BEAT) / 4 - BEAT)}s">${f.svg()}</g>`).join('')}</g>`);
    css.push(`.arm{animation:arm ${BEAT * 2}s linear infinite}@keyframes arm{0%{transform:translateY(0)}7%{transform:translateY(5px)}18%{transform:translateY(5px)}40%{transform:translateY(0)}100%{transform:translateY(0)}}`);
    [7, 27].forEach((wx, k) => {
      const x = ASM.x + wx;
      defs.push(`<clipPath id="awin${k}"><rect x="${x}" y="${MY + 11}" width="10" height="12"/></clipPath>`);
      body.push(`<g clip-path="url(#awin${k})"><g class="arm" style="animation-delay:${n(-k * BEAT)}s">${press(x + 2, MY + 12, 6)}</g></g>`);
    });
    [PINK, PURPLE, CYAN, GOLD].forEach((c, k) => body.push(`<path class="lt" style="animation:lt ${BEAT * 4}s step-end ${n(k * BEAT - BEAT * 4)}s infinite" fill="${c}" d="M${ASM.x + 21} ${MY + 11 + k * 3}h2v2h-2z"/>`));
    body.push(`<path class="bl" fill="#ff5a6e" d="M${ASM.x + 39} ${MY}h3v2h-3z"/>`);
  }
  // ELEVATOR: lamps round the base and a beacon that blinks every other beat
  [[11, '#5dff9a', 0], [23, CYAN, 1], [26, PINK, 2]].forEach(([lx, c, k]) => body.push(`<path class="lt" style="animation-delay:${n(k * BEAT - BEAT * 3)}s" fill="${c}" d="M${ELV.x + lx} ${ELV.y + 31}h2v2h-2z"/>`));
  body.push(`<path class="bl" fill="${CYAN}" d="M${ELV.x + 14} ${ELV.y + 10}h6v3h-6z"/><path class="bl" fill="#d8fbff" d="M${ELV.x + 14} ${ELV.y + 10}h6v1h-6z"/>`);
}

// scroller
{
  defs.push(rowGradient('sg', 0, SCROLL_COLORS));
  const used = new Set(scrollChars.filter((c) => c !== ' '));
  for (const c of used) {
    const g = F8[c];
    if (!g) throw new Error(`scroll font lacks ${JSON.stringify(c)}`);
    const on = (x, y) => (g[y] || '')[x] === '#';
    const shadow = cellsToPath((x, y) => on(x - 1, y - 1) && !on(x, y), 9, 9);
    defs.push(`<g id="c${c.charCodeAt(0)}"><path fill="#1c1a5e" d="${shadow}"/><path fill="url(#sg)" d="${cellsToPath(on, 8, 8)}"/></g>`);
  }
  const groups = Array.from({ length: PHASES }, () => []);
  const place = (c, i, x) => { if (c !== ' ') groups[i % PHASES].push(`<use href="#c${c.charCodeAt(0)}" x="${x}"/>`); };
  scrollChars.forEach((c, i) => place(c, i, SCROLL_X0 + i * 8));
  const tail = Math.ceil(W / 8) + 1;
  for (let i = 0; i < tail; i++) place(scrollChars[i], i + scrollChars.length, SCROLL_X0 + SCROLL_LEN + i * 8);
  const g = groups.map((uses, j) => {
    const x0 = SCROLL_X0 + j * 8 + 4; // glyph centre
    const d = PERIOD * (((x0 / WAVE + 0.25) % 1 + 1) % 1) - PERIOD;
    return `<g style="animation:sw ${n(PERIOD / 2)}s cubic-bezier(.37,0,.63,1) ${n(d)}s infinite alternate">${uses.join('')}</g>`;
  }).join('');
  body.push(`<g class="aa" transform="translate(0 ${SCROLL_Y})"><g class="scr">${g}</g></g>`);
  // soft edges so glyphs slide in and out of the dark
  defs.push(`<linearGradient id="fadeL"><stop offset="0" stop-color="${BG}"/><stop offset="1" stop-color="${BG}" stop-opacity="0"/></linearGradient>`);
  defs.push(`<linearGradient id="fadeR"><stop offset="0" stop-color="${BG}" stop-opacity="0"/><stop offset="1" stop-color="${BG}"/></linearGradient>`);
  body.push(`<rect y="${FLOOR_Y + 1}" width="6" height="${STATUS_Y - FLOOR_Y - 3}" fill="url(#fadeL)"/><rect x="${W - 6}" y="${FLOOR_Y + 1}" width="6" height="${STATUS_Y - FLOOR_Y - 3}" fill="url(#fadeR)"/>`);
}

css.push('.aa{shape-rendering:geometricPrecision}');
css.push('@media (prefers-reduced-motion:reduce){*{animation:none!important}.spk,.sp,.smk{opacity:0}.lt{opacity:1}}');

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W * 3}" height="${H * 3}" shape-rendering="crispEdges" role="img" aria-labelledby="t">
<title id="t">ULTRA-SATISFACTORY: an Amiga demoscene-style intro with a chrome logo, copper bars, a conveyor-belt factory, a Space Elevator and a sine scroller</title>
<style>${css.join('')}</style>
<defs>${defs.join('')}</defs>
<g clip-path="url(#panel)">${body.join('\n')}</g>
</svg>
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
console.log(`wrote ${path.relative(process.cwd(), OUT)} (${(svg.length / 1024).toFixed(1)} KB), scroll ${scrollChars.length} chars, loop ${n(SCROLL_T)}s`);

// ------------------------------------------------ closing conveyor rule SVG
// A strip of belt that closes the header: one of everything rides past, over a
// colour-cycling floor line. Slides exactly one pattern length per loop.
{
  const RH = 16;
  const by = 11; // belt surface row
  const order = ['ingotFe', 'plate', 'screw', 'frame', 'ingotCu', 'rods', 'coil', 'frame'];
  const period = order.length * SLOT;
  const itemDefs = Object.entries(ITEMS).map(([name, s]) => `<g id="i-${name}">${s.svg()}</g>`).join('');
  let uses = '';
  for (let k = 0, x = -period; x < W; k++, x += SLOT) {
    const name = order[k % order.length];
    const s = ITEMS[name];
    uses += `<use href="#i-${name}" x="${x + Math.floor((SLOT - s.w) / 2)}" y="${by - s.h}"/>`;
  }
  let cleats = '';
  for (let x = -8; x < W; x += 8) cleats += `M${x} ${by + 1}h2v2h-2z`;
  const floor = HUES.map((c, h) => {
    let d = '';
    for (let m = 0; m < 7; m++) d += `M${h * 4 + m * 64} ${RH - 1}h4v1h-4z`;
    return `<path fill="${c}" d="${d}"/>`;
  }).join('');
  const rule = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${RH}" width="${W * 3}" height="${RH * 3}" shape-rendering="crispEdges" role="img" aria-labelledby="t">
<title id="t">A conveyor belt carrying pixel ingots, plates, screws and frames</title>
<style>.it{animation:it ${n(period / BELT_SPEED)}s linear infinite}@keyframes it{from{transform:translateX(0)}to{transform:translateX(${period}px)}}.bt{animation:bt ${n(8 / BELT_SPEED)}s linear infinite}@keyframes bt{from{transform:translateX(0)}to{transform:translateX(8px)}}.rb{animation:rb 1.6s linear infinite}@keyframes rb{from{transform:translateX(0)}to{transform:translateX(-64px)}}@media (prefers-reduced-motion:reduce){*{animation:none!important}}</style>
<defs><clipPath id="c"><rect width="${W}" height="${RH}" rx="3"/></clipPath>${itemDefs}</defs>
<g clip-path="url(#c)"><rect width="${W}" height="${RH}" fill="${BG}"/>
<path fill="#b4bedc" d="M0 ${by}h${W}v1h-${W}z"/><path fill="#262b40" d="M0 ${by + 1}h${W}v2h-${W}z"/><path fill="#10121c" d="M0 ${by + 3}h${W}v1h-${W}z"/>
<path class="bt" fill="#5d6688" d="${cleats}"/>
<g class="it">${uses}</g>
<g class="rb">${floor}</g></g>
</svg>
`;
  fs.writeFileSync(RULE, rule);
  console.log(`wrote ${path.relative(process.cwd(), RULE)} (${(rule.length / 1024).toFixed(1)} KB)`);
}
