// Win32 "new old-school" cracktro README banner for ULTRA-SATISFACTORY.
//
//   node examples/ultra-satisfactory/src/11-win32-cracktro_opus_5.5.mjs
//   node examples/ultra-satisfactory/src/11-win32-cracktro_opus_5.5.mjs --ascii
//
// Regenerates ../assets/11-win32-cracktro_opus_5.5.svg. With --ascii it also
// prints the text-mode twister used in the .md's NFO block (same maths as the
// SVG one). Plain Node, no deps, deterministic (seeded PRNG, no clock).
//
// The look is the 2004-2011 Windows cracktro revival: a bevelled, extruded
// vector-chrome logo standing on a mirror floor, a sine-twister each side, a
// text-writer block and a dot-matrix sine scroller. The factory reading: the
// twisters are square girders (hazard tape, riveted plate, a light bar and a
// lattice face) being wrung out between two chucks.
//
// Everything is drawn from geometry defined in this file: the logo letters are
// parametric polygons (no font), the small type is a 5x7 bitmap font drawn as
// paths, the scroller is the same font as round dots. No <text>, no filters.
// (The .md beside the assets is hand-edited, not generated by this script.)
//
// Loop maths
//   Twister: a square column whose rotation angle at row y and time t is
//   theta(t + y*d), one periodic function sampled into two @keyframes (one
//   per pair of opposite faces: left edge, width, brightness, and which of
//   the two is showing). Every row is two <g> elements sharing those
//   keyframes with a negative animation-delay, so the twist travels along the
//   column and the loop is seamless. 60 rows x 2 x 2 columns = 240 animated
//   elements; that count is what the banner costs to play, so keep it low.
//   Scroller: moves at SPEED px/s through a stationary sine, PHASES characters
//   long. Characters that share a phase (index mod PHASES) share one bobbing
//   <g>. The text is padded to a whole number of wavelengths and its head is
//   repeated after the tail, so the wrap is invisible.
//   Text-writer: three pages on one timeline. Page 1 is already typed at t=0
//   (so the first frame, and the reduced-motion frame, is complete) and
//   re-types at the end of the loop. Typing is a floor-coloured cover stepping
//   away one character at a time, with the cursor riding its leading edge.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '../assets/11-win32-cracktro_opus_5.5.svg');

const W = 900;
const H = 430;
const FLOOR = 191; // y of the mirror floor's far edge (the logo stands on it)
const BG = '#04050b';
const FLOOR_STOPS = [[0, '#0b1830'], [0.22, '#070d1c'], [0.6, '#04060d'], [1, '#030409']];

// App palette (the app's own neon)
const CYAN = '#00cfff';
const GOLD = '#e8d44d';
const PURPLE = '#a855f7';
const PINK = '#ec4899';
const BLUE = '#38bdf8';

// ---------------------------------------------------------------- utilities
function mulberry32(seed) {
  return () => {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(0x70c9);
const n = (v, d = 2) => String(+(+v).toFixed(d));
const n1 = (v) => n(v, 1);
function lerpHex(a, b, t) {
  const pa = [1, 3, 5].map((i) => parseInt(a.slice(i, i + 2), 16));
  const pb = [1, 3, 5].map((i) => parseInt(b.slice(i, i + 2), 16));
  return `#${pa.map((v, i) => Math.round(v + (pb[i] - v) * t).toString(16).padStart(2, '0')).join('')}`;
}
const polyD = (p) => `M${p.map(([x, y]) => `${n1(x)} ${n1(y)}`).join('L')}Z`;
const stops = (list) => list.map(([o, c, a]) => `<stop offset="${o}" stop-color="${c}"${a === undefined ? '' : ` stop-opacity="${a}"`}/>`).join('');
const vgrad = (id, y0, y1, list) => `<linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="0" y1="${n1(y0)}" x2="0" y2="${n1(y1)}">${stops(list)}</linearGradient>`;
const hgrad = (id, x0, x1, list) => `<linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="${n1(x0)}" y1="0" x2="${n1(x1)}" y2="0">${stops(list)}</linearGradient>`;

const defs = [];
const css = [];

// ---------------------------------------------------------------- 5x7 font
// Rows top to bottom, '#' = lit. An optional 8th row is the descender.
const FONT = {
  A: '.###.|#...#|#...#|#...#|#####|#...#|#...#', B: '####.|#...#|#...#|####.|#...#|#...#|####.',
  C: '.###.|#...#|#....|#....|#....|#...#|.###.', D: '###..|#..#.|#...#|#...#|#...#|#..#.|###..',
  E: '#####|#....|#....|####.|#....|#....|#####', F: '#####|#....|#....|####.|#....|#....|#....',
  G: '.###.|#...#|#....|#.###|#...#|#...#|.####', H: '#...#|#...#|#...#|#####|#...#|#...#|#...#',
  I: '.###.|..#..|..#..|..#..|..#..|..#..|.###.', J: '..###|...#.|...#.|...#.|...#.|#..#.|.##..',
  K: '#...#|#..#.|#.#..|##...|#.#..|#..#.|#...#', L: '#....|#....|#....|#....|#....|#....|#####',
  M: '#...#|##.##|#.#.#|#.#.#|#...#|#...#|#...#', N: '#...#|#...#|##..#|#.#.#|#..##|#...#|#...#',
  O: '.###.|#...#|#...#|#...#|#...#|#...#|.###.', P: '####.|#...#|#...#|####.|#....|#....|#....',
  Q: '.###.|#...#|#...#|#...#|#.#.#|#..#.|.##.#', R: '####.|#...#|#...#|####.|#.#..|#..#.|#...#',
  S: '.####|#....|#....|.###.|....#|....#|####.', T: '#####|..#..|..#..|..#..|..#..|..#..|..#..',
  U: '#...#|#...#|#...#|#...#|#...#|#...#|.###.', V: '#...#|#...#|#...#|#...#|#...#|.#.#.|..#..',
  W: '#...#|#...#|#...#|#.#.#|#.#.#|#.#.#|.#.#.', X: '#...#|#...#|.#.#.|..#..|.#.#.|#...#|#...#',
  Y: '#...#|#...#|#...#|.#.#.|..#..|..#..|..#..', Z: '#####|....#|...#.|..#..|.#...|#....|#####',
  a: '.....|.....|.###.|....#|.####|#...#|.####', b: '#....|#....|#.##.|##..#|#...#|#...#|####.',
  c: '.....|.....|.###.|#....|#....|#...#|.###.', d: '....#|....#|.##.#|#..##|#...#|#...#|.####',
  e: '.....|.....|.###.|#...#|#####|#....|.###.', f: '..##.|.#..#|.#...|###..|.#...|.#...|.#...',
  g: '.....|.....|.####|#...#|#...#|.####|....#|.###.', h: '#....|#....|#.##.|##..#|#...#|#...#|#...#',
  i: '..#..|.....|.##..|..#..|..#..|..#..|.###.', j: '...#.|.....|..##.|...#.|...#.|...#.|#..#.|.##..',
  k: '#....|#....|#..#.|#.#..|##...|#.#..|#..#.', l: '.##..|..#..|..#..|..#..|..#..|..#..|.###.',
  m: '.....|.....|##.#.|#.#.#|#.#.#|#.#.#|#...#', n: '.....|.....|#.##.|##..#|#...#|#...#|#...#',
  o: '.....|.....|.###.|#...#|#...#|#...#|.###.', p: '.....|.....|####.|#...#|#...#|####.|#....|#....',
  q: '.....|.....|.####|#...#|#...#|.####|....#|....#', r: '.....|.....|#.##.|##..#|#....|#....|#....',
  s: '.....|.....|.####|#....|.###.|....#|####.', t: '.#...|.#...|###..|.#...|.#...|.#..#|..##.',
  u: '.....|.....|#...#|#...#|#...#|#..##|.##.#', v: '.....|.....|#...#|#...#|#...#|.#.#.|..#..',
  w: '.....|.....|#...#|#...#|#.#.#|#.#.#|.#.#.', x: '.....|.....|#...#|.#.#.|..#..|.#.#.|#...#',
  y: '.....|.....|#...#|#...#|#...#|.####|....#|.###.', z: '.....|.....|#####|...#.|..#..|.#...|#####',
  0: '.###.|#...#|#..##|#.#.#|##..#|#...#|.###.', 1: '..#..|.##..|..#..|..#..|..#..|..#..|.###.',
  2: '.###.|#...#|....#|...#.|..#..|.#...|#####', 3: '#####|...#.|..#..|...#.|....#|#...#|.###.',
  4: '...#.|..##.|.#.#.|#..#.|#####|...#.|...#.', 5: '#####|#....|####.|....#|....#|#...#|.###.',
  6: '..##.|.#...|#....|####.|#...#|#...#|.###.', 7: '#####|....#|...#.|..#..|.#...|.#...|.#...',
  8: '.###.|#...#|#...#|.###.|#...#|#...#|.###.', 9: '.###.|#...#|#...#|.####|....#|...#.|.##..',
  '!': '..#..|..#..|..#..|..#..|..#..|.....|..#..', "'": '..#..|..#..|.#...|.....|.....|.....|.....',
  '(': '...#.|..#..|.#...|.#...|.#...|..#..|...#.', ')': '.#...|..#..|...#.|...#.|...#.|..#..|.#...',
  '*': '.....|..#..|#.#.#|.###.|#.#.#|..#..|.....', '+': '.....|..#..|..#..|#####|..#..|..#..|.....',
  ',': '.....|.....|.....|.....|.##..|..#..|.#...', '-': '.....|.....|.....|#####|.....|.....|.....',
  '.': '.....|.....|.....|.....|.....|.##..|.##..', '/': '....#|....#|...#.|..#..|.#...|#....|#....',
  ':': '.....|.##..|.##..|.....|.##..|.##..|.....', '>': '.#...|..#..|...#.|....#|...#.|..#..|.#...',
  '?': '.###.|#...#|....#|...#.|..#..|.....|..#..', '[': '.###.|.#...|.#...|.#...|.#...|.#...|.###.',
  ']': '.###.|...#.|...#.|...#.|...#.|...#.|.###.', '·': '.....|.....|.....|.##..|.##..|.....|.....',
};
for (const [ch, src] of Object.entries(FONT)) {
  const rows = src.split('|');
  if (rows.some((r) => r.length !== 5) || rows.length < 7 || rows.length > 8) throw new Error(`bad glyph ${ch}`);
  FONT[ch] = rows;
}
const gid = (prefix, ch) => `${prefix}${ch.codePointAt(0).toString(36)}`;

// Lit cells as a compact path: horizontal runs, merged down rows.
function cellsPath(rows) {
  const rects = [];
  let active = new Map();
  rows.forEach((row, y) => {
    const next = new Map();
    let x = 0;
    while (x < row.length) {
      if (row[x] !== '#') { x++; continue; }
      let x1 = x;
      while (x1 < row.length && row[x1] === '#') x1++;
      const key = `${x},${x1}`;
      const r = active.get(key);
      if (r) { r.h++; next.set(key, r); } else { const nr = { x, y, w: x1 - x, h: 1 }; rects.push(nr); next.set(key, nr); }
      x = x1;
    }
    active = next;
  });
  return rects.map((r) => `M${r.x} ${r.y}h${r.w}v${r.h}h${-r.w}z`).join('');
}
// Glyph <defs> are emitted once per prefix ('t' pixel type, 'p' dot-matrix),
// only for the characters actually used.
const usedGlyphs = { t: new Set(), p: new Set() };
function needGlyph(prefix, ch) {
  if (ch === ' ') return null;
  if (!FONT[ch]) throw new Error(`no glyph for "${ch}"`);
  usedGlyphs[prefix].add(ch);
  return gid(prefix, ch);
}

// Small type: 5x7 pixels at PX user units each, as <use> of per-glyph paths.
const PX = 2;
function textUses(str, col0 = 0, cell = 6) {
  let s = '';
  [...str].forEach((ch, i) => {
    const id = needGlyph('t', ch);
    if (id) s += `<use href="#${id}" x="${(col0 + i) * cell}"/>`;
  });
  return s;
}

// ================================================================ background
defs.push(`<clipPath id="panel"><rect width="${W}" height="${H}" rx="12"/></clipPath>`);
defs.push(`<radialGradient id="sky" gradientUnits="userSpaceOnUse" cx="${W / 2}" cy="112" r="430" gradientTransform="translate(0 112) scale(1 .55) translate(0 -112)">${stops([[0, '#12305a'], [0.45, '#0a1730'], [1, BG]])}</radialGradient>`);
const backSvg = `<rect width="${W}" height="${H}" fill="${BG}"/><rect width="${W}" height="${FLOOR + 4}" fill="url(#sky)"/>`;

// ---------------------------------------------------------------- starfield
// A 3D starfield flying outward from behind the logo: each star is a short
// streak on its own spoke, accelerating and stretching as it leaves.
let starSvg = '';
{
  const N = 44;
  const DUR = [2.6, 3.4, 4.4];
  const TINT = ['#fff', '#bfefff', '#fff', '#ffe9a6'];
  defs.push('<rect id="sr" y="-.7" width="4" height="1.4"/>');
  for (let i = 0; i < N; i++) {
    // Upper half-plane plus a little below the horizon; the floor hides the rest.
    const a = 172 + rand() * 196;
    const delay = -(rand() * DUR[i % 3]);
    starSvg += `<g transform="rotate(${n1(a)})"><use href="#sr" class="st s${i % 3}" fill="${TINT[i % 4]}" style="animation-delay:${n(delay)}s"/></g>`;
  }
  defs.push(`<clipPath id="skyclip"><rect x="98" width="${W - 196}" height="${FLOOR}"/></clipPath>`);
  starSvg = `<g clip-path="url(#skyclip)"><g transform="translate(${W / 2} 108)">${starSvg}</g></g>`;
  css.push(`.st{opacity:0;animation:st 3s cubic-bezier(.55,0,.9,.5) infinite}${DUR.map((d, i) => `.s${i}{animation-duration:${d}s}`).join('')}`
    + '@keyframes st{0%{transform:translateX(26px) scaleX(.3);opacity:0}12%{opacity:.75}100%{transform:translateX(470px) scaleX(4.5);opacity:1}}');
}

// ---------------------------------------------------------------- mirror floor
defs.push(vgrad('floor', FLOOR, H, FLOOR_STOPS));
defs.push(hgrad('hz', 96, W - 96, [[0, '#7fe3ff', 0], [0.2, '#7fe3ff', 0.55], [0.5, '#e8fbff', 1], [0.8, '#7fe3ff', 0.55], [1, '#7fe3ff', 0]]));
defs.push(`<radialGradient id="hzglow">${stops([[0, CYAN, 0.26], [0.6, CYAN, 0.08], [1, CYAN, 0]])}</radialGradient>`);
const floorSvg = `<rect y="${FLOOR}" width="${W}" height="${H - FLOOR}" fill="url(#floor)"/>`;
const horizonGlow = `<ellipse cx="${W / 2}" cy="${FLOOR}" rx="345" ry="22" fill="url(#hzglow)"/>`;
const horizonLine = `<rect x="96" y="${n1(FLOOR - 0.2)}" width="${W - 192}" height="1.3" fill="url(#hz)"/>`;

// ================================================================ chrome logo
// Parametric block capitals: w/h cell, s stem, t bar, c chamfer. Each glyph is
// a list of polygons (first is the outline, the rest are counters). Original
// letterforms, drawn for this banner.
function glyph(ch, { w, h, s, t, c }) {
  const ci = c * 0.55;
  switch (ch) {
    case 'U': return { adv: w, polys: [[[0, 0], [s, 0], [s, h - t - ci], [s + ci, h - t], [w - s - ci, h - t], [w - s, h - t - ci], [w - s, 0], [w, 0], [w, h - c], [w - c, h], [c, h], [0, h - c]]] };
    case 'L': { const lw = w * 0.86; return { adv: lw, polys: [[[0, 0], [s, 0], [s, h - t], [lw, h - t], [lw, h], [c, h], [0, h - c]]] }; }
    case 'T': { const a = (w - s) / 2, b = (w + s) / 2; return { adv: w, polys: [[[0, 0], [w, 0], [w, t], [b, t], [b, h], [a, h], [a, t], [0, t]]] }; }
    case 'R': {
      const m = Math.round(h * 0.57), lw = s * 1.08, a = s + (w - 2 * s) * 0.22;
      return { adv: w, polys: [
        [[0, 0], [w - c, 0], [w, c], [w, m - c], [w - c, m], [a + lw, m], [w, h], [w - lw, h], [a, m], [s, m], [s, h], [0, h]],
        [[s, t], [w - s - ci, t], [w - s, t + ci], [w - s, m - t - ci], [w - s - ci, m - t], [s, m - t]],
      ] };
    }
    case 'A': {
      const ca = w * 0.28, m1 = h * 0.56, cj = ca * 0.42, bt = t * 0.9;
      return { adv: w, polys: [
        [[ca, 0], [w - ca, 0], [w, ca], [w, h], [w - s, h], [w - s, m1 + bt], [s, m1 + bt], [s, h], [0, h], [0, ca]],
        [[s + cj, t], [w - s - cj, t], [w - s, t + cj], [w - s, m1], [s, m1], [s, t + cj]],
      ] };
    }
    case 'S': {
      const a = (h - t) / 2, b = (h + t) / 2;
      return { adv: w, polys: [[[c, 0], [w, 0], [w, t], [s, t], [s, a], [w - c, a], [w, a + c], [w, h - c], [w - c, h], [0, h], [0, h - t], [w - s, h - t], [w - s, b], [c, b], [0, b - c], [0, c]]] };
    }
    case 'I': { const iw = s * 1.05; return { adv: iw, polys: [[[0, 0], [iw, 0], [iw, h], [0, h]]] }; }
    case 'F': { const fw = w * 0.92, m = h * 0.42, bt = t * 0.9; return { adv: fw, polys: [[[0, 0], [fw, 0], [fw, t], [s, t], [s, m], [fw * 0.8, m], [fw * 0.8, m + bt], [s, m + bt], [s, h], [0, h]]] }; }
    case 'C': return { adv: w, polys: [[[c, 0], [w, 0], [w, t], [s, t], [s, h - t], [w, h - t], [w, h], [c, h], [0, h - c], [0, c]]] };
    case 'O': return { adv: w, polys: [
      [[c, 0], [w - c, 0], [w, c], [w, h - c], [w - c, h], [c, h], [0, h - c], [0, c]],
      [[s + ci, t], [w - s - ci, t], [w - s, t + ci], [w - s, h - t - ci], [w - s - ci, h - t], [s + ci, h - t], [s, h - t - ci], [s, t + ci]],
    ] };
    case 'Y': {
      const sa = s * 1.1, jy = h * 0.52, a = (w - s) / 2, b = (w + s) / 2, vy = jy * (w / 2 - sa) / a;
      return { adv: w, polys: [[[0, 0], [sa, 0], [w / 2, vy], [w - sa, 0], [w, 0], [b, jy], [b, h], [a, h], [a, jy]]] };
    }
    default: throw new Error(`no logo glyph ${ch}`);
  }
}
const area2 = (p) => p.reduce((a, [x1, y1], i) => { const [x2, y2] = p[(i + 1) % p.length]; return a + x1 * y2 - x2 * y1; }, 0);
// Normalise winding so the metal is always on the right of each edge
// (outlines clockwise on screen, counters anticlockwise).
const wind = (p, clockwise) => ((area2(p) > 0) === clockwise ? p : [...p].reverse());
// Unit normal pointing into the metal, per edge.
function edgeNormals(p) {
  return p.map(([x1, y1], i) => {
    const [x2, y2] = p[(i + 1) % p.length];
    const dx = x2 - x1, dy = y2 - y1, l = Math.hypot(dx, dy);
    return [-dy / l, dx / l];
  });
}
// Mitred inset of a polygon by b, towards the metal.
function inset(p, b) {
  const nn = edgeNormals(p);
  return p.map(([x, y], i) => {
    const a = nn[(i + p.length - 1) % p.length], c = nn[i];
    const k = b / Math.max(0.35, 1 + a[0] * c[0] + a[1] * c[1]);
    return [x + (a[0] + c[0]) * k, y + (a[1] + c[1]) * k];
  });
}

const LIGHT = [-0.55, -0.835]; // towards the light: up and to the left
const PAL = {
  u: { // cyan chrome for ULTRA
    sky: [[0, '#0077c2'], [0.5, '#22c4f7'], [0.85, '#c8f6ff'], [1, '#ffffff']],
    ground: [[0, '#020d1f'], [0.3, '#063a66'], [0.75, '#00bdf2'], [1, '#d4f8ff']],
    bevel: ['#03395e', '#1fb7ea', '#f0fdff'], ext: ['#04182b', '#0a4d78'], rim: '#9feaff',
  },
  s: { // silver chrome for SATISFACTORY
    sky: [[0, '#5d6f8e'], [0.5, '#b4c0d3'], [0.85, '#f1f5fa'], [1, '#ffffff']],
    ground: [[0, '#0a0c12'], [0.3, '#363e4f'], [0.75, '#b0bace'], [1, '#fbfcfe']],
    bevel: ['#2a3140', '#9aa5b8', '#ffffff'], ext: ['#12161f', '#465066'], rim: '#ffffff',
  },
};
const ROWS = [
  { id: 'u', text: 'ULTRA', y: 31, h: 72, w: 82, s: 25, t: 18, c: 9, gap: 12, k: 0.16, bevel: 3.4, depth: [5, 8], kern: { LT: -10, RA: -2 } },
  { id: 's', text: 'SATISFACTORY', y: 117, h: 65, w: 48, s: 14.5, t: 13, c: 6, gap: 7.5, k: 0.16, bevel: 2.6, depth: [5, 8], kern: { AT: -3, FA: -3, CT: -1, TO: -1, RY: -1 } },
];
const KEY = '#02030a'; // keyline around the metal

function buildRow(row) {
  const pal = PAL[row.id];
  const glyphs = [...row.text].map((ch) => glyph(ch, row));
  let total = 0;
  const xs = glyphs.map((g, i) => {
    if (i) total += row.gap + (row.kern[row.text[i - 1] + row.text[i]] || 0);
    const x = total; total += g.adv; return x;
  });
  const lean = row.h * row.k; // the italic: tops sit this far right of the feet
  const x0 = (W - total - lean) / 2;
  const x1 = x0 + total + lean;
  const tf = (gx) => ([x, y]) => [x0 + gx + x + (row.h - y) * row.k, row.y + y];
  const polys = []; // screen-space polygons, wound
  glyphs.forEach((g, i) => g.polys.forEach((p, j) => polys.push(wind(p.map(tf(xs[i])), j === 0))));

  // extrusion walls: edges whose outward normal faces the depth direction
  const [dx, dy] = row.depth;
  const dl = Math.hypot(dx, dy);
  const walls = new Map();
  let wallsAll = '';
  for (const p of polys) {
    const nn = edgeNormals(p);
    p.forEach((a, i) => {
      const b = p[(i + 1) % p.length];
      const ox = -nn[i][0], oy = -nn[i][1];
      if ((ox * dx + oy * dy) / dl <= 0.02) return;
      const q = polyD([a, b, [b[0] + dx, b[1] + dy], [a[0] + dx, a[1] + dy]]);
      // right-facing walls catch a little light, floor-facing walls are darkest
      const shade = Math.round(Math.max(0, Math.min(1, ox * 0.9 + 0.1)) * 4) / 4;
      const col = lerpHex(pal.ext[0], pal.ext[1], shade);
      walls.set(col, (walls.get(col) || '') + q);
      wallsAll += q;
    });
  }
  // bevel: a quad per edge between the outline and the inset face
  const faces = polys.map((p) => inset(p, row.bevel));
  const bevels = new Map();
  let rim = '';
  polys.forEach((p, pi) => {
    const nn = edgeNormals(p);
    const f = faces[pi];
    p.forEach((a, i) => {
      const j = (i + 1) % p.length;
      const lit = -(nn[i][0] * LIGHT[0] + nn[i][1] * LIGHT[1]); // outward normal . light
      const q = Math.round(lit * 4) / 4;
      const col = q >= 0 ? lerpHex(pal.bevel[1], pal.bevel[2], q) : lerpHex(pal.bevel[1], pal.bevel[0], -q);
      bevels.set(col, (bevels.get(col) || '') + polyD([a, p[j], f[j], f[i]]));
      if (lit > 0.5) rim += `M${n1(f[i][0])} ${n1(f[i][1])}L${n1(f[j][0])} ${n1(f[j][1])}`;
    });
  });

  const top = row.y + row.bevel, bot = row.y + row.h - row.bevel;
  const hor = row.y + row.h * 0.61;
  const id = row.id;
  defs.push(`<path id="o${id}" d="${polys.map(polyD).join('')}"/><path id="f${id}" d="${faces.map(polyD).join('')}"/><path id="w${id}" d="${wallsAll}"/>`);
  defs.push(vgrad(`sk${id}`, top, hor + 3, pal.sky));
  defs.push(vgrad(`gd${id}`, hor - 4, bot, pal.ground));
  defs.push(`<clipPath id="fc${id}"><use href="#f${id}" clip-rule="evenodd"/></clipPath>`);

  // The chrome's horizon is a factory skyline: sheds, tanks and the odd chimney.
  let ground = `M${n1(x0 - 8)} ${n1(bot + 2)}L${n1(x0 - 8)} ${n1(hor)}`;
  let skyline = `M${n1(x0 - 8)} ${n1(hor)}`;
  let x = x0 - 8;
  const unit = row.h / 70;
  while (x < x1 + 8) {
    const chimney = rand() < 0.18;
    const wd = chimney ? 3.5 : 9 + rand() * 20;
    const up = (chimney ? 9 + rand() * 4 : [0, 0, 2.5, 4, 6][Math.floor(rand() * 5)]) * unit;
    const seg = `L${n1(x)} ${n1(hor - up)}L${n1(x + wd)} ${n1(hor - up)}`;
    ground += seg; skyline += seg;
    x += wd;
  }
  ground += `L${n1(x)} ${n1(bot + 2)}Z`;
  // brushed streaks: a few hairlines in the sky half
  let streaks = '';
  for (let i = 0; i < 16; i++) {
    const sx = x0 + rand() * (x1 - x0), sy = top + 3 + rand() * (hor - top - 12), sw = 30 + rand() * 90;
    streaks += `M${n1(sx)} ${n1(sy)}h${n1(sw)}`;
  }

  let g = `<g id="row${id}">`;
  g += `<g fill="${KEY}" stroke="${KEY}" stroke-width="3.2" stroke-linejoin="round"><use href="#o${id}" fill-rule="evenodd"/><use href="#w${id}"/></g>`;
  for (const [col, d] of walls) g += `<path d="${d}" fill="${col}" stroke="${col}" stroke-width=".6" stroke-linejoin="round"/>`;
  g += `<use href="#o${id}" fill-rule="evenodd" fill="${pal.bevel[1]}"/>`;
  for (const [col, d] of bevels) g += `<path d="${d}" fill="${col}"/>`;
  g += `<use href="#f${id}" fill-rule="evenodd" fill="url(#sk${id})"/>`;
  g += `<g clip-path="url(#fc${id})"><path d="${streaks}" stroke="#fff" stroke-opacity=".22" stroke-width=".8" fill="none"/>`
    + `<path d="${ground}" fill="url(#gd${id})"/><path d="${skyline}" fill="none" stroke="#fff" stroke-opacity=".85" stroke-width="1.1"/></g>`;
  g += `<path d="${rim}" fill="none" stroke="${pal.rim}" stroke-opacity=".9" stroke-width=".9" stroke-linecap="round"/>`;
  g += '</g>';
  return { svg: g, x0, x1, polys };
}
const rowU = buildRow(ROWS[0]);
const rowS = buildRow(ROWS[1]);

// reflection of the bottom row in the floor, fading with distance
const REFL = 56;  // the reflection has faded out completely this far below the horizon
const RCOV = 84;  // the fade cover reaches this far, past the last reflected pixel
// The floor gradient's own colour at y, so the fade cover can end up opaque
// and still be invisible against the floor.
function floorAt(y) {
  const t = Math.max(0, Math.min(1, (y - FLOOR) / (H - FLOOR)));
  for (let i = 1; i < FLOOR_STOPS.length; i++) {
    const [o0, c0] = FLOOR_STOPS[i - 1], [o1, c1] = FLOOR_STOPS[i];
    if (t <= o1) return lerpHex(c0, c1, (t - o0) / (o1 - o0));
  }
  return FLOOR_STOPS[FLOOR_STOPS.length - 1][1];
}
defs.push(`<clipPath id="rfc"><rect y="${FLOOR}" width="${W}" height="${H - FLOOR}"/></clipPath>`);
defs.push(vgrad('rfs', ROWS[1].y, ROWS[1].y + ROWS[1].h, [[0, '#7c8aa6'], [0.5, '#e6ebf3'], [0.56, '#232a38'], [1, '#dfe5ee']]));
{
  // Opacity of the cover by depth below the horizon: the reflection shows
  // through at the top and is gone by REFL. The cover is fully opaque (and
  // exactly floor-coloured) from there down, so neither its own bottom edge
  // nor the reflection's can show as a line at fractional scales.
  const alpha = [[0, 0.5], [0.45 * REFL, 0.84], [0.85 * REFL, 1], [(FLOOR_STOPS[1][0] * (H - FLOOR)), 1], [RCOV, 1]].sort((a, b) => a[0] - b[0]);
  defs.push(vgrad('rff', FLOOR, FLOOR + RCOV, alpha.map(([d, a]) => [n(d / RCOV, 3), floorAt(FLOOR + d), a])));
}
// (a simplified copy: walls, metal and faces only; re-drawing the full row costs too much per frame)
const reflSvg = `<g clip-path="url(#rfc)"><g transform="translate(0 ${2 * FLOOR}) scale(1 -1)"><use href="#ws" fill="${PAL.s.ext[1]}"/><use href="#os" fill-rule="evenodd" fill="${PAL.s.bevel[1]}"/><use href="#fs" fill-rule="evenodd" fill="url(#rfs)"/></g><rect y="${FLOOR}" width="${W}" height="${RCOV}" fill="url(#rff)"/></g>`;

// "presents" line above the logo, widely tracked, with a rule either side
const CREW = 'TORQUE DIRTY';
let presentsSvg = '';
{
  const y = 9, cell = 8, tail = 'PRESENTS';
  const cols = CREW.length + 3 + tail.length;
  const half = ((cols * cell - 3) * PX) / 2;
  presentsSvg = `<g transform="translate(${n1(W / 2 - half)} ${y}) scale(${PX})"><g fill="#f4f8ff">${textUses(CREW, 0, cell)}</g>`
    + `<g fill="${GOLD}">${textUses('·', CREW.length + 1, cell)}</g><g fill="#8ea2c2">${textUses(tail, CREW.length + 3, cell)}</g></g>`;
  const xl = W / 2 - half - 150, xr = W / 2 + half + 14;
  defs.push(hgrad('rl', xl, xl + 136, [[0, '#8ea2c2', 0], [1, '#8ea2c2', 0.8]]));
  defs.push(hgrad('rr', xr, xr + 136, [[0, '#8ea2c2', 0.8], [1, '#8ea2c2', 0]]));
  presentsSvg += `<rect x="${n1(xl)}" y="${y + 6}" width="136" height="1.4" fill="url(#rl)"/><rect x="${n1(xr)}" y="${y + 6}" width="136" height="1.4" fill="url(#rr)"/>`;
}

// moving sheen clipped to the letters, and a few glints on their corners
defs.push('<clipPath id="lc"><use href="#ou" clip-rule="evenodd"/><use href="#os" clip-rule="evenodd"/></clipPath>');
const sheenSvg = '<g clip-path="url(#lc)"><path class="sh" fill="#fff" d="M0 20h34l-28 176h-34zM48 20h9l-28 176h-9z"/></g>';
css.push(`.sh{opacity:.5;transform:translateX(-120px);animation:sh 8s linear infinite}@keyframes sh{0%,58%{transform:translateX(-120px)}88%,100%{transform:translateX(${W + 60}px)}}`);
let glintSvg = '';
{
  const star = 'M0-13L1.6-1.6L13 0L1.6 1.6L0 13L-1.6 1.6L-13 0L-1.6-1.6Z';
  defs.push(`<g id="gl"><path d="${star}" fill="#fff"/><path d="${star}" fill="#fff" opacity=".6" transform="rotate(45) scale(.45)"/><circle r="2.2" fill="#fff"/></g>`);
  const pts = [
    [rowU.polys[0][0][0] + 3, ROWS[0].y + 2, 0],   // top-left of the U
    [rowU.x1 - 28, ROWS[0].y + 3, 2.1],            // shoulder of the A
    [rowS.x0 + 52, ROWS[1].y + 2, 4.0],            // top of the first S
    [rowS.x1 - 3, ROWS[1].y + 2, 5.6],             // tip of the Y
  ];
  for (const [x, y, d] of pts) glintSvg += `<g transform="translate(${n1(x)} ${n1(y)})"><use href="#gl" class="gl" style="animation-delay:${-d}s"/></g>`;
  css.push('.gl{transform:scale(0);animation:gl 7s linear infinite}@keyframes gl{0%{transform:scale(0) rotate(0deg)}6%{transform:scale(1) rotate(20deg)}12%,100%{transform:scale(0) rotate(40deg)}}');
}

// ================================================================ twisters
const TW = { cx: 58, y0: 30, rows: 60, rh: 5, R: 36, T: 12, turns: 2, spread: 0.36, A1: 1.9, A2: 0.45, sway: 4, S: 72, park: 500 };
const twTheta = (u) => 2 * Math.PI * TW.turns * u + TW.A1 * Math.sin(2 * Math.PI * u) + TW.A2 * Math.sin(4 * Math.PI * u + 1.1);
const twSway = (u) => TW.sway * Math.sin(4 * Math.PI * u + 0.6);
const twCorner = (k, u) => TW.R * Math.sin(twTheta(u) + (k * Math.PI) / 2); // corner k of the square column, seen from the front
// Face k (between corners k and k+1) at phase u: left edge, signed width
// (positive when it faces the viewer) and brightness. Lit from the middle of
// the screen (the logo's side), so faces turned inward are brightest.
function twFace(k, u) {
  const phi = twTheta(u) + (k * Math.PI) / 2 + Math.PI / 4; // face normal: 0 = facing the viewer
  return { x: twCorner(k, u) + twSway(u), w: twCorner(k + 1, u) - twCorner(k, u), b: 0.2 + 0.8 * Math.max(0, Math.cos(phi - 0.6)) ** 0.85 };
}
// Opposite faces are never on show together, so faces k and k+2 share ONE
// animated element: a <g> holding both strips, the second parked TW.park px
// below the banner. At the instant the pair is edge-on the keyframes jump the
// group up by TW.park, which swaps the strip in view. (Animated elements are
// what costs CPU here, so this halves the twisters' bill.)
function twPair(k) {
  const at = (u) => { const f = twFace(k, u); return f.w > 0 ? { ...f, y: 0 } : { ...twFace(k + 2, u), y: -TW.park }; };
  const kf = [];
  for (let j = 0; j <= TW.S; j++) {
    const u = j / TW.S, u1 = (j + 1) / TW.S;
    kf.push({ u, ...at(u) });
    if (j === TW.S || twFace(k, u).w * twFace(k, u1).w >= 0) continue;
    let lo = u, hi = u1; // bisect for the edge-on instant
    for (let i = 0; i < 40; i++) { const mid = (lo + hi) / 2; if (twFace(k, lo).w * twFace(k, mid).w <= 0) hi = mid; else lo = mid; }
    const out = twFace(k, u).w > 0 ? k : k + 2, inn = out === k ? k + 2 : k;
    // the outgoing face closes at one silhouette edge, the incoming one opens at the other
    kf.push({ u: lo, ...twFace(out, lo), w: 0, y: out === k ? 0 : -TW.park });
    kf.push({ u: lo + 1e-4, ...twFace(inn, lo), w: 0, y: inn === k ? 0 : -TW.park });
  }
  return kf.map((f) => `${n(f.u * 100, 3)}%{transform:translate(${n1(f.x)}px,${f.y}px) scaleX(${n1(Math.max(0, f.w))});opacity:${n(f.b)}}`).join('');
}
let twisterSvg = '';
{
  css.push(`@keyframes fa{${twPair(0)}}@keyframes fb{${twPair(1)}}.a,.b{animation:fa ${TW.T}s linear infinite}.b{animation-name:fb}`);
  const step = (TW.spread * TW.T) / TW.rows;
  const OFF = 25; // right-hand twister: reversed travel, shifted phase
  const used = new Set();
  const rh = TW.rh;
  // Face textures: horizontal hard-stop gradients in bounding-box units, so a
  // face row is one unit-wide strip and the texture squashes with it.
  const tex = [];
  const G = (id, bands) => { // bands: [[x0, x1, colour], ...] painted over the first as a base
    const base = bands[0][2];
    const cuts = [...new Set(bands.flatMap(([a, b]) => [a, b]))].filter((v) => v > 0 && v < 1).sort((p, q) => p - q);
    const edges = [0, ...cuts, 1];
    let st = '';
    for (let i = 0; i < edges.length - 1; i++) {
      const mid = (edges[i] + edges[i + 1]) / 2;
      let col = base;
      for (const [a, b, c] of bands) if (mid >= a && mid <= b) col = c;
      st += `<stop offset="${n(edges[i], 3)}" stop-color="${col}"/><stop offset="${n(edges[i + 1], 3)}" stop-color="${col}"/>`;
    }
    tex.push(`<linearGradient id="${id}">${st}</linearGradient>`);
    css.push(`.${id}{fill:url(#${id})}`);
  };
  for (let v = 0; v < 4; v++) { // a: hazard tape, diagonal
    const bands = [[0, 1, '#17140a']];
    for (const st of [v * 0.125 - 0.5, v * 0.125, v * 0.125 + 0.5]) { const a = Math.max(0, st), b = Math.min(1, st + 0.25); if (b > a) bands.push([a, b, GOLD]); }
    G(`h${v}`, bands);
  }
  const plate = [[0, 1, '#566073'], [0.06, 0.94, '#8893a6'], [0.24, 0.76, '#aab4c5']]; // b: riveted steel plate
  G('p0', plate); G('p1', [...plate, [0.11, 0.19, '#232a38'], [0.81, 0.89, '#232a38']]); G('p2', [[0, 1, '#4a5466']]);
  G('b0', [[0, 1, '#0a2436'], [0.28, 0.72, CYAN], [0.41, 0.59, '#d6f8ff']]); G('b1', [[0, 1, '#0a2436'], [0.28, 0.72, '#0e4a66']]); // c: light bar
  const LP = 14; // d: lattice truss, one X per LP rows
  for (let v = 0; v < LP; v++) {
    const p = v / LP, sw = 0.15;
    const a = 0.1 + (0.8 - sw) * p, b = 0.9 - sw - (0.8 - sw) * p;
    G(`x${v}`, [[0, 1, '#0d121c'], [a, a + sw, '#5c677b'], [b, b + sw, '#77839a'], [0, 0.1, '#77839a'], [0.9, 1, '#77839a']]);
  }
  defs.push(tex.join(''));
  const texFor = (k, i) => {
    if (k === 0) return `h${i % 4}`;
    if (k === 1) return i % 19 === 9 ? 'p2' : i % 6 === 2 ? 'p1' : 'p0';
    if (k === 2) return i % 8 === 7 ? 'b1' : 'b0';
    return `x${i % LP}`;
  };
  const column = (right) => {
    let s = '';
    for (let i = 0; i < TW.rows; i++) {
      const di = right ? TW.rows - 1 - i + OFF : i;
      used.add(di);
      const y = TW.y0 + i * rh;
      for (let k = 0; k < 2; k++) s += `<g class="${'ab'[k]} d${di}"><path d="M0 ${y}h1v${rh}h-1z" class="${texFor(k, i)}"/><path d="M0 ${y + TW.park}h1v${rh}h-1z" class="${texFor(k + 2, i)}"/></g>`;
    }
    return s;
  };
  // chuck: the clamp that holds (and wrings) each end of the girder
  defs.push(hgrad('ck', -50, 50, [[0, '#2b3342'], [0.3, '#8e99ad'], [0.5, '#c9d2e0'], [0.7, '#8e99ad'], [1, '#2b3342']]));
  defs.push(hgrad('cj', -44, 44, [[0, '#171c27'], [0.5, '#596377'], [1, '#171c27']]));
  defs.push('<g id="chuck"><path d="M-50 0h100v14l-5 6h-90l-5-6z" fill="url(#ck)" stroke="#05070c" stroke-width="1.2"/>'
    + '<path d="M-44 20h88v8h-88z" fill="url(#cj)" stroke="#05070c" stroke-width="1.2"/>'
    + '<path d="M-50 1.2h100" stroke="#eef3fa" stroke-opacity=".7" stroke-width="1"/>'
    + `<path d="M-38 6h18v6h-18zM20 6h18v6h-18z" fill="#12161f"/><path d="M-36 8h6v2h-6zM30 8h6v2h-6z" fill="${GOLD}"/><path d="M-27 8h5v2h-5zM22 8h5v2h-5z" fill="#3a4354"/>`
    + '<circle cy="9" r="4.2" fill="#1b212d"/><circle cy="9" r="2" fill="#0e4a66"/>'
    + '<path d="M-40 22.5h4v3h-4zM-28 22.5h4v3h-4zM24 22.5h4v3h-4zM36 22.5h4v3h-4z" fill="#0b0e15"/></g>');
  const yB = TW.y0 + TW.rows * rh;
  const one = (x, right) => `<g transform="translate(${x} 0)${right ? ' scale(-1 1)' : ''}">`
    + `<g shape-rendering="crispEdges">${column(right)}</g>`
    + `<use href="#chuck" y="${TW.y0 - 27}"/><use href="#chuck" transform="translate(0 ${yB + 27}) scale(1 -1)"/></g>`;
  twisterSvg = one(TW.cx, false) + one(W - TW.cx, true);
  // status LEDs on the chucks, blinking out of step (drawn here, not in the <use>d chuck, so the animation is plain)
  [[TW.cx, TW.y0 - 18, 0], [TW.cx, yB + 18, 0.8], [W - TW.cx, TW.y0 - 18, 0.8], [W - TW.cx, yB + 18, 0]].forEach(([x, y, d]) => { twisterSvg += `<circle class="le" cx="${x}" cy="${y}" r="2" fill="${CYAN}" style="animation-delay:${-d}s"/>`; });
  css.push('.le{animation:le 1.6s steps(1,end) infinite}@keyframes le{0%{opacity:1}50%,100%{opacity:0}}');
  css.push([...used].sort((p, q) => p - q).map((d) => `.d${d}{animation-delay:${n(-d * step, 3)}s}`).join(''));
}

// ================================================================ text-writer
// Three pages in the small white bitmap font, typed then wiped.
const TXT = { y: 252, lh: 20, cps: 46, hold: 5.5, wipe: 0.5 };
const PAGES = [
  { align: 'centre', lines: [
    [['A COMPANION APP FOR THE FACTORY GAME ', 'w'], ['SATISFACTORY', 'y']],
    [['EVERY RECIPE, BUILDING AND SPACE ELEVATOR OBJECTIVE,', 'w']],
    [['ONE CLICK APART.', 'c']],
    [['[ OBJECTIVES ]', 'po'], ['   ', 'w'], ['[ ITEMS ]', 'pi'], ['   ', 'w'], ['[ BUILDINGS ]', 'pb']],
  ] },
  { align: 'left', lines: [
    [['RUN IT LOCALLY (Python 3.10+, from the repo root):', 'w']],
    [['> ', 'y'], ['python -m pip install -r requirements.txt', 'c']],
    [['> ', 'y'], ['python -m streamlit run app/app.py', 'c']],
    [['NO INSTALL: ', 'w'], ['lukexyz.github.io/ULTRA-SATISFACTORY', 'y']],
  ] },
  { align: 'centre', lines: [
    [['140', 'y'], [' ITEMS · ', 'w'], ['211', 'y'], [' RECIPES (88 ALTERNATE) · ', 'w'], ['477', 'y'], [' BUILDINGS', 'w']],
    [['5', 'y'], [' SPACE ELEVATOR PHASES · PROTECTION: ', 'w'], ['NONE', 'c'], [' (APACHE 2.0)', 'w']],
    [[`GIRDERS TWISTED BY ${CREW}. THEY SIGNED A WAIVER.`, 'g']],
    [['UNOFFICIAL FAN PROJECT. THE GAME IS SOLD SEPARATELY.', 'g']],
  ] },
];
let pagesSvg = '';
let PAGE_T = 0;
{
  const COL = { w: '#eef3fb', y: GOLD, c: '#5fe0ff', g: '#93a4bf', po: PURPLE, pi: PINK, pb: BLUE };
  const cw = 6 * PX; // user px per character
  const block = { x: 108, y: TXT.y - 6, w: W - 216, h: TXT.lh * 4 + 6 };
  const lens = PAGES.map((pg) => pg.lines.map((ln) => ln.reduce((a, [t]) => a + t.length, 0)));
  const typeDur = lens.map((ls) => ls.reduce((a, l) => a + l, 0) / TXT.cps);
  // Timeline: page 1 is up at t=0 and holds; wipe; page 2 types, holds, wipes;
  // page 3 likewise; then page 1 types again, ending exactly at the loop point.
  const wipes = [];
  const sched = [];
  let t = TXT.hold;
  wipes.push([t, t + TXT.wipe]); t += TXT.wipe;
  sched[0] = { hide: t };
  for (const p of [1, 2]) {
    sched[p] = { a: t };
    t += typeDur[p] + TXT.hold;
    wipes.push([t, t + TXT.wipe]); t += TXT.wipe;
    sched[p].hide = t;
  }
  sched[0].a = t;
  PAGE_T = +(t + typeDur[0]).toFixed(2);
  const pc = (s) => `${n((100 * Math.min(s, PAGE_T)) / PAGE_T, 3)}%`;
  const EPS = 0.02; // seconds: a "jump" is a 20 ms ramp while the page is hidden

  PAGES.forEach((pg, p) => {
    const { a, hide } = sched[p];
    css.push(p === 0
      ? `@keyframes pg0{0%{opacity:1}${pc(hide)}{opacity:0}${pc(a)},100%{opacity:1}}`
      : `@keyframes pg${p}{0%{opacity:0}${pc(a)}{opacity:1}${pc(hide)},100%{opacity:0}}`);
    const maxLen = Math.max(...lens[p]);
    let g = `<g class="pg pg${p}">`;
    let tt = a;
    pg.lines.forEach((ln, li) => {
      const len = lens[p][li];
      const x = Math.round((W - (pg.align === 'left' ? maxLen : len) * cw) / 2);
      const y = TXT.y + li * TXT.lh;
      let col = 0, uses = '';
      for (const [str, c] of ln) { uses += `<g fill="${COL[c]}">${textUses(str, col)}</g>`; col += str.length; }
      g += `<g transform="translate(${x} ${y}) scale(${PX})">${uses}</g>`;
      // the cover: steps right one character at a time, cursor on its leading edge
      const X = len * cw;
      const t0 = tt, t1 = tt + len / TXT.cps; tt = t1;
      const id = `k${p}${li}`;
      const last = li === pg.lines.length - 1;
      const typing = `${pc(t0)}{transform:translateX(0);animation-timing-function:steps(${len},end)}${pc(t1)},100%{transform:translateX(${X}px)}`;
      const kf = p === 0
        ? `0%,${pc(hide)}{transform:translateX(${X}px)}${pc(hide + EPS)}{transform:translateX(0)}${typing}`
        : `0%{transform:translateX(0)}${typing}`;
      // cursor: on while its line types; the last line's cursor waits there until the wipe
      const wipeAt = hide - TXT.wipe;
      const ck = p === 0 && last
        ? `0%{opacity:1}${pc(wipeAt)}{opacity:0}${pc(t0)},100%{opacity:1}`
        : `0%{opacity:0}${pc(t0)}{opacity:1}${pc(last ? wipeAt : t1)},100%{opacity:0}`;
      css.push(`@keyframes ${id}{${kf}}.${id}{animation-name:${id}}@keyframes c${id}{${ck}}.c${id}{animation-name:c${id}}`);
      g += `<g class="kv ${id}"><rect x="${x - 2}" y="${y - 3}" width="${X + 6}" height="${TXT.lh}" fill="url(#floor)"/>`
        + `<rect class="cu c${id}" x="${x + 1}" y="${y}" width="9" height="14" fill="${GOLD}"/></g>`;
    });
    pagesSvg += `${g}</g>`;
  });
  // wipe: a cover sweeping left to right with a bright leading edge
  const wk = wipes.map(([a, b]) => `${pc(a)}{transform:scaleX(0)}${pc(b)}{transform:scaleX(1)}${pc(b + EPS)}{transform:scaleX(0)}`).join('');
  const bk = wipes.map(([a, b]) => `${pc(a - EPS)}{transform:translateX(0);opacity:0}${pc(a)}{transform:translateX(0);opacity:1}${pc(b)}{transform:translateX(${block.w}px);opacity:1}${pc(b + EPS)}{transform:translateX(${block.w}px);opacity:0}`).join('');
  css.push(`.pg,.kv,.cu,.wp,.wb{animation-duration:${PAGE_T}s;animation-timing-function:linear;animation-iteration-count:infinite}`
    + '.pg,.cu{animation-timing-function:steps(1,end)}'
    + '.pg0{animation-name:pg0}.pg1{animation-name:pg1;opacity:0}.pg2{animation-name:pg2;opacity:0}'
    + `@keyframes wp{0%{transform:scaleX(0)}${wk}100%{transform:scaleX(0)}}.wp{transform:scaleX(0);animation-name:wp}`
    + `@keyframes wb{0%{transform:translateX(0);opacity:0}${bk}100%{transform:translateX(0);opacity:0}}.wb{opacity:0;animation-name:wb}`);
  // The wipe cover lives in a translated group (so it scales from the block's
  // left edge), which needs its own copy of the floor gradient to line up.
  defs.push(vgrad('floorw', FLOOR - block.y, H - block.y, FLOOR_STOPS));
  defs.push(`<clipPath id="txc"><rect x="${block.x}" y="${block.y}" width="${block.w}" height="${block.h}"/></clipPath>`);
  pagesSvg = `<g clip-path="url(#txc)">${pagesSvg}<g transform="translate(${block.x} ${block.y})"><rect class="wp" width="${block.w}" height="${block.h}" fill="url(#floorw)"/>`
    + `<rect class="wb" x="-2" width="3" height="${block.h}" fill="${CYAN}"/></g></g>`;
}

// ================================================================ sine scroller
// Dot-matrix capitals riding a stationary sine, right to left.
const SC = { y: 373, pitch: 5, adv: 30, amp: 11, speed: 116, dot: 4, phases: 12 };
const SCROLL_TEXT = [
  `${CREW} PROUDLY PRESENTS`, // exactly one screen wide: this is the first frame
  ' ULTRA-SATISFACTORY ...',
  ' EVERY RECIPE, BUILDING AND SPACE ELEVATOR OBJECTIVE, ONE CLICK APART ...',
  ' 140 ITEMS * 211 RECIPES * 477 BUILDINGS ...',
  ' PROTECTION: NONE. IT IS APACHE 2.0 ...',
  ' REQUIRES: NO DIRECTX, NO INSTALLER WIZARD, NO BROWSER TOOLBAR ...',
  ' GREETZ TO EVERYONE WHO ALT-TABBED OUT AT 3 A.M. FOR ONE RECIPE',
  ' AND CAME BACK WITH A WHOLE NEW FACTORY ...',
  ' NO GIRDERS WERE HARMED. SEVERAL WERE THRILLED ...',
  ' RIGHTY TIGHTY, LEFTY LOOSEY, JUST ONE MORE BELT ...',
  ' PRESS ANY KEY. NOTHING HAPPENS. IT IS A README ...    ',
].join('');
let scrollSvg = '';
let SCROLL_T = 0;
{
  const NP = SC.phases;
  let txt = SCROLL_TEXT;
  while (txt.length % NP) txt += ' ';
  const L = txt.length * SC.adv;
  const head = Math.ceil(W / SC.adv) + 2;
  const groups = Array.from({ length: NP }, () => '');
  [...txt, ...[...txt].slice(0, head)].forEach((ch, i) => {
    const id = needGlyph('p', ch);
    if (id) groups[i % NP] += `<use href="#${id}" x="${i * SC.adv}"/>`;
  });
  const period = (NP * SC.adv) / SC.speed; // one wavelength passes in this long
  SCROLL_T = L / SC.speed;
  scrollSvg = `<g transform="translate(17 ${SC.y})"><g class="sc">${groups.map((g, p) => `<g class="wv w${p}">${g}</g>`).join('')}</g></g>`;
  css.push(`.sc{animation:sc ${n(SCROLL_T)}s linear infinite}@keyframes sc{to{transform:translateX(${-L}px)}}`
    + `.wv{animation:wv ${n(period / 2, 4)}s cubic-bezier(.37,0,.63,1) infinite alternate}@keyframes wv{from{transform:translateY(${-SC.amp}px)}to{transform:translateY(${SC.amp}px)}}`
    + groups.map((g, p) => `.w${p}{animation-delay:${n(-(period - (p * period) / NP), 4)}s}`).join(''));
  defs.push(vgrad('led', 0, 6 * SC.pitch, [[0, '#fffbe2'], [0.35, '#ffe45e'], [0.7, GOLD], [1, '#ff8a1f']]));
  css.push(`.lg{stroke:${GOLD};stroke-opacity:.16;stroke-width:${SC.dot + 4.5}}.ld{stroke:url(#led);stroke-width:${SC.dot}}.lg,.ld{fill:none;stroke-linecap:round}`);
}

// ---------------------------------------------------------------- glyph defs
{
  let d = '';
  for (const ch of usedGlyphs.t) d += `<path id="${gid('t', ch)}" d="${cellsPath(FONT[ch])}"/>`;
  for (const ch of usedGlyphs.p) {
    // each LED is a near-zero-length stroke with round caps
    let dots = '';
    FONT[ch].forEach((row, y) => [...row].forEach((c, x) => { if (c === '#') dots += `M${x * SC.pitch} ${y * SC.pitch}h.01`; }));
    const id = gid('p', ch);
    d += `<path id="${id}d" d="${dots}"/><g id="${id}"><use href="#${id}d" class="lg"/><use href="#${id}d" class="ld"/></g>`;
  }
  defs.push(d);
}

// ================================================================ assemble
const body = [
  backSvg,
  starSvg,
  presentsSvg,
  horizonGlow, // an ellipse centred on the horizon; the floor covers its lower half
  floorSvg,
  reflSvg,
  rowS.svg,
  rowU.svg,
  horizonLine,
  sheenSvg,
  glintSvg,
  pagesSvg,
  twisterSvg,
  scrollSvg,
  `<rect x=".75" y=".75" width="${W - 1.5}" height="${H - 1.5}" rx="11.5" fill="none" stroke="#22314a" stroke-width="1.5"/>`,
];
css.push('@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}');

const desc = `A Windows-era cracktro banner. ${CREW} presents ULTRA-SATISFACTORY as a bevelled chrome logo (ULTRA in cyan chrome, SATISFACTORY in silver) standing on a mirror floor with its reflection, a starfield flying outward behind it. `
  + 'On each side a square girder with hazard tape, riveted plate, a light bar and a lattice face is twisted like a wrung towel between two chucks. '
  + 'A text writer types three pages: a companion app for the factory game Satisfactory, every recipe, building and Space Elevator objective, one click apart, with tabs Objectives, Items and Buildings; '
  + 'how to run it (python -m pip install -r requirements.txt, then python -m streamlit run app/app.py, or install nothing at lukexyz.github.io/ULTRA-SATISFACTORY); '
  + 'and the numbers: 140 items, 211 recipes of which 88 are alternates, 477 buildings, 5 Space Elevator phases, protection none (Apache 2.0), unofficial fan project. '
  + 'A gold dot-matrix scroller rides a sine wave along the bottom.';

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-labelledby="t d">
<title id="t">ULTRA-SATISFACTORY</title>
<desc id="d">${desc}</desc>
<style>${css.join('\n')}</style>
<defs>${defs.join('\n')}</defs>
<g clip-path="url(#panel)">
${body.join('\n')}
</g>
</svg>
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
console.log(`${path.relative(process.cwd(), OUT)}: ${(svg.length / 1024).toFixed(1)} KB; loops: twister ${TW.T}s, pages ${PAGE_T}s, scroller ${SCROLL_T.toFixed(1)}s`);
// The .md's "how the twister twists" note quotes these three numbers by hand; keep them in step.
console.log(`twister: ${TW.rows} slices per girder, ${Math.round((1000 * TW.spread * TW.T) / TW.rows)} ms between slices, ${TW.T} s loop`);

// ---------------------------------------------------------------- --ascii
// The banner again for text terminals: the same twisters (same maths, faces
// drawn as / # = X) either side of the release card. Paste into the .md.
if (process.argv.includes('--ascii')) {
  const N = 20, HALF = 6, FACE = '/#=X', WIDE = 80;
  const column = (u0, dir) => Array.from({ length: N }, (_, i) => {
    const u = u0 + dir * (i / N) * TW.spread;
    const line = Array(2 * HALF + 1).fill(' ');
    for (let k = 0; k < 4; k++) {
      const f = twFace(k, u);
      if (f.w <= 0) continue;
      const a = Math.round(((f.x - twSway(u)) / TW.R) * HALF) + HALF, b = Math.round(((f.x - twSway(u) + f.w) / TW.R) * HALF) + HALF;
      for (let x = a; x <= b; x++) line[x] = x === a || x === b ? '|' : FACE[k];
    }
    return line.join('');
  });
  const chuck = '[=====o=====]'.padEnd(2 * HALF + 1);
  const left = [chuck, ...column(0.08, 1), chuck];
  const right = [chuck, ...column(0.3, -1).map((l) => [...l].reverse().join('').replaceAll('/', '\\')), chuck];
  const mid = WIDE - 2 * (2 * HALF + 1);
  const table = [
    'WHAT ......... companion app for Satisfactory',
    'INSIDE ....... 140 items, 211 recipes (88 alt),',
    '               477 buildings, 5 elevator phases',
    'PROTECTION ... none. It is Apache 2.0.',
    'REQUIRES ..... Python 3.10+, or a browser tab',
    'DIRECTX ...... not required',
    'INTRO ........ 1 SVG, 0 lines of JavaScript',
    'GIRDERS ...... 2, twisted. They signed a waiver.',
    'THE GAME ..... sold separately. Fan project.',
  ];
  const tw = Math.max(...table.map((l) => l.length));
  const centre = (t) => { const pad = Math.floor((mid - t.length) / 2); return ' '.repeat(pad) + t; };
  const title = '   U L T R A - S A T I S F A C T O R Y   ';
  const card = [
    '',
    [...CREW].join(' ').replace('   ', '     '),
    'proudly presents',
    '',
    `╔${'═'.repeat(title.length)}╗`,
    `║${title}║`,
    `╚${'═'.repeat(title.length)}╝`,
    'every recipe, building and Space Elevator objective,',
    'one click apart',
    '',
  ].map(centre);
  for (const l of table) card.push(' '.repeat(Math.floor((mid - tw) / 2)) + l);
  card.push('', centre('press any key. nothing happens. it is a README.'), '');
  if (card.length !== N + 2) throw new Error(`card is ${card.length} rows, twisters are ${N + 2}`);
  for (let i = 0; i < N + 2; i++) console.log((left[i] + card[i].padEnd(mid) + right[i]).trimEnd());
}
