// "Chrome spheres over a checkerboard" README banner for ULTRA-SATISFACTORY.
//
//   node examples/ultra-satisfactory/src/13-chrome-spheres_opus_5.5.mjs
//   node examples/ultra-satisfactory/src/13-chrome-spheres_opus_5.5.mjs --ascii
//
// Regenerates ../assets/13-chrome-spheres_opus_5.5.svg. With --ascii it also
// prints the 80-column checker floor used in the .md's text block (same
// projection as the SVG floor). Plain Node, no deps, deterministic (seeded
// PRNG, no clock). Two more flags exist only for checking frames that are a
// long way into the loop without waiting for them:
//   --at=30        bake a 30 s head start into every animation delay
//   --out=file.svg write somewhere else (use this with --at, never in place)
//
// The style is the demoscene's own in-joke for "a demo", played straight in
// Razor 1911's 2016 cracktro (code XT95, logo Sprocket): mirror balls bouncing
// over an endless checker floor under an italic chrome logo, with the sky
// running a day-night cycle and a small scroller out at the horizon. Nothing
// here is copied from it: the letterforms, spheres and copy are drawn for this
// banner. The factory reading: the floor is foundations to the horizon, and
// the six spheres are the only things on site with nothing missing.
//
// Everything is geometry from this file: the logo is parametric polygons (no
// font), small type is a 5x7 bitmap font drawn as paths. No <text>, no filters,
// no blend modes, no SMIL: CSS keyframes only.
//
// How the moving parts work
//   Floor: a checker is (rows XOR columns). Flying forward never moves the
//   column boundaries on screen (they are wedges fanning out of the vanishing
//   point), so the columns are two static clip paths, even wedges and odd
//   wedges. The rows are plain full-width rects. Every row follows the same
//   journey from the horizon to the bottom edge, y = HY + K / z with z falling
//   at a steady rate, so all of them share ONE @keyframes (sampled densely
//   where the hyperbola bends) and differ only in animation-delay. The rows
//   under the odd wedges run one tile out of step with the rows under the
//   even wedges, and that is the checker. Sideways drift is one more transform
//   on the parent: a lateral camera move is exactly a skewX about the horizon
//   line, and the pattern repeats every two tiles, so the skew loops.
//   Spheres: a mirror ball over a floor shows that floor's columns as wedges
//   fanning out of the ball's centre (that part is exact) and its rows as
//   nested arcs collapsing onto the equator (here: nested ellipses in a
//   geometric ladder, so a scaleY by the ladder's ratio squared maps the rings
//   onto themselves and the zoom loops). Same two-clip trick, same skew.
//   Day and night: the day scene is the base. Dusk and night are two groups
//   fading in and out on one 60 s timeline, each holding that hour's whole
//   backdrop (sky, floor tint, haze) so sky and haze fade as one layer and the
//   horizon never shows a seam. Every other lit thing (logo, spheres) carries a
//   dusk tint and a night tint on the same two classes. The sun and moon sit
//   at opposite ends of one wheel turning about the horizon's centre, clipped
//   at the horizon so they set behind the floor.
//   prefers-reduced-motion pauses everything on frame 0, which is the complete
//   daytime scene.
// (The .md beside the assets is hand-written, not generated by this script.)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const arg = (name) => {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
};
const T0 = Number(arg('at') || 0);
const OUT = arg('out') ? path.resolve(arg('out')) : path.resolve(here, '../assets/13-chrome-spheres_opus_5.5.svg');

const W = 900;
const H = 470;
const CX = W / 2;
const HY = 268;      // horizon
const LOOP = 60;     // day-night cycle, seconds

// ---------------------------------------------------------------- utilities
function mulberry32(seed) {
  return () => {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(0x5fe2e5);
const n = (v, d = 2) => String(+(+v).toFixed(d));
const n1 = (v) => n(v, 1);
const pc = (v) => `${n(v * 100, 3)}%`;
function lerpHex(a, b, t) {
  const pa = [1, 3, 5].map((i) => parseInt(a.slice(i, i + 2), 16));
  const pb = [1, 3, 5].map((i) => parseInt(b.slice(i, i + 2), 16));
  return `#${pa.map((v, i) => Math.round(v + (pb[i] - v) * t).toString(16).padStart(2, '0')).join('')}`;
}
const polyD = (p, d = 1) => `M${p.map(([x, y]) => `${n(x, d)} ${n(y, d)}`).join('L')}Z`;
const stops = (list) => list.map(([o, c, a]) => `<stop offset="${o}" stop-color="${c}"${a === undefined ? '' : ` stop-opacity="${a}"`}/>`).join('');
const vgrad = (id, y0, y1, list) => `<linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="0" y1="${n(y0)}" x2="0" y2="${n(y1)}">${stops(list)}</linearGradient>`;
const rgrad = (id, list, extra = '') => `<radialGradient id="${id}"${extra}>${stops(list)}</radialGradient>`;
// Every animation delay goes through here so --at can shift the whole film.
const dly = (s = 0) => `${n(s - T0, 3)}s`;

const defs = [];
const css = [];

// ---------------------------------------------------------------- 5x7 font
// Rows top to bottom, '#' = lit. An optional 8th row is the descender.
const FONT = {
  A: '.###.|#...#|#...#|#...#|#####|#...#|#...#', B: '####.|#...#|#...#|####.|#...#|#...#|####.',
  C: '.###.|#...#|#....|#....|#....|#...#|.###.', D: '###..|#..#.|#...#|#...#|#...#|#..#.|###..',
  E: '#####|#....|#....|####.|#....|#....|#####', F: '#####|#....|#....|####.|#....|#....|#....',
  G: '.###.|#...#|#....|#.###|#...#|#...#|.####', H: '#...#|#...#|#...#|#####|#...#|#...#|#...#',
  I: '.###.|..#..|..#..|..#..|..#..|..#..|.###.', J: '..###|...#.|...#.|...#.|...#.|#..#.|.##..',
  K: '#...#|#..#.|#.#..|##...|#.#..|#..#.|#...#', L: '#....|#....|#....|#....|#....|#....|#####',
  M: '#...#|##.##|#.#.#|#.#.#|#...#|#...#|#...#', N: '#...#|#...#|##..#|#.#.#|#..##|#...#|#...#',
  O: '.###.|#...#|#...#|#...#|#...#|#...#|.###.', P: '####.|#...#|#...#|####.|#....|#....|#....',
  Q: '.###.|#...#|#...#|#...#|#.#.#|#..#.|.##.#', R: '####.|#...#|#...#|####.|#.#..|#..#.|#...#',
  S: '.####|#....|#....|.###.|....#|....#|####.', T: '#####|..#..|..#..|..#..|..#..|..#..|..#..',
  U: '#...#|#...#|#...#|#...#|#...#|#...#|.###.', V: '#...#|#...#|#...#|#...#|#...#|.#.#.|..#..',
  W: '#...#|#...#|#...#|#.#.#|#.#.#|#.#.#|.#.#.', X: '#...#|#...#|.#.#.|..#..|.#.#.|#...#|#...#',
  Y: '#...#|#...#|#...#|.#.#.|..#..|..#..|..#..', Z: '#####|....#|...#.|..#..|.#...|#....|#####',
  a: '.....|.....|.###.|....#|.####|#...#|.####', b: '#....|#....|#.##.|##..#|#...#|#...#|####.',
  c: '.....|.....|.###.|#....|#....|#...#|.###.', d: '....#|....#|.##.#|#..##|#...#|#...#|.####',
  e: '.....|.....|.###.|#...#|#####|#....|.###.', f: '..##.|.#..#|.#...|###..|.#...|.#...|.#...',
  g: '.....|.....|.####|#...#|#...#|.####|....#|.###.', h: '#....|#....|#.##.|##..#|#...#|#...#|#...#',
  i: '..#..|.....|.##..|..#..|..#..|..#..|.###.', j: '...#.|.....|..##.|...#.|...#.|...#.|#..#.|.##..',
  k: '#....|#....|#..#.|#.#..|##...|#.#..|#..#.', l: '.##..|..#..|..#..|..#..|..#..|..#..|.###.',
  m: '.....|.....|##.#.|#.#.#|#.#.#|#.#.#|#...#', n: '.....|.....|#.##.|##..#|#...#|#...#|#...#',
  o: '.....|.....|.###.|#...#|#...#|#...#|.###.', p: '.....|.....|####.|#...#|#...#|####.|#....|#....',
  q: '.....|.....|.####|#...#|#...#|.####|....#|....#', r: '.....|.....|#.##.|##..#|#....|#....|#....',
  s: '.....|.....|.####|#....|.###.|....#|####.', t: '.#...|.#...|###..|.#...|.#...|.#..#|..##.',
  u: '.....|.....|#...#|#...#|#...#|#..##|.##.#', v: '.....|.....|#...#|#...#|#...#|.#.#.|..#..',
  w: '.....|.....|#...#|#...#|#.#.#|#.#.#|.#.#.', x: '.....|.....|#...#|.#.#.|..#..|.#.#.|#...#',
  y: '.....|.....|#...#|#...#|#...#|.####|....#|.###.', z: '.....|.....|#####|...#.|..#..|.#...|#####',
  0: '.###.|#...#|#..##|#.#.#|##..#|#...#|.###.', 1: '..#..|.##..|..#..|..#..|..#..|..#..|.###.',
  2: '.###.|#...#|....#|...#.|..#..|.#...|#####', 3: '#####|...#.|..#..|...#.|....#|#...#|.###.',
  4: '...#.|..##.|.#.#.|#..#.|#####|...#.|...#.', 5: '#####|#....|####.|....#|....#|#...#|.###.',
  6: '..##.|.#...|#....|####.|#...#|#...#|.###.', 7: '#####|....#|...#.|..#..|.#...|.#...|.#...',
  8: '.###.|#...#|#...#|.###.|#...#|#...#|.###.', 9: '.###.|#...#|#...#|.####|....#|...#.|.##..',
  '!': '..#..|..#..|..#..|..#..|..#..|.....|..#..', "'": '..#..|..#..|.#...|.....|.....|.....|.....',
  '(': '...#.|..#..|.#...|.#...|.#...|..#..|...#.', ')': '.#...|..#..|...#.|...#.|...#.|..#..|.#...',
  '*': '.....|..#..|#.#.#|.###.|#.#.#|..#..|.....', '+': '.....|..#..|..#..|#####|..#..|..#..|.....',
  ',': '.....|.....|.....|.....|.##..|..#..|.#...', '-': '.....|.....|.....|#####|.....|.....|.....',
  '.': '.....|.....|.....|.....|.....|.##..|.##..', '/': '....#|....#|...#.|..#..|.#...|#....|#....',
  ':': '.....|.##..|.##..|.....|.##..|.##..|.....', '>': '.#...|..#..|...#.|....#|...#.|..#..|.#...',
  '?': '.###.|#...#|....#|...#.|..#..|.....|..#..', '[': '.###.|.#...|.#...|.#...|.#...|.#...|.###.',
  ']': '.###.|...#.|...#.|...#.|...#.|...#.|.###.', '·': '.....|.....|.....|.##..|.##..|.....|.....',
};
for (const [ch, src] of Object.entries(FONT)) {
  const rows = src.split('|');
  if (rows.some((r) => r.length !== 5) || rows.length < 7 || rows.length > 8) throw new Error(`bad glyph ${ch}`);
  FONT[ch] = rows;
}
const gid = (ch) => `t${ch.codePointAt(0).toString(36)}`;

// Lit cells as a compact path: horizontal runs, merged down rows.
function cellsPath(rows) {
  const rects = [];
  let active = new Map();
  rows.forEach((row, y) => {
    const next = new Map();
    let x = 0;
    while (x < row.length) {
      if (row[x] !== '#') { x++; continue; }
      let x1 = x;
      while (x1 < row.length && row[x1] === '#') x1++;
      const key = `${x},${x1}`;
      const r = active.get(key);
      if (r) { r.h++; next.set(key, r); } else { const nr = { x, y, w: x1 - x, h: 1 }; rects.push(nr); next.set(key, nr); }
      x = x1;
    }
    active = next;
  });
  return rects.map((r) => `M${r.x} ${r.y}h${r.w}v${r.h}h${-r.w}z`).join('');
}
const usedGlyphs = new Set();
// A run of type as <use> elements, in cell units (6 to a character).
function textUses(str, col0 = 0, cell = 6) {
  let s = '';
  [...str].forEach((ch, i) => {
    if (ch === ' ') return;
    if (!FONT[ch]) throw new Error(`no glyph for "${ch}"`);
    usedGlyphs.add(ch);
    s += `<use href="#${gid(ch)}" x="${(col0 + i) * cell}"/>`;
  });
  return s;
}

// ================================================================ timeline
// One 60 s day. It opens in late afternoon, so frame 0 is the daytime scene.
//    0-8   afternoon        17-26  night falls      40-48  night lifts
//    8-17  dusk comes in    26-40  night            48-56  dawn fades to day
css.push(`.dk,.nt{opacity:0}.dk{animation:dk ${LOOP}s linear ${dly()} infinite}.nt{animation:nt ${LOOP}s linear ${dly()} infinite}`);
css.push(`@keyframes dk{0%,${pc(8 / LOOP)}{opacity:0}${pc(17 / LOOP)},${pc(48 / LOOP)}{opacity:1}${pc(56 / LOOP)},100%{opacity:0}}`);
css.push(`@keyframes nt{0%,${pc(17 / LOOP)}{opacity:0}${pc(26 / LOOP)},${pc(40 / LOOP)}{opacity:1}${pc(48 / LOOP)},100%{opacity:0}}`);

// ================================================================ sky
defs.push(`<clipPath id="panel"><rect width="${W}" height="${H}" rx="12"/></clipPath>`);
const HAZE = { day: '#dcc0c9', dusk: '#ffc477', night: '#2c1c60' };
defs.push(vgrad('skd', 0, HY, [[0, '#4a6fb5'], [0.4, '#7b8cbf'], [0.75, '#b3a2c2'], [1, HAZE.day]]));
defs.push(vgrad('skk', 0, HY, [[0, '#241a52'], [0.38, '#6b3479'], [0.68, '#d2566d'], [0.9, '#ff9a5e'], [1, HAZE.dusk]]));
defs.push(vgrad('skn', 0, HY, [[0, '#03040f'], [0.5, '#070926'], [0.84, '#130f3c'], [1, HAZE.night]]));
// Only the day sky sits under the floor. The dusk sky and the night sky (with its stars) are
// returned as fragments and painted later, inside the same fading group as that hour's haze and
// floor tint: one group, one opacity, so where sky meets haze there is a single layer and no seam
// can appear at the horizon while two hours cross-fade.
const skySvg = `<rect width="${W}" height="${H}" fill="#07091c"/><rect width="${W}" height="${HY + 2}" fill="url(#skd)"/>`;
const duskSky = `<rect width="${W}" height="${HY + 2}" fill="url(#skk)"/>`;
let nightSky = '';
{
  // stars: three brightness tiers as merged paths, a handful that twinkle, one that falls
  const tiers = ['', '', ''];
  let twinkle = '';
  for (let i = 0; i < 96; i++) {
    const x = 6 + rand() * (W - 12), y = 4 + rand() ** 1.3 * (HY - 26), s = 1 + rand() * 1.2;
    if (i % 12 === 5) twinkle += `<rect class="tw" x="${n1(x)}" y="${n1(y)}" width="2.2" height="2.2" style="animation-delay:${dly(-rand() * 3)}"/>`;
    else tiers[i % 3] += `M${n1(x)} ${n1(y)}h${n1(s)}v${n1(s)}h${n1(-s)}z`;
  }
  defs.push('<linearGradient id="ssg"><stop offset="0" stop-color="#fff" stop-opacity="0"/><stop offset="1" stop-color="#fff"/></linearGradient>');
  nightSky = `<rect width="${W}" height="${HY + 2}" fill="url(#skn)"/>`
    + `<g fill="#fff">${tiers.map((d, i) => `<path d="${d}" opacity="${[0.9, 0.6, 0.35][i]}"/>`).join('')}${twinkle}</g>`
    + '<g transform="translate(770 22) rotate(152)"><rect class="ss" width="52" height="1.5" rx=".7" fill="url(#ssg)"/></g>';
  css.push('.tw{animation:tw 2.4s ease-in-out infinite alternate}@keyframes tw{from{opacity:1}to{opacity:.15}}');
  css.push(`.ss{opacity:0;animation:ss ${LOOP}s linear ${dly()} infinite}@keyframes ss{0%,55%{opacity:0;transform:translateX(0)}55.4%{opacity:1}57.2%,100%{opacity:0;transform:translateX(230px)}}`);
}

// Sun and moon: opposite ends of one wheel about the horizon's centre. The
// wheel dawdles while either is near the horizon and hurries over the top,
// where both are off-frame anyway.
const WR = 410;
{
  defs.push(rgrad('sunh', [[0, '#fffdf0', 0.95], [0.27, '#fff6d8', 0.5], [0.6, '#ffe9d0', 0.14], [1, '#ffe9d0', 0]]));
  defs.push(rgrad('sunk', [[0, '#ffd27a', 0.85], [0.2, '#ff9850', 0.5], [0.55, '#ff6a5a', 0.16], [1, '#ff6a5a', 0]]));
  defs.push(rgrad('sunc', [[0, '#fff3b0'], [0.6, '#ffb347'], [1, '#ff6a3d']]));
  defs.push(rgrad('moonh', [[0, '#dfe6ff', 0.6], [0.35, '#b8c4ff', 0.2], [1, '#b8c4ff', 0]]));
}
defs.push(`<clipPath id="skc"><rect width="${W}" height="${HY}"/></clipPath>`);
const orbSvg = '<g clip-path="url(#skc)"><g class="wh">'
  + `<g transform="translate(${CX + WR} ${HY})"><circle r="62" fill="url(#sunh)"/><circle r="16.5" fill="#fffbe8"/>`
  + '<g class="dk"><circle r="170" fill="url(#sunk)"/><circle r="19" fill="url(#sunc)"/></g></g>'
  + `<g transform="translate(${CX - WR} ${HY})"><circle r="46" fill="url(#moonh)"/><circle r="14" fill="#eef1ff"/>`
  + '<path d="M-5 -4a3.4 3.4 0 1 0 .1 0zM4 3a2.4 2.4 0 1 0 .1 0zM3.5 -8a1.7 1.7 0 1 0 .1 0zM-6 6a1.5 1.5 0 1 0 .1 0z" fill="#c3cbe8"/></g>'
  + '</g></g>';
css.push(`.wh{transform-origin:${CX}px ${HY}px;animation:wh ${LOOP}s linear ${dly()} infinite}`);
css.push(`@keyframes wh{0%{transform:rotate(-32deg)}${pc(20 / LOOP)}{transform:rotate(7deg)}${pc(32 / LOOP)}{transform:rotate(30deg);animation-timing-function:ease-in-out}`
  + `${pc(36 / LOOP)}{transform:rotate(150deg)}${pc(46 / LOOP)}{transform:rotate(190deg)}${pc(54 / LOOP)}{transform:rotate(215deg);animation-timing-function:ease-in}`
  + `${pc(58 / LOOP)}{transform:rotate(322deg)}100%{transform:rotate(328deg)}}`);

// ================================================================ floor
// Camera: eye EYE tiles above the floor, looking level. A point z tiles ahead
// lands K / z below the horizon; a tile is (y - HY) / EYE wide at that depth.
const ZB = 3;                  // depth at the bottom edge of the frame, in tiles
const K = (H - HY) * ZB;
const EYE = 1.5;
const NB = 16;                 // dark rows alive at once, per wedge parity
const ZEND = ZB - 1;           // a row is recycled once its far edge leaves the frame
const ZFAR = ZEND + 2 * NB;    // and is born here, under the haze
const TZ = 3;                  // seconds to fly two tiles forward
const TX = 12;                 // seconds to drift two tiles sideways
const TILE_DARK = '#47474f';   // the light tiles are the gradient under them
let floorSvg = '';
{
  // the shared journey of one row: far edge at zb + 1, near edge at zb
  const us = [0];
  for (let u = 0; u < 1;) {
    let du = 0.2;
    for (let it = 0; it < 5; it++) {
      const z = Math.max(ZFAR - (u + du) * 2 * NB, ZB - 0.2);
      du = Math.min(0.2, Math.sqrt((8 * 0.1) / ((2 * K * (2 * NB) ** 2) / z ** 3)));
    }
    u = Math.min(1, u + du);
    us.push(u);
  }
  const kf = us.map((u) => {
    const zb = ZFAR - u * 2 * NB, zt = zb + 1;
    return `${pc(u)}{transform:translateY(${n(HY + K / zt)}px) scaleY(${n(K / zb - K / zt, 3)})}`;
  }).join('');
  const D = NB * TZ;
  css.push(`.fb{animation:fb ${D}s linear infinite}@keyframes fb{${kf}}`);
  const k1 = 1 / EYE;
  css.push(`.fk{animation:fk ${TX}s linear ${dly()} infinite}@keyframes fk{from{transform:matrix(1,0,${n(k1, 4)},1,${n(-k1 * HY, 3)},0)}to{transform:matrix(1,0,${n(-k1, 4)},1,${n(k1 * HY, 3)},0)}}`);
  const wedges = ['', ''];
  const yb = H + 12, tw = (yb - HY) / EYE;
  for (let j = -37; j < 37; j++) wedges[j & 1] += `M${CX} ${HY}L${n1(CX + j * tw)} ${yb}L${n1(CX + (j + 1) * tw)} ${yb}Z`;
  defs.push(`<clipPath id="fwa"><path d="${wedges[0]}"/></clipPath><clipPath id="fwb"><path d="${wedges[1]}"/></clipPath>`);
  defs.push(`<clipPath id="flc"><rect y="${HY}" width="${W}" height="${H - HY}"/></clipPath>`);
  defs.push(vgrad('flg', HY, H, [[0, '#f4f3f6'], [1, '#dddde4']]));
  const band = (phase) => `<rect class="fb" x="-1500" width="3900" height="1" style="animation-delay:${dly(-phase * D)}"/>`;
  let a = '', b = '';
  for (let j = 0; j < NB; j++) { a += band(j / NB); b += band((j + 0.5) / NB); }
  floorSvg = `<g clip-path="url(#flc)"><rect y="${HY}" width="${W}" height="${H - HY}" fill="url(#flg)"/>`
    + `<g class="fk" fill="${TILE_DARK}"><g clip-path="url(#fwa)">${a}</g><g clip-path="url(#fwb)">${b}</g></g></g>`;
}
// haze at the horizon (it also hides the rows being born), then the dusk and
// night tints over the whole floor
{
  const fog = (id, col) => defs.push(vgrad(id, HY, HY + 130, [[0, col, 1], [0.14, col, 1], [0.3, col, 0.72], [0.55, col, 0.3], [1, col, 0]]));
  // (every haze rect starts one unit above the horizon, overlapping the sky of its own hour, which
  // ends in the same colour: opaque on opaque inside one group, so nothing shows through)
  fog('fgd', HAZE.day); fog('fgk', HAZE.dusk); fog('fgn', HAZE.night);
  defs.push(vgrad('ftk', HY, H, [[0, '#ff9a5e', 0.5], [0.5, '#e0506a', 0.34], [1, '#7a2a6a', 0.42]]));
  defs.push(vgrad('ftn', HY, H, [[0, '#120c3a', 0.86], [0.4, '#0a0a2c', 0.8], [1, '#05061a', 0.78]]));
}
const fogSvg = `<rect y="${HY - 1}" width="${W}" height="131" fill="url(#fgd)"/>`
  + `<g class="dk">${duskSky}<rect y="${HY}" width="${W}" height="${H - HY}" fill="url(#ftk)"/><rect y="${HY - 1}" width="${W}" height="131" fill="url(#fgk)"/></g>`
  + `<g class="nt">${nightSky}<rect y="${HY}" width="${W}" height="${H - HY}" fill="url(#ftn)"/><rect y="${HY - 1}" width="${W}" height="131" fill="url(#fgn)"/></g>`;

// ================================================================ scroller
// Small, out in the distance, standing on the horizon line like a sign at the far end of the
// floor: the spheres only brush its feet at the top of a bounce, so it stays readable. It is
// slow. It is meant to be.
const PX = 2;
const CREW = 'REFLECTIVE ASSETS DIVISION';
const SCROLL = [
  'R.A.D. PRESENTS ULTRA-SATISFACTORY',
  'TABS: OBJECTIVES * ITEMS * BUILDINGS',
  'A COMPANION APP FOR THE FACTORY GAME SATISFACTORY: EVERY RECIPE, BUILDING AND SPACE ELEVATOR OBJECTIVE, ONE CLICK APART',
  '140 ITEMS * 211 RECIPES (88 ALTERNATE) * 477 BUILDINGS * 5 SPACE ELEVATOR PHASES',
  'RUN IT: python -m pip install -r requirements.txt THEN python -m streamlit run app/app.py',
  'OR INSTALL NOTHING: lukexyz.github.io/ULTRA-SATISFACTORY',
  'UNOFFICIAL FAN PROJECT, NOT AFFILIATED WITH COFFEE STAIN STUDIOS',
  'SPHERES ON SHIFT: 6. OUTPUT: 0/MIN. POWER DRAW: NONE. MORALE: SHINY',
  'YES, THIS SCROLLER IS SLOW. NOBODY OVERCLOCKED IT',
].map((s) => `  +++  ${s}`).join('');
const SCROLL_SPEED = 56; // px per second
const SCROLL_L = SCROLL.length * 6 * PX;
const SCROLL_T = SCROLL_L / SCROLL_SPEED;
let scrollSvg = '';
{
  const head = SCROLL.slice(0, Math.ceil(W / (6 * PX)) + 1);
  defs.push(vgrad('scg', 0, 7, [[0, '#fffbe0'], [0.45, '#ffe066'], [1, '#f2a31c']]));
  scrollSvg = `<g transform="translate(0 ${HY - 7 * PX - 1}) scale(${PX})"><g class="sc" fill="url(#scg)" stroke="#1d1238" stroke-width=".8" stroke-linejoin="round" paint-order="stroke">`
    + `${textUses(SCROLL + head)}</g></g>`;
  css.push(`.sc{animation:sc ${n(SCROLL_T, 3)}s linear ${dly()} infinite}@keyframes sc{from{transform:translateX(0)}to{transform:translateX(${-SCROLL.length * 6}px)}}`);
}

// ================================================================ chrome logo
// Parametric capitals drawn for this banner: wide, heavy, and "sliced". Every
// big cut runs the same way as the italic slope (/): the top-left of a stem or
// bowl, the bottom-right of a bowl, and the free end of every bar.
function glyph(ch, { w, h, s, t }) {
  const C = s * 0.62;            // stem-tip cut
  const CB = Math.min(w, h) * 0.34; // bowl cut
  const c = s * 0.2;             // the small opposite chamfer
  const d = t * 0.6;             // slope of a bar's free end
  const ci = Math.max(2, CB - 0.293 * (s + t)); // inner cut parallel to CB
  const a = (w - s) / 2, b = (w + s) / 2;
  switch (ch) {
    case 'U': return { adv: w, polys: [[[0, C], [C, 0], [s, 0], [s, h - t], [w - s - ci, h - t], [w - s, h - t - ci], [w - s, C], [w - s + C, 0], [w, 0], [w, h - CB], [w - CB, h], [c, h], [0, h - c]]] };
    case 'L': { const lw = w * 0.84; return { adv: lw, polys: [[[0, C], [C, 0], [s, 0], [s, h - t], [lw, h - t], [lw - d, h], [c, h], [0, h - c]]] }; }
    case 'T': return { adv: w, polys: [[[d, 0], [w, 0], [w - d, t], [b, t], [b, h - C], [b - C, h], [a, h], [a, t], [0, t]]] };
    case 'R': {
      const m = h * 0.56, lw = s * 1.1, la = s + (w - 2 * s) * 0.2, cb = CB * 0.8, cj = Math.max(2, cb - 0.293 * (s + t));
      return { adv: w, polys: [
        [[0, C], [C, 0], [w - c, 0], [w, c], [w, m - cb], [w - cb, m], [la + lw, m], [w, h], [w - lw, h], [la, m], [s, m], [s, h - C], [s - C, h], [0, h]],
        [[s, t], [w - s, t], [w - s, m - t - cj], [w - s - cj, m - t], [s, m - t]],
      ] };
    }
    case 'A': {
      const xl = w * 0.29, s2 = s * 1.06, run = xl / h, y1 = h * 0.6, y2 = y1 + t * 0.85;
      const inL = (y) => s2 + (h - y) * run;
      const ya = h - (w / 2 - s2) / run; // where the inner edges meet
      const top = ya > t * 0.9 ? [[w / 2, ya]] : [[inL(t), t], [w - inL(t), t]];
      return { adv: w, polys: [
        [[0, h], [xl, 0], [w - xl, 0], [w, h], [w - s2, h], [w - inL(y2), y2], [inL(y2), y2], [s2, h]],
        [...top, [w - inL(y1), y1], [inL(y1), y1]],
      ] };
    }
    case 'S': {
      const m0 = (h - t) / 2, m1 = (h + t) / 2;
      return { adv: w, polys: [[[CB, 0], [w, 0], [w - d, t], [s + ci, t], [s, t + ci], [s, m0], [w - c, m0], [w, m0 + c], [w, h - CB], [w - CB, h], [0, h], [d, h - t], [w - s - ci, h - t], [w - s, h - t - ci], [w - s, m1], [c, m1], [0, m1 - c], [0, CB]]] };
    }
    case 'I': { const iw = s * 1.08; return { adv: iw, polys: [[[0, C], [C, 0], [iw, 0], [iw, h - C], [iw - C, h], [0, h]]] }; }
    case 'F': { const fw = w * 0.92, m = h * 0.43, bt = t * 0.9, mw = fw * 0.8; return { adv: fw, polys: [[[0, C], [C, 0], [fw, 0], [fw - d, t], [s, t], [s, m], [mw, m], [mw - d, m + bt], [s, m + bt], [s, h - C], [s - C, h], [0, h]]] }; }
    case 'C': return { adv: w, polys: [[[CB, 0], [w, 0], [w - d, t], [s + ci, t], [s, t + ci], [s, h - t], [w, h - t], [w - d, h], [c, h], [0, h - c], [0, CB]]] };
    case 'O': return { adv: w, polys: [
      [[CB, 0], [w - c, 0], [w, c], [w, h - CB], [w - CB, h], [c, h], [0, h - c], [0, CB]],
      [[s + ci, t], [w - s, t], [w - s, h - t - ci], [w - s - ci, h - t], [s, h - t], [s, t + ci]],
    ] };
    case 'Y': {
      const sa = s * 1.12, jy = h * 0.5, vy = (jy * (w / 2 - sa)) / a;
      return { adv: w, polys: [[[0, 0], [sa, 0], [w / 2, vy], [w - sa, 0], [w, 0], [b, jy], [b, h - C], [b - C, h], [a, h], [a, jy]]] };
    }
    default: throw new Error(`no logo glyph ${ch}`);
  }
}
const area2 = (p) => p.reduce((acc, [x1, y1], i) => { const [x2, y2] = p[(i + 1) % p.length]; return acc + x1 * y2 - x2 * y1; }, 0);
// Normalise winding so the metal is always on the right of each edge.
const wind = (p, clockwise) => ((area2(p) > 0) === clockwise ? p : [...p].reverse());
// Unit normal pointing into the metal, per edge.
function edgeNormals(p) {
  return p.map(([x1, y1], i) => {
    const [x2, y2] = p[(i + 1) % p.length];
    const dx = x2 - x1, dy = y2 - y1, l = Math.hypot(dx, dy);
    return [-dy / l, dx / l];
  });
}
// Mitred inset of a polygon by b, towards the metal.
function inset(p, b) {
  const nn = edgeNormals(p);
  return p.map(([x, y], i) => {
    const u = nn[(i + p.length - 1) % p.length], v = nn[i];
    const k = b / Math.max(0.4, 1 + u[0] * v[0] + u[1] * v[1]);
    return [x + (u[0] + v[0]) * k, y + (u[1] + v[1]) * k];
  });
}

const VP = [CX, HY];       // the slab's depth runs to the floor's vanishing point
const DEPTH = 0.058;       // how far along that line the back face sits
const LOOM = 0.00055;      // keystone: the logo leans out over the viewer a little
const LOOM_Y = 105;
const LIGHT = [-0.3, -0.954]; // towards the light
const KEY = '#07112a';
const PAL = {
  u: {
    face: [[0, '#0b2a6a'], [0.22, '#1b57a8'], [0.4, '#56b3ee'], [0.5, '#e4f8ff'], [0.535, '#ffffff'], [0.535, '#05133a'], [0.68, '#124a92'], [0.86, '#3fa4e6'], [1, '#c8f1ff']],
    bevel: ['#08255a', '#3a86cc', '#f2fcff'], wall: ['#06122e', '#2c5b9c'],
  },
  s: {
    face: [[0, '#1b3a66'], [0.22, '#3b5f98'], [0.4, '#86acd9'], [0.5, '#eaf4ff'], [0.535, '#ffffff'], [0.535, '#0a1830'], [0.68, '#2a4c7e'], [0.86, '#6f98cf'], [1, '#e2f0ff']],
    bevel: ['#11264a', '#6188bd', '#ffffff'], wall: ['#081226', '#3c5b8e'],
  },
};
const ROWS = [
  { id: 'u', text: 'ULTRA', y: 31, h: 78, w: 92, s: 28, t: 20, gap: 13, k: 0.24, bevel: 3.2, kern: { LT: -7, RA: -3, TR: 1 } },
  { id: 's', text: 'SATISFACTORY', y: 122, h: 60, w: 60, s: 18, t: 14, gap: 10.5, k: 0.24, bevel: 2.5, kern: { SA: -3, AT: -6, FA: -8, AC: -4, TO: -2, RY: -3, CT: -1 } },
];
const loom = ([x, y]) => [CX + (x - CX) * (1 + LOOM * (LOOM_Y - y)), y];
const back = ([x, y]) => [x + (VP[0] - x) * DEPTH, y + (VP[1] - y) * DEPTH];

function buildRow(row) {
  const pal = PAL[row.id];
  const glyphs = [...row.text].map((ch) => glyph(ch, row));
  let total = 0;
  const xs = glyphs.map((g, i) => {
    if (i) total += row.gap + (row.kern[row.text[i - 1] + row.text[i]] || 0);
    const x = total; total += g.adv; return x;
  });
  const lean = row.h * row.k;
  const x0 = (W - total - lean) / 2;
  const tf = (gx) => ([x, y]) => loom([x0 + gx + x + (row.h - y) * row.k, row.y + y]);
  const polys = [];
  glyphs.forEach((g, i) => g.polys.forEach((p, j) => polys.push(wind(p.map(tf(xs[i])), j === 0))));

  // Walls: an edge shows its side if that side faces the vanishing point.
  // Painted far-from-the-vanishing-point first, so nearer walls overlap.
  const walls = [];
  let wallsAll = '';
  for (const p of polys) {
    const nn = edgeNormals(p);
    p.forEach((a, i) => {
      const b = p[(i + 1) % p.length];
      const ox = -nn[i][0], oy = -nn[i][1];
      const mx = (a[0] + b[0]) / 2, my = (a[1] + b[1]) / 2;
      const vx = VP[0] - mx, vy = VP[1] - my, vl = Math.hypot(vx, vy);
      if ((ox * vx + oy * vy) / vl <= 0.03) return;
      const shade = Math.round(Math.min(1, Math.abs(ox) * 0.85 + (oy < 0 ? 0.15 : 0)) * 4) / 4;
      const q = polyD([a, b, back(b), back(a)]);
      walls.push({ dist: vl, col: lerpHex(pal.wall[0], pal.wall[1], shade), d: q });
      wallsAll += q;
    });
  }
  walls.sort((p, q) => q.dist - p.dist);
  let wallSvg = '';
  for (let i = 0; i < walls.length;) {
    let j = i, d = '';
    while (j < walls.length && walls[j].col === walls[i].col) d += walls[j++].d;
    wallSvg += `<path d="${d}" fill="${walls[i].col}" stroke="${walls[i].col}" stroke-width=".5" stroke-linejoin="round"/>`;
    i = j;
  }

  // Bevel: a quad per edge between the outline and the inset face, lit from above.
  const faces = polys.map((p) => inset(p, row.bevel));
  const bevels = new Map();
  let rim = '';
  polys.forEach((p, pi) => {
    const nn = edgeNormals(p), f = faces[pi];
    p.forEach((a, i) => {
      const j = (i + 1) % p.length;
      const lit = -(nn[i][0] * LIGHT[0] + nn[i][1] * LIGHT[1]);
      const q = Math.round(lit * 4) / 4;
      const col = q >= 0 ? lerpHex(pal.bevel[1], pal.bevel[2], q) : lerpHex(pal.bevel[1], pal.bevel[0], -q);
      bevels.set(col, (bevels.get(col) || '') + polyD([a, p[j], f[j], f[i]]));
      if (lit > 0.55) rim += `M${n1(f[i][0])} ${n1(f[i][1])}L${n1(f[j][0])} ${n1(f[j][1])}`;
    });
  });

  const id = row.id;
  const top = row.y, bot = row.y + row.h, brk = top + row.h * 0.535;
  defs.push(`<path id="o${id}" d="${polys.map((p) => polyD(p)).join('')}"/><path id="f${id}" d="${faces.map((p) => polyD(p)).join('')}"/><path id="w${id}" d="${wallsAll}"/>`);
  defs.push(vgrad(`cf${id}`, top, bot, pal.face));
  defs.push(`<clipPath id="fc${id}"><use href="#f${id}" clip-rule="evenodd"/></clipPath>`);

  // The chrome's lower half mirrors the floor: a faint checker running to the
  // break line, as if the letters were polished enough to show the foundations.
  let check = '';
  {
    const depth = bot - brk + 2, eye = 0.5;
    const rowsY = [];
    for (let z = 1; z < 9; z++) rowsY.push(brk + depth / z);
    const cxr = CX + 23;
    for (let r = 0; r < rowsY.length - 1; r++) {
      const ya = rowsY[r], yb = rowsY[r + 1];
      const wa = (ya - brk) / eye, wb = (yb - brk) / eye;
      const j0 = Math.floor((x0 - 20 - cxr) / wa) - 1, j1 = Math.ceil((x0 + total + lean + 20 - cxr) / wa) + 1;
      for (let j = j0; j <= j1; j++) {
        if ((j + r) & 1) continue;
        check += `M${n1(cxr + j * wa)} ${n1(ya)}L${n1(cxr + (j + 1) * wa)} ${n1(ya)}L${n1(cxr + (j + 1) * wb)} ${n1(yb)}L${n1(cxr + j * wb)} ${n1(yb)}Z`;
      }
    }
  }

  let g = `<g fill="${KEY}" stroke="${KEY}" stroke-width="3" stroke-linejoin="round"><use href="#o${id}" fill-rule="evenodd"/><use href="#w${id}"/></g>`;
  g += wallSvg;
  g += `<use href="#o${id}" fill-rule="evenodd" fill="${pal.bevel[1]}"/>`;
  for (const [col, d] of bevels) g += `<path d="${d}" fill="${col}"/>`;
  g += `<use href="#f${id}" fill-rule="evenodd" fill="url(#cf${id})"/>`;
  g += `<g clip-path="url(#fc${id})"><path d="${check}" fill="#fff" fill-opacity=".17"/>`
    + `<rect x="0" y="${n1(brk - 0.6)}" width="${W}" height="1.2" fill="#fff" fill-opacity=".9"/></g>`;
  g += `<path d="${rim}" fill="none" stroke="#fff" stroke-opacity=".85" stroke-width=".8" stroke-linecap="round"/>`;
  return { svg: g, x0, x1: x0 + total + lean, top, bot, brk, polys };
}
const rowU = buildRow(ROWS[0]);
const rowS = buildRow(ROWS[1]);

// dusk and night tints: translucent gradients over the finished metal
let logoTint = '';
for (const r of [rowU, rowS]) {
  const id = r === rowU ? 'u' : 's';
  defs.push(vgrad(`ck${id}`, r.top, r.bot, [[0, '#2a1458', 0.62], [0.3, '#8a3a86', 0.5], [0.53, '#ffb060', 0.62], [0.54, '#3a0f3a', 0.6], [0.8, '#d04a5e', 0.5], [1, '#ffc27a', 0.5]]));
  defs.push(vgrad(`cn${id}`, r.top, r.bot, [[0, '#0a0f3c', 0.86], [0.3, '#2a2f9c', 0.74], [0.5, '#9a7bff', 0.7], [0.53, '#ff9ae0', 0.88], [0.54, '#060824', 0.88], [0.8, '#2b2fa2', 0.74], [1, '#9aa2ff', 0.6]]));
  logoTint += `<g class="dk"><use href="#w${id}" fill="#5a1d4e" fill-opacity=".5"/><use href="#o${id}" fill-rule="evenodd" fill="url(#ck${id})"/></g>`
    + `<g class="nt"><use href="#w${id}" fill="#03041a" fill-opacity=".72"/><use href="#o${id}" fill-rule="evenodd" fill="url(#cn${id})"/>`
    + `<use href="#o${id}" fill="none" stroke="#d6d2ff" stroke-opacity=".85" stroke-width=".9"/></g>`;
}

// A sheen crossing the faces every 10 s, and three corner sparkles.
let sheenSvg = '';
{
  defs.push('<clipPath id="lgc"><use href="#ou" clip-rule="evenodd"/><use href="#os" clip-rule="evenodd"/></clipPath>');
  defs.push(`<linearGradient id="shg">${stops([[0, '#fff', 0], [0.4, '#fff', 0.55], [0.5, '#fff', 0.9], [0.6, '#fff', 0.55], [1, '#fff', 0]])}</linearGradient>`);
  sheenSvg = '<g clip-path="url(#lgc)"><g transform="skewX(-24)"><rect class="sn" x="-60" y="20" width="70" height="180" fill="url(#shg)"/></g></g>';
  css.push(`.sn{animation:sn 10s linear ${dly(-5.6)} infinite}@keyframes sn{0%,72%{transform:translateX(0)}100%{transform:translateX(1080px)}}`);
  defs.push('<path id="spk" d="M0 -1Q.07 -.07 1 0Q.07 .07 0 1Q-.07 .07 -1 0Q-.07 -.07 0 -1Z"/>');
  const at = [[rowU.polys[0][1][0] + 1, rowU.top + 1, 13, 0], [rowS.x1 - 5, rowS.top + 2, 10, -2.1], [rowU.x1 - 27, rowU.top + 2, 9, -3.9]];
  for (const [x, y, r, d0] of at) {
    sheenSvg += `<g transform="translate(${n1(x)} ${n1(y)}) scale(${r})"><use href="#spk" class="sp" fill="#fff" style="animation-delay:${dly(d0)}"/></g>`;
  }
  css.push('.sp{animation:sp 6s ease-in-out infinite}@keyframes sp{0%,58%{transform:scale(0) rotate(0deg)}70%{transform:scale(1) rotate(40deg)}82%,100%{transform:scale(0) rotate(80deg)}}');
}

// "presents" above, the pitch below
let typeSvg = '';
{
  const line = (str, y, px, fill, cell = 6) => {
    const wpx = ((str.length - 1) * cell + 5) * px;
    return `<g transform="translate(${n1(CX - wpx / 2)} ${y}) scale(${px})" fill="${fill}">${textUses(str, 0, cell)}</g>`;
  };
  const shadowed = (s) => `<g stroke="#0c1536" stroke-opacity=".85" stroke-width=".7" stroke-linejoin="round" paint-order="stroke">${s}</g>`;
  defs.push(vgrad('tyg', 0, 7, [[0, '#ffffff'], [1, '#d5e6ff']]));
  const PITCH = 'EVERY RECIPE, BUILDING AND SPACE ELEVATOR OBJECTIVE, ONE CLICK APART';
  // a sliced plate behind the pitch, so white type holds up against the pale afternoon sky
  const pw = ((PITCH.length - 1) * 6 + 5) * 2 / 2 + 16, py = 192, ph = 24, cut = 7;
  const plate = polyD([[CX - pw + cut, py], [CX + pw, py], [CX + pw - cut, py + ph], [CX - pw, py + ph]]);
  typeSvg = `<path d="${plate}" fill="#0a1238" fill-opacity=".4"/><path d="M${n1(CX - pw + cut)} ${py + 0.5}H${n1(CX + pw)}" stroke="#fff" stroke-opacity=".35"/>`
    + shadowed(line(`${CREW}  PRESENTS`, 9, 1.5, '#f4f8ff', 8) + line(PITCH, 197, 2, 'url(#tyg)'));
}

const logoSvg = `<g class="lf">${rowS.svg}${rowU.svg}${logoTint}${sheenSvg}</g>`;
css.push(`.lf{animation:lf 7.5s ease-in-out ${dly()} infinite alternate}@keyframes lf{from{transform:translateY(-2px)}to{transform:translateY(2.5px)}}`);

// ================================================================ spheres
// Six mirror balls in a loose row, half a tile in radius, each tinted along
// the app's cyan-to-pink run. Sizes and floor positions come from the same
// camera as the floor, so they sit on it properly.
const SPHERES = [
  { x: 92, z: 4.6, tint: '#19c8f5' },
  { x: 232, z: 5.7, tint: '#38bdf8' },
  { x: 372, z: 4.0, tint: '#5f86ff' },
  { x: 530, z: 5.2, tint: '#a855f7' },
  { x: 672, z: 3.8, tint: '#d44ee8' },
  { x: 812, z: 5.5, tint: '#ec4899' },
];
const RW = 0.5;       // radius in tiles
const HOVER = 0.12;   // clearance at the bottom of the bounce, in radii
const AMP = 0.95;     // bounce height, in radii
const BOUNCE = 2.4;   // seconds
const Q = 0.64;       // ratio of the ring ladder in the reflection
const SLOPE = 0.55;   // wedge pitch in the reflection
let shadowSvg = '';
const sphereParts = [];
{
  // shared reflection parts, in unit-sphere coordinates (y down, equator y = 0)
  let rings = '';
  for (let k = -3; k <= 12; k++) { const ry = n(Q ** k, 4); rings += `M-1 0A1 ${ry} 0 1 0 1 0A1 ${ry} 0 1 0 -1 0Z`; }
  defs.push(`<path id="rg" fill-rule="evenodd" d="${rings}"/>`);
  const wd = ['', ''];
  for (let j = -24; j <= 24; j++) wd[j & 1] += `M0 0L${n((j - 0.5) * SLOPE * 1.1, 3)} 1.1L${n((j + 0.5) * SLOPE * 1.1, 3)} 1.1Z`;
  defs.push(`<clipPath id="swa"><path d="${wd[0]}"/></clipPath><clipPath id="swb"><path d="${wd[1]}"/></clipPath>`);
  defs.push('<clipPath id="slo"><path d="M-1 0A1 1 0 0 0 1 0Z"/></clipPath>');
  const zk = [];
  for (let i = 0; i <= 8; i++) zk.push(`${pc(i / 8)}{transform:scaleY(${n(Q ** ((2 * i) / 8), 4)})}`);
  css.push(`.zm{animation:zm ${TZ}s linear ${dly()} infinite}@keyframes zm{${zk.join('')}}`);
  css.push(`.zk{animation:zk ${TX}s linear ${dly()} infinite}@keyframes zk{from{transform:matrix(1,0,${SLOPE},1,0,0)}to{transform:matrix(1,0,${-SLOPE},1,0,0)}}`);
  css.push(`.bn{animation:bn ${BOUNCE}s infinite}@keyframes bn{0%,100%{transform:translateY(0);animation-timing-function:cubic-bezier(.33,.67,.67,1)}50%{transform:translateY(${-AMP}px);animation-timing-function:cubic-bezier(.33,0,.67,.33)}}`);
  css.push(`.sw{animation:sw ${BOUNCE}s infinite}@keyframes sw{0%,100%{transform:scale(1);opacity:.62;animation-timing-function:cubic-bezier(.33,.67,.67,1)}50%{transform:scale(.72);opacity:.26;animation-timing-function:cubic-bezier(.33,0,.67,.33)}}`);
  defs.push(rgrad('shd', [[0, '#0a0c1c', 1], [0.55, '#0a0c1c', 0.75], [1, '#0a0c1c', 0]]));
  defs.push(rgrad('shz', [[0, '#fff', 0.95], [0.5, '#fff', 0.5], [1, '#fff', 0]]));
  defs.push(rgrad('spc', [[0, '#fff', 1], [0.25, '#fff', 0.85], [1, '#fff', 0]]));
  defs.push(`<linearGradient id="sdk" x1="0" y1="0" x2="0" y2="1">${stops([[0, '#2a1458', 0.7], [0.4, '#b04a7a', 0.5], [0.5, '#ffb060', 0.6], [0.52, '#3a0f3a', 0.55], [1, '#c8506a', 0.45]])}</linearGradient>`);
  defs.push(`<linearGradient id="snt" x1="0" y1="0" x2="0" y2="1">${stops([[0, '#02030f', 0.86], [0.42, '#0b0c3a', 0.74], [0.5, '#4a36a8', 0.62], [0.52, '#02030f', 0.76], [1, '#060626', 0.6]])}</linearGradient>`);

  SPHERES.forEach((sp, i) => {
    const drop = K / sp.z;                 // floor contact below the horizon
    const yg = HY + drop, r = (RW * drop) / EYE;
    const cy = yg - r * (1 + HOVER);
    const lightTile = lerpHex(sp.tint, '#ffffff', 0.8), darkTile = lerpHex(sp.tint, '#0b1230', 0.72);
    const deep = lerpHex(sp.tint, '#030818', 0.74), skyTop = lerpHex(sp.tint, '#0c2460', 0.62), skyMid = lerpHex(sp.tint, '#8fb4ee', 0.6);
    defs.push(`<linearGradient id="sb${i}" x1="0" y1="0" x2="0" y2="1">${stops([[0, skyTop], [0.3, skyMid], [0.47, '#f4f8ff'], [0.5, '#ffffff'], [0.5, lightTile], [1, lightTile]])}</linearGradient>`);
    defs.push(rgrad(`sr${i}`, [[0, deep, 0], [0.5, deep, 0.05], [0.78, deep, 0.42], [0.93, deep, 0.85], [1, deep, 0.96]], ' cx=".56" cy=".4" r=".62" fx=".6" fy=".34"'));
    defs.push(rgrad(`sg${i}`, [[0, sp.tint, 0.7], [0.5, sp.tint, 0.3], [1, sp.tint, 0]]));
    const delay = dly(-((i * 0.37) % BOUNCE) - 0.2);
    shadowSvg += `<g transform="translate(${sp.x} ${n1(yg)}) scale(${n(r)})"><ellipse class="sw" rx="1.02" ry="${n((EYE / sp.z) * 1.05, 3)}" fill="url(#shd)" style="animation-delay:${delay}"/>`
      + `<ellipse class="nt" rx="2.1" ry="${n((EYE / sp.z) * 2.1, 3)}" fill="url(#sg${i})"/></g>`;
    sphereParts.push({ z: sp.z, svg: `<g transform="translate(${sp.x} ${n1(cy)}) scale(${n(r)})"><g class="bn" style="animation-delay:${delay}">`
      + `<circle r="1" fill="url(#sb${i})"/>`
      + `<g clip-path="url(#slo)" fill="${darkTile}"><g class="zk"><g clip-path="url(#swa)"><use href="#rg" class="zm"/></g><g clip-path="url(#swb)"><g transform="scale(1 ${Q})"><use href="#rg" class="zm"/></g></g></g></g>`
      + '<ellipse rx="1" ry=".15" fill="url(#shz)"/>'
      + '<ellipse cy=".8" rx=".36" ry=".1" fill="#0a0c1c" fill-opacity=".38"/>'
      + `<circle r="1" fill="url(#sr${i})"/>`
      + '<ellipse cx=".4" cy="-.5" rx=".3" ry=".2" transform="rotate(38 .4 -.5)" fill="url(#spc)"/>'
      + '<circle class="dk" r="1" fill="url(#sdk)"/>'
      + `<g class="nt"><circle r="1" fill="url(#snt)"/><circle r=".96" fill="none" stroke="${sp.tint}" stroke-opacity=".8" stroke-width=".06"/><ellipse cx="-.42" cy="-.5" rx=".2" ry=".12" transform="rotate(-38 -.42 -.5)" fill="url(#spc)" opacity=".8"/></g>`
      + `<circle r=".985" fill="none" stroke="${lerpHex(deep, '#000010', 0.4)}" stroke-opacity=".6" stroke-width=".03"/>`
      + '</g></g>' });
  });
}
// paint far spheres first
const sphereSvg = sphereParts.sort((a, b) => b.z - a.z).map((p) => p.svg).join('');

// ================================================================ glyph defs
{
  let d = '';
  for (const ch of [...usedGlyphs].sort()) d += `<path id="${gid(ch)}" d="${cellsPath(FONT[ch])}"/>`;
  defs.push(d);
}

// ================================================================ assemble
const body = [
  skySvg,
  floorSvg,
  fogSvg,
  orbSvg,
  scrollSvg,
  typeSvg,
  logoSvg,
  shadowSvg,
  sphereSvg,
  `<rect x=".75" y=".75" width="${W - 1.5}" height="${H - 1.5}" rx="11.5" fill="none" stroke="#1c2340" stroke-opacity=".9" stroke-width="1.5"/>`,
];
css.push('@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}');

const desc = 'A demoscene banner: chrome spheres over a checkerboard. ULTRA SATISFACTORY floats in the sky as a thick italic chrome logo, steel blue with a bright break line across each row of letters, its sides running back to the vanishing point. '
  + 'Below it a grey and white checker floor of foundations flies towards the viewer and drifts sideways, fading into haze at a low horizon. Six mirror balls tinted from cyan through purple to pink bounce over it in a wave, each reflecting the moving floor and the sky, each with a soft shadow. '
  + 'The sky runs a one-minute day: dusty mauve afternoon, the sun setting at the right, a starry indigo night with the moon and coloured light pooling under the spheres, then dawn. '
  + `Small type above the logo says ${CREW} presents; under it: every recipe, building and Space Elevator objective, one click apart. `
  + 'A small gold scroller at the horizon lists the three tabs (Objectives, Items, Buildings), the counts (140 items, 211 recipes of which 88 are alternates, 477 buildings, 5 Space Elevator phases), how to run it (python -m pip install -r requirements.txt, then python -m streamlit run app/app.py, or nothing to install at lukexyz.github.io/ULTRA-SATISFACTORY), and that it is an unofficial fan project.';

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-labelledby="t d">
<title id="t">ULTRA-SATISFACTORY</title>
<desc id="d">${desc}</desc>
<style>${css.join('\n')}</style>
<defs>${defs.join('\n')}</defs>
<g clip-path="url(#panel)">
${body.join('\n')}
</g>
</svg>
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
console.log(`${path.relative(process.cwd(), OUT)}: ${(svg.length / 1024).toFixed(1)} KB; day ${LOOP}s, floor ${TZ}s forward / ${TX}s sideways, bounce ${BOUNCE}s, scroller ${SCROLL.length} chars in ${SCROLL_T.toFixed(1)}s${T0 ? `; PREVIEW at t=${T0}s` : ''}`);

// ---------------------------------------------------------------- --ascii
// The same scene for text terminals, from the same projection: prints an
// 80-column checker floor with three of the spheres bouncing over it. Paste it
// into the .md by hand.
if (process.argv.includes('--ascii')) {
  const COLS = 80, FLOOR_ROWS = 9, SKY = 5;
  const eye = 1.3, Ka = (FLOOR_ROWS * 2 - 1) * ZB;
  const grid = [];
  for (let i = 0; i < SKY; i++) grid.push(Array(COLS).fill(' '));
  for (let r = 0; r < FLOOR_ROWS; r++) {
    const y = r * 2 + 1, z = Ka / y, tw = y / eye;
    const row = [];
    for (let c = 0; c < COLS; c++) {
      if (tw < 1.5) { row.push(c % 2 ? '.' : ' '); continue; } // haze
      const X = (c - COLS / 2 + 0.5) / tw - 0.5;
      row.push(((Math.floor(X + 100) + Math.floor(z)) & 1) ? '#' : ' ');
    }
    grid.push(row);
  }
  const BALL = [
    '  .-"""-.',
    ' /  o    \\',
    '|=========|',
    ' \\ # # # /',
    "  `-...-'",
  ];
  const stamp = (lines, col, top) => lines.forEach((line, i) => {
    const first = line.search(/\S/);
    // one clear cell either side, so the outline does not run into the tiles
    [...` ${line.slice(first)} `].forEach((ch, j) => { if (grid[top + i]) grid[top + i][col + first - 1 + j] = ch; });
  });
  // [column, top row, row of the shadow]
  for (const [c, t, sh] of [[5, 2, 9], [34, 5, 12], [63, 1, 8]]) {
    stamp(['  (:::::)'], c, sh);
    stamp(BALL, c, t);
  }
  console.log(grid.map((r) => r.join('').trimEnd()).join('\n'));
}
