// "Neon cube field" README banner for ULTRA-SATISFACTORY.
//
//   node examples/ultra-satisfactory/src/14-neon-cube-field_opus_5.5.mjs
//   node examples/ultra-satisfactory/src/14-neon-cube-field_opus_5.5.mjs --ascii
//
// Regenerates ../assets/14-neon-cube-field_opus_5.5.svg (the banner) and
// ../assets/14-neon-cube-field_opus_5.5-rule.svg (a divider: a row of spinning
// glenz octahedra). With --ascii it also prints the text-mode cube wave used
// in the .md's info file. Plain Node, no deps, deterministic (a seeded PRNG
// places the stars; no clock, no Math.random).
// (The .md beside the assets is hand-edited, not generated by this script. It
// quotes the cube count, the wave numbers and the 64k size limit: see the
// console output, and the size check near the end.)
//
// The look is the 2010-2012 Windows 64k-intro / cracktro revival (the style
// people call "the rez-era Razor 1911 look"): a field of hundreds of small
// glowing cubes that reads as one rainbow ramp, rolling in a wave; a segmented
// LCD-like wordmark pinned top centre; a text writer; scanlines over the lot.
// Nothing of theirs is reproduced: the wordmark is a generic segment display
// drawn from geometry in this file, the small type is a 5x7 bitmap font drawn
// as paths, and the crew name is made up. No <text>, one small blur filter
// (the wordmark's glow). The factory reading: the cubes are a floor of
// foundations, and the three signs standing on it are the app's three tabs.
//
// How it moves (every period divides LOOP = 32 s, bar the starfield, which
// wraps on its own, so nothing ever jumps)
//   Wave: the floor height is a sum of plane waves that share one period. A
//   sum of same-frequency sines is itself a sine at every point,
//   R(p) sin(wt + P(p)), so each cube needs only an amplitude (one of a few
//   @keyframes: up, down, and slightly bigger at the top) and a phase (a
//   negative animation-delay). Each cube is one <use> of one grey symbol and
//   animates nothing but its transform.
//   Colour: animating an inherited fill on hundreds of <use> elements costs a
//   style recalculation per cube per frame (about 10 fps when measured in
//   headless Chrome; this version measured at the full 60).
//   So the cubes are grey and the colour is done by blending: a rainbow
//   gradient slides underneath and the grey layer goes over it with
//   mix-blend-mode:hard-light (black stays black, mid grey shows the hue,
//   white stays white). Crests and troughs are lit by one sliding band
//   gradient per wave component inside the grey layer. Three sliding rects.
//   Where blend modes are missing the floor simply shows in greys.
//   Text writer: four pages on one 32 s timeline. Page 1 is already typed at
//   t = 0 (so the first frame, and the reduced-motion frame, is complete) and
//   is re-typed at the end of the loop. Typing is a background-coloured cover
//   stepping away one character at a time, the cursor riding its edge.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '../assets/14-neon-cube-field_opus_5.5.svg');
const OUT_RULE = path.resolve(here, '../assets/14-neon-cube-field_opus_5.5-rule.svg');

const W = 900;
const H = 450;
const BG = '#04040a';
const LOOP = 32;

// App palette (the app's own neon)
const CYAN = '#00cfff';
const GOLD = '#e8d44d';
const PURPLE = '#a855f7';
const PINK = '#ec4899';
const BLUE = '#38bdf8';

const CREW = 'CUBIC METRES PER MINUTE';

// ---------------------------------------------------------------- utilities
const n = (v, d = 2) => String(+(+v).toFixed(d));
const n1 = (v) => n(v, 1);
const hexRgb = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const rgbHex = (c) => `#${c.map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('')}`;
const lerpHex = (a, b, t) => { const pa = hexRgb(a), pb = hexRgb(b); return rgbHex(pa.map((v, i) => v + (pb[i] - v) * t)); };
const polyD = (p) => `M${p.map(([x, y]) => `${n1(x)} ${n1(y)}`).join('L')}Z`;
const stops = (list) => list.map(([o, c, a]) => `<stop offset="${o}" stop-color="${c}"${a === undefined ? '' : ` stop-opacity="${a}"`}/>`).join('');
const vgrad = (id, y0, y1, list) => `<linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="0" y1="${n1(y0)}" x2="0" y2="${n1(y1)}">${stops(list)}</linearGradient>`;
const mod1 = (v) => ((v % 1) + 1) % 1;
function mulberry32(seed) {
  return () => {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const defs = [];
const css = [];

// ---------------------------------------------------------------- 5x7 font
// Rows top to bottom, '#' = lit. An optional 8th row is the descender.
const FONT = {
  A: '.###.|#...#|#...#|#...#|#####|#...#|#...#', B: '####.|#...#|#...#|####.|#...#|#...#|####.',
  C: '.###.|#...#|#....|#....|#....|#...#|.###.', D: '###..|#..#.|#...#|#...#|#...#|#..#.|###..',
  E: '#####|#....|#....|####.|#....|#....|#####', F: '#####|#....|#....|####.|#....|#....|#....',
  G: '.###.|#...#|#....|#.###|#...#|#...#|.####', H: '#...#|#...#|#...#|#####|#...#|#...#|#...#',
  I: '.###.|..#..|..#..|..#..|..#..|..#..|.###.', J: '..###|...#.|...#.|...#.|...#.|#..#.|.##..',
  K: '#...#|#..#.|#.#..|##...|#.#..|#..#.|#...#', L: '#....|#....|#....|#....|#....|#....|#####',
  M: '#...#|##.##|#.#.#|#.#.#|#...#|#...#|#...#', N: '#...#|#...#|##..#|#.#.#|#..##|#...#|#...#',
  O: '.###.|#...#|#...#|#...#|#...#|#...#|.###.', P: '####.|#...#|#...#|####.|#....|#....|#....',
  Q: '.###.|#...#|#...#|#...#|#.#.#|#..#.|.##.#', R: '####.|#...#|#...#|####.|#.#..|#..#.|#...#',
  S: '.####|#....|#....|.###.|....#|....#|####.', T: '#####|..#..|..#..|..#..|..#..|..#..|..#..',
  U: '#...#|#...#|#...#|#...#|#...#|#...#|.###.', V: '#...#|#...#|#...#|#...#|#...#|.#.#.|..#..',
  W: '#...#|#...#|#...#|#.#.#|#.#.#|#.#.#|.#.#.', X: '#...#|#...#|.#.#.|..#..|.#.#.|#...#|#...#',
  Y: '#...#|#...#|#...#|.#.#.|..#..|..#..|..#..', Z: '#####|....#|...#.|..#..|.#...|#....|#####',
  a: '.....|.....|.###.|....#|.####|#...#|.####', b: '#....|#....|#.##.|##..#|#...#|#...#|####.',
  c: '.....|.....|.###.|#....|#....|#...#|.###.', d: '....#|....#|.##.#|#..##|#...#|#...#|.####',
  e: '.....|.....|.###.|#...#|#####|#....|.###.', f: '..##.|.#..#|.#...|###..|.#...|.#...|.#...',
  g: '.....|.....|.####|#...#|#...#|.####|....#|.###.', h: '#....|#....|#.##.|##..#|#...#|#...#|#...#',
  i: '..#..|.....|.##..|..#..|..#..|..#..|.###.', j: '...#.|.....|..##.|...#.|...#.|...#.|#..#.|.##..',
  k: '#....|#....|#..#.|#.#..|##...|#.#..|#..#.', l: '.##..|..#..|..#..|..#..|..#..|..#..|.###.',
  m: '.....|.....|##.#.|#.#.#|#.#.#|#.#.#|#...#', n: '.....|.....|#.##.|##..#|#...#|#...#|#...#',
  o: '.....|.....|.###.|#...#|#...#|#...#|.###.', p: '.....|.....|####.|#...#|#...#|####.|#....|#....',
  q: '.....|.....|.####|#...#|#...#|.####|....#|....#', r: '.....|.....|#.##.|##..#|#....|#....|#....',
  s: '.....|.....|.####|#....|.###.|....#|####.', t: '.#...|.#...|###..|.#...|.#...|.#..#|..##.',
  u: '.....|.....|#...#|#...#|#...#|#..##|.##.#', v: '.....|.....|#...#|#...#|#...#|.#.#.|..#..',
  w: '.....|.....|#...#|#...#|#.#.#|#.#.#|.#.#.', x: '.....|.....|#...#|.#.#.|..#..|.#.#.|#...#',
  y: '.....|.....|#...#|#...#|#...#|.####|....#|.###.', z: '.....|.....|#####|...#.|..#..|.#...|#####',
  0: '.###.|#...#|#..##|#.#.#|##..#|#...#|.###.', 1: '..#..|.##..|..#..|..#..|..#..|..#..|.###.',
  2: '.###.|#...#|....#|...#.|..#..|.#...|#####', 3: '#####|...#.|..#..|...#.|....#|#...#|.###.',
  4: '...#.|..##.|.#.#.|#..#.|#####|...#.|...#.', 5: '#####|#....|####.|....#|....#|#...#|.###.',
  6: '..##.|.#...|#....|####.|#...#|#...#|.###.', 7: '#####|....#|...#.|..#..|.#...|.#...|.#...',
  8: '.###.|#...#|#...#|.###.|#...#|#...#|.###.', 9: '.###.|#...#|#...#|.####|....#|...#.|.##..',
  '!': '..#..|..#..|..#..|..#..|..#..|.....|..#..', "'": '..#..|..#..|.#...|.....|.....|.....|.....',
  '(': '...#.|..#..|.#...|.#...|.#...|..#..|...#.', ')': '.#...|..#..|...#.|...#.|...#.|..#..|.#...',
  '*': '.....|..#..|#.#.#|.###.|#.#.#|..#..|.....', '+': '.....|..#..|..#..|#####|..#..|..#..|.....',
  ',': '.....|.....|.....|.....|.##..|..#..|.#...', '-': '.....|.....|.....|#####|.....|.....|.....',
  '.': '.....|.....|.....|.....|.....|.##..|.##..', '/': '....#|....#|...#.|..#..|.#...|#....|#....',
  ':': '.....|.##..|.##..|.....|.##..|.##..|.....', '>': '.#...|..#..|...#.|....#|...#.|..#..|.#...',
  '?': '.###.|#...#|....#|...#.|..#..|.....|..#..', '[': '.###.|.#...|.#...|.#...|.#...|.#...|.###.',
  ']': '.###.|...#.|...#.|...#.|...#.|...#.|.###.', '·': '.....|.....|.....|.##..|.##..|.....|.....',
  '$': '..#..|.####|#.#..|.###.|..#.#|####.|..#..', '=': '.....|.....|#####|.....|#####|.....|.....',
};
for (const [ch, src] of Object.entries(FONT)) {
  const rows = src.split('|');
  if (rows.some((r) => r.length !== 5) || rows.length < 7 || rows.length > 8) throw new Error(`bad glyph ${ch}`);
  FONT[ch] = rows;
}
// glyph ids: a letter is its own id, anything else is _ plus its code point
const gid = (ch) => (/[A-Za-z]/.test(ch) ? ch : `_${ch.codePointAt(0).toString(36)}`);
// Lit cells as a compact path: horizontal runs, merged down rows.
function cellsPath(rows) {
  const rects = [];
  let active = new Map();
  rows.forEach((row, y) => {
    const next = new Map();
    let x = 0;
    while (x < row.length) {
      if (row[x] !== '#') { x++; continue; }
      let x1 = x;
      while (x1 < row.length && row[x1] === '#') x1++;
      const key = `${x},${x1}`;
      const r = active.get(key);
      if (r) { r.h++; next.set(key, r); } else { const nr = { x, y, w: x1 - x, h: 1 }; rects.push(nr); next.set(key, nr); }
      x = x1;
    }
    active = next;
  });
  return rects.map((r) => `M${r.x} ${r.y}h${r.w}v${r.h}h${-r.w}z`).join('');
}
const usedGlyphs = new Set();
// Small type: 5x7 cells, one user unit per cell (scale the group), <use> per glyph.
function textUses(str, col0 = 0, cell = 6) {
  let s = '';
  [...str].forEach((ch, i) => {
    if (ch === ' ') return;
    if (!FONT[ch]) throw new Error(`no glyph for "${ch}"`);
    usedGlyphs.add(ch);
    s += `<use href="#${gid(ch)}" x="${(col0 + i) * cell}"/>`;
  });
  return s;
}
const PX = 2; // user units per font pixel for the body type
const CW = 6 * PX;

// ================================================================ background
defs.push(`<clipPath id="panel"><rect width="${W}" height="${H}" rx="12"/></clipPath>`);
const backSvg = `<rect width="${W}" height="${H}" fill="${BG}"/>`;

// ---------------------------------------------------------------- starfield
// Three layers of small stars drifting left behind the wordmark. Each layer
// is drawn twice, W apart, and slides exactly W, so it wraps unseen.
let starSvg = '';
{
  const rand = mulberry32(0x14c0be);
  const LAYERS = [{ count: 26, r: 0.7, dur: 96, o: 0.4, c: '#d9c8ff' }, { count: 18, r: 1, dur: 64, o: 0.6, c: '#bfe9ff' }, { count: 10, r: 1.3, dur: 40, o: 0.85, c: '#fff' }];
  for (const L of LAYERS) {
    let d = '';
    for (let i = 0; i < L.count; i++) {
      const x = Math.round(rand() * W), y = Math.round(31 + rand() * 86), sq = `h${L.r * 2}v${L.r * 2}h${-L.r * 2}z`;
      d += `M${x} ${y}${sq}M${x + W} ${y}${sq}`;
    }
    starSvg += `<path class="sf" d="${d}" fill="${L.c}" opacity="${L.o}" style="animation-duration:${L.dur}s"/>`;
  }
  css.push(`@keyframes sf{to{transform:translateX(-${W}px)}}.sf{animation:sf 60s linear infinite}`);
}

// ================================================================ cube field
// 2:1 dimetric floor. Lattice point (i, j) sits at screen
//   x = X0 + (i - j) * hx,   y = Y0 + (i + j) * hy
// and rows of equal depth d = i + j are drawn back to front.
const FLD = { hx: 26, hy: 13, f: 0.52, ch: 13, x0: -8, y0: 198, top: 160, rows: 21, T: 4, amp: 21, levels: 8, phases: 44, grow: 0.14 };
// One-letter class names keep the file small: a..h = amplitude level 1..8,
// A..Z then i..z = the 44 phase steps.
const LVL_CLASS = (k) => 'abcdefgh'[k - 1];
const PH_CLASS = (p) => 'ABCDEFGHIJKLMNOPQRSTUVWXYZijklmnopqrstuvwxyz'[p];
if (FLD.levels > 8 || FLD.phases > 44) throw new Error('not enough one-letter class names for that many levels or phases');
const WHEEL = ['#00cfff', '#3b82f6', '#7c5cff', PURPLE, PINK, '#ff4d6d', '#ff8a1f', GOLD, '#8de04a', '#1fe0a0'];
const HUE_PER_I = 0.03; // colour-wheel turns per lattice step along i
const HUE_AT_0 = 0.0; // colour-wheel position at lattice i = 0 when t = 0
// Greys for the hard-light layer: 0 = black, 128 = the pure hue, 255 = white.
const CUBE = { top: '#989898', left: '#6e6e6e', right: '#3d3d3d', rim: '#f4f4f4', rimFar: '#c4c4c4', floor: [[0, '#141414'], [0.6, '#0e0e0e'], [1, '#060606']] };
const LIGHT = { crest: 0.34, trough: 0.62 }; // band opacity at full wave share
const TAU = Math.PI * 2;

// Wave components: plane waves sharing the period FLD.T; k in radians per
// lattice step, a = relative amplitude, ph = phase offset.
const WAVES = [
  { ki: TAU / 10, kj: TAU / 30, a: 1.0, ph: 0 },
  { ki: -TAU / 26, kj: TAU / 8.5, a: 0.8, ph: 1.1 },
];
const WSUM = WAVES.reduce((s, w) => s + w.a, 0);
function waveAt(i, j) {
  let re = 0, im = 0;
  for (const w of WAVES) {
    const arg = -(w.ki * i + w.kj * j) + w.ph;
    re += w.a * Math.cos(arg); im += w.a * Math.sin(arg);
  }
  // up(t) = R sin(wt + P)
  return { R: Math.hypot(re, im) / WSUM, P: Math.atan2(im, re) };
}
// A floor-space plane wave is a plane wave on screen too. Its phase at screen
// point (x, y) is gx (x - x0) + gy (y - y0); return the screen-space segment
// covering one period, starting where the phase equals `at`, plus the
// horizontal distance the pattern travels per period.
function screenWave(ki, kj, at) {
  const gx = (ki - kj) / (2 * FLD.hx), gy = (ki + kj) / (2 * FLD.hy);
  const g2 = gx * gx + gy * gy;
  const x1 = FLD.x0 + (gx * at) / g2, y1 = FLD.y0 + (gy * at) / g2;
  return { x1, y1, x2: x1 + (gx * TAU) / g2, y2: y1 + (gy * TAU) / g2, px: TAU / gx };
}

const cubes = [];
let fieldSvg = '';
const cubeAt = new Map();
{
  const { hx, hy, f, ch } = FLD;
  const cx = hx * f, cy = hy * f;
  // One cube, drawn in greys. The colour comes from the layer underneath (see
  // below): mid grey shows the pure hue, darker greys shade it, lighter greys
  // push it towards white. Top face, two shaded sides, a pale rim.
  defs.push('<g id="cb">'
    + `<path d="M0 ${n1(-cy)}L${n1(cx)} 0L0 ${n1(cy)}L${n1(-cx)} 0Z" fill="${CUBE.top}"/>`
    + `<path d="M${n1(-cx)} 0L0 ${n1(cy)}V${n1(cy + ch)}L${n1(-cx)} ${ch}Z" fill="${CUBE.left}"/>`
    + `<path d="M${n1(cx)} 0L0 ${n1(cy)}V${n1(cy + ch)}L${n1(cx)} ${ch}Z" fill="${CUBE.right}"/>`
    + `<path d="M${n1(-cx)} 0L0 ${n1(-cy)}L${n1(cx)} 0" fill="none" stroke="${CUBE.rimFar}" stroke-width="1"/>`
    + `<path d="M${n1(-cx)} 0L0 ${n1(cy)}L${n1(cx)} 0M0 ${n1(cy)}V${n1(cy + ch)}" fill="none" stroke="${CUBE.rim}" stroke-width="1.2"/>`
    + '</g>');

  const usedK = new Set(), usedP = new Set();
  for (let d = 0; d < FLD.rows; d++) {
    const y = FLD.y0 + d * hy;
    fieldSvg += `<g transform="translate(0 ${y})">`;
    for (let u = -2; FLD.x0 + u * hx < W + hx; u++) {
      if (((u + d) % 2 + 2) % 2) continue;
      const x = FLD.x0 + u * hx;
      if (x < -hx) continue;
      const i = (u + d) / 2, j = (d - u) / 2;
      const { R, P } = waveAt(i, j);
      const lvl = Math.round(R * FLD.levels);
      // keyframes run trough (0%) -> crest (50%) -> trough, i.e. up = -R cos(w tau)
      const ph = Math.round(mod1((P + Math.PI / 2) / TAU) * FLD.phases) % FLD.phases;
      usedK.add(lvl); if (lvl) usedP.add(ph);
      const cube = { x, y, i, j, d, u, lvl, ph };
      cubes.push(cube);
      cubeAt.set(`${u},${d}`, cube);
      // the <g> places the cube, so the <use> can scale about its own origin
      fieldSvg += `<g transform="translate(${x})"><use href="#cb"${lvl ? ` class="${LVL_CLASS(lvl)} ${PH_CLASS(ph)}"` : ''}/></g>`;
    }
    fieldSvg += '</g>';
  }
  const ease = 'cubic-bezier(.37,0,.63,1)'; // easeInOutSine: two of these make a sine
  // (a bare type selector, so the one-class rules below outrank it; on the
  // glyph <use>s it sets a duration for no animation at all, which is nothing)
  css.push(`use{animation:${FLD.T}s ${ease} infinite}`);
  for (const k of [...usedK].sort((a, b) => a - b)) {
    if (!k) continue;
    const q = k / FLD.levels;
    const A = n1(FLD.amp * q), s0 = n(1 - FLD.grow * q, 3), s1 = n(1 + FLD.grow * q, 3);
    css.push(`@keyframes k${k}{0%,100%{transform:translateY(${A}px) scale(${s0})}50%{transform:translateY(-${A}px) scale(${s1})}}.${LVL_CLASS(k)}{animation-name:k${k}}`);
  }
  css.push([...usedP].sort((a, b) => a - b).map((p) => `.${PH_CLASS(p)}{animation-delay:${n((-p * FLD.T) / FLD.phases, 2)}s}`).join(''));

  // Colour and light without a single per-cube colour animation:
  //   1. underneath everything, a repeating rainbow gradient banded along the
  //      floor's i axis, sliding sideways once per LOOP (the hue sweep);
  //   2. on top of it the grey floor and cubes as one group with
  //      mix-blend-mode:hard-light, which turns black into black, mid grey
  //      into the hue below and white into white;
  //   3. inside that group, one soft band gradient per wave component (white
  //      on the crest line, black in the trough), sliding at the wave's own
  //      speed, so crests flare and troughs fall into shade.
  // Three sliding rects, however many cubes there are.
  const slide = (id, sw, list, dur) => {
    defs.push(`<linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="${n1(sw.x1)}" y1="${n1(sw.y1)}" x2="${n1(sw.x2)}" y2="${n1(sw.y2)}" spreadMethod="repeat">${stops(list)}</linearGradient>`);
    const P = Math.abs(sw.px), right = sw.px > 0;
    css.push(`@keyframes ${id}{to{transform:translateX(${right ? '' : '-'}${n1(P)}px)}}.${id}{animation:${id} ${dur}s linear infinite}`);
    return `<rect class="${id}" x="${n1(right ? -P : 0)}" y="${FLD.top}" width="${n1(W + P)}" height="${H - FLD.top}" fill="url(#${id})"/>`;
  };
  const rainbow = slide('rb', screenWave(TAU * HUE_PER_I, 0, -TAU * HUE_AT_0), [...WHEEL, WHEEL[0]].map((c, k) => [n(k / WHEEL.length, 2), c]), LOOP);
  const bands = WAVES.map((w, k) => {
    // crest where the component's phase is ph - pi/2 at t = 0
    const share = w.a / WSUM;
    const hi = n(LIGHT.crest * share, 3), lo = n(LIGHT.trough * share, 3);
    const list = [[0, '#fff', hi], [0.25, '#fff', 0], [0.25, '#000', 0], [0.5, '#000', lo], [0.75, '#000', 0], [0.75, '#fff', 0], [1, '#fff', hi]];
    return slide(`sh${k}`, screenWave(w.ki, w.kj, w.ph - Math.PI / 2), list, FLD.T);
  });
  css.push('.hl{mix-blend-mode:hard-light}');
  // the floor under the cubes: a dark grey, so a little of the hue glows through
  defs.push(`<radialGradient id="haze" gradientUnits="userSpaceOnUse" cx="${W / 2}" cy="330" r="560" gradientTransform="translate(0 330) scale(1 .5) translate(0 -330)">${stops(CUBE.floor)}</radialGradient>`);
  defs.push(`<clipPath id="fc"><rect y="${FLD.top}" width="${W}" height="${H - FLD.top}"/></clipPath>`);
  // distance fog: the far rows sink into the background under the type
  defs.push(vgrad('fog', FLD.top, FLD.y0 + 70, [[0, BG, 1], [0.25, BG, 0.94], [1, BG, 0]]));
  fieldSvg = `<g clip-path="url(#fc)" style="isolation:isolate">${rainbow}`
    + `<g class="hl"><rect y="${FLD.top}" width="${W}" height="${H - FLD.top}" fill="url(#haze)"/><g id="fld">${fieldSvg}</g>${bands.join('')}</g></g>`
    + `<rect y="${FLD.top - 1}" width="${W}" height="${FLD.y0 + 71 - FLD.top}" fill="url(#fog)"/>`;
}

// ================================================================ wordmark
// A segment display: the seven classic bars plus a centre post, a leg for the
// R and two arms for the Y, all thick, with chamfered ends and hairline gaps.
// Every cell also shows its unlit bars faintly, the way an LCD does.
const SEG = { w: 32, h: 64, t: 9, g: 1.1, adv: 47, space: 28, skew: -9 };
const LETTERS = {
  U: 'f e d c b', L: 'f e d', T: 'a v', R: 'a f e b g leg', A: 'a f e b c g',
  S: 'a f g c d', I: 'a v d', F: 'a f e g1', C: 'a f e d', O: 'a f e b c d', Y: 'yl yr l',
};
let logoSvg = '';
const LOGO = { y: 40 };
{
  const { w, h, t, g } = SEG;
  const xm = w / 2, ym = h / 2, r = t / 2;
  const hz = (xa, xb, y) => [[xa + g, y], [xa + g + r, y - r], [xb - g - r, y - r], [xb - g, y], [xb - g - r, y + r], [xa + g + r, y + r]];
  const vt = (x, ya, yb) => [[x, ya + g], [x + r, ya + g + r], [x + r, yb - g - r], [x, yb - g], [x - r, yb - g - r], [x - r, ya + g + r]];
  const bw = t * 1.08; // horizontal width of a slanted bar
  const S = {
    a: hz(0, w, 0), g: hz(0, w, ym), g1: hz(0, xm + 3, ym), d: hz(0, w, h),
    f: vt(0, 0, ym), e: vt(0, ym, h), b: vt(w, 0, ym), c: vt(w, ym, h),
    // centre post: starts under the top bar (T) and reaches the bottom bar (I)
    v: [[xm - r, r + g], [xm + r, r + g], [xm + r, h - g - r], [xm, h - g], [xm - r, h - g - r]],
    l: vt(xm, ym, h),
    // the R's leg, from under the middle bar to the bottom right corner
    leg: [[xm - 5, ym + r + g], [xm - 5 + bw, ym + r + g], [w + r, h + r], [w + r - bw, h + r]],
    // the Y's arms, from the top corners to the middle
    yl: [[-r, -r], [-r + bw, -r], [xm - g / 2, ym - g], [xm - g / 2 - bw, ym - g]],
    yr: [[w + r, -r], [w + r - bw, -r], [xm + g / 2, ym - g], [xm + g / 2 + bw, ym - g]],
  };
  defs.push(`<path id="gh" d="${['a', 'g', 'd', 'f', 'e', 'b', 'c'].map((k) => polyD(S[k])).join('')}"/>`);
  for (const [ch, segs] of Object.entries(LETTERS)) defs.push(`<path id="L${ch}" d="${segs.split(' ').map((s) => polyD(S[s])).join('')}"/>`);

  const words = ['ULTRA', 'SATISFACTORY'];
  const total = (words[0].length + words[1].length) * SEG.adv - (SEG.adv - w) + SEG.space;
  let x = (W - total) / 2;
  const cells = [];
  words.forEach((word, wi) => {
    for (const ch of word) { cells.push({ ch, x, wi }); x += SEG.adv; }
    x += SEG.space;
  });
  defs.push(vgrad('lu', -r, h + r, [[0, '#f2fdff'], [0.22, '#7be9ff'], [0.55, CYAN], [1, '#0a8fe0']]));
  defs.push(vgrad('ls', -r, h + r, [[0, '#ffffff'], [0.55, '#f1f8ff'], [1, '#a9cdf0']]));
  defs.push('<filter id="glow" x="-6%" y="-50%" width="112%" height="200%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="6"/></filter>');
  const ghost = cells.map((c) => `<use href="#gh" x="${n1(c.x)}"/>`).join('');
  [0, 1].forEach((wi) => defs.push(`<g id="w${wi}">${cells.filter((c) => c.wi === wi).map((c) => `<use href="#L${c.ch}" x="${n1(c.x)}"/>`).join('')}</g>`));
  const lit = (wi) => `<use href="#w${wi}"/>`;
  // skew about the wordmark's vertical middle so it stays centred
  const sk = Math.tan((SEG.skew * Math.PI) / 180);
  const tf = `matrix(1 0 ${n(sk, 4)} 1 ${n1(-sk * (LOGO.y + h / 2))} 0) translate(0 ${LOGO.y})`;
  // one tired segment: the lower right bar of the O drops out twice every 16 s
  const oCell = cells.find((c) => c.ch === 'O');
  css.push('@keyframes fz{0%,61%{opacity:0}61.2%,62%{opacity:.9}62.2%,63.4%{opacity:0}63.6%,65.6%{opacity:.9}65.8%,100%{opacity:0}}.fz{opacity:0;animation:fz 16s linear infinite}');
  const fizz = `<path class="fz" transform="translate(${n1(oCell.x)} 0)" d="${polyD(S.c)}" fill="#0b1020" stroke="#0b1020" stroke-width="1.2"/>`;
  logoSvg = `<g transform="${tf}">`
    + `<g fill="#8fb8ff" fill-opacity=".055">${ghost}</g>`
    + `<g filter="url(#glow)"><use href="#w0" fill="${CYAN}" fill-opacity=".8"/><use href="#w1" fill="#8fc4ff" fill-opacity=".55"/></g>`
    // a CRT's colour fringe: a red copy nudged left, a blue copy nudged right
    + `<g fill="#ff2e6e" fill-opacity=".6" transform="translate(-1.6 0)">${lit(0)}${lit(1)}</g><g fill="#3d5bff" fill-opacity=".7" transform="translate(1.6 0)">${lit(0)}${lit(1)}</g>`
    + `<use href="#w0" fill="url(#lu)"/><use href="#w1" fill="url(#ls)"/>${fizz}`
    + '</g>';
}

// ---------------------------------------------------------------- presents
let presentsSvg = '';
{
  const str = `${CREW}  PRESENTS`;
  const cell = 7.5; // letter-spaced
  const wpx = (str.length - 1) * cell * 1.5 + 5 * 1.5;
  const x = (W - wpx) / 2;
  presentsSvg = `<g transform="translate(${n1(x)} 15) scale(1.5)" fill="#7f8db0">${textUses(str, 0, cell)}</g>`
    + `<rect x="60" y="19.5" width="${n1(x - 60 - 16)}" height="1.5" fill="#2a3352"/><rect x="${n1(x + wpx + 16)}" y="19.5" width="${n1(W - 60 - (x + wpx + 16))}" height="1.5" fill="#2a3352"/>`;
}

// ================================================================ text writer
const TXT = { y: 125, lh: 21, cps: 42, erase: 0.3, gap: 0.25 };
const PAGES = [
  [
    [['A COMPANION APP FOR THE FACTORY GAME ', 'w'], ['SATISFACTORY', 'y']],
    [['EVERY RECIPE, BUILDING AND SPACE ELEVATOR OBJECTIVE, ', 'w'], ['ONE CLICK APART', 'c']],
  ],
  [
    [['140', 'y'], [' ITEMS · ', 'w'], ['211', 'y'], [' RECIPES (', 'w'], ['88', 'y'], [' ALTERNATE) · ', 'w'], ['477', 'y'], [' BUILDINGS', 'w']],
    [['5', 'y'], [' SPACE ELEVATOR PHASES · ', 'w'], ['3', 'y'], [' TABS · ', 'w'], ['0', 'y'], [' SPREADSHEETS REQUIRED', 'w']],
  ],
  [
    [['$ ', 'y'], ['python -m pip install -r requirements.txt', 'c']],
    [['$ ', 'y'], ['python -m streamlit run app/app.py', 'c']],
  ],
  [
    [['NO INSTALL: ', 'w'], ['lukexyz.github.io/ULTRA-SATISFACTORY', 'y']],
    [['UNOFFICIAL FAN PROJECT · PROTECTION: ', 'w'], ['NONE', 'c'], [", IT'S APACHE 2.0", 'w']],
  ],
];
let pagesSvg = '';
{
  const COL = { w: '#e9f1ff', y: GOLD, c: '#6fe6ff' };
  const NPG = PAGES.length;
  const SLOT = LOOP / NPG;
  const pc = (s) => `${n((100 * mod1(s / LOOP)), 2)}%`;
  const lens = PAGES.map((pg) => pg.map((ln) => ln.reduce((a, [t]) => a + t.length, 0)));
  const typeDur = lens.map((ls) => ls.reduce((a, l) => a + l, 0) / TXT.cps);
  // page p is fully typed at S = p * SLOT; its typing starts typeDur earlier; it
  // is erased just before the next page starts typing.
  PAGES.forEach((pg, p) => {
    const S = p * SLOT;
    const a0 = S - typeDur[p];                       // typing starts (negative for page 0: wraps)
    const next = (p + 1) % NPG;
    const e1 = (p + 1) * SLOT - typeDur[next] - TXT.gap; // erase ends
    const e0 = e1 - TXT.erase;                       // erase starts
    // group visibility
    if (p === 0) {
      const a = LOOP + a0;
      css.push(`@keyframes pg0{0%{opacity:1}${pc(e1)}{opacity:0}${pc(a)},100%{opacity:1}}`);
    } else {
      css.push(`@keyframes pg${p}{0%{opacity:0}${pc(a0)}{opacity:1}${pc(e1)},100%{opacity:0}}`);
    }
    let g = `<g class="pg pg${p}">`;
    let tt = a0;
    pg.forEach((ln, li) => {
      const len = lens[p][li];
      const X = len * CW;
      // a page whose lines all start with a prompt is set flush left, as a block
      const flush = pg.every((l) => l[0][0] === '$ ');
      const x = Math.round((W - (flush ? Math.max(...lens[p]) * CW : X)) / 2);
      const y = TXT.y + li * TXT.lh;
      let col = 0, uses = '';
      for (const [str, c] of ln) { uses += `<g fill="${COL[c]}">${textUses(str, col)}</g>`; col += str.length; }
      g += `<g transform="translate(${x} ${y}) scale(${PX})">${uses}</g>`;
      const t0 = tt, t1 = tt + len / TXT.cps; tt = t1;
      const last = li === pg.length - 1;
      const id = `v${p}${li}`;
      const typing = (ta, tb) => `${pc(ta)}{transform:translateX(0);animation-timing-function:steps(${len},end)}${pc(tb)}{transform:translateX(${X}px)}`;
      const erase = `${pc(e0)}{transform:translateX(${X}px);animation-timing-function:linear}${pc(e1)}{transform:translateX(0)}`;
      const kf = p === 0
        ? `0%{transform:translateX(${X}px)}${erase}${typing(LOOP + t0, LOOP + t1 - 1e-4)}100%{transform:translateX(${X}px)}`
        : `0%{transform:translateX(0)}${typing(t0, t1)}${erase}100%{transform:translateX(0)}`;
      // cursor: shown while its line types; the last line keeps it until the erase ends
      const cEnd = last ? e1 : t1;
      const ck = p === 0
        ? (last
          ? `0%{opacity:1}${pc(e1)}{opacity:0}${pc(LOOP + t0)},100%{opacity:1}`
          : `0%{opacity:0}${pc(LOOP + t0)}{opacity:1}${pc(LOOP + t1 - 1e-4)},100%{opacity:0}`)
        : `0%{opacity:0}${pc(t0)}{opacity:1}${pc(cEnd)},100%{opacity:0}`;
      css.push(`@keyframes ${id}{${kf}}.${id}{animation-name:${id}}@keyframes c${id}{${ck}}.c${id}{animation-name:c${id}}`);
      const shown = p === 0;
      g += `<g class="kv ${id}"${shown ? ` transform="translate(${X} 0)"` : ''}><rect x="${x - 2}" y="${y - 3}" width="${X + 8}" height="${TXT.lh}" fill="${BG}"/>`
        + `<rect class="cu c${id}" x="${x + 2}" y="${y}" width="9" height="14" fill="${CYAN}"${shown && last ? '' : ' opacity="0"'}/></g>`;
    });
    pagesSvg += `${g}</g>`;
  });
  css.push(`.pg,.kv,.cu{animation-duration:${LOOP}s;animation-timing-function:linear;animation-iteration-count:infinite}`
    + '.pg,.cu{animation-timing-function:steps(1,end)}'
    + PAGES.map((_, p) => `.pg${p}{animation-name:pg${p}${p ? ';opacity:0' : ''}}`).join(''));
}

// ================================================================ signs
// Three signs on poles, one per tab, standing on the floor and riding the wave
// with the cube under them. Each board runs along the floor's i axis (a 2:1
// skew), drawn after the field: it hangs above the cubes, so nothing on the
// floor can overlap it.
const SIGNS = [
  { label: 'OBJECTIVES', col: PURPLE, near: [178, 338] },
  { label: 'ITEMS', col: PINK, near: [462, 392] },
  { label: 'BUILDINGS', col: BLUE, near: [742, 322] },
];
let signsSvg = '';
{
  const POLE = 52, SPX = 2.5, SCW = 6 * SPX;
  for (const s of SIGNS) {
    const c = cubes.reduce((best, q) => (Math.hypot(q.x - s.near[0], q.y - s.near[1]) < Math.hypot(best.x - s.near[0], best.y - s.near[1]) ? q : best));
    const tw = s.label.length * SCW - SPX;
    const bw = tw + 22, bh = 33;
    const x = -bw / 2, y = -bh / 2;
    const A = (FLD.amp * c.lvl) / FLD.levels;
    const delay = n((-c.ph * FLD.T) / FLD.phases, 3);
    const board = `<g transform="translate(0 ${-POLE}) matrix(1 .5 0 1 0 0)">`
      + `<rect x="${x - 5}" y="${y - 5}" width="${bw + 10}" height="${bh + 10}" rx="5" fill="${BG}" fill-opacity=".5"/>`
      + `<rect x="${x - 1}" y="${y - 1}" width="${bw + 2}" height="${bh + 2}" rx="3" fill="none" stroke="${s.col}" stroke-opacity=".35" stroke-width="6"/>`
      + `<rect x="${x}" y="${y}" width="${bw}" height="${bh}" rx="2.5" fill="#080916" fill-opacity=".95" stroke="${s.col}" stroke-width="2"/>`
      + `<rect x="${x + 5}" y="${y + bh - 7.5}" width="${bw - 10}" height="3" fill="${s.col}"/>`
      + `<g transform="translate(${-tw / 2} ${y + 5.5}) scale(${SPX})" fill="#fff">${textUses(s.label)}</g>`
      + '</g>';
    signsSvg += `<g transform="translate(${c.x} ${c.y})"><g${c.lvl ? ` style="animation:s${c.lvl} ${FLD.T}s cubic-bezier(.37,0,.63,1) ${delay}s infinite"` : ''}>`
      + `<path d="M0 -6L9 -1.5L0 3L-9 -1.5Z" fill="${s.col}" stroke="#fff" stroke-opacity=".7" stroke-width=".8"/>`
      + `<rect x="-2" y="${-POLE}" width="4" height="${POLE - 1}" fill="#aab8d8"/><rect x="-2" y="${-POLE}" width="1.6" height="${POLE - 1}" fill="#fff"/>`
      + board + '</g></g>';
    if (c.lvl && !css.some((r) => r.startsWith(`@keyframes s${c.lvl}{`))) css.push(`@keyframes s${c.lvl}{0%,100%{transform:translateY(${n1(A)}px)}50%{transform:translateY(-${n1(A)}px)}}`);
  }
}

// ================================================================ screen dressing
// scanlines (a repeating 3-unit gradient, fixed on top: light over the type,
// a second coat over the floor) and a vignette
defs.push(`<linearGradient id="scan" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="3" spreadMethod="repeat">${stops([[0, '#000', 0], [0.5, '#000', 0], [0.5, '#000', 0.1], [1, '#000', 0.1]])}</linearGradient>`);
defs.push(`<radialGradient id="vig" gradientUnits="userSpaceOnUse" cx="${W / 2}" cy="${H / 2}" r="${W * 0.62}" gradientTransform="translate(0 ${H / 2}) scale(1 .62) translate(0 ${-H / 2})">${stops([[0.62, '#000', 0], [1, '#000', 0.5]])}</radialGradient>`);
const dressSvg = `<rect width="${W}" height="${H}" fill="url(#vig)"/><rect width="${W}" height="${H}" fill="url(#scan)"/><rect y="${FLD.top + 2}" width="${W}" height="${H - FLD.top - 2}" fill="url(#scan)"/>`
  + `<rect x=".75" y=".75" width="${W - 1.5}" height="${H - 1.5}" rx="11.5" fill="none" stroke="#252a44" stroke-width="1.5"/>`;

// ---------------------------------------------------------------- glyph defs
{
  let d = '';
  for (const ch of [...usedGlyphs].sort()) d += `<path id="${gid(ch)}" d="${cellsPath(FONT[ch])}"/>`;
  defs.push(d);
}

// ================================================================ assemble
const body = [backSvg, starSvg, fieldSvg, signsSvg, presentsSvg, logoSvg, pagesSvg, dressSvg];
css.push('@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}');

const desc = `A demoscene cube field: a floor of ${cubes.length} small glowing cubes in an isometric grid, coloured as one rainbow, rolling in a slow wave under scanlines. `
  + `${CREW} presents ULTRA SATISFACTORY on a segment display. A text writer types: a companion app for the factory game Satisfactory, every recipe, building and Space Elevator objective, one click apart; `
  + '140 items, 211 recipes (88 alternate), 477 buildings, 5 Space Elevator phases; python -m pip install -r requirements.txt, then python -m streamlit run app/app.py; '
  + "no install at lukexyz.github.io/ULTRA-SATISFACTORY; unofficial fan project; protection none, it's Apache 2.0. "
  + 'Three signs stand on the floor, one per tab: OBJECTIVES, ITEMS, BUILDINGS.';

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-labelledby="ti de">
<title id="ti">ULTRA-SATISFACTORY</title>
<desc id="de">${desc}</desc>
<style>${css.join('\n')}</style>
<defs>${defs.join('\n')}</defs>
<g clip-path="url(#panel)">
${body.join('\n')}
</g>
</svg>
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
// The .md brags that the banner would fit a 64k intro compo. Keep it true.
const BYTES = Buffer.byteLength(svg);
if (BYTES >= 65536) throw new Error(`banner is ${BYTES} bytes: over the 64k (65,536 byte) limit the .md brags about`);
console.log(`${path.relative(process.cwd(), OUT)}: ${BYTES} bytes (${(BYTES / 1024).toFixed(1)} KB of the 64 allowed); ${cubes.length} cubes; loop ${LOOP}s (wave ${FLD.T}s)`);
// The .md quotes these by hand (cube count, amplitude levels, phase steps, periods); keep them in step.
console.log(`field: ${cubes.length} cubes, ${FLD.levels} amplitude levels, ${FLD.phases} phase steps, wave ${FLD.T}s, hue sweep ${LOOP}s, ${WAVES.length} wave components`);

// ================================================================ the rule
// A divider for the .md: a row of translucent "glenz" octahedra, one per hue,
// turning on a rail. CSS only: an octahedron seen side-on is eight triangles
// that each keep one corner on the axis, so every face is one reference
// triangle under translateX + skewX + scaleX, and the four faces of a half
// share one @keyframes a quarter turn apart.
{
  const RW = 900, RH = 46;
  const G = { n: 19, r: 11.5, h: 15, T: 6, samples: 24, lag: 0.12 };
  const wheelAt = (q) => { const f = mod1(q) * WHEEL.length; const k = Math.floor(f); return lerpHex(WHEEL[k], WHEEL[(k + 1) % WHEEL.length], f - k); };
  let kf = '';
  for (let s = 0; s <= G.samples; s++) {
    const th = (s / G.samples) * TAU;
    const xa = G.r * Math.cos(th), xb = G.r * Math.cos(th + Math.PI / 2);
    kf += `${n((100 * s) / G.samples, 2)}%{transform:translateX(${n(xa)}px) skewX(${n((Math.atan(xa / G.h) * 180) / Math.PI)}deg) scaleX(${n(xb - xa, 3)})}`;
  }
  const rcss = [
    `@keyframes gz{${kf}}`,
    `.f{animation:gz ${G.T}s linear infinite}`,
    '@media (prefers-reduced-motion:reduce){*{animation-play-state:paused!important}}',
  ];
  const tri = `<path id="tr" d="M0 ${-G.h}L0 0L1 0Z"/>`;
  let row = '';
  const pitch = (RW - 100) / (G.n - 1);
  for (let g = 0; g < G.n; g++) {
    const hue = wheelAt(g / G.n);
    const half = (flip) => {
      let h = '';
      for (let k = 0; k < 4; k++) {
        const white = (k % 2 === 0) !== flip;
        const delay = n(-(k * G.T) / 4 - g * G.lag, 2);
        h += `<use href="#tr" class="f" style="animation-delay:${delay}s" fill="${white ? '#fff' : hue}" fill-opacity="${white ? 0.5 : 0.66}"/>`;
      }
      return flip ? `<g transform="scale(1 -1)">${h}</g>` : h;
    };
    row += `<g transform="translate(${n1(50 + g * pitch)} ${RH / 2})">`
      + `<circle r="20" fill="${hue}" fill-opacity=".05"/><circle r="15" fill="${hue}" fill-opacity=".06"/><circle r="10" fill="${hue}" fill-opacity=".07"/>`
      + `${half(false)}${half(true)}</g>`;
  }
  const rule = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${RW} ${RH}" width="${RW}" height="${RH}" role="img" aria-labelledby="t d">
<title id="t">divider</title>
<desc id="d">A row of ${G.n} small translucent octahedra, one per hue of the rainbow, turning in a slow wave on a dark strip.</desc>
<style>${rcss.join('\n')}</style>
<defs><clipPath id="p"><rect width="${RW}" height="${RH}" rx="9"/></clipPath>${tri}
<linearGradient id="scan" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="0" y2="3" spreadMethod="repeat">${stops([[0, '#000', 0], [0.5, '#000', 0], [0.5, '#000', 0.16], [1, '#000', 0.16]])}</linearGradient></defs>
<g clip-path="url(#p)">
<rect width="${RW}" height="${RH}" fill="${BG}"/>
<rect x="22" y="${RH / 2 - 0.75}" width="${RW - 44}" height="1.5" fill="#262c48"/>
${row}
<rect width="${RW}" height="${RH}" fill="url(#scan)"/>
<rect x=".75" y=".75" width="${RW - 1.5}" height="${RH - 1.5}" rx="8.25" fill="none" stroke="#252a44" stroke-width="1.5"/>
</g>
</svg>
`;
  fs.writeFileSync(OUT_RULE, rule);
  console.log(`${path.relative(process.cwd(), OUT_RULE)}: ${(rule.length / 1024).toFixed(1)} KB; ${G.n} glenz, turn ${G.T}s`);
}

// ---------------------------------------------------------------- --ascii
// The cube wave for text terminals: two staggered rows of little cubes riding
// a sine. Paste into the .md.
if (process.argv.includes('--ascii')) {
  const CUBE_ART = [' /\\ ', '|\\/|', ' \\/ '];
  const WIDE = 76, PITCH = 8, AMP = 2, ROWS = 2;
  const rowsOut = Array.from({ length: 3 + 2 * AMP + 2 * (ROWS - 1) }, () => Array(WIDE).fill(' '));
  const put = (x, y) => CUBE_ART.forEach((line, r) => [...line].forEach((ch, c) => { if (ch !== ' ' && x + c < WIDE && x + c >= 0) rowsOut[y + r][x + c] = ch; }));
  for (let row = 0; row < ROWS; row++) {
    const off = (row % 2) * (PITCH / 2);
    for (let k = 0; k * PITCH + off + 4 <= WIDE; k++) {
      const x = k * PITCH + off;
      put(x, row * 2 + AMP - Math.round(Math.sin((x / WIDE) * TAU * 2) * AMP));
    }
  }
  console.log(rowsOut.map((r) => r.join('').replace(/\s+$/, '')).join('\n'));
}
