// Amiga 4-channel tracker README banner for ULTRA-SATISFACTORY.
//
//   node examples/ultra-satisfactory/src/17-amiga-tracker_opus_5.5.mjs
//
// Regenerates ../assets/17-amiga-tracker_opus_5.5.svg. Plain Node, no deps,
// fully deterministic (no clock, no randomness). The .md beside the assets is
// hand-edited, not generated by this script.
//
// The look is the editor screen of the late-80s / early-90s Amiga sample
// trackers (the Soundtracker / NoiseTracker / ProTracker 2.3D family): an
// embossed grey panel of numeric fields with arrow buttons, a button grid, a
// logo plate, four small scopes, name strips, a status strip, and four black
// pattern windows scrolling under a fixed grey edit row with one fat VU bar
// per channel and a yellow arrow pointer. Nothing is traced: both bitmap faces
// (a 6x5 panel face and a 7x7 pattern face) and the slab logo letters are
// drawn in this file, and no real tracker's name, logo or credit line appears.
//
// The factory reading (every number comes from the app's own data):
//   - the four channels are four production machines;
//   - one row is one second, so one pattern is one minute. A minute has 60
//     seconds and a pattern has 64 rows, hence the D00 pattern break on row 59;
//   - a note is a machine finishing one craft cycle of its standard recipe, so
//     a 2 s recipe plays every 2 rows and a 60 s recipe plays once a pattern;
//   - the effect column is Cxx, "set volume", where volume means items out
//     per cycle. Notes per pattern x volume = items per minute (asserted below);
//   - the SAMPLE / PER MIN / CYCLE S / POWER MW fields and the SAMPLENAME and
//     MACHINE strips are the recipe card of whichever channel the cursor is on.
//
// Loop maths (one loop = 4 patterns x 60 rows x 0.25 s = 60 s)
//   Pattern scroll: the four patterns sit on one tall strip, STRIDE rows apart
//   (far enough that neighbours never share the window, so the window is blank
//   above row 00 and below row 63, as on the real thing). Two nested groups
//   move it: the inner one steps 60 rows in 15 s, the outer one steps one
//   STRIDE per pattern. The strip is drawn three times (blue above the edit
//   row, black on it, blue below it), each through its own clip.
//   VU bars: a fixed green-to-yellow gradient bar (red only at full height)
//   under a black cover that jumps up on a note and steps back down. One cover
//   per channel per pattern, shown only during its pattern, each looping on its
//   own recipe's cycle. The scope traces take their amplitude from the same hit
//   timeline.
//   Status line: eight lines a loop. While it reads FUSE BLOWN. AGAIN the lamp
//   on the OVERCLOCK button blinks (a 5 px lamp at 2 Hz, nothing larger).
//   Readouts: strips of pre-drawn lines stepping through a clip, steps(n).
//   Every animation starts T0 seconds into the loop (negative delay), so the
//   first frame is mid-pattern with notes on the edit row; the same frame is
//   written as the base state, which is what prefers-reduced-motion shows.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '../assets/17-amiga-tracker_opus_5.5.svg');

// ------------------------------------------------------------------ geometry
const B = 3;            // black border round the screen
const SW = 408;         // screen width in native pixels (shown at 2x: 828 px image)
const SH = 281;
const W = SW + 2 * B;
const H = SH + 2 * B;
const ROWH = 11;        // panel row height
const ADV = 7;          // panel face advance (6 px glyph + 1)
const LEFTW = 124;      // numeric field stack
const RW = 28;          // row-number window
const CW = 95;          // channel window pitch
const PY = 154;         // top of the pattern windows
const PITCH = 9;        // pattern row pitch: a 7 px face with 2 px of air, six whole rows either side of the edit row
const EDIT_Y = 214;     // glyph top of the edit row
const BAND_Y = 212;
const SPLIT = 2;        // the rows above and below stand this far off the edit row
const BAND_H = 11;
const VU_MAX = 50;

// ------------------------------------------------------------------ palette
const PANEL = '#888888';
const HI = '#bbbbbb';
const LO = '#555555';
const FIELD = '#7b7b7b';
const BLUE = '#5468ff';     // a touch lighter than the period #3344ff, for contrast
const YELLOW = '#ffdd00';
const CYAN = '#00cfff';     // the app's own neon
const GOLD = '#e8d44d';
const PURPLE = '#a855f7';
const PINK = '#ec4899';
const SKY = '#38bdf8';

// ------------------------------------------------------------------ timing
const ROW_S = 0.25;               // seconds of wall clock per row
const PAT_ROWS = 60;              // rows played per pattern (D00 on row 59)
const PAT_S = PAT_ROWS * ROW_S;   // 15 s
const NPAT = 4;
const LOOP_S = PAT_S * NPAT;      // 60 s
const STRIDE = 80;                // rows between pattern starts on the strip
const START_ROW = 30;             // first frame / still frame: pattern 0, row 30
const T0 = START_ROW * ROW_S + 0.01;

// ------------------------------------------------------------------ the song
// Standard recipes, verified against the app's data (ultra_satisfactory.data
// get_item_recipe) on 2026-09-30: machine, cycle seconds, items out per cycle,
// items per minute, machine MW.
const MACHINES = ['SMELTER', 'CONSTRUCTOR', 'ASSEMBLER', 'MANUFACTURER'];
const SAMPLES = {
  0x01: { name: 'IRON INGOT', machine: 0, cycle: 2, out: 1, perMin: 30, mw: 4 },
  0x02: { name: 'IRON PLATE', machine: 1, cycle: 6, out: 2, perMin: 20, mw: 4 },
  0x03: { name: 'REINFORCED IRON PLATE', machine: 2, cycle: 12, out: 1, perMin: 5, mw: 15 },
  0x04: { name: 'HEAVY MODULAR FRAME', machine: 3, cycle: 30, out: 1, perMin: 2, mw: 55 },
  0x05: { name: 'COPPER INGOT', machine: 0, cycle: 2, out: 1, perMin: 30, mw: 4 },
  0x06: { name: 'WIRE', machine: 1, cycle: 4, out: 2, perMin: 30, mw: 4 },
  0x07: { name: 'ROTOR', machine: 2, cycle: 15, out: 1, perMin: 4, mw: 15 },
  0x08: { name: 'MODULAR ENGINE', machine: 3, cycle: 60, out: 1, perMin: 1, mw: 55 },
  0x09: { name: 'CATERIUM INGOT', machine: 0, cycle: 4, out: 1, perMin: 15, mw: 4 },
  0x0a: { name: 'SCREW', machine: 1, cycle: 6, out: 4, perMin: 40, mw: 4 },
  0x0b: { name: 'SMART PLATING', machine: 2, cycle: 30, out: 1, perMin: 2, mw: 15 },
  0x0c: { name: 'IRON ROD', machine: 1, cycle: 4, out: 1, perMin: 15, mw: 4 },
  0x0d: { name: 'MODULAR FRAME', machine: 2, cycle: 60, out: 2, perMin: 2, mw: 15 },
};
// One entry per pattern: [sample, riff] per channel. The riffs are decoration
// (invented note data); everything else is the recipe.
const PATTERNS = [
  [[0x01, ['A-2', 'E-3', 'A-3', 'E-3']], [0x02, ['C-3', 'E-3']], [0x03, ['A-1', 'E-2']], [0x04, ['A-1']]],
  [[0x05, ['F-2', 'C-3', 'F-3', 'C-3']], [0x06, ['A-2', 'C-3', 'F-3']], [0x07, ['F-1', 'C-2']], [0x08, ['F-1']]],
  [[0x09, ['G-2', 'D-3', 'G-3', 'B-2']], [0x0a, ['D-3', 'G-3']], [0x0b, ['G-1', 'D-2']], [0x04, ['G-1']]],
  [[0x01, ['E-2', 'B-2', 'E-3', 'G#2']], [0x0c, ['E-3', 'G#3', 'B-3']], [0x0d, ['E-1']], [0x04, ['E-1']]],
];
const hex2 = (v) => v.toString(16).toUpperCase().padStart(2, '0');
for (const pat of PATTERNS) {
  pat.forEach(([smp], k) => {
    const s = SAMPLES[smp];
    if (s.machine !== k) throw new Error(`${s.name} is on the wrong channel`);
    if (PAT_ROWS % s.cycle) throw new Error(`${s.name}: cycle does not divide a minute`);
    if ((PAT_ROWS / s.cycle) * s.out !== s.perMin) throw new Error(`${s.name}: notes x volume != per minute`);
  });
}
// The readout follows the cursor: 15 rows on each channel, 16 states a loop.
const STATES = PATTERNS.flatMap((pat) => pat.map(([smp]) => smp));

// Eight status lines a loop, 7.5 s each (two per pattern). The fuse goes as the
// Modular Engine starts up, and the box fills while the Constructor is on Screws.
const STATUS = ['ALL RIGHT', 'ALL RIGHT', 'FUSE BLOWN. AGAIN', 'ALL RIGHT-ISH', 'SCREW BOX FULL', 'ALL RIGHT', 'PIPE CLIPS WALL', 'NOBODY SAW THAT'];
const FUSE_AT = STATUS.indexOf('FUSE BLOWN. AGAIN');
if (PATTERNS[2][1][0] !== 0x0a || STATUS.indexOf('SCREW BOX FULL') !== 4) throw new Error('SCREW BOX FULL must show while the Screw pattern plays');

// ------------------------------------------------------------------ helpers
const n = (v, d = 2) => String(+(+v).toFixed(d));
const code = (ch) => ch.codePointAt(0).toString(36);

// '#' cells of a bitmap -> rectangles, merging identical runs down the rows.
function bitsToRects(rows, ox = 0, oy = 0) {
  const rects = [];
  let open = new Map();
  rows.forEach((row, y) => {
    const next = new Map();
    let x = 0;
    while (x < row.length) {
      if (row[x] !== '#') { x++; continue; }
      const x0 = x;
      while (x < row.length && row[x] === '#') x++;
      const key = `${x0},${x - x0}`;
      const r = open.get(key);
      if (r) { r.h++; next.set(key, r); } else {
        const nr = { x: x0 + ox, y: y + oy, w: x - x0, h: 1 };
        rects.push(nr);
        next.set(key, nr);
      }
    }
    open = next;
  });
  return rects;
}
const rectsPath = (rects) => rects.map((r) => `M${r.x} ${r.y}h${r.w}v${r.h}h${-r.w}z`).join('');
const bitsPath = (rows, ox = 0, oy = 0) => rectsPath(bitsToRects(rows, ox, oy));

function parseFont(src, w, h) {
  const out = {};
  for (const [ch, s] of Object.entries(src)) {
    const rows = s.split('|');
    if (rows.length !== h || rows.some((r) => r.length !== w)) throw new Error(`bad glyph ${ch}`);
    out[ch] = rows;
  }
  return out;
}

// ------------------------------------------------------------------ panel face
// 6x5, all caps, wide and low: original letterforms. '{' and '}' are the up
// and down arrows on the little buttons.
const PANEL_FONT = parseFont({
  A: '.####.|#....#|######|#....#|#....#', B: '#####.|#....#|#####.|#....#|#####.',
  C: '.#####|#.....|#.....|#.....|.#####', D: '#####.|#....#|#....#|#....#|#####.',
  E: '######|#.....|####..|#.....|######', F: '######|#.....|####..|#.....|#.....',
  G: '.#####|#.....|#..###|#....#|.#####', H: '#....#|#....#|######|#....#|#....#',
  I: '#####.|..#...|..#...|..#...|#####.', J: '...###|....#.|....#.|#...#.|.###..',
  K: '#...##|#..#..|###...|#..#..|#...##', L: '#.....|#.....|#.....|#.....|######',
  M: '##..##|#.##.#|#.##.#|#....#|#....#', N: '#....#|##...#|#.##.#|#...##|#....#',
  O: '.####.|#....#|#....#|#....#|.####.', P: '#####.|#....#|#####.|#.....|#.....',
  Q: '.####.|#....#|#..#.#|#...#.|.###.#', R: '#####.|#....#|#####.|#..#..|#...##',
  S: '.#####|#.....|.####.|.....#|#####.', T: '######|..##..|..##..|..##..|..##..',
  U: '#....#|#....#|#....#|#....#|.####.', V: '#....#|#....#|.#..#.|.#..#.|..##..',
  W: '#....#|#....#|#.##.#|#.##.#|##..##', X: '#....#|.#..#.|..##..|.#..#.|#....#',
  Y: '#....#|.#..#.|..##..|..##..|..##..', Z: '######|....#.|..##..|.#....|######',
  0: '.####.|#...##|#.##.#|##...#|.####.', 1: '..##..|.###..|..##..|..##..|.####.',
  2: '#####.|.....#|.####.|#.....|######', 3: '#####.|.....#|..###.|.....#|#####.',
  4: '#...#.|#...#.|######|....#.|....#.', 5: '######|#.....|#####.|.....#|#####.',
  6: '.####.|#.....|#####.|#....#|.####.', 7: '######|....#.|...#..|..#...|..#...',
  8: '.####.|#....#|.####.|#....#|.####.', 9: '.####.|#....#|.#####|.....#|.####.',
  ':': '......|..##..|......|..##..|......', '.': '......|......|......|......|..##..',
  ',': '......|......|......|..##..|.##...', '-': '......|......|.####.|......|......',
  _: '......|......|......|......|######', '=': '......|.####.|......|.####.|......',
  '/': '.....#|....#.|..##..|.#....|#.....', '!': '..##..|..##..|..##..|......|..##..',
  '?': '.####.|#....#|...##.|......|..##..', '{': '......|..##..|.####.|######|......',
  '}': '......|######|.####.|..##..|......',
}, 6, 5);

// ------------------------------------------------------------------ pattern face
// 7x7, heavy (2 px stems): digits, the note letters, sharp and dash.
const PAT_FONT = parseFont({
  0: '.#####.|##...##|##...##|##...##|##...##|##...##|.#####.',
  1: '...##..|..###..|...##..|...##..|...##..|...##..|.######',
  2: '.#####.|##...##|.....##|..####.|.##....|##.....|#######',
  3: '.#####.|##...##|.....##|..####.|.....##|##...##|.#####.',
  4: '...###.|..####.|.##.##.|##..##.|#######|....##.|....##.',
  5: '#######|##.....|######.|.....##|.....##|##...##|.#####.',
  6: '.#####.|##.....|##.....|######.|##...##|##...##|.#####.',
  7: '#######|.....##|....##.|...##..|..##...|..##...|..##...',
  8: '.#####.|##...##|##...##|.#####.|##...##|##...##|.#####.',
  9: '.#####.|##...##|##...##|.######|.....##|.....##|.#####.',
  A: '..###..|.##.##.|##...##|##...##|#######|##...##|##...##',
  B: '######.|##...##|##...##|######.|##...##|##...##|######.',
  C: '.#####.|##...##|##.....|##.....|##.....|##...##|.#####.',
  D: '#####..|##..##.|##...##|##...##|##...##|##..##.|#####..',
  E: '#######|##.....|##.....|#####..|##.....|##.....|#######',
  F: '#######|##.....|##.....|#####..|##.....|##.....|##.....',
  G: '.#####.|##...##|##.....|##.####|##...##|##...##|.#####.',
  '#': '.##.##.|.##.##.|#######|.##.##.|#######|.##.##.|.##.##.',
  '-': '.......|.......|.......|.#####.|.......|.......|.......',
}, 7, 7);
// The enlarged row number: the same digits stretched to 9 rows.
const BIG_ROWS = [0, 1, 1, 2, 3, 4, 5, 5, 6];

// ------------------------------------------------------------------ logo face
// 13x17 slab capitals built from 3 px strokes with chamfered corners.
function logoGlyph(ch) {
  const w = ch === 'I' ? 7 : ch === '-' ? 8 : 13;
  const g = Array.from({ length: 17 }, () => Array(w).fill(false));
  const r = (x, y, rw, rh) => { for (let j = y; j < y + rh; j++) for (let i = x; i < x + rw; i++) g[j][i] = true; };
  const cut = (cx, cy, size = 2) => { // chamfer the corner at (cx, cy)
    for (let j = 0; j < size; j++) for (let i = 0; i < size - j; i++) {
      const x = cx === 0 ? i : cx - i;
      const y = cy === 0 ? j : cy - j;
      g[y][x] = false;
    }
  };
  switch (ch) {
    case 'U': r(0, 0, 3, 17); r(10, 0, 3, 17); r(0, 14, 13, 3); cut(0, 16); cut(12, 16); break;
    case 'L': r(0, 0, 3, 17); r(0, 14, 13, 3); break;
    case 'T': r(0, 0, 13, 3); r(5, 0, 3, 17); break;
    case 'R': r(0, 0, 3, 17); r(0, 0, 13, 3); r(0, 7, 13, 3); r(10, 0, 3, 10); cut(12, 0); cut(12, 9, 1);
      r(6, 10, 4, 2); r(8, 12, 4, 2); r(10, 14, 3, 3); break;
    case 'A': r(0, 0, 3, 17); r(10, 0, 3, 17); r(0, 0, 13, 3); r(0, 8, 13, 3); cut(0, 0); cut(12, 0); break;
    case 'S': r(0, 0, 13, 3); r(0, 7, 13, 3); r(0, 14, 13, 3); r(0, 0, 3, 10); r(10, 7, 3, 10);
      cut(0, 0); cut(12, 16); cut(12, 0, 1); cut(0, 16, 1); break;
    case 'I': r(2, 0, 3, 17); r(0, 0, 7, 3); r(0, 14, 7, 3); break;
    case 'F': r(0, 0, 3, 17); r(0, 0, 13, 3); r(0, 7, 10, 3); break;
    case 'C': r(0, 0, 3, 17); r(0, 0, 13, 3); r(0, 14, 13, 3); r(10, 0, 3, 6); r(10, 11, 3, 6);
      cut(0, 0); cut(0, 16); cut(12, 0, 1); cut(12, 16, 1); break;
    case 'O': r(0, 0, 3, 17); r(10, 0, 3, 17); r(0, 0, 13, 3); r(0, 14, 13, 3);
      cut(0, 0); cut(12, 0); cut(0, 16); cut(12, 16); break;
    case 'Y': r(0, 0, 3, 9); r(10, 0, 3, 9); r(0, 7, 13, 3); r(5, 7, 3, 10); cut(0, 9); cut(12, 9); break;
    case '-': r(0, 7, 8, 3); break;
    default: throw new Error(`no logo glyph ${ch}`);
  }
  return { w, rows: g.map((row) => row.map((v) => (v ? '#' : '.')).join('')) };
}

// ------------------------------------------------------------------ output buckets
const defs = [];
const css = [];
const hi = [];
const lo = [];
const fills = new Map();
const out = [];
const usedPanel = new Set();

const bevelL = (x, y, w, h) => `M${x} ${y}h${w - 1}v1h${-(w - 2)}v${h - 2}h-1z`;
const bevelR = (x, y, w, h) => `M${x + w} ${y + h}h${-(w - 1)}v-1h${w - 2}v${-(h - 2)}h1z`;
const raised = (x, y, w, h) => { hi.push(bevelL(x, y, w, h)); lo.push(bevelR(x, y, w, h)); };
const fillRect = (x, y, w, h, colour) => fills.set(colour, `${fills.get(colour) || ''}M${x} ${y}h${w}v${h}h${-w}z`);
const inset = (x, y, w, h, colour) => {
  lo.push(bevelL(x, y, w, h));
  hi.push(bevelR(x, y, w, h));
  if (colour) fillRect(x + 1, y + 1, w - 2, h - 2, colour);
};

const textW = (s) => s.length * ADV - 1;
// Embossed panel text (light with a dark drop shadow): one <use> per character.
function chars(str, prefix, y) {
  let s = '';
  [...str].forEach((ch, i) => {
    if (ch === ' ') return;
    if (!PANEL_FONT[ch]) throw new Error(`no panel glyph for "${ch}" in "${str}"`);
    usedPanel.add(ch);
    s += `<use href="#${prefix}${code(ch)}"${i ? ` x="${i * ADV}"` : ''}${y ? ` y="${y}"` : ''}/>`;
  });
  return s;
}
const emb = (str, x, y, cls = 't') => `<g class="${cls}" transform="translate(${x} ${y})">${chars(str, 'b')}</g>`;
const flat = (str, x, y, cls) => `<g class="${cls}" transform="translate(${x} ${y})">${chars(str, 'a')}</g>`;
const embR = (str, xRight, y, cls) => emb(str, xRight - textW(str), y, cls);
const embC = (str, x, w, y, cls) => emb(str, x + Math.floor((w - textW(str)) / 2), y, cls);

let clipN = 0;
function clip(x, y, w, h) {
  const id = `k${clipN++}`;
  defs.push(`<clipPath id="${id}"><rect x="${x}" y="${y}" width="${w}" height="${h}"/></clipPath>`);
  return id;
}
// A readout: lines stacked ROWH apart, stepping up through a clip.
function readout(lines, x, y, cls, anim, clipW) {
  const id = clip(x - 1, y - 2, clipW + 2, 9);
  const body = lines.map((line, i) => (typeof line === 'string' ? chars(line, 'b', i * ROWH) : line(i * ROWH))).join('');
  return `<g clip-path="url(#${id})"><g transform="translate(${x} ${y})"><g class="${anim}"><g class="${cls}">${body}</g></g></g></g>`;
}
const anim = (name, dur, timing) => `animation:${name} ${n(dur)}s ${timing} ${n(-T0)}s infinite`;

const arrowButton = (x, y, up) => { raised(x, y, 11, ROWH); out.push(emb(up ? '{' : '}', x + 2, y + 3)); };
function led(x, y, colour, cls) {
  return `<path d="M${x - 1} ${y - 1}h7v7h-7z" fill="#2b2b2b"/><path${cls ? ` class="${cls}"` : ''} d="M${x} ${y}h5v5h-5z" fill="${colour}"/>`
    + (colour === UNLIT ? '' : `<path d="M${x} ${y}h2v1h-1v1h-1z" fill="#fff" fill-opacity=".55"/>`);
}

// ================================================================== the panel
// ---- numeric field stack (top left)
const stack = [
  ['POS', null], ['PATTERN', null], ['LENGTH', '0004'], ['ITEMS', '0140'], ['RECIPES', '0211'],
  ['BUILDINGS', '0477'], ['SAMPLE', null], ['PER MIN', null], ['CYCLE S', null], ['POWER MW', null],
];
const FX = 71; // x of the first digit
stack.forEach(([label, value], i) => {
  const y = i * ROWH;
  raised(0, y, 102, ROWH);
  inset(68, y + 1, 33, 9, FIELD);
  out.push(embR(label, 65, y + 3));
  if (value) out.push(emb(value, FX, y + 3, 'v'));
  arrowButton(102, y, true);
  arrowButton(113, y, false);
});
const pos4 = [0, 1, 2, 3].map((p) => `000${p}`);
const pad4 = (v) => String(v).padStart(4, '0');
out.push(readout(pos4, FX, 3, 'v', 'p4', 27));
out.push(readout(pos4, FX, ROWH + 3, 'v', 'p4', 27));
out.push(readout(STATES.map((s) => `00${hex2(s)}`), FX, 6 * ROWH + 3, 'v', 's16', 27));
out.push(readout(STATES.map((s) => pad4(SAMPLES[s].perMin)), FX, 7 * ROWH + 3, 'v', 's16', 27));
out.push(readout(STATES.map((s) => pad4(SAMPLES[s].cycle)), FX, 8 * ROWH + 3, 'v', 's16', 27));
// the power draw depends only on the machine, so four states cover every pattern
const MW = MACHINES.map((_, k) => SAMPLES[PATTERNS[0][k][0]].mw);
for (const pat of PATTERNS) pat.forEach(([smp], k) => { if (SAMPLES[smp].mw !== MW[k]) throw new Error('power differs between patterns'); });
out.push(readout(MW.map(pad4), FX, 9 * ROWH + 3, 'v', 'c4', 27));

// ---- button grid (top right): the third row is the app's three tabs
const colX = [LEFTW, LEFTW + 95, LEFTW + 189];
const colW = [95, 94, 95];
const UNLIT = '#505050';
const buttons = [
  [['PLAY', '#3fe06c', 'bl'], ['STOP', UNLIT], ['EDIT', UNLIT]],
  [['PATTERN', UNLIT], ['OVERCLOCK', '#ff3b30'], ['SPAGHETTI', '#ffb020']],
  [['OBJECTIVES', PURPLE], ['ITEMS', PINK], ['BUILDINGS', SKY]],
];
buttons.forEach((row, j) => row.forEach(([label, colour, cls], i) => {
  const x = colX[i];
  const y = j * ROWH;
  raised(x, y, colW[i], ROWH);
  if (colour) out.push(led(x + 6, y + 3, colour, cls));
  // while the status line says the fuse has gone, the OVERCLOCK lamp blinks (a 5 px lamp, 2 Hz)
  if (label === 'OVERCLOCK') out.push(`<g class="fz"><path class="bz" d="M${x + 6} ${y + 3}h5v5h-5z" fill="${UNLIT}"/></g>`);
  out.push(emb(label, x + 15, y + 3));
}));

// ---- logo plate
const LOGO_Y = 3 * ROWH;        // 33
const LOGO_H = 47;
const RIGHTW = SW - LEFTW;      // 284
raised(LEFTW, LOGO_Y, RIGHTW, LOGO_H);
inset(LEFTW + 3, LOGO_Y + 3, RIGHTW - 6, LOGO_H - 6, '#000000');
{
  const title = 'ULTRA-SATISFACTORY';
  const glyphs = [...title].map(logoGlyph);
  const total = glyphs.reduce((s, g) => s + g.w, 0) + (glyphs.length - 1) * 2;
  let x = LEFTW + 3 + Math.round((RIGHTW - 6 - total) / 2);
  const ty = LOGO_Y + 7;
  const parts = { u: '', s: '', h: '' };
  [...title].forEach((ch, i) => {
    const key = ch === '-' ? 'h' : i < 5 ? 'u' : 's';
    parts[key] += bitsPath(glyphs[i].rows, x, ty);
    x += glyphs[i].w + 2;
  });
  const bands = (id, cols) => `<linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="0" y1="${ty}" x2="0" y2="${ty + 17}">`
    + [[0, 3], [3, 8], [8, 13], [13, 17]].map(([a, b], i) => `<stop offset="${n(a / 17, 3)}" stop-color="${cols[i]}"/><stop offset="${n(b / 17, 3)}" stop-color="${cols[i]}"/>`).join('')
    + '</linearGradient>';
  defs.push(bands('gu', ['#c4f6ff', '#52ddff', CYAN, '#0096c8']));
  defs.push(bands('gs', ['#ffffff', '#f2f2f2', '#d2d2d2', '#9c9c9c']));
  out.push(`<path d="${parts.u}" transform="translate(2 2)" fill="#003a52"/><path d="${parts.u}" transform="translate(1 1)" fill="#006b91"/><path d="${parts.u}" fill="url(#gu)"/>`);
  out.push(`<path d="${parts.s}" transform="translate(2 2)" fill="#3a3a3a"/><path d="${parts.s}" transform="translate(1 1)" fill="#6a6a6a"/><path d="${parts.s}" fill="url(#gs)"/>`);
  out.push(`<path d="${parts.h}" transform="translate(1 1)" fill="#6d6114"/><path d="${parts.h}" fill="${GOLD}"/>`);
  const l1 = 'COMPANION APP FOR SATISFACTORY';
  const l2 = 'EVERY RECIPE, ONE CLICK APART';
  const cx = (s) => LEFTW + 3 + Math.floor((RIGHTW - 6 - textW(s)) / 2);
  out.push(flat(l1, cx(l1), ty + 21, 'g1'));
  out.push(flat(l2, cx(l2), ty + 29, 'g2'));
}

// ---- four scopes
const SC_Y = LOGO_Y + LOGO_H;   // 80
const SC_H = 110 - SC_Y;        // 30
raised(LEFTW, SC_Y, RIGHTW, SC_H);
const SCOPE_W = 66;
const scopeX = (k) => LEFTW + 4 + k * (SCOPE_W + 4);
const SC_CY = SC_Y + 15;
for (let k = 0; k < 4; k++) inset(scopeX(k), SC_Y + 3, SCOPE_W, SC_H - 6, '#000000');

// ---- name strips
{
  const y = 110;
  raised(0, y, 230, ROWH);
  out.push(embR('SONGNAME:', 80, y + 3));
  inset(83, y + 1, 145, 9, FIELD);
  out.push(emb('ULTRA-SATISFACTORY__', 86, y + 3, 'v'));
  raised(230, y, SW - 230, ROWH);
  out.push(embC('UNOFFICIAL FAN PROJECT', 230, SW - 230, y + 3));
}
const bgRun = (len, y) => `<path class="f" d="M-1 ${y - 1}h${len * ADV + 1}v8h${-(len * ADV + 1)}z"/>`;
{
  const y = 121;
  raised(0, y, SW, ROWH);
  out.push(embR('SAMPLENAME:', 80, y + 3));
  inset(83, y + 1, 159, 9, FIELD);
  out.push(emb('_'.repeat(22), 86, y + 3, 'v'));
  out.push(readout(STATES.map((s) => (yy) => bgRun(SAMPLES[s].name.length, yy) + chars(SAMPLES[s].name, 'b', yy)), 86, y + 3, 'v', 's16', 154));
  out.push(emb('MACHINE:', 248, y + 3));
  inset(305, y + 1, 101, 9, FIELD);
  out.push(emb('_'.repeat(14), 307, y + 3, 'v'));
  out.push(readout(MACHINES.map((m) => (yy) => bgRun(m.length, yy) + chars(m, 'b', yy)), 307, y + 3, 'v', 'c4', 98));
}

// ---- status strip
{
  const y = 132;
  raised(0, y, RW, ROWH);
  inset(3, y + 1, RW - 6, 9, FIELD);
  out.push(readout(['00', '01', '02', '03'], 8, y + 3, 'v', 'p4', 13));
  raised(RW, y, 64, ROWH);
  out.push(emb('TEMPO', RW + 4, y + 3));
  out.push(emb('125', RW + 42, y + 3, 'v'));
  arrowButton(RW + 64, y, true);
  arrowButton(RW + 75, y, false);
  raised(114, y, 180, ROWH);
  out.push(emb('STATUS:', 118, y + 3));
  out.push(readout(STATUS.map((line) => (line === 'ALL RIGHT' ? line : (yy) => `<g class="g2">${chars(line, 'b', yy)}</g>`)), 171, y + 3, 'v', 's8', 120));
  raised(294, y, SW - 294, ROWH);
  out.push(embC('1 ROW = 1 SEC', 294, SW - 294, y + 3));
}

// ---- channel label strip
const chX = (k) => RW + k * CW;
{
  const y = 143;
  raised(0, y, RW, ROWH);
  out.push(embC('ROW', 0, RW, y + 3));
  MACHINES.forEach((m, k) => {
    raised(chX(k), y, CW, ROWH);
    out.push(embC(m, chX(k), CW, y + 3));
  });
}

// ---- pattern windows
inset(0, PY, RW, SH - PY, '#000000');
for (let k = 0; k < 4; k++) inset(chX(k), PY, CW, SH - PY, '#000000');

// ================================================================== the pattern
// A cell is eight characters: note (3), sample (2), effect (3), in three groups.
const CELL_X = [0, 8, 16, 27, 35, 46, 54, 62];
const cellIds = new Map();
function cellId(text8) {
  if (!cellIds.has(text8)) {
    const id = `c${cellIds.size}`;
    const d = [...text8].map((ch, i) => { return bitsPath(PAT_FONT[ch], CELL_X[i], 0); }).join('');
    defs.push(`<path id="${id}" d="${d}"${text8 === EMPTY ? ' fill-opacity=".45"' : ''}/>`);
    cellIds.set(text8, id);
  }
  return cellIds.get(text8);
}
const EMPTY = '---00000';
const emptyRuns = new Map();
function emptyRun(count) {
  if (count === 1) return cellId(EMPTY);
  if (!emptyRuns.has(count)) {
    const id = `e${count}`;
    const one = cellId(EMPTY);
    defs.push(`<g id="${id}">${Array.from({ length: count }, (_, i) => `<use href="#${one}"${i ? ` y="${i * PITCH}"` : ''}/>`).join('')}</g>`);
    emptyRuns.set(count, id);
  }
  return emptyRuns.get(count);
}
function channelCells(p, k) {
  const [smp, riff] = PATTERNS[p][k];
  const s = SAMPLES[smp];
  const cells = [];
  for (let r = 0; r < 64; r++) {
    if (r < PAT_ROWS && r % s.cycle === 0) cells.push(`${riff[(r / s.cycle) % riff.length]}${hex2(smp)}C${hex2(s.out)}`);
    else if (r === PAT_ROWS - 1 && k === 3) cells.push('---00D00'); // pattern break: a minute is 60 rows
    else cells.push(EMPTY);
  }
  return cells;
}
{
  let strip = '';
  for (let p = 0; p < NPAT; p++) {
    for (let k = 0; k < 4; k++) {
      const cells = channelCells(p, k);
      let g = '';
      let r = 0;
      while (r < 64) {
        if (cells[r] === EMPTY) {
          let e = r;
          while (e < 64 && cells[e] === EMPTY) e++;
          g += `<use href="#${emptyRun(e - r)}"${r ? ` y="${r * PITCH}"` : ''}/>`;
          r = e;
        } else {
          g += `<use href="#${cellId(cells[r])}"${r ? ` y="${r * PITCH}"` : ''}/>`;
          r++;
        }
      }
      strip += `<g transform="translate(${chX(k) + 6} ${EDIT_Y + p * STRIDE * PITCH})">${g}</g>`;
    }
  }
  defs.push(`<g id="strip">${strip}</g>`);
  // row numbers 00-63 (the same for every pattern, so only the inner step moves them)
  let rows = '';
  for (let r = 0; r < 64; r++) {
    const t = String(r).padStart(2, '0');
    rows += `<use href="#h${t[0]}" y="${r * PITCH}"/><use href="#h${t[1]}" x="8" y="${r * PITCH}"/>`;
  }
  defs.push(`<g id="rows" transform="translate(7 ${EDIT_Y})">${rows}</g>`);
  for (let d = 0; d < 10; d++) {
    defs.push(`<path id="h${d}" d="${bitsPath(PAT_FONT[d])}"/>`);
    defs.push(`<path id="d${d}" d="${bitsPath(BIG_ROWS.map((i) => PAT_FONT[d][i]))}"/>`);
  }
}

// ---- hit timelines: VU covers and scope amplitudes
// One period holds `vols.length` hits, `cycle` rows apart. After a hit the bar
// falls at `rate` px/s in 2 px steps.
function hitTrack(cycle, vols, rate) {
  const gap = cycle * ROW_S;
  const period = gap * vols.length;
  const frames = [];
  vols.forEach((v, i) => {
    const t = i * gap;
    const h0 = Math.round(v * VU_MAX);
    const fall = Math.min(gap, h0 / rate);
    const end = Math.max(0, Math.round(h0 - rate * gap));
    frames.push({ t, h: h0, tf: `steps(${Math.max(1, Math.round((h0 - end) / 2))})` });
    if (fall < gap - 1e-6) frames.push({ t: t + fall, h: 0, tf: 'step-end' });
    else if (i < vols.length - 1) frames.push({ t: t + gap - period * 1e-4, h: end, tf: 'step-end' });
    if (i === vols.length - 1) frames.push({ t: period, h: end });
  });
  const at = (time) => {
    const tt = ((time % period) + period) % period;
    const i = Math.min(vols.length - 1, Math.floor(tt / gap + 1e-9));
    return Math.max(0, Math.round((Math.round(vols[i] * VU_MAX) - rate * (tt - i * gap)) / 2) * 2);
  };
  return { period, frames, at };
}
const trackIds = new Map();
function trackClasses(cycle, vols, rate) {
  const key = `${cycle}/${vols.join(',')}/${rate}`;
  if (!trackIds.has(key)) {
    const id = trackIds.size;
    const tr = hitTrack(cycle, vols, rate);
    const kf = (fn) => tr.frames.map((f) => `${n((f.t / tr.period) * 100, 3)}%{transform:${fn(f.h)}${f.tf ? `;animation-timing-function:${f.tf}` : ''}}`).join('');
    const vu = (h) => `translateY(${-h}px)`;
    const amp = (h) => `scaleY(${n(Math.max(0.07, h / VU_MAX), 3)})`;
    css.push(`@keyframes u${id}{${kf(vu)}}.u${id}{transform:${vu(tr.at(T0))};${anim(`u${id}`, tr.period, 'linear')}}`);
    css.push(`@keyframes w${id}{${kf(amp)}}.w${id}{transform:${amp(tr.at(T0))};${anim(`w${id}`, tr.period, 'linear')}}`);
    trackIds.set(key, id);
  }
  return trackIds.get(key);
}
const VOLS = [[0.5, 0.66, 0.56], [0.62, 0.8, 0.7], [0.9], [1]];
const RATES = [36, 32, 20, 14];   // px per second: the big machines ring longer
function trackFor(p, k) {
  const cycle = SAMPLES[PATTERNS[p][k][0]].cycle;
  let vols = VOLS[k];
  // use as many accents as still loop cleanly inside one pattern
  let len = Math.min(2, vols.length);
  if (PAT_ROWS % (cycle * len)) len = Math.min(3, vols.length);
  if (PAT_ROWS % (cycle * len)) len = 1;
  vols = vols.slice(0, len);
  return trackClasses(cycle, vols, RATES[k]);
}

// ---- scopes: a periodic trace, one period wider than its window
const WAVES = [
  { period: 10, dur: 0.5, f: (x) => 9 * Math.sin((2 * Math.PI * x) / 10) },
  { period: 16, dur: 0.8, f: (x) => ((x % 16) < 8 ? -8 : 8) },
  { period: 22, dur: 1.1, f: (x) => 9 * (2 * ((x % 22) / 22) - 1) },
  { period: 33, dur: 1.65, f: (x) => 6 * Math.sin((2 * Math.PI * x) / 33) + 3.5 * Math.sin((6 * Math.PI * x) / 33 + 0.6) },
];
WAVES.forEach((wv, k) => {
  const pts = [];
  for (let x = 0; x <= SCOPE_W + wv.period; x++) {
    if (k === 1 && x % 8 === 0 && x) pts.push(`${x},${n(wv.f(x - 1), 1)}`); // square edges stay vertical
    pts.push(`${x},${n(wv.f(x), 1)}`);
  }
  defs.push(`<polyline id="wv${k}" points="${pts.join(' ')}" fill="none" stroke="${YELLOW}" stroke-width="1.5" vector-effect="non-scaling-stroke"/>`);
  css.push(`@keyframes x${k}{from{transform:translateX(0)}to{transform:translateX(${-wv.period}px)}}.x${k}{animation:x${k} ${wv.dur}s steps(${wv.period}) infinite}`);
  const id = clip(scopeX(k) + 11, SC_Y + 4, SCOPE_W - 12, SC_H - 8); // the first 10 px are the number's own column
  let g = '';
  for (let p = 0; p < NPAT; p++) {
    g += `<g class="v${p}"><g transform="translate(${scopeX(k) + 1} ${SC_CY})"><g class="w${trackFor(p, k)}"><g class="x${k}"><use href="#wv${k}"/></g></g></g></g>`;
  }
  out.push(`<g clip-path="url(#${id})">${g}</g>`);
  out.push(flat(String(k + 1), scopeX(k) + 3, SC_CY - 2, 'g0'));
});

// ---- pattern area
{
  const top = clip(0, PY + 3, SW, BAND_Y - PY - 3);                       // six whole rows above
  const bot = clip(0, BAND_Y + BAND_H, SW, SH - 3 - BAND_Y - BAND_H);     // six whole rows below
  const band = clip(0, EDIT_Y - 1, SW, PITCH + 1); // just the edit row: its neighbours stay out
  const moving = (what, cls) => `<g class="ro"><g class="ri"><use href="#${what}"${cls ? ` class="${cls}"` : ''}/></g></g>`;
  const movingRows = '<g class="ri"><use href="#rows"/></g>';
  out.push(`<g class="blu" clip-path="url(#${top})"><g transform="translate(0 ${-SPLIT})">${moving('strip')}${movingRows}</g></g>`);
  out.push(`<g class="blu" clip-path="url(#${bot})"><g transform="translate(0 ${SPLIT})">${moving('strip')}${movingRows}</g></g>`);

  // VU bars: they stand on the edit row, in the free column right of each cell
  defs.push(`<linearGradient id="vg" gradientUnits="userSpaceOnUse" x1="0" y1="${BAND_Y}" x2="0" y2="${BAND_Y - VU_MAX}">`
    + '<stop offset="0" stop-color="#00b000"/><stop offset=".45" stop-color="#7fd800"/><stop offset=".72" stop-color="#ffdd00"/><stop offset=".9" stop-color="#ff9000"/><stop offset="1" stop-color="#ff3000"/></linearGradient>');
  let vu = '';
  for (let k = 0; k < 4; k++) {
    const x = chX(k) + 80;
    const y = BAND_Y - VU_MAX;
    vu += `<path d="M${x} ${y}h10v${VU_MAX}h-10z" fill="url(#vg)"/><path d="M${x} ${y}h2v${VU_MAX}h-2z" fill="#fff" fill-opacity=".3"/><path d="M${x + 8} ${y}h2v${VU_MAX}h-2z" fill-opacity=".28"/>`;
    for (let p = 0; p < NPAT; p++) vu += `<g class="v${p}"><path class="u${trackFor(p, k)}" d="M${x} ${y}h10v${VU_MAX}h-10z"/></g>`;
  }
  out.push(`<g clip-path="url(#${top})">${vu}</g>`);

  // the edit row
  out.push(`<path d="M0 ${BAND_Y}h${SW}v${BAND_H}h${-SW}z" fill="#b6b6b6"/><path d="M0 ${BAND_Y}h${SW}v1h${-SW}z" fill="#e6e6e6"/><path d="M0 ${BAND_Y + BAND_H - 1}h${SW}v1h${-SW}z" fill="#5a5a5a"/>`);
  out.push(`<g clip-path="url(#${band})">${moving('strip')}</g>`);
  // cursor: one red outline on the note of the channel the readout is showing
  out.push(`<g class="cx"><path d="M${chX(0) + 4} ${BAND_Y}h27v${BAND_H}h-27zM${chX(0) + 5} ${BAND_Y + 1}v${BAND_H - 2}h25v${-(BAND_H - 2)}z" fill="#ff2222" fill-rule="evenodd"/></g>`);
  // enlarged row number in its own bevelled box
  const bx = 2;
  const by = BAND_Y - 1;
  const bh = BAND_H + 2;
  out.push(`<path d="M${bx} ${by}h24v${bh}h-24z" fill="#9a9a9a"/><path d="${bevelL(bx, by, 24, bh)}" fill="#e6e6e6"/><path d="${bevelR(bx, by, 24, bh)}" fill="#444444"/>`);
  let big = '';
  for (let r = 0; r < PAT_ROWS; r++) {
    const t = String(r).padStart(2, '0');
    big += `<use href="#d${t[0]}" y="${r * 16}"/><use href="#d${t[1]}" x="8" y="${r * 16}"/>`;
  }
  out.push(`<g clip-path="url(#${clip(bx + 1, by + 1, 22, bh - 2)})"><g transform="translate(${bx + 5} ${BAND_Y + 1})"><g class="rb">${big}</g></g></g>`);
}

// ---- the pointer, idling over OVERCLOCK
{
  const shape = [
    '#..........', '##.........', '###........', '####.......', '#####......', '######.....', '#######....',
    '########...', '#########..', '##########.', '######.....', '###.###....', '##..###....', '#....###...', '.....###...', '......##...',
  ];
  const at = (x, y) => shape[y]?.[x] === '#';
  const outline = shape.map((row, y) => [...row, '.'].map((_, x) => {
    for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) if (at(x + dx, y + dy)) return '#';
    return '.';
  }).join(''));
  const shade = shape.map((row, y) => [...row].map((c, x) => (c === '#' && (!at(x + 1, y) || !at(x, y + 1)) ? '#' : '.')).join(''));
  const px = colX[1] + 82;
  const py = ROWH + 3;
  out.push(`<g transform="translate(${px} ${py})"><path d="${bitsPath(['.'.repeat(12), ...outline], -1, -2)}${bitsPath(outline, 0, 0)}" fill="#1c1600"/><path d="${bitsPath(shape)}" fill="${YELLOW}"/><path d="${bitsPath(shade)}" fill="#b89600"/></g>`);
}

// ================================================================== stylesheet
const stepAnim = (name, prop, total, steps, dur, still) => {
  css.push(`@keyframes ${name}{from{transform:${prop}(0)}to{transform:${prop}(${total}px)}}.${name}{transform:${prop}(${still}px);${anim(name, dur, `steps(${steps})`)}}`);
};
const state16 = Math.floor(START_ROW / 15);              // which readout state the still frame shows
stepAnim('ri', 'translateY', -PAT_ROWS * PITCH, PAT_ROWS, PAT_S, -START_ROW * PITCH);
stepAnim('ro', 'translateY', -NPAT * STRIDE * PITCH, NPAT, LOOP_S, 0);
stepAnim('rb', 'translateY', -PAT_ROWS * 16, PAT_ROWS, PAT_S, -START_ROW * 16);
stepAnim('s16', 'translateY', -16 * ROWH, 16, LOOP_S, -state16 * ROWH);
stepAnim('s8', 'translateY', -8 * ROWH, 8, LOOP_S, -Math.floor(T0 / (LOOP_S / 8)) * ROWH);
stepAnim('c4', 'translateY', -4 * ROWH, 4, PAT_S, -state16 * ROWH);
stepAnim('p4', 'translateY', -4 * ROWH, 4, LOOP_S, 0);
stepAnim('cx', 'translateX', 4 * CW, 4, PAT_S, state16 * CW);
for (let p = 0; p < NPAT; p++) {
  const a = n((p / NPAT) * 100);
  const b = n(((p + 1) / NPAT) * 100);
  const frames = p === 0 ? `0%{visibility:visible}${b}%{visibility:hidden}100%{visibility:hidden}`
    : `0%{visibility:hidden}${a}%{visibility:visible}${p === NPAT - 1 ? '' : `${b}%{visibility:hidden}`}100%{visibility:${p === NPAT - 1 ? 'visible' : 'hidden'}}`;
  css.push(`@keyframes v${p}{${frames}}.v${p}{visibility:${p ? 'hidden' : 'visible'};${anim(`v${p}`, LOOP_S, 'step-end')}}`);
}
css.push(`@keyframes bl{0%{opacity:.3}50%{opacity:1}}.bl{${anim('bl', 1, 'step-end')}}`);
{
  const a = n((FUSE_AT / STATUS.length) * 100, 3);
  const b = n(((FUSE_AT + 1) / STATUS.length) * 100, 3);
  css.push(`@keyframes fz{0%{visibility:hidden}${a}%{visibility:visible}${b}%{visibility:hidden}100%{visibility:hidden}}.fz{visibility:hidden;${anim('fz', LOOP_S, 'step-end')}}`);
  css.push(`@keyframes bz{0%{opacity:1}50%{opacity:0}}.bz{${anim('bz', 0.5, 'step-end')}}`);
}
css.unshift(
  `.t{fill:#dcdcdc}.v{fill:#ffffff}.sh{fill:#454545}.f{fill:${FIELD}}`,
  `.g0{fill:#9c9c9c}.g1{fill:#c8c8c8}.g2{fill:${YELLOW}}`,
  `.blu{fill:${BLUE}}`,
);
css.push('@media (prefers-reduced-motion:reduce){*{animation:none!important}}');

// panel glyph defs (only the characters used)
for (const ch of [...usedPanel].sort()) {
  const c = code(ch);
  defs.push(`<path id="a${c}" d="${bitsPath(PANEL_FONT[ch])}"/>`);
  defs.push(`<g id="b${c}"><use href="#a${c}" x="1" y="1" class="sh"/><use href="#a${c}"/></g>`);
}

// ================================================================== assemble
const xml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const TITLE = 'ULTRA-SATISFACTORY as a four-channel tracker module';
const DESC = 'The editor screen of an Amiga-style music tracker, playing a song called ULTRA-SATISFACTORY. '
  + 'A grey embossed panel holds a stack of numeric fields with arrow buttons (POS, PATTERN, LENGTH 0004, ITEMS 0140, RECIPES 0211, BUILDINGS 0477, SAMPLE, PER MIN, CYCLE S, POWER MW), '
  + 'a button grid (PLAY, STOP, EDIT, PATTERN, OVERCLOCK, SPAGHETTI, and the three tabs OBJECTIVES, ITEMS, BUILDINGS with purple, pink and blue lamps), '
  + 'a logo plate reading ULTRA-SATISFACTORY, companion app for Satisfactory, every recipe, one click apart, and four small scopes with yellow traces. '
  + 'Below: SONGNAME ULTRA-SATISFACTORY, unofficial fan project; SAMPLENAME and MACHINE, which step through real recipes (for example Reinforced Iron Plate, Assembler, 5 per minute, 12 second cycle, 15 MW); '
  + 'and a status strip: tempo 125, 1 row = 1 sec, and a STATUS line that reads ALL RIGHT, then FUSE BLOWN. AGAIN (the OVERCLOCK lamp blinks), ALL RIGHT-ISH, SCREW BOX FULL, PIPE CLIPS WALL and NOBODY SAW THAT. '
  + 'Four black pattern windows labelled SMELTER, CONSTRUCTOR, ASSEMBLER and MANUFACTURER scroll blue note data under a fixed grey edit row. '
  + 'Each note is a machine finishing a craft cycle, so a 2 second recipe plays every 2 rows and one pattern is one minute of factory. A fat green-to-yellow VU bar per channel jumps on every note, and a yellow arrow pointer idles over the OVERCLOCK button.';

const fillPaths = [...fills].map(([colour, d]) => `<path d="${d}" fill="${colour}"/>`).join('');
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W * 2}" height="${H * 2}" role="img" aria-labelledby="ttl dsc">
<title id="ttl">${xml(TITLE)}</title>
<desc id="dsc">${xml(DESC)}</desc>
<style>
${css.join('\n')}
</style>
<defs>
${defs.join('\n')}
</defs>
<rect width="${W}" height="${H}" rx="3" fill="#000"/>
<g transform="translate(${B} ${B})">
<path d="M0 0h${SW}v${SH}h${-SW}z" fill="${PANEL}"/>
${fillPaths}
<path d="${hi.join('')}" fill="${HI}"/>
<path d="${lo.join('')}" fill="${LO}"/>
${out.join('\n')}
</g>
</svg>
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, svg);
console.log(`wrote ${path.relative(process.cwd(), OUT)}  ${(svg.length / 1024).toFixed(1)} KB  (${cellIds.size} cells, ${trackIds.size} hit tracks, loop ${LOOP_S}s)`);
