// Stitches the forty-two ULTRA-SATISFACTORY header examples into examples/ultra-satisfactory/README.md
// (GitHub shows it when you open the folder).
//   node examples/ultra-satisfactory/src/build-gallery.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.resolve(HERE, '..');
const OPTIONS = [
  ['01-nfo-release_opus_5.5', 'Scene Release NFO', 'Pure text: an 80-column .NFO with a block-character logo and hex-cog emblem, RELEASE INFO, PAYLOAD and INSTALL NOTES, and a three-tab flow diagram. Phase list, factory skyline, credits and greetz are collapsed. No images, works everywhere.'],
  ['02-amiga-cracktro_opus_5.5', 'Amiga Cracktro', 'Animated SVG: a chrome logo over copper bars and a starfield, above a pixel production line (Smelter, Constructor, Assembler, Space Elevator) and a sine scroller. Below it, a ProTracker pattern where the channels are machines and the notes are real per-minute recipe rates.'],
  ['03-keygen-dialog_opus_5.5', 'Keygen Dialog', 'Animated SVG: a skinned mid-2000s keygen window that generates recipes, not keys. It types an item, scrambles, and settles on four real recipes with machine, cycle time, power and rates, above a strip linking the three tabs.'],
  ['04-c64-loader_opus_5.5', 'C64 SID Loader', 'Animated SVG on a 15 s loop: the C64 boots, LOAD"ULTRA-SATISFACTORY",8,1, turbo-loader stripes, then a title screen where a pointer clicks through the three tabs while a conveyor feeds an Assembler. Quick start as a BASIC listing.'],
  ['05-crt-terminal_opus_5.5', 'Control Terminal', 'Animated SVG: an amber phosphor CRT that boots, shows ACCESS GRANTED, then looks up Space Elevator phase 2, the Modular Frame recipe and the Assembler. Quick start as a shell session.'],
  ['06-ansi-bbs_opus_5.5', 'ANSI BBS', 'Animated SVG: a 16-colour ANSI BBS login for THE CLOGGED MERGER BBS, with the Modular Frame recipe running through an Assembler, the five Space Elevator phases as the line-up and the nine production machines as the shift roster. Below it, a BBS menu with real links.'],
  // 07 to 12: styles drawn at random from the catalogue in ../../styles (the fourth field is the catalogue ID)
  ['07-compo-slides_opus_5.5', 'Demoparty Compo Slides', 'Animated SVG: a demoparty big screen seen over a crowd, cycling through a title slide, a countdown, one slide per app tab and a prize-giving with score bars. Below it, a text results table ranking ten real recipes by items per minute.', 'demo-07'],
  ['08-milkdrop-visualiser_opus_5.5', 'MilkDrop Visualiser', 'Animated SVG: an early-2000s music visualiser with nothing playing. Rings zoom out of a hex-cog behind the title and cross-fade through three presets, one per tab. A playlist of 16 real recipes is collapsed below.', 'idle-04'],
  ['09-oscilloscope_opus_5.5', 'Oscilloscope Channels', 'Animated SVG: the title as a glowing trace above a 3x3 grid of scopes, one per production machine, each with its own waveform and a real recipe readout (items per minute, cycle seconds, MW). Channel 10 is the Pioneer, flatlining.', 'trk-09'],
  ['10-arcade-attract_opus_5.5', 'Arcade Attract Mode', 'Animated SVG: an arcade cabinet front whose screen loops a title card, a to-scale screw-factory demo and a high-score table of the five Space Elevator phases. INSERT NOTHING: free play, it is Apache 2.0.', 'mach-08'],
  ['11-win32-cracktro_opus_5.5', 'Win32 Cracktro', 'Animated SVG: a mid-2000s Windows cracktro with a bevelled chrome logo on a mirror floor between two twisting steel girders, a three-page text-writer and a dot-matrix sine scroller. An 80-column NFO is collapsed below.', 'pc-05'],
  ['12-cassette-jcard_opus_5.5', 'Netlabel Cassette', 'Animated SVG: an orange cassette with turning reels beside its opened J-card and obi strip. The track list is twelve recipes whose running times are their real craft cycles, and the deck counter adds them up.', 'print-02'],
  // 13 to 27: styles asked for by name (Razor 1911 looks, chiptune, NFO and ASCII schools, vaporwave)
  ["13-chrome-spheres_opus_5.5", "Chrome Spheres", "Animated SVG: an italic chrome ULTRA SATISFACTORY logo over a moving checkerboard floor with six bouncing mirror spheres, a 60-second day-night sky and a gold horizon scroller listing the tabs, counts, run commands and live link.", "pc-03"],
  ["14-neon-cube-field_opus_5.5", "Neon Cube Field", "Animated SVG: an isometric floor of 378 rainbow cubes rolling in a wave under scanlines, with a segment-display ULTRA SATISFACTORY wordmark, a four-page text writer (pitch, counts, run commands, live link), three tab signposts and a divider of spinning octahedra.", "pc-12"],
  ["15-brush-script-nfo_opus_5.5", "Brush-Script NFO", "Animated SVG: an 80-column DOS .NFO screen with \"Ultra\" as a cyan half-block brush script (twelve-row capital U, tail under the word) over \"Satisfactory\" in white brush italic inside a die-cut contour.", "nfo-01"],
  ["16-poster-installer_opus_5.5", "Text-Mode Poster Installer", "Animated SVG: a character-cell installer poster with ULTRA in giant cyan block letters over SATISFACTORY in white inside a gold hazard-tape border, gold parts stepping along belt channels cut through the letters, a title strip, a path field, a progress bar that unpacks the app's item, recipe, building and phase counts, and two small buttons (INSTALL, QUIT), with a plain-text version of the same poster in a collapsed block.", "pc-07"],
  ["17-amiga-tracker_opus_5.5", "Amiga 4-Channel Tracker", "Animated SVG: a full Amiga-style four-channel tracker editor screen (embossed grey field stack, button grid with the three tabs, ULTRA-SATISFACTORY logo plate, four scopes, name and status strips) over four scrolling pattern windows labelled Smelter, Constructor, Assembler and Manufacturer, where each note is a real standard-recipe craft cycle and the readouts step through 13 verified recipes.", "trk-01"],
  ["18-fm-synth-display_opus_5.5", "FM-Synth Keyboard Display", "Animated SVG: an early-1990s FM-synth player status screen in lavender on black, with nine keyboard strips (one per production machine, a lime key stepping once per item made), segment-digit counters, a 31-bar spectrum of real output rates, power level bars with pan dials, and a file selector of the README sections.", "asia-01"],
  ["19-handheld-tracker_opus_5.5", "Handheld Tracker", "Animated SVG: four pastel LCD tracker screens on a dark panel (a PROJECT title screen with the name and counts, a four-channel song grid, a sixteen-row recipe phrase grid in hex and a readout of each recipe or building card).", "trk-05"],
  ["20-player-stack_opus_5.5", "Media Player Stack", "Animated SVG: five snapped pixel-art media-player windows (player with LED clock, analyser and ticker; ten-band equaliser whose sliders are real app counts on a log scale; visualiser with the ULTRA SATISFACTORY logo; library of the three tabs; playlist as table of contents).", "trk-11"],
  ["21-shaded-block-nfo_opus_5.5", "Shaded Block NFO", "Animated SVG: a 96 x 44 character-cell NFO screen with a dithered two-tone ULTRA SATISFACTORY logo, shaded frame walls, debris and scrolling shade bands, half-block headings, leader-dot field rows giving the app's counts, three tabs and run commands.", "nfo-02"],
  ["22-poster-nfo_opus_5.5", "Poster NFO", "Animated SVG: a 100 x 45 character-grid poster NFO with a shaded block painting of a night-time factory, Space Elevator and planet, a tall faded-stem ULTRA SATISFACTORY logo, five mirrored dot-leader fact rows between two pillars.", "nfo-03"],
  ["23-illustrated-ansi_opus_5.5", "Illustrated ANSI", "Animated SVG: an 80x139-cell, 16-colour illustrated ANSI comic that scrolls through a 30-row window once a minute, with a block-letter title, an original hard-hatted cog mascot, a credit plaque, one comic panel per tab (Objectives, Items, Buildings), a run-it panel and a DOS viewer status bar.", "ansi-03"],
  ["24-amiga-ascii-colly_opus_5.5", "Amiga ASCII Colly", "Animated SVG: an 80-column, 144-line Amiga-style ASCII collection paged through a dark text viewer (sheared slash-and-macron logos for ULTRA, SATISFACTORY and the three tabs, a release frame, phase table, Modular Frame recipe card, building counts, run commands, greets and respects).", "nfo-07"],
  ["25-desktop-95_opus_5.5", "Mid-90s Desktop", "Animated SVG: a grey bevelled mid-90s desktop in which a disk-defragmenter window sorts an 828-cell block map of the app's items, recipes and buildings (with a legend of the real counts), hits 100%, shows a cascading error dialog and restarts, beside an editor window holding the two run commands and the live link.", "vap-07"],
  ["26-vaporwave_opus_5.5", "Classic Vaporwave", "Animated SVG: a pink vaporwave collage with an original marble bust, a perspective checker floor, a mint title with katakana, and 1990s-style windows whose three tabs show phase 1 objectives, the Modular Frame recipe and machine power figures.", "vap-01"],
  ["27-signalwave-forecast_opus_5.5", "Signalwave Forecast", "Animated SVG: a 4:3 1990s cable forecast screen that hard-cuts through six pages (current conditions with the app's counts, the pitch as a forecast, the three tabs, seven recipe readings, a joke spaghetti radar and the five Space Elevator phases) with a ticking clock and a bottom crawl carrying the run commands and live link.", "vap-04"],
  // 28 to 42: a second random draw from the catalogue
  ["28-flat-silhouette-intro_opus_5.5", "Flat-Colour Silhouette Intro", "Animated SVG: a flat-colour intro banner with the project name in black capitals on two waves over pink, mustard and green stepped factory skylines, a Space Elevator silhouette against expanding orange and violet rings and a curved text scroller.", "c64-10"],
  ["29-site-race_opus_5.5", "Site Race", "Pure text: a 7-bit ASCII FTP site-race session with ULTRA stencilled out of a '#' progress bar, a zipscript-style reply box carrying the counts, tabs and links, a 99% progress directory and COMPLETE bar, and a MACHINETOP table of the nine machines' recipe counts.", "xfer-01"],
  ["30-pencil-on-paper_opus_5.5", "Pencil on Paper", "Animated SVG: a green pencil writes ULTRA-SATISFACTORY and the pitch in chalk-white handwriting on blue woven paper, then sketches a three-machine iron plan with real recipe rates, a cog mascot carrying a crate of screws, and the three tabs.", "pc-09"],
  ["31-type-in-listing_opus_5.5", "Magazine Type-In Listing", "Pure text: a two-column magazine type-in listing of 26 BASIC lines carrying twelve real recipes, a computed checksum on every line and a 42-byte machine-code block.", "print-03"],
  ["32-generated-banner_opus_5.5", "Generated Banner", "Pure text: an 80-column 7-bit ASCII page with ULTRA- in a bracket-pixel font over SATISFACTORY in a smushed outline font, a per-letter dimension line, the three tabs as boxed-letter strips, the run commands and live link, and three fold-outs (a spacing QC report, a specimen sheet of the six faces, credits).", "nfo-09"],
  ["33-sysop-dashboard_opus_5.5", "Sysop Dashboard", "Animated SVG: an 80-column blue DOS BBS sysop waiting-for-caller dashboard with a block-letter ULTRA SATISFACTORY logo, four stat panels of the app's real counts and per-minute rates, a black Modem window showing the two quick-start commands, a rotating Last Caller window, a ticking clock and uptime, and a bracketed-hotkey grid.", "xfer-08"],
  ["34-dos-setup_opus_5.5", "DOS Setup Dialog", "Animated SVG: an 80x25 blue DOS text-mode setup screen in the VGA palette where stacked, shadowed windows walk through choosing a production machine, recipe, port, IRQ and DMA, run a level-meter test and end on the two run commands and live URL.", "mach-05"],
  ["35-terminal-session_opus_5.5", "Terminal Program Session", "Animated SVG: an 80x25 DOS terminal-program session (typed modem init, blue dialing directory of the three tabs, redialer, Rotor lookup, a Zmodem box downloading data.json, Alt-Z command menu, red status bar, external modem with blinking lights) above a plain-text dialing directory of real links and two collapsed text blocks.", "xfer-05"],
  ["36-mml-listing_opus_5.5", "MML Listing", "Pure text: an 80-column PMD-dialect Music Macro Language song file whose header lines carry the pitch and live link, whose ten note rows spell ULTRA SATISFACTORY, whose FM voice tables use machine power draws as operator levels, and whose two collapsed sections hold the rest of the tune (the five Space Elevator phases, drums) and liner notes with counts, cycle times and credits.", "asia-05"],
  ["37-blue-screen_opus_5.5", "Blue Error Screen", "Animated SVG: a white-on-blue 80x25 text-mode error screen with the project name in an inverted title bar, the pitch and run commands as recovery options, a stop-code screen whose hex values are the app's real counts beside a QR code for the live app, and a restart into a black title screen with the three tabs.", "vap-08"],
  ["38-piano-roll_opus_5.5", "Piano Roll", "Animated SVG: a falling-note piano roll in which the app's 211 machine recipes drop onto an 88-key keyboard as bars sized by cycle time and coloured by machine, under the project name spelled in note blocks, with a recipes-played counter and the three tabs as pattern blocks.", "trk-10"],
  ["39-userbar-kit_opus_5.5", "Userbar Kit", "Animated SVG: a 700 x 152 pixel-lettered banner with a conveyor of miniature userbars above six linked 350 x 19 forum-signature strips (three tabs, live build, local run, fan project), each with gradient, diagonal stripes, gloss and a highlight sweep.", "xfer-04"],
  ["40-power-on-self-test_opus_5.5", "Power-On Self Test", "Animated SVG: an 80 x 25 grey-on-black PC power-on self-test screen with a yellow-and-green corner badge, counters that run up to 140 items, 211 recipes and 477 buildings, the three tabs detected one by one, the run commands and live URL as the setup prompts, then a configuration table listing the nine production machines before the picture collapses and reboots.", "mach-04"],
  ["41-attribute-grid-demo_opus_5.5", "Attribute-Grid Demo Screen", "Animated SVG: a 256x192 8-bit demo screen in a raster-bar border, with ULTRA in whole bright-cyan cells over a colour-cycling two-armed spiral, SATISFACTORY in white, three tabs that light up in turn with their counts, a multicolour twister drawn as a giant screw with its real recipe, and a rainbow-banded scroller.", "demo-08"],
  ["42-aero-gloss_opus_5.5", "Aero Gloss", "Animated SVG: a Frutiger Aero / Web 2.0 banner with a two-tone glossy lowercase wordmark and its reflection, a starburst version badge, a glass window holding the three tab buttons with their counts and a progress bar, bubbles, lens flare, aurora and grass.", "vap-10"],
];
const styleLink = (id) => (id ? `[${id}](../../styles/${id.split('-')[0]}.md#${id})` : 'original six');

const parts = [
  '# ULTRA-SATISFACTORY header examples',
  '',
  'Forty-two retro README headers for [ULTRA-SATISFACTORY](https://github.com/lukexyz/ULTRA-SATISFACTORY), a companion app for the game *Satisfactory*. Each one replaces the title and one-line pitch at the top of that README. 01 to 06 use the same six styles as the [Dance Vision examples](../dance-vision), redrawn around a factory. The rest come from the [style catalogue](../../styles): 07 to 12 were drawn at random, 13 to 27 are styles asked for by name (Razor 1911 looks, chiptune and tracker screens, NFO and ASCII art schools, vaporwave), and 28 to 42 are a second random draw. Build times for every header are in [../build-log.csv](../build-log.csv).',
  '',
  'Each example is its own `.md` in this folder. Animated art is in `assets/`, and the generator that rebuilds it is in `src/` (`node examples/ultra-satisfactory/src/<option>.mjs`). Rebuild this page with `node examples/ultra-satisfactory/src/build-gallery.mjs`. Anchor and file links were written for the ULTRA-SATISFACTORY repo root, so they don\'t resolve here. Every number quoted (140 items, 211 recipes, 477 buildings, recipe rates and cycle times) was checked against that repo\'s data on 2026-09-30.',
  '',
  'Unofficial fan work, not affiliated with Coffee Stain Studios. The art is original. The keygen and cracktro styling is parody of the app itself, which is free and Apache 2.0: nothing here cracks, unlocks or offers a key for the game. Every crew, label, party, station and maker named is invented, and real groups, artists and products are style references only: none of their names, logos or lettering is used.',
  '',
  '| # | Option | Style | What it is |',
  '| --- | --- | --- | --- |',
  ...OPTIONS.map(([slug, name, blurb, id], i) => `| ${String(i + 1).padStart(2, '0')} | [${name}](${slug}.md) | ${styleLink(id)} | ${blurb} |`),
  '',
];
for (const [i, [slug, name]] of OPTIONS.entries()) {
  const body = fs.readFileSync(path.join(DIR, `${slug}.md`), 'utf8').replace(/\r\n/g, '\n').trim();
  parts.push('<br>', '', '---', '', `## ${String(i + 1).padStart(2, '0')} · ${name}`, '', `<sub><code>${slug}.md</code></sub>`, '', body, '');
}
fs.writeFileSync(path.join(DIR, 'README.md'), parts.join('\n'));
console.log(`wrote ${path.join(DIR, 'README.md')} (${OPTIONS.length} options)`);
